### ISSUE TITLE
Recurring Billing

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#10]
Tie a subscription / recurring billing management system into the plugin.  

Express Checkout and Website Payments Pro 3.0 will use Recurring Payments API's.

Payments Pro 2.0 will use PayFlow Recurring Billing.  

Checkout will handle regular items only, subscription items only, and orders with both regular and subscription items at the same time.  

Will model subscription management system after Woo's extension.

**Comment by rayflores** [comment]
done :+1:  https://github.com/angelleye/paypal-woocommerce/pull/150

**Comment by angelleye** [comment]
cool, thanks!  I'll take a look and get it merged in before long.  Hoping to get a bunch of stuff merged and release 1.1.6 here soon.

**Comment by angelleye** [comment]
Here's a guide on adding subscription support for WooCommerce into any gateway:  http://docs.woothemes.com/document/subscriptions/develop/payment-gateway-integration/

We may be able to simply do this so that our gateways work with Woo subscriptions and that would be enough.  Seems that may require the person to purchase subscriptions from Woo, though, which I'd like to try and avoid if we can.

**Comment by angelleye** [comment]
We may be able to handle both scenarios, actually.  We can follow the integration guide for Woo Subscriptions to make that compatible, but then we could also build in our own "Subscription" product type for people who don't have Woo Subscriptions.  

We could make ours a little more simplified, where they can create a "Subscription" product, provide all of the details for a recurring payments profile, etc.  Then orders with such items would include the CreateRecurringPaymentsProfile request to create that profile.

The Woo order could have a meta field for recurring profile ID, but we don't need to worry about catching future payments and relating them to our orders for now.  Simply the ability to create the subscription product and have it use the CRPP API correctly will be sufficient for now.

I'll probably split this up into separate issues:  1 for the Woo Subscriptions compatibility and then one for our own recurring payments integration.

**Comment by angelleye** [comment]
One thing we'll need to consider when building our own recurring payments profiles is that an order could include both physical/shipped products as well as a subscription product.

In such cases, with Express Checkout we would call DoExpressCheckoutPayment to process the one-time payment for physical/shipped goods, and then we'd follow that up with a call to CreateRecurringPaymentsProfile to create the profile.

Of course, orders could also have physical goods only or subscription goods only, so the logic will have to handle all of that correctly.

We are doing this already in USBSwiper.com, but that's not using WordPress/WooCommerce.  It was completely custom.  We could refer to it if need be, though.

**Comment by angelleye** [comment]
Need to let Christopher Roenfeld from PayPal know when this is ready.

**Comment by angelleye** [comment]
This is probably going to turn into a separate, premium extension.

We can utilize the WC tokens introduced in 2.6:  https://woocommerce.wordpress.com/2016/04/04/payment-token-api-in-2-6/

**Comment by angelleye** [comment]
@kcppdevelopers Just want to verify here...all of our gateways are now compatible with WC Subscriptions extension, right?  Were you able to do complete testing of this for all gateways with the Subscriptions plugin to ensure it's all working smoothly and effectively?

**Comment by angelleye** [comment]
@kcppdevelopers Just checking in again now that you said you have the updated WC Subscriptions plugin.  Please verify here once you've fully tested all of our gatweays with the latest Subscriptions and everything is good.
