### ISSUE TITLE
Invalid or missing payment token fields

### ISSUE THREAD

**Issue by cj-at-openthink** [angelleye/paypal-woocommerce#1001]
Hello,

Our client's site (https://cawaterlibrary.net/) is having payment issues. When some users try to make a payment for membership, they receive the error message "Invalid or missing payment token fields". They try to purchase this product: (https://cawaterlibrary.net/document/ca-water-library-membership/)

When I tested in Chrome (63) and Firefox on Mac (macOS High Sierra), I could not replicate the error. This is her message to us:

> "I tried the payment system again, and I got the same response.  I was on Firefox with Windows 10, Monthly donation $10, I used my debit card in the other gateway that isn’t PayPal.  I entered my information and got that same message, invalid payment tokens.  Then I tried it through the PayPal gateway and then it worked.

> IMPORTANT TO NOTE … Even though the first payment through the non-PayPal gateway doesn’t seem to complete, it does go through on the PayPal side.  However, I don’t think it ends up as a successful monthly transaction into the system; those donors end up listed on the WooCommerce subscriptions as pending, so something is not right there."

I opened a ticket with WooCommerce and they believe our client's "PayPal" option is PayPal Standard, which is their built-in method. However, the "Credit Card" option is created by "PayPal Website Payments Pro (DoDirectPayment)" is failing.

Is this gateway/method of payment fully compatible with WooCommerce Subscriptions and the recurring payments feature? It also appears that this only occurs with debit cards and not credit cards.

Any help or insight would be appreciated. Let me know if you need additional information as well!

Thank you,
CJ

**Comment by iMansoorAliKhan** [comment]
@cj-at-openthink , Well, We have reports for this issue in our earlier release 1.4.7.2 but it was fixed in our next version 1.4.7.3 .  so if you are using our most recent release 1.4.7.4 then it should be working fine.
Can you please check your PP for WOO version and make sure to be using the most recent one then give it another shot?

It would be great if you can provide feedback about this.
Thanks!

**Comment by cj-at-openthink** [comment]
Hi,

We updated the plugin from 1.4.6.5 to 1.4.7.4 and, after some testing, are no longer receiving the error notification.

Thank you!

**Comment by iMansoorAliKhan** [comment]
@cj-at-openthink , Glad that things are working as expected.
So I'm going to mark this as closed.
Cheers
