### ISSUE TITLE
Issue with woo subscriptions : _payment_tokens_id-value-is-required 

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1008]
https://wordpress.org/support/topic/error-updating-some-information-a-_payment_tokens_id-value-is-required

When edit subscription order : then from right hand side subscription actions: click on any action and hit update, this this error shows/ _payment_tokens_id-value-is-required

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I tried to generate error but for me it's working fine. It seems issue is 

> "Merchant not enabled for reference transactions"  

Please confirm with user this is still not working after enable reference transactions?

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers , Yeah , you are correct, I already told them about this, and they confirmed this was the problem with their account so this makes this matter resolved..
I'm going to go ahead close this now.
