### ISSUE TITLE
Express Checkout - Item Amount Invalid

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#101]
User complaint about error 10431 - Item amount is invalid.  The log file shows a request like this:

    [REQUESTDATA] => Array
        (
            [USER] => ***
            [PWD] => ***
            [VERSION] => 112.0
            [BUTTONSOURCE] => AngellEYE_SP_WooCommerce
            [SIGNATURE] => ***
            [METHOD] => DoExpressCheckoutPayment
            [TOKEN] => EC-7NF464083J648223A
            [PAYERID] => 6NUAHNKT9C4VY
            [PAYMENTREQUEST_0_AMT] => 49.90
            [PAYMENTREQUEST_0_CURRENCYCODE] => EUR
            [PAYMENTREQUEST_0_INVNUM] => 347
            [PAYMENTREQUEST_0_SHIPTONAME] => Enrico Fontan
            [PAYMENTREQUEST_0_SHIPTOSTREET] => via pedrotti 47
            [PAYMENTREQUEST_0_SHIPTOCITY] => Tirano
            [PAYMENTREQUEST_0_SHIPTOSTATE] => SO
            [PAYMENTREQUEST_0_SHIPTOZIP] => 23037
            [PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE] => IT
            [PAYMENTREQUEST_0_PAYMENTACTION] => Sale
            [PAYMENTREQUEST_0_ITEMAMT] => 49.90
            [L_PAYMENTREQUEST_0_NAME0] => Complete Basic German Grammar Set
            [L_PAYMENTREQUEST_0_AMT0] => 49.900032
            [L_PAYMENTREQUEST_0_QTY0] => 1
            [L_PAYMENTREQUEST_0_NAME1] => A1 smarterGrammar Video Course
            [L_PAYMENTREQUEST_0_QTY1] => 1
            [L_PAYMENTREQUEST_0_NAME2] => A2 smarterGrammar Video Course
            [L_PAYMENTREQUEST_0_QTY2] => 1
            [L_PAYMENTREQUEST_0_NAME3] => B1 smarterGrammar Video Course
            [L_PAYMENTREQUEST_0_QTY3] => 1
            [L_PAYMENTREQUEST_0_NAME4] => Handout A1 Video Course
            [L_PAYMENTREQUEST_0_QTY4] => 1
            [L_PAYMENTREQUEST_0_NAME5] => Handout A2 Video Course
            [L_PAYMENTREQUEST_0_QTY5] => 1
            [L_PAYMENTREQUEST_0_NAME6] => Handout B1 Video Course
            [L_PAYMENTREQUEST_0_QTY6] => 1
            [L_PAYMENTREQUEST_0_NAME7] => English Subtitles for A1 Video Course
            [L_PAYMENTREQUEST_0_QTY7] => 1
        )

The amount of the first item is 49.900032 which isn't valid, and then the additional items don't have any amount at all.  We need to add number_format() to the amounts here so they are formatted to the second decimal, and we also need to check to ensure that all items on the order have an amount.  

We could let PayPal handle the invalid item amount errors when no price is sent, but I'd like to see if there's a better way for us to handle it before ever making the API call since we know it'll fail that way anyway.

**Comment by levansy2020** [comment]
Hi,

I tested and it works with this dev branch

**Comment by angelleye** [comment]
They're still having this issue even with our 1.1.6.2 release, so we still need to address this and get it working.

I can clearly see in their logs that the pricing is getting passed like it shows in the log provided here.  Seems like a pretty simple thing we should be able to fix.  Just another case where the value isn't getting rounded like it should be.

**Comment by levansy** [comment]
Hi Can you require wp-admin and wp-log file? I tested again and it works fine

**Comment by angelleye** [comment]
I am getting consistent errors like this when people either have sales tax included in pricing or when they're using some sort of discount plugin like the bulk discount.

@levansy Did you test under these circumstances?
