### ISSUE TITLE
Admin Notice

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1010]
With this release we really want to get people to see our info about Marketing Solutions and Smart Buttons, and get as many people to enable them as possible.

I'm going to do some "PayPal Quick Tip" videos about both of these products, and then I'd like to embed these videos into an admin notice that people will see when they update the plugin.  

I'd like our admin notice to be more nicely designed than the basic, generic notice.  For example, the SmushIt plugin has some really nice admin notices.

**Comment by kcppdevelopers** [comment]
@angelleye Could you please provide  "PayPal Quick Tip" videos for about Marketing Solutions and Smart Buttons?
