### ISSUE TITLE
Tokenized Option not working with REST CC : 

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1011]
https://wordpress.org/support/topic/paypal-rest-api-save-payment-method-not-working/
I have tested this on my local setup and its not saving any methods at all.
Please look into it and see if there are some adjustments we need to make.
Thanks!

**Comment by iMansoorAliKhan** [comment]
Also, this one

> 
> [28-02-2018 02:47:08] PayPal\Core\PayPalHttpConnection: ERROR	: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment. 
> {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"913cc9dd6919d"}
> [28-02-2018 02:47:08] PayPal\Core\PayPalHttpConnection: DEBUG	: 

I received the same response on sandbox too while I was testing , seems like temporary but this was never seen before. Can you look at it and see why this service error be triggering?

**Comment by kcppdevelopers** [comment]
![1011](https://user-images.githubusercontent.com/13145461/36843480-163a00a6-1d75-11e8-8a75-b5bf9bb21343.png)

**Comment by iMansoorAliKhan** [comment]
Are you using current release branch or dev? Becasue I have tested with current version 1.4.7.4 and that didnot worked for me.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have resolved this issue and push to dev branch.

**Comment by iMansoorAliKhan** [comment]
Can I send that dev branch to the client?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan Yes.
