### ISSUE TITLE
Express Checkout - Shipping Address Problem

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1014]
* https://www.angelleye.com/support/scp/tickets.php?id=1841

User reports an issue with the following scenario...

- WC Checkout page is being used.
- Billing address is filled in on the checkout page.
- Shipping address is NOT filled in because the option to ship to the same address as billing is enabled.
- Express Checkout is used to submit payment.
- When returned to the review page back on the site there is no shipping address provided.

**Comment by angelleye** [comment]
In the scenario above, since the WC checkout page was used we should be using the shipping address provided there with ADDROVERRIDE enabled in the SEC request so that the address entered on the WC checkout page is used all the way through.  We need to consider that "same as billing" option, though, and make sure we're grabbing actual values from billing if the specific shipping fields were left empty because of that same as billing option.

**Comment by iMansoorAliKhan** [comment]
Should I give this to the user ? is it part of dev ? or just share this specific issue file?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have merge this issue with dev branch, so you can deliver dev branch to the user.
