### ISSUE TITLE
guest checkout : Order received page dont have billing and shipping info

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1016]
Please see the screenshot and can test it here.
![image](https://user-images.githubusercontent.com/11312949/37454563-beaa0bf4-285c-11e8-89a5-e974fd3530ed.png)

**Tested this with current release; Even with dev branch as well**

Also, without login doing EC from product detail page gives this:
**your order amount is zero, We were unable to process your order, please try again.**
**or your cart is empty**

![image](https://user-images.githubusercontent.com/11312949/37454643-e82446d4-285c-11e8-84a9-8b2edacd3972.png)

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan Order received page only display shipping/billing address if user is logged in WordPress. it is woo by default functionality.

Regarding "your order amount is zero, We were unable to process your order, please try again.
or your cart is empty" I have try multiple time to generate this error but for me it's working each and every time.

**Comment by iMansoorAliKhan** [comment]
Sorry for delay, Me and @angelleye saw this same problem of zero amount and cart is empty.
so not sure if that is related specifically to my sandbox site ....

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have tested on your website and it's working fine.

**Comment by angelleye** [comment]
I don't know if this is related or not, but check out this product on my live site:  https://www.angelleye.com/product/paypal-woocommerce-multi-account-management/

If you add it to the cart, and then go back to the product page and try to add to cart again it gives an error:  

![image](https://user-images.githubusercontent.com/629241/38021312-1d142e9c-3242-11e8-84b3-345d8f593634.png)

I do not see anything about the product setup that should cause this, and I do not have the option enabled in EC settings to prevent adding an additional item (which should only be related to the PayPal button anyway.)

If I use the PayPal button from this page after it's already added then it loads the Smart Button pop-up momentarily, but then sends me to the cart page.  

So somehow that option to prevent is getting seen as enabled I think, even when it's not...
