### ISSUE TITLE
Braintree - Kount Custom is still not correct..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1020]
* https://mail.google.com/mail/u/0/#inbox/1604cdd2da9831ac

>Hey Andrew – can you verify if your plugin is passing over device data for Kount; as Braintree pulled the log and is reporting that SpecialOpsWatch.com is missing it from their payments.
>
> Braintree Team:
> 
> “Another thing to note is that while Advanced Fraud Tools are enabled, no device data is being collected. In order to properly use our Advanced Fraud Tools, device data needs to be collected and passed so Kount can evaluate the transaction for fraud. Here is some documentation on how to set that up client-side.
> 
> Device data is data that is collected about the pages the customer accesses, computer IP address, device ID or unique identifier, device type, geo-location information, computer and connection information, mobile network information, statistics on page views, traffic to and from the sites, referral URL, ad data, and standard web log data and other information used to help identify the customer to help reduce fraud and declines.

**Comment by angelleye** [comment]
To throw a little more light into the Kount integration with Braintree –

1. Kount integration is the same irrespective of what client side integration is being used ( Drop-In or Hosted Fields )
2. The implementation details can be found on our developer documentation here
3. Kount custom/standard defines whether you have access to a Kount dashboard or not
4. Kount custom has a dedicated access to a dashboard/portal in Kount where you can define & configure rules & filters
5. Kount standard has no access to the Kount portal. The rules and filters are already configured and ready to use based on feedback and data collected across the board
6. Irrespective of what Kount integration it is, the implementation for Kount through the BT SDK remains the same.
7. Irrespective of what client side implementation it is ( Hosted fields/Drop-In ) Kount implementation remains the same.

**Comment by kcppdevelopers** [comment]
@angelleye 

> Kount integration is the same irrespective of what client side integration is being used ( Drop-In or Hosted Fields )

Our plugin provide two type of UI in the Braintree 1) Drop-In and 2) simple credit card UI ( woo default UI)
Kount integration only work with Drop-In or Hosted Fields not for simple credit card form.

**Comment by angelleye** [comment]
@kcppdevelopers Where do we see the info about "hosted fields"?  Sounds like we should add the hosted fields option into the plugin..??

**Comment by angelleye** [comment]
More feedback from PayPal rep on this:  https://mail.google.com/mail/u/0/#inbox/1629273c9d21aad6

> Thank you for taking time to talk with me about the issue my merchant is having on their account.  I will do my best to summarize the issue and include what Kount Support was able to determine so WE can determine where the limitation is coming from the Angelleye plugin or WooCommerce.
> 
>  
> 
> Merchant is using Kount Custom and most of the information is coming into Kount for evaluation, with the exception of the device identification.  Below is what Kount Support was able to determine based on the 18 chargebacks they received in one month:
> 
>  
> 
>  0% overall device collection rate. In addition of their 18 chargebacks since they joined Kount none had device information. Improving device collection will vastly improve performance and effectiveness. 
> Of those 18 chargebacks around 45% were marked for additional review by their agents and was never reviewed.
> We are only receiving email addresses for about 40% of transactions this along with low device collection makes linking orders and stopping fraud extremely difficult.
> Of their 18 chargebacks 95% did not have an email address. 
> So really the “device collection” is a vital piece of how Kount functions and would be extremely useful so Kount can function in its fullest capacity.  If you could help determine if it’s the plugin or the platform that is not allowing this info to go to Kount, I would greatly appreciate it.  Please let me know if there is any other information I can provide or if anyone would like to hop on a call in case they don’t fully understand the need.

**Comment by kcppdevelopers** [comment]
![riskdata_1](https://user-images.githubusercontent.com/13145461/39047352-37b96c80-44b7-11e8-8fcb-03a3fcc905b0.png)




![riskdata_2](https://user-images.githubusercontent.com/13145461/39047358-3bbde7f2-44b7-11e8-91fc-57ca11cac98b.png)
