### ISSUE TITLE
Express Checkout - Smart Button Adjustments

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1026]
* We need to go ahead and remove Venmo from the "Hide specific funding method" option in our plugin.  We can't give them the option to hide that at all.

* We're missing a color option:  black

* When I setup Horizontal display with Responsive set for size, it's getting stuck in a very small element on the product page..??

![image](https://user-images.githubusercontent.com/629241/37682412-7f5c267c-2c57-11e8-993f-ec4636f9569b.png)

**Comment by iMansoorAliKhan** [comment]
Also, on the checkout page incase of blue button this looks a bit difficult to read.
![image](https://user-images.githubusercontent.com/11312949/37759863-b6b24824-2dd6-11e8-8280-20cdf9ab0abe.png)

dont know how this color is being applied, is that from theme color or???

**Comment by angelleye** [comment]
@iMansoorAliKhan There is an option in the Smart Button settings to adjust the color.  The default should be Gold, so you must have changed it to Blue..??

**Comment by iMansoorAliKhan** [comment]
Yes, What I meant here was that, the background blue color.... I know about the blue part.
can we change that in case of blue button?
