### ISSUE TITLE
Express Checkout - Settings Panel Issues..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1027]
I keep getting locked up when trying to load the EC settings panel.  Lags for a very long time before it will load the pages.  Chrome console shows a bunch of requests being made and 20+ seconds to load the page.

**Comment by kcppdevelopers** [comment]
![1027](https://user-images.githubusercontent.com/13145461/37697291-0faa4fc4-2d02-11e8-8fca-b725b2b52289.png)
