### ISSUE TITLE
Express Checkout - Smart Buttons not working properly with mini-cart.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1042]
* https://wordpress.org/support/topic/smart-buttons-disappear-if-update-shipping-methods/

**Comment by iMansoorAliKhan** [comment]
I need to reopen this issue as its still not working for me on my local as well .
Its not showing in minicart: 
![image](https://user-images.githubusercontent.com/11312949/38070568-03ff5a4a-3336-11e8-8dc8-03af327d0a36.png)

**Comment by iMansoorAliKhan** [comment]
![image](https://user-images.githubusercontent.com/11312949/38070717-c8b1e632-3336-11e8-8337-875c70680b17.png)
