### ISSUE TITLE
Saved Card Data Checkout - Reference Transactions

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#105]
Ability to utilize reference transactions with EC, DDP, and PayFlow.  

For EC this will involve adjusting the SEC request to include billing agreement parameters (and users will need to get this enabled on their PayPal account for it to work for them.)

For Pro DDP we'll use [DoReferenceTransaction](https://developer.paypal.com/webapps/developer/docs/classic/api/merchant/DoReferenceTransaction_API_Operation_NVP/), and for PayFlow we'll [adjust parameters accordingly](https://developer.paypal.com/docs/classic/payflow/integration-guide/#submitting-reference-transactions---tokenization).

In all cases, what will be involved is that when a buyer is signed in they will be able to specify that they want to pay using a previous card.  We'll lookup a previous transaction ID for them in the system, and pass into the reference transaction request to process accordingly.

**Comment by kcppdevelopers** [comment]
Issue #10
