### ISSUE TITLE
Express Checkout - Performance Improvements

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1056]
I've noticed on my own sites that the performance of the site in general, especially inside our plugin settings pages, is very slow.  Also getting feedback from other users about this.  For example, one complaint is that our Express Checkout JS file is 1MB loading on the page by itself.  That does seem a bit extreme.  Why is that file so big?  Need to review and make adjustments if possible.

**Comment by kcppdevelopers** [comment]
yes right, In express checkout setting panel we have added two large PayPal JS file

1) Smart Button ( https://www.paypalobjects.com/api/checkout.js )  Size: 1.34 MB
2) PayPal MS ( https://www.paypalobjects.com/muse/partners/muse-button-bundle.js ) Size: 247.30 KB

but both are really required for functionality.

**Comment by angelleye** [comment]
@kcppdevelopers Is there any way to minify them or compress them without breaking them?

**Comment by angelleye** [comment]
@kcppdevelopers Or, can't we pull those from the PayPal hosted source instead of including them at the plugin level?  That way we wouldn't have to worry about staying up to date with their changes..??
