### ISSUE TITLE
Add - OR - between the Proceed to checkout and PayPal buttons.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1061]
* https://mail.google.com/mail/u/0/#inbox/16268c3fd19d3319

>Hey Andrew! Small feedback I’m integrating a merchant right now and  previously in the cart there was an “- OR –“ phrasing in between the WC button to proceed to checkout. That usually alleviated some confusion to some people, even though here at PayPal we try to tell merchants that the PayPal customers know where to look and what that product is exactly, the merchants still push back and either remove the buttons from that location altogether or halt the process. Did your plugin original add the “OR” or was it WooCommerce? I wasn’t sure. Anyways, something to think about perhaps!

**Comment by angelleye** [comment]
We can just do this on the cart page for now.  I don't think we need it on the product page, but it makes sense for the cart page.

I am curious if it was WC or us that had this originally..??  Did we remove it?

**Comment by angelleye** [comment]
Should probably add a filter hook around this in case people want to change the - OR - to something else or remove it entirely.

**Comment by kcppdevelopers** [comment]
@angelleye We never added this functionality and never remove it. it was WC EC.

**Comment by angelleye** [comment]
@kcppdevelopers Let's go ahead and add it with a filter so people can change it if they want to.  The goal would be something like this:

![image](https://user-images.githubusercontent.com/629241/38027520-83e5c80c-3255-11e8-9e40-886f8695a1f2.png)

**Comment by kcppdevelopers** [comment]
![1061](https://user-images.githubusercontent.com/13145461/38030024-16f649dc-32b5-11e8-8b07-226a67a5059b.png)

**Comment by kcppdevelopers** [comment]
WordPress hook filter sample code: https://pastebin.com/mT1kgSFw
