### ISSUE TITLE
Express Checkout - Smart Buttons Default Settings

### ISSUE THREAD

**Issue by ghost** [angelleye/paypal-woocommerce#1067]
Need to use these settings for the default options in Smart Button settings.

{
layout: 'vertical',
size: 'responsive',
shape: 'rect',
color: 'gold'
}

**Comment by kcppdevelopers** [comment]
@angelleye  As Per PayPal [document](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-button/#button-styles)  they recommended below
{
size: 'small',
shape: 'pill',
color: 'gold'
}

And about layout


horizontal : 
Recommended when Placing buttons on a product page, next to the product , Space on the page is limited and Alternative payment options are already provided.

vertical : 
Recommended when Presenting a dynamic list of alternative and local payment options on checkout and shopping cart pages and Leveraging PayPal checkout as a full stack payments platform.
