### ISSUE TITLE
syntax error, unexpected '{'  ??

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1068]
Parse error: syntax error, unexpected '{' in /home1/brdeclos/public_html/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye.php on line 874

Found 3 tickets reporting the same , can you check this one please?
https://www.angelleye.com/support/scp/tickets.php?id=1884
https://www.angelleye.com/support/scp/tickets.php?id=1882

**Comment by iMansoorAliKhan** [comment]
I person said 1.4.8.6 resolved this. Still waiting for others confirmation.

**Comment by angelleye** [comment]
Yes, this was fixed in 1.4.8.6
