### ISSUE TITLE
Express Checkout - PHP Failure

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1069]
* https://wordpress.org/support/topic/paypal-express-checkout-returning-error/

>Catchable fatal error: Object of class WC_Product_Attribute could not be converted to string in /home3/klassix/public_html/bs/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-calculations-angelleye.php on line 99

* https://wordpress.org/support/topic/catchable-fatal-error-after-pay-for-order

>The variable product has 2 attributes: color and brand
>The variation is based on the attribute color.
>
>There are 4 colors.
>The colors are “Green-Gray”, “Green-Blue”, “Pink-Gray”, “Pink-Blue”

**Comment by iMansoorAliKhan** [comment]
Got another one report for this : https://www.angelleye.com/support/scp/tickets.php?id=1890
Is this resolved?

**Comment by kcppdevelopers** [comment]
#1069

**Comment by angelleye** [comment]
@kcppdevelopers According to another user reporting this, it's only happening when Smart Buttons are disabled.  Is this expected, and are we sure this is fully resolved?

**Comment by angelleye** [comment]
@kcppdevelopers To follow up on that, the user was originally reporting that when they tried to check out it was redirecting to the cart page instead of the PayPal page for payment.  I asked him to disable Smart Buttons to see if that would resolve the problem, and that's when he started getting the actual PHP "catchable fatal error" as shown in the original notes here.

**Comment by angelleye** [comment]
I have sent that user the current dev branch to see if it resolves his problem.
