### ISSUE TITLE
Smart Buttons : Random in the console

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1071]
I saw this error 2 times but dont know how to reproduce this:

ppxo_unhandled_error 
Object { stack: "./node_modules/post-robot/src/index.js/U[k.b.POST_MESSAGE_TYPE.RESPONSE]@https://www.paypalobjects.com/api/checkout.min.js:14:33010\ng@https://www.paypalobjects.com/api/checkout.min.js:14:22550\ny@https://www.paypalobjects.com/api/checkout.min.js:14:22832\n", errtype: "[object Error]", timestamp: 1522394000850, windowID: "9eb11f4eb2", pageID: "677abed35f", prev_corr_ids: "", referer: "https://sandbox.mansooralikhan.com", host: "www.sandbox.paypal.com", path: "/webapps/hermes/button", env: "sandbox", … }
checkout.min.js:14:65111
Error: Request to post https://sandbox.mansooralikhan.com/?wc-api=WC_Gateway_PayPal_Express_AngellEYE&pp_action=set_express_checkout failed with 408 error. Correlation id: unknown

<!doctype html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="https://sandbox.mansooralikhan.com/xmlrpc.php">

<title>AngellEYE Sandbox &#8211; AngellEYE Sandbox account for testing</title>
<link rel='dns-prefetch' href='//www.paypalobjects.com' />
<link rel='dns-prefetch' href='//fonts.googleapis.com' />
<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="AngellEYE Sandbox &raquo; Feed" href="https://sandbox.mansooralikhan.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="AngellEYE Sandbox &raquo; Comments Feed" href="https://sandbox.mansooralikhan.com/co…

**Comment by kcppdevelopers** [comment]
#1069
