### ISSUE TITLE
Smart Button : Minicart styling issues 

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1072]
When set style to larg or medium in vertical and horizontal mode it shows like this.

![image](https://user-images.githubusercontent.com/11312949/38130158-523c6ce4-341b-11e8-9a10-6fe08d96fa09.png)

![image](https://user-images.githubusercontent.com/11312949/38129865-362f08aa-341a-11e8-9d42-3fd60cfeae3c.png)

**More importantly, they only show when I'm login to the site incase of guest they simply dont show up.**

_Suggestions: I think it would be best to force Responsive mode in-case of Minicart._

**Comment by angelleye** [comment]
I agree.  Regardless of the size option set in Smart Buttons, mini-cart should always use responsive.
