### ISSUE TITLE
Express Checkout - Marketing Solutions will not activate..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1073]
I just setup a clean install of WP on a new laptop for dev purposes.  I'm trying to activate Marketing Solutions but it's not working for some reason.  I'm in live mode, of course, and I enter the credentials and Save.  It says settings saved successfully, but then the check box for the Marketing Solutions option is simply still there as if it wasn't checked.  I try again, and still, it will not trigger the activation of the Marketing Solutions option.

Not sure if this is related to adjustments we made in #1041, but we need to get this figured out.

**Comment by kcppdevelopers** [comment]
@angelleye  Marketing Solutions API only work for live/public URL , If you trying to active on local machine you will got error like "url does not have public suffix".

![error](https://user-images.githubusercontent.com/13145461/38184941-e7190fe4-3668-11e8-84a9-b14f9962d8a2.png)

**Comment by angelleye** [comment]
@kcppdevelopers I was trying to activate with my live account.  I can't even check the box if it's not in live mode.  I'm in live mode, I check the box, but when I click save it does not actually hold the checkbox to leave it enabled, and it doesn't switch to the Manage Settings buttons like it should.

**Comment by angelleye** [comment]
@kcppdevelopers Video provided in slack.

**Comment by kcppdevelopers** [comment]
@angelleye MS only work for live mode and public URL.
