### ISSUE TITLE
Express Checkout - Conflict with Coupon Code

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1075]
* https://wordpress.org/support/topic/enabling-paypal-express-checkout-will-disbale-coupon-code-link

I'm thinking this must be related to the new smart buttons.

**Comment by angelleye** [comment]
User says smart buttons are not enabled.

**Comment by kcppdevelopers** [comment]
@angelleye 
User said
> Disabling “Autoptimize” plugin resolved the issue.

@angelleye said

> Glad to hear that worked! @optimizingmatters, thanks for stepping in and helping out! 

so it seem it's not our plugin issue.
