### ISSUE TITLE
USPS and UPS plugin compatibility on Order reveiw page

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1079]
Based on my test and a customer's report, when a user comes back from PayPal to order review page and thought of changing the shipping address then the shipping costs dont change based on the updated address.
Please look into this and see if we need any adjustments to make for this?
I have that installed and setup on my sandbox site you can run some test there, we also have customer's staging site too, if you need that just let me know I will provide you that as well.

**Comment by angelleye** [comment]
@iMansoorAliKhan Can you elaborate on how you reproduced this issue?  @kcppdevelopers says he cannot reproduce this.

**Comment by iMansoorAliKhan** [comment]
Okay, This is specific to those 2 plugins which I have mentioned and are available on my sandbox site, when we go , from product page / cart page or checkout with regular / smart  buttons, to paypal and returned to order review page. Then if we change the shipping address ( in setting we have set shipping to customers shipping address ) then the shipping costs dont change. If you like to see this then I can provide user's staging site as well where you can experience this same problem.
