### ISSUE TITLE
EC: create acount on Order review page issue.

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1087]
https://wordpress.org/support/topic/paypal-express-create-an-account-on-review-order-page-doesnt-work/

**Comment by kcppdevelopers** [comment]
#1090

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers , I have already asked them for that and now waiting for their feedback.

**Comment by kcppdevelopers** [comment]
> Ended up being webhost issue with database and not your plugin. Sorry for the mistake.

**Comment by iMansoorAliKhan** [comment]
Sorry, Based on the client comment it was something related to their hosting and DB issue which they figured out so closing this issue no.
