### ISSUE TITLE
Smart Buttons not displaying on product page..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1089]
Just noticed on my live www.angelleye.com site that Smart Buttons are not displaying on product pages even though they are enabled at both the plugin level and the product level.

**Comment by kcppdevelopers** [comment]
@angelleye I have checked every product on angelleye.com and it seem smart buttons are displaying on each product on desktop and mobile as well

**Comment by iMansoorAliKhan** [comment]
Yeah, me and @kcppdevelopers developer checked on the same time and for us Smart buttons are showing, so my guess is that its could be related to some on the device you are testing.....

**Comment by angelleye** [comment]
Yes, it seems they are showing up again now.  Not sure why there weren't previously, but I'll close this issue for now.
