### ISSUE TITLE
USPS and UPS plugin compatibility on Order reveiw page : User feedback

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1090]
https://www.angelleye.com/support/scp/tickets.php?id=1841

The user said now they are seeing anonymous NAN
```
[L_PAYMENTREQUEST_0_AMT0] => nan
[L_PAYMENTREQUEST_0_NAME1] => Y Formula
[L_PAYMENTREQUEST_0_AMT1] => nan
```

**Comment by angelleye** [comment]
@kcppdevelopers The user that submitted this ticket is now reporting that problems seem to be fixed after adjustments with their host.  I see that you did make a commit here which is included in the dev branch already.  Does that commit still need to be here?  Is this ready for review in that case?

**Comment by kcppdevelopers** [comment]
@angelleye Yes, this commit is required and very used full. It just prevent non numeric amount value.

**Comment by angelleye** [comment]
@kcppdevelopers Okay, so this issue is ready for review then..??

**Comment by kcppdevelopers** [comment]
@angelleye Yes.
