### ISSUE TITLE
Express Checkout - PayPal Credit Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1099]
PayPal Credit was documented to be available in both US and UK, and our plugin logic allows PayPal Credit as an option in both original buttons as well as Smart Buttons based on whether you're in one of these countries.

The UK version is not working properly, and we've been asked to set the PayPal Credit options so they only show up for US users.  So if the site country is anything other than US we need to default the PayPal Credit options to hide/disallow.

**Comment by iMansoorAliKhan** [comment]
I think we had that option coded that way, right? @kcppdevelopers , or at-least we discussed and was implemented too...
