### ISSUE TITLE
PayPal Advanced / PayFlow Link

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#11]
Add PayPal Advanced / PayFlow Link as an additional payment gateway option.

**Comment by angelleye** [comment]
This was done in thet paypal_advanced branch, but I don't think it was ever fully completed, and I'm pretty sure there have been updates to the Advanced plugin that we copied here.  

I'll get the updated version and then we can re-do this using that.

**Comment by angelleye** [comment]
I'm confused about how to get this merged because it shows so many different branches involved..??

**Comment by angelleye** [comment]
Need to add Payments Advanced to our settings panel under Settings -> PayPal for WooCommerce.

**Comment by angelleye** [comment]
When I try to checkout with PayPal Advanced the "Layout C" seems to load for me, so it gives me the option to pay with PayPal or a credit card, however, when I try to pay with PayPal I get this error message after logging in and clicking to continue:

>Some required information is missing or incorrect. Please correct the fields below and try again.

>Error: Secure Token is not enabled. Please return to the website from where you started your purchase and try again.

Were you able to test this successfully?

**Comment by kcppdevelopers** [comment]
Yes, I have test this successfully. it seem you need to enable **Enable Secure Token**

![issue-11](https://cloud.githubusercontent.com/assets/13145461/13311484/e94d4f02-dbb4-11e5-806f-33d43a0ccc3a.png)
