### ISSUE TITLE
Need to upgrade Braintree JavaScript v2 SDK to JavaScript v3 SDK

### ISSUE THREAD

**Issue by kcppdevelopers** [angelleye/paypal-woocommerce#1101]

**Comment by angelleye** [comment]
@kcppdevelopers I had Braintree configured already on woo.angelleye.com.  I have now updated the site with the current dev branch here, and when I try to load the checkout page it's giving me a generic error...

>Error processing checkout.  Please try again.

When I look at the Braintree log I see this:

>2018-05-09T10:49:42+00:00 INFO Braintree_ClientToken::generate Exception: The API key that you're using is not authorized to perform the attempted action according to the role assigned to the user who owns the API key.

So somehow this update causes our previously entered credentials to break..??

**Comment by angelleye** [comment]
@kcppdevelopers I have now re-entered my API credentials into the Braintree settings, and now it's working fine.  So yeah, something about this update caused the previously entered values to become obsolete..??  This is not good because anybody using Braintree that updates would break until they re-enter their credentials.

**Comment by angelleye** [comment]
@kcppdevelopers After updating my credentials I'm able to load the checkout page again, but now I'm discovering another issue.  I left the checkout forms completely blank, and I click Place Order, but "nothing" happens.  It does not load any sort of spinner on the page itself or even in the browser tab. If I scroll up I do see a red highlight on the State field, as if it's required, but it's not giving me any actual messages about validation or required fields, and it didn't scroll back up to make this clear when I clicked the Place Order button.  This is not a good user experience.

When I switch back to PayFlow and click Place Order then all of the fields highlight red and it sends me back to the top with a bunch of validation error messages as expected.  This needs to happen with Braintree as well.

**Comment by angelleye** [comment]
@kcppdevelopers Another issue I'm having here.  I went ahead and started filling out all of the checkout fields to see if I could get through checkout that way.  When I enter my zip code I get a spinner while it updates shipping options, but then it popped up this error:

![image](https://user-images.githubusercontent.com/629241/39826342-f519a3a0-5379-11e8-8eb7-1f648cd2e422.png)

**Comment by angelleye** [comment]
@kcppdevelopers It seems the validation issues are only happening with the drop-in UI.

**Comment by kcppdevelopers** [comment]
@angelleye In the Braintree there are two SDK version for drop-in UI 1) V2 and 2) V3 

Why upgrade to v3:

**No dependency on form submission**: Previous versions of the SDK required a form submission for tokenization. Now we're giving you control of tokenization through a simple API call.

**Hosted Fields formatting:** This release introduces input formatting in Hosted Fields, creating a UX-friendly and PCI-compliant experience.

**Smaller file size:** Our new modular component structure means you can selectively include payment methods to fit your needs.

**Improved error messaging:** One of our main goals in this version of the SDK is to make error messaging much more transparent, giving you a clearer picture of what’s happening in your checkout flows.

And more...

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I am done with above issue, could you please help to re test this issue?

**Comment by angelleye** [comment]
@kcppdevelopers @iMansoorAliKhan This is still not working for me.  I'm having the same exact problem I reported 2 days ago where the validation is not triggering at all on the checkout page.  Also, I cannot get PayPal to work at all...

![image](https://user-images.githubusercontent.com/629241/39933817-9dd409a0-5509-11e8-82a2-a41ec857c20c.png)

I get that before I'm even seeing any login or anything, so it has nothing to do with Billing Agreement or duplicate ID or anything like that.  I can't even load the login.

**Comment by angelleye** [comment]
Our log file here is not correct either.  Not sure what changed, but now all I see is this in my log file...

```
2018-05-10T00:58:51+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T00:58:55+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:15:25+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:15:30+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:15:48+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:15:51+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:17:19+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:17:23+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:18:04+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:18:09+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:18:38+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:18:42+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:20:17+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:20:21+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:21:42+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:21:47+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:27:06+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:27:07+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:27:08+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:27:09+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:27:10+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:27:11+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:27:11+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-10T01:27:18+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-11T10:49:00+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-11T10:49:03+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-11T10:52:20+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-11T10:52:24+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-11T10:53:06+00:00 INFO Begin Braintree_ClientToken::generate Request
2018-05-11T10:53:10+00:00 INFO Begin Braintree_ClientToken::generate Request
```

**Comment by kcppdevelopers** [comment]
@angelleye regarding validation I have applied few changes [here](https://github.com/angelleye/paypal-woocommerce/commit/420c1c873955e648d1aed486aa62d550fb7f0e32) and now it's working

**Comment by iMansoorAliKhan** [comment]
When not login it showing fields like this

![Uploading image.png…]()

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have disable our PayPal for Woo plugin and only enable case on delivery and it is still display same so it is not our plugin issue. 

![screenshot-2018-5-16 checkout woocommerce demo](https://user-images.githubusercontent.com/13145461/40105489-b538a118-5910-11e8-9171-651c271645be.png)

**Comment by angelleye** [comment]
@kcppdevelopers I'm a little confused here.  The other gateways work just fine with Divi.  Why would this one be any different?

**Comment by iMansoorAliKhan** [comment]
I agree with @angelleye if this is Divi issue then how come for Creditcard Rest it works fine, or incase of an other gateways from our plugin?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan @angelleye I said I have disable our plugin and only enable "Cash on delivery" Payment method it from by default woo and still state/country filed highlight. so it is not our plugin issue.

**Comment by angelleye** [comment]
@kcppdevelopers Then what did we do in our other gateways that makes it work better?

**Comment by iMansoorAliKhan** [comment]
@angelleye  After installing the most recent dev branch just today, I can confirm that the validation in-case of BT is working back again, It look like some old code was there which was not updating,
After deactivating all plugins except for woo, PP for woo, I tried and it worked, then reactivated all other plugins and tested and the validation thing started to work again on woo and my sandbox site.

**Comment by iMansoorAliKhan** [comment]
Not sure what caused that trouble ....

**Comment by angelleye** [comment]
@iMansoorAliKhan So does that mean this is ready for my review?

**Comment by iMansoorAliKhan** [comment]
@angelleye Yeah, I have tried many things , ran many test so far its running smooth for me.

**Comment by angelleye** [comment]
I just pulled the dev branch and uploaded everything fresh to woo.angelleye.com.  I am running in Chrome Incognito, and I still do not see proper validation happening on this Braintree gateway.  I don't understand why this is becoming such a complicated thing for us to all get on the same page with.

Here is another video explaining what I'm seeing vs. what I expect to see:  http://fiber.angelleye.com/temp/paypal-for-woo-braintree-validation.mp4

**Comment by iMansoorAliKhan** [comment]
@angelleye  This is how I have tested this https://www.useloom.com/share/f88972d2cb1344e18bcd7237217582be , and not sure if this is related to new JS or what.....

**Comment by kcppdevelopers** [comment]
@angelleye I found when user not filling in the Braintree iFrame form and press order button on that time validation not working so I have making necessary adjustments for that.

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers  in case of normal braintree form, the validation works fine but only show error for card expiration date?
![image](https://user-images.githubusercontent.com/11312949/40326136-b867735a-5d57-11e8-9e08-0d78557d63cc.png)

Is that the expected behavior??

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan Yes it is expected behavior.

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers  the validation still needs to be fixed. Please see this,
https://www.useloom.com/share/ae6dd28525f04b189552c5037c347cde

and the load time for drop-in UI??? can we make it quicker ?
