### ISSUE TITLE
Express Checkout - Smart Buttons - Locale Code

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1105]
* https://mail.google.com/mail/u/0/#inbox/162e402b2579928d

>The EC JSv4 is working for the “shortcut” integration, we see there are some configuration parameters but we don’t see the locale, so we are unable to configure our locale and have the button with pt_BR language and our bank flags.
>
>![image](https://user-images.githubusercontent.com/629241/39198067-bfcc9f9c-47ab-11e8-8d81-45b52e0fc998.png)

**Comment by angelleye** [comment]
Seems we should just use the site local code instead of adding an option like this..??

**Comment by kcppdevelopers** [comment]
![setting](https://user-images.githubusercontent.com/13145461/39425121-85e924e4-4c97-11e8-871b-e13c7d13963e.png)



![use_local](https://user-images.githubusercontent.com/13145461/39425126-8a66d23c-4c97-11e8-85bb-cde547d084a9.png)



![page_details](https://user-images.githubusercontent.com/13145461/39425127-8e3c2c18-4c97-11e8-8736-5c8df687550d.png)
