### ISSUE TITLE
Express Checkout - Smart Buttons

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1106]
The last few times I've tested PayPal checkout from a product page it's sending me to the cart page instead of fully loading the PayPal login.  The iFrame pops up for a minute, but then it sends us to the cart instead of fully loading the iFrame for login.

Once I'm on the cart page the Smart Buttons there do work fine.  I noticed this on woo.angelleye.com, and I also noticed it on redtagdeal.com.

**Comment by angelleye** [comment]
I at tempted to test this on my live angelleye.com site, and this time when I loaded my product page I did not see any smart buttons at all (just like I reported last week.)  Upon doing a hard refresh on the page, though, the smart buttons did show up again.

So it seems like maybe we have some sort of a caching conflict going on with our smart buttons..??

**Comment by angelleye** [comment]
I'm testing on a brand new laptop as well.  Very first attempt in a fresh browser on a brand new laptop.  The buttons showed up, but when we click the PayPal button we're just sent to the cart page instead.

Then when we go back to the product page again the buttons do not show up again.  A regular refresh does not display them.  However, if we do a hard refresh at this point then the buttons do show up again...but it still redirects us back to the cart instead of sending us to PayPal.

So we definitely have some sort of an issue going on here that we need to get fixed.

**Comment by angelleye** [comment]
The above was tested in both Chrome and Edge on this brand new laptop as well as my desktop/workstation.  This is from our live angelleye.com site, and it's also happening on woo.angelleye.com in our preview screen (in settings) as well as our product pages.

**Comment by angelleye** [comment]
On this new laptop that we're testing on we realize that it's actually sending us to the shopping cart page without anything in the cart, so that seems to be why it's not sending us to PayPal for payment...since there is nothing to pay for.

I do NOT have the option enabled to keep from adding an item to the cart, though, so it seems like our logic around that is still broken.  We HAVE to get this fixed once and for all.

**Comment by angelleye** [comment]
Reports from other users of this same problem:  https://wordpress.org/support/topic/no-handler-found-error-paypal-express-checkout

**Comment by iMansoorAliKhan** [comment]
I have applied this patch on my sandbox site but its not working for me.. still getting errors

**Comment by iMansoorAliKhan** [comment]
Getting more heat about this issue:
https://wordpress.org/support/topic/in-context-stopped-working/
https://wordpress.org/support/topic/paypal-not-working-with-woocommerce/
https://wordpress.org/support/topic/paypal-express-7/

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers I tried on both site even on my mobile but it didnot worked for me.
lets wait for Andrew;s call, lets see if he is seeing the same problem on his device

**Comment by iMansoorAliKhan** [comment]
Even tested my site on my friends laptop where I never opened this site, its doing the same, 
may be its again a paypal wall firewal issue like I was having with paypal here?

**Comment by iMansoorAliKhan** [comment]
even with 1.4.8.7 this issue exists, if I rollback to 1.4.8.6 this works just fine

**Comment by angelleye** [comment]
But now we're finding that 1.4.8.6 is doing the same thing as well.  Very random.  Seems to be working in Firefox but not Chrome, but not sure if that's just the randomness happening...
