### ISSUE TITLE
EC : Smart buttons conflict with Offers plugin

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1112]
![image](https://user-images.githubusercontent.com/11312949/39306542-e0cff1ba-4979-11e8-988a-fc9abf8c02f5.png)

When offers enabled this wont work on the detail page. and that error shows.

**Comment by iMansoorAliKhan** [comment]
This seems to be a cache problem , closing this now.

**Comment by iMansoorAliKhan** [comment]
I really dont know if this is a conflict but for me on product page the button is not showing.

**Comment by kcppdevelopers** [comment]
#1106
