### ISSUE TITLE
non-unique IDs on page elements..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1113]
* https://wordpress.org/support/topic/console-error-found-2-elements-with-non-unique-id-paypal_pro-card-cvc/

> I am getting a console error on the Checkout page when I am NOT logged into the website.
> 
> Everything appears to be updated.
> 
> I have had customers report an issue with multiple billing, when they only wanted to place one order.
> 
> I am wondering of the id conflict is interfering with the validation on the checkout form.

**Comment by iMansoorAliKhan** [comment]
Based on my testing on client site without this patch, I dont see any console error... so I dont know what error they are referring to......
