### ISSUE TITLE
Spinner not loading?

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1117]
https://wordpress.org/support/topic/not-seeing-spinner-while-checkout-processes-the-order/#post-10245303

Although , I'm not seeing this issue but 2 people reported this, so can you check if some css might be conflicting?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan 

I have checked on user's staging website stage2.fitafvegan.com and it's working fine.


![1117](https://user-images.githubusercontent.com/13145461/39627202-a9463958-4fc2-11e8-86a4-ff929da4fb4f.png)

**Comment by iMansoorAliKhan** [comment]
Yeah, that user used some css to tweak this, You can see the WP thread, another use reported the same.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan but they not provided URL for troubleshoot, Could you please ask for that?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have try with different themes and it's working well with all themes.

**Comment by iMansoorAliKhan** [comment]
I have already asked them will leave more notes upon their reply.
