### ISSUE TITLE
Review page message.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1119]
* Order [8511](https://www.angelleye.com/wp-admin/post.php?post=8511&action=edit)
* https://www.angelleye.com/support/scp/tickets.php?id=1952

User would like the ability to include a custom message here.  We could do this with a setting or with a hook..??

![image](https://user-images.githubusercontent.com/629241/39797967-3429be96-5324-11e8-9abd-115006dfeaa2.png)

**Comment by angelleye** [comment]
It might be best to go ahead and make it an option under settings so people can add a message there without having to mess with code.

By default it can be empty, but then they can fill in any message they want.

and it would be displayed right under the Review Order header with a specific class name so that it can be easily styled.

**Comment by kcppdevelopers** [comment]
1) DIVI :

![01](https://user-images.githubusercontent.com/13145461/39799839-5b5865c6-5383-11e8-93ce-13bd3be2a2d5.png)

2) storefront: 

![03](https://user-images.githubusercontent.com/13145461/39799840-5b8ad9e8-5383-11e8-8289-42566e1eb9e5.png)

3) twentyeleven:

![20](https://user-images.githubusercontent.com/13145461/39799841-5bbc126a-5383-11e8-8d0c-ad45f7a4ee00.png)
