### ISSUE TITLE
Minor Tweaks for 1.4.9

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1122]
Smart button vertical : Large
http://prntscr.com/jg07px

On save , notice duplications, not this even the billing agrement.
![image](https://user-images.githubusercontent.com/11312949/39860016-3820e812-5455-11e8-9e50-1ce7ae5e7638.png)

bRAINTREE DROP-PIN ISSUE.

![image](https://user-images.githubusercontent.com/11312949/39860944-8ce9e120-5458-11e8-8993-8c90db7829c7.png)

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan 

Regarding Smart button vertical : Large CSS it's depend on themes CSS I think medium and small are best suitable for DIVI themes. if I add some CSS then it will conflict with other theme so it would be great to remain as it.

Regarding notice: I have resolved issue and push to dev branch.

Regarding JS console error: I have already resolved it in previous issue.

**Comment by iMansoorAliKhan** [comment]
In avada at product level its showing like this, verticla large button
![image](https://user-images.githubusercontent.com/11312949/39869534-53725f84-5477-11e8-8d7a-d8cbc9218535.png)

**Comment by iMansoorAliKhan** [comment]
Using Braintree PayPal option getting follow error, in-context is working with Braintree PayPal

Error: PayPal Powered by Braintree was unable to complete the transaction. Please try again later or use another means of payment. Reason: PayPal Blocking Duplicate Order IDs

**Comment by iMansoorAliKhan** [comment]
Even After applying the last comitt I'm seeing this error
![image](https://user-images.githubusercontent.com/11312949/39873954-d9ffe324-5485-11e8-884e-6b1f62e5b71d.png)

**Comment by iMansoorAliKhan** [comment]
Another thing which I;m seeing since yesterday is that, when , on my sandbox site, I click on shop which loads shop page , I click on a product and that open product detail page, there I dont see smart buttons, but then I do CTRL + SHIFT + R then it loads the smart buttons.
I have tested this on firefox and chrome and only to reproduce is to be login to as admin 

![image](https://user-images.githubusercontent.com/11312949/39954938-7c790f2a-55e1-11e8-8817-3d7754952d02.png)

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have on your website and it's seem working for me. may be caching issue.

**Comment by iMansoorAliKhan** [comment]
this is strange though,. you switched theme to Divi then switched back to storefront and it started to show again. @angelleye , This issue seems to be final now.
Please check and close it

**Comment by iMansoorAliKhan** [comment]
on woo.angelleye.com with newest dev branch installed, when I click on prooced to checkout, this notice comes in console/.
![image](https://user-images.githubusercontent.com/11312949/40046283-06189b7c-5846-11e8-941c-a1ebf777d0e8.png)

is this something we need to look? this was not coming before...

**Comment by iMansoorAliKhan** [comment]
this button becomes irresponsive for some unknown reason, it works and then all in a sudden it wont.
![image](https://user-images.githubusercontent.com/11312949/40046640-deffdf90-5846-11e8-9faf-481724fa311b.png)

**Comment by iMansoorAliKhan** [comment]
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.


notice being reported either n backend and now on front-end, with an internal server error and this notice in console

in backend I saw this when I was refunding a authorization order ( using PayFlow )

**Comment by iMansoorAliKhan** [comment]
![image](https://user-images.githubusercontent.com/11312949/40047040-d0421e7c-5847-11e8-85af-55fec74e2554.png)

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have discus all above thing on slack and confirm that issue is ready to reviews.

**Comment by iMansoorAliKhan** [comment]
@angelleye  This issue can be closed now.

**Comment by angelleye** [comment]
@iMansoorAliKhan , @kcppdevelopers I see some Braintree validation adjustments in this issue, which are related to #1101, but I still cannot see proper validation, so I cannot close either of these issues.

**Comment by iMansoorAliKhan** [comment]
@angelleye you are seeing that issue on woo? But yesterday I have tested it on woo and validation worked for me on my sandbox and woo as well.

**Comment by iMansoorAliKhan** [comment]
which validation you are referring to...

**Comment by angelleye** [comment]
@iMansoorAliKhan Yes, this is happening on woo.angelleye.com.  Take a look in #1101.  My last comment I left a video link showing what's happening.

**Comment by iMansoorAliKhan** [comment]
@angelleye  OK
