### ISSUE TITLE
REST CC Logs are not secure..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1125]
* https://wordpress.org/support/topic/gdpr-compliant-and-questions-about-data-collection/

> We’re in sandbox mode right now, and under the REST settings under Woocommerce -> Settings -> Checkout, we have NOT enabled logging. However, I can see all transactions made since May 1st in the wc-log, with all credit card details, first and last name, address, etc. shown there in plain text!
> 
> Is this happening because logging is defaulted to “on” when in sandbox mode or something? When we go to live payments will wc-logs still be made like this?

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers I have just installed Dev branch on my sandbox site
deleted all old logs, deactivated logging in REST and all other methods. The performed a few orders.
Log is still being generated even though I have disabled that in plugin settings.

**Comment by angelleye** [comment]
@kcppdevelopers I see you made a commit after @iMansoorAliKhan's last message, but you didn't mark this ready for review again.  Are you still working on this?

**Comment by angelleye** [comment]
@kcppdevelopers The cf648e7 commit above has Braintree stuff in it.  Why was that commit done here?

**Comment by iMansoorAliKhan** [comment]
CC log now shows this?

![image](https://user-images.githubusercontent.com/11312949/40326411-8f2fe200-5d58-11e8-80fc-6c3417af2ccc.png)

**Comment by iMansoorAliKhan** [comment]
REST automatic log creation is now fixed...
it only generates log when we enable from settings page.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan Yes it is expected behavior, it will display full log when Notice/Error on response.

**Comment by iMansoorAliKhan** [comment]
so no details when its success ???
