### ISSUE TITLE
TLS-1.2-and-HTTP1.1-Upgrade

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1127]
https://www.paypal-notice.com/en/TLS-1.2-and-HTTP1.1-Upgrade/

Are we compliant to this upgrade?

**Comment by angelleye** [comment]
@iMansoorAliKhan Yes, this is all part of that POODLE stuff, too.  Our plugin is updated for it, but there is a chance people could have a problem at their server level.  This is where they need to make sure PHP and OpenSSL are updated accordingly, and their server passes TLS tests.
