### ISSUE TITLE
New log is being generated for new date?

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1128]
With new update I just realized that every day a new log is generated. although there are only few transactions like 3-4 may be...

**Comment by iMansoorAliKhan** [comment]
Here is screenshot of what I mean
![image](https://user-images.githubusercontent.com/11312949/40713877-7fa60e86-641a-11e8-8c87-2b3fbdd16c4d.png)

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan This is not our plugin issue, it's handle/functionality by default woo it self.
