### ISSUE TITLE
Express Checkout - Item Total errors when using WooThemes Bulk Discount plugin

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#113]
Site owner using [WooCommerce Bulk Discount plugin](https://wordpress.org/plugins/woocommerce-bulk-discount/) and getting order totals do not match error back from PayPal because it seems to be simply adjusting the item price on the fly, but when our plugin pulls item prices it's still grabbing the original price of the item.

[PAYMENTREQUEST_0_AMT] => 7.58
[PAYMENTREQUEST_0_CURRENCYCODE] => GBP
[PAYMENTREQUEST_0_SHIPPINGAMT] => 0.00
[PAYMENTREQUEST_0_TAXAMT] => 0.00
[PAYMENTREQUEST_0_PAYMENTACTION] => Sale
[L_PAYMENTREQUEST_0_NAME0] => Black Twisted Vintage Cable
[L_PAYMENTREQUEST_0_AMT0] => 3.99
[L_PAYMENTREQUEST_0_QTY0] => 2
[PAYMENTREQUEST_0_ITEMAMT] => 7.98

He says the WooThemes Express Checkout plugin does not have this problem, so I'm not sure what we've done differently to cause it.  

https://wordpress.org/support/topic/payment-request-error?replies=4

**Comment by angelleye** [comment]
The first test I attempted resulted in another item totals error.

![image](https://cloud.githubusercontent.com/assets/629241/5750879/88b9bb6e-9c20-11e4-8e15-c9f8b5f7d158.png)

**Comment by angelleye** [comment]
I've tried a number of tests here and I can't get through a single one.

**Comment by angelleye** [comment]
Ok, now I did just get a successful order to go through with a bulk item discount, but only when shipping was not included on the order.

**Comment by angelleye** [comment]
We seem to have fixed the 10413 error (where cart items don't add up) but we're still having problems with the item amounts themselves coming out with more than 2 decimal places causing 10431 error where item amount is invalid (something like 49.25300003423, for example).

So again, somewhere something isn't getting rounded correctly to 2 decimals.

**Comment by RenzoF** [comment]
Hi, 
With the latest dev version I still get the error 10413, the way I resolved it is by calculating the price from the cart values you can see 
https://github.com/RenzoF/paypal-woocommerce/commit/7baaead8f67714696fb1fe3165de39d2755530cd

The other problem with the decimals is an issue with the 
woocommerce-bulk-discount which it has been resolved on the master branch https://github.com/fahrenheit-marketing/woocommerce-bulk-discount/commit/74dab790705e568ac1ba8bcb3ab6beed27581f57#diff-d488f766269a0750b01f76b25e7e0b3e

I am using that combination to make it work.

Anyway thanks for creating this plugin.

I can send a pull if you need for that change?

Cheers

**Comment by angelleye** [comment]
@RenzoF Sorry for the delay getting back with you.  Sure, go ahead and send a pull request and I'll be happy to take a look and merge it in if all goes well.  I guess you've been using it this way for awhile now without issue..??

**Comment by RenzoF** [comment]
@angelleye I been using this for a while without problems, I need to update few plugins (including this one) then I'll test again and report back.
