### ISSUE TITLE
Review page message on PayPal screen??

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#1130]
https://wordpress.org/support/topic/skip-final-review-option-issue/

We have skipped the final review option in the settings but on paypal screen we still see message telling that we will be redirected back to the site to review the order..
![image](https://user-images.githubusercontent.com/11312949/40796466-9618a782-651e-11e8-8a29-871639ca6a2b.png)

Because clicking on continue it brings you back to site and then to order received, 
So My questions is : Is that something we need to adjust in our plugin or is that something related to PayPal in general?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I confirm it's our plugin issue only in smart button.

**Comment by angelleye** [comment]
Moved to Jira:  https://angelleye.atlassian.net/browse/PFW-132
