### ISSUE TITLE
PFW-47 reference ticket

### ISSUE THREAD

**Issue by robwatson-intechra** [angelleye/paypal-woocommerce#1142]
Referencing the end comment of #1006 where a ticket in the new system needs to be made, I've been asked to create a new ticket that points to PFW-47 for further resolution.

**Comment by angelleye** [comment]
@robwatson-intechra I'm sorry, I didn't include the link I meant to when I asked you to create a new ticket.  I meant to send you to our direct help desk at https://www.angelleye.com/support.  If you can please bear with me and do that it would be helpful.  Thanks!
