### ISSUE TITLE
Plugin should FORCE TLS 1.2 automatically

### ISSUE THREAD

**Issue by zab-allah** [angelleye/paypal-woocommerce#1143]
Starting June 30th 2018 , PayPal will NOT process payments if your not using TLS 1.2

I believe the next update should Force TLS 1.2 by default (have the checkbox auto selected) because if people don't find the option there in the settings > paypal for woocommerce > global settings then they are going to be in for a huge surprise at the end of this month.

**Comment by iMansoorAliKhan** [comment]
Thanks for the feedback, we will be looking into this in a future release. 
Moreover, we have moved to a new system so in future it would be great if you can [submit a ticket here in future](https://www.angelleye.com/support/), that would be appreciated.
Thanks!

**Comment by angelleye** [comment]
The plugin has been configured properly based on all the technical details for handling this.  It basically lets the server use its own default method for HTTP requests, so it's really up to the server configuration to ensure it will properly use TLS 1.2.

In the past we actually did force the TLS 1.2, but then when servers weren't configured with that as an available option it caused more harm than good.  So at this point we're really just providing people with the details necessary to ensure their server is ready to go, and this will not be a problem.

**Comment by angelleye** [comment]
@iMansoorAliKhan Gary and I are going to improve our sync with GitHub and Jira at some point.  Right now we should expect that we'll continue getting new tickets here, and we'll just need to move them as necessary.
