### ISSUE TITLE
Adjustments to the buttons on the cart page

### ISSUE THREAD

**Issue by maanoobh** [angelleye/paypal-woocommerce#1195]
Hello,

On the cart page, the button is not displaying (centering) correctly on mobile devices like iPhone 6 for example, proposed fix is to lower the **screen min-width** and **max-width** from _400px_ to _330px_ in _cart.css_ to accommodate more devices.

Also, in the **Hide Funding Method(s)** setting, the option to hide _Venmo_ is missing, could you add it please?

And in the **Order Review** page, I think that the _Place Order button_ should be before the _Cancel Order button_ to avoid accidental cancellation?

Thanks.

**Comment by iMansoorAliKhan** [comment]
Hi @maanoobh   Thanks for the feedback, we will get that adjusted in a future release.
About Venmo, that is actually controlled by PayPal, we tried that already but there is no control over that for now, PayPal is showing that on mobile devices only.

Thanks!

**Comment by iMansoorAliKhan** [comment]
[Jira Ref #](https://angelleye.atlassian.net/browse/PFW-236)
