### ISSUE TITLE
Cancel Order Button Does Not Resize Properly On Review Page

### ISSUE THREAD

**Issue by tyladubyabeatbox** [angelleye/paypal-woocommerce#1196]
The "Cancel Order" button does not resize properly on the review page. The goal would be to have it resize the same as the "Place Order" button. This is mainly displayed on mobile or any smaller screen that would require responsiveness. I have attempted to fix this myself but unfortunately, I do not know enough about CSS to do so. Let me know if you can help.

![cancel_order_resize_issue](https://user-images.githubusercontent.com/42697873/44619353-06860b00-a853-11e8-9c21-1d45845ed47c.png)

**Comment by angelleye** [comment]
Thanks for the feedback.  You can probably fix that pretty easily in your theme's CSS, but I agree it should be matching up better by default.  I'll add this to our backlog and we'll get it fixed in an update.

**Comment by tyladubyabeatbox** [comment]
Thank you for the quick response! I apologize if this is a dumb question, but I have attempted to fix the CSS a couple times and was unsuccessful. The <a> button uses the class "button alt angelleye_cancel" which I have tried to modify but I can't seem to get it to be responsive for mobile devices.  Would you be able to point me in the right direction to solve this? If this uses my theme's CSS, do you have any idea what I would need to modify? I appreciate your time and help.

**Comment by iMansoorAliKhan** [comment]
Are you aware of apply !important with any css rule you write, this would override the already added CSS and will force your  added style. Or if you can share your site, I can look at the css and can guide further.

**Comment by tyladubyabeatbox** [comment]
I have tried making changes, even using the !important tag to the .button.alt.angelleye_cancel class in the angelleye-express-checkout.css file.  The <a> tag that mimics a button in the class-wc-gateway-paypal-express-helper-angelleye.php file uses the class "button alt angelleye_cancel" which is why I thought making modifications to that would work. If this is incorrect and changes needed to be made elsewhere, I would appreciate some insight.

**Comment by iMansoorAliKhan** [comment]
Thanks for the detailed feedback, we will look into that and make the necessary adjustments in a future release.
Thanks!

**Comment by iMansoorAliKhan** [comment]
Jira ref: [`pfw-261`](https://angelleye.atlassian.net/browse/PFW-261)
