### ISSUE TITLE
Billing address sent to PayPal instead of Shipping address

### ISSUE THREAD

**Issue by mimrank** [angelleye/paypal-woocommerce#1200]
Hi, 
any way or method to send Billing address sent to PayPal instead of Shipping address?
because woocommerce send Shipping address.

**Comment by iMansoorAliKhan** [comment]
[pfw-260](https://angelleye.atlassian.net/browse/PFW-260)

**Comment by angelleye** [comment]
@mimrank Are you working with Express Checkout?  Are you using the Woo checkout page, or are you skipping it via a PayPal button somewhere before it?
