### ISSUE TITLE
PayPalModal.php error

### ISSUE THREAD

**Issue by neopaws** [angelleye/paypal-woocommerce#1205]
I have PayPal Credit Card (REST) setup with the correct credentials but when i try to pay for a product i get this error:

Warning: sizeof(): Parameter must be an array or an object that implements Countable in /homepages/25/d744427291/htdocs/website/wp-content/plugins/paypal-woocommerce-release/classes/lib/PayPal/Common/PayPalModel.php on line 176

Error processing checkout. Please try again.

My log file shows:
PayPal\Core\PayPalHttpConnection: ERROR   : Got Http response code 401 when accessing https://api.paypal.com/v1/payments/payment. {"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment.","information_link":$
09-11-2018 @ 15:53:16 - Got Http response code 401 when accessing https://api.paypal.com/v1/payments/payment.

this same error repeats a few times.  I am using the latest woocommerce and your latest version of your plugin.  I am on php7.2.

The payment does not go through.

**Comment by iMansoorAliKhan** [comment]
[Jira](https://angelleye.atlassian.net/browse/AHD-1028)
