### ISSUE TITLE
Fatal when billing agreement fails. WooCommerce incompatibility

### ISSUE THREAD

**Issue by diedexx** [angelleye/paypal-woocommerce#1207]
Hi there, 

it seems like 53da090023eef4c8052c3d9a7599300403c7ad08 introduced an incompatibility issue with WooCommerce. When PayPal fails to create a billing agreement, an attempt is made to send an email, but that fails because of missing arguments on [this line](https://github.com/angelleye/paypal-woocommerce/commit/53da090023eef4c8052c3d9a7599300403c7ad08#diff-4e8488a26eac7ab1d37129f75f371ce5R290): 
```
Fatal error: Uncaught ArgumentCountError: 
Too few arguments to function WC_Emails::wrap_message(), 1 passed 
in .../plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-request-angelleye.php on line 209 
and at least 2 expected in .../plugins/woocommerce/includes/class-wc-emails.php:263
```

`wrap_message` expects the first param to be the email headers. Instead, the message is given, which should be the second param.

This has been the case since before WooCommerce 1.6.4 (I haven't checked any further), and hasn't changed until now (WooCommerce master).

**Comment by iMansoorAliKhan** [comment]
Hi @diedexx  Thanks for the feedback, we will look into this and see if there are any adjustments we need to make, then we will get those done in a future release. 

Thanks!

**Comment by iMansoorAliKhan** [comment]
To add here, Could you explain how to reproduce this error? Could you outline steps to reproduce along with Woo, WP, paypal for woo versions?

**Comment by diedexx** [comment]
Hi @iMansoorAliKhan, Thanks for your response. 
Sure, I'm using:
- WooCommerce: 3.2.6. Also verified on master (= 3.5-beta I believe)
- WordPress: 4.9.8
- PayPal for WC: 1.4.15
- WooCommerce Subscriptions: 2.2.17

I was able to reproduce this by using a new PayPal facilitator sandbox account and completing the checkout process while purchasing a simple-subscription product. The sandbox account does not have any renewal settings configured afaik.

**Comment by iMansoorAliKhan** [comment]
@diedexx  Did you tried updating woo to 3.4.5 with woo 2.3.5 ( as I'm using right now ) and then try one more time to see if you still get the same issue? Because I tried to reproduce this but I simply can't. So maybe there is a plugin conflict or an outdated plugin that might be causing trouble for you.

It would be great if you could run those test and see what you got.

**Comment by iMansoorAliKhan** [comment]
Okay, we will review that soon.

Thanks!

**Comment by iMansoorAliKhan** [comment]
moved to jira: [pfw-259](https://angelleye.atlassian.net/browse/PFW-259)

**Comment by iMansoorAliKhan** [comment]
Hi @diedexx .


Development has been completed, tested, and merged for the issue reported in this help desk ticket

Fatal Error

The changes will be included in our next release.
**Tested with woo subscription 2.3.5 and PayPal for woo release branch.**

Thanks!

The AngellEYE Team
