### ISSUE TITLE
paypal wont work

### ISSUE THREAD

**Issue by goltche1** [angelleye/paypal-woocommerce#1209]
after the update the extension doesnt work, after trying to check out you just get an empty error message
![untitled-1](https://user-images.githubusercontent.com/18596108/46167386-a7595300-c263-11e8-9859-277962961991.jpg)

**Comment by iMansoorAliKhan** [comment]
Hi @goltche1 I'm sorry but I dont see any indication of our plugin here, could you explain a bit more which gateway you are using and which plugin? Are you using standard Paypal that comes with the woocommerce?

**Comment by iMansoorAliKhan** [comment]
@goltche1  I'm closing this ticket now as I think you are moved to our Jira Support system so please check your ticket there and reply with the relevant information.

**Comment by iMansoorAliKhan** [comment]
**REF:**  https://angelleye.atlassian.net/browse/AHD-1157
