### ISSUE TITLE
Braintree : hide and not require Postal code field or use postal-code field from billing address

### ISSUE THREAD

**Issue by simon-3t** [angelleye/paypal-woocommerce#1210]
Hello,
First, thank you very much for this excellent plugin.

I would like to know if we can **hide and not require** the **"postal code**" **field** for the "Credit Card payments Powered by Braintree".
**Or even better, use the "postal code" field from billing address.**

In France most of the VISA and Mastercard doesn't use AVS rules. I would like to **not** add more steps during checkout.

Thank you !
Best regards,
Simon

**Comment by iMansoorAliKhan** [comment]
Hi @simon-3t  Thank you so much for your nice words, We are happy to know that you like it.

I think that that can be controlled from your Braintree Merchant account, and then look for something like this below.

![image](https://user-images.githubusercontent.com/11312949/46331403-38984300-c631-11e8-98aa-12b25ef99978.png)

There you can enable / disable what kind of verifications you want from your users.
Hope that helps.

Regards,
Mansoor

**Comment by simon-3t** [comment]
Hi @iMansoorAliKhan ,
Thank you, yes I already configured on Braintree side.
I would like to hide this field : 
![image](https://user-images.githubusercontent.com/30625240/46333095-8b81f280-c651-11e8-89b4-68e1399d9042.png)
And instead of writing again the postal code for their credit card, the plugin use the postal code written in the billing address.

**Comment by iMansoorAliKhan** [comment]
@angelleye Sorry for delay in getting back, I think somehow we missed to move this. 
I will get this moved now...

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PFW-319

**Comment by iMansoorAliKhan** [comment]
@simon-3t  we will look into that and see if there are some adjustments we can make for this.

Thanks!
