### ISSUE TITLE
10426 - Item total is invalid

### ISSUE THREAD

**Issue by lightson** [angelleye/paypal-woocommerce#122]
Hi there,

I'm using the dev version 1.1.5 of your plugin (suggested by you so I could add paypal to the payment types drop down), and when a user adds a coupon I'm getting "10426 - Item total is invalid".

Oddly, this only occurs with EU users that pay VAT, for none-VAT purchases the coupon works ok.

Here's a log extract of a test purchase I ran. The Order total is £53.64 on my site, however £53.6400102319 seems to get passed to paypal:

[L_PAYMENTREQUEST_0_NAME0] => 'nana Cream

[L_PAYMENTREQUEST_0_AMT0] => 8.16
[L_PAYMENTREQUEST_0_NUMBER0] => b-nc-6
[L_PAYMENTREQUEST_0_QTY0] => 4
[L_PAYMENTREQUEST_0_NAME1] => Kiss the Ring

[L_PAYMENTREQUEST_0_AMT1] => 9.00
[L_PAYMENTREQUEST_0_NUMBER1] => b-ktr-6
[L_PAYMENTREQUEST_0_QTY1] => 1
[L_PAYMENTREQUEST_0_NAME2] => Gizzard Juice

[L_PAYMENTREQUEST_0_AMT2] => 8.50
[L_PAYMENTREQUEST_0_NUMBER2] => qjf-gi-6
[L_PAYMENTREQUEST_0_QTY2] => 2
[L_PAYMENTREQUEST_0_NAME3] => Cart Discount
[L_PAYMENTREQUEST_0_NUMBER3] => bgk5vpc2bdkt
[L_PAYMENTREQUEST_0_QTY3] => 1
[L_PAYMENTREQUEST_0_AMT3] => -5.00
[PAYMENTREQUEST_0_ITEMAMT] => 53.6400102319

Hope that's helpful

**Comment by lightson** [comment]
Just updated the the latest dev channel (1.1.5.3) and thought I'd test things just in case you'd fixed the bug.

Well, I can't seem to replicate the previous problem and paypal loads up fine and reflects the correct discount, so at least for the moment things appear to be working as they should.

I'm going to monitor things and will be straight back if the problem reappers, but things look good :)

**Comment by angelleye** [comment]
That's good news, but I'm still not 100% satisfied as I haven't fully tested and merged all of these changes yet.  Please do keep me informed.

**Comment by lightson** [comment]
I will do. I'm going to set it live and then keep a very close eye on my
error messages from paypal.

Here's hoping it's resolved :)

**Comment by lightson** [comment]
Sigh, Just had an error message through.

I ran at least a couple dozen tests and saw no problems myself but there's
obviously a few occasions it's going to blow up.

Ah well.

**Comment by levansy2020** [comment]
We added the number_format to the code, so this problem is resloved

**Comment by angelleye** [comment]
People still seem to be having this issue, and everybody seems to be using the bulk discount plugin with percentage based discounts enabled.  

#113

**Comment by angelleye** [comment]
Another thing causing this problem is when people are setting taxes to be included in item pricing.  

https://wordpress.org/support/topic/paypal-express-checkout-error-code-10431?replies=27

**Comment by angelleye** [comment]
Here's an article where they're discussing the same problem in Magento:

https://www.addedbytes.com/blog/how-to-correct-magentos-paypal-rounding-error/

Maybe we should apply the same thing here..??  I think maybe you actually did this in one of our branches already, but I'm not entirely sure.  Figured it would something worth looking at.
