### ISSUE TITLE
Braintree Payments Don't Send Cardholder Name to Braintree

### ISSUE THREAD

**Issue by marpstar** [angelleye/paypal-woocommerce#1264]
I have a site running this plugin and we're set up for Braintree payments. In October, we updated from an older version of the plugin to 1.4.18. Since then, my client has noticed that when running reports in Braintree, the `Cardholder Name` is no longer being populated. 

After that upgrade to 1.4.18, our site also stopped tokenizing payments by default (which, after checking the "Use Tokenized Payments" checkbox, started working again). 

Maybe the two are unrelated, but the tokenized payments and cardholder name aren't mutually exclusive, are they?

I've updated the plugin to latest and am seeing the same behavior. Any ideas?

**Comment by iMansoorAliKhan** [comment]
Hi @marpstar ,

We are looking into this and will get back to you as quickly as we can.

Thanks!
Mansoor

**Comment by iMansoorAliKhan** [comment]
@marpstar  I think we may need to dig deeper into this. I have added to our backlog and will get this tested and sorted in a future release.
Thanks for bringing this to our attention.

Regards.
Mansoor.

**Comment by angelleye** [comment]
This has been fixed in our dev branch and will be included in the next update that we'll be releasing this week.

**Comment by marpstar** [comment]
thank you, @angelleye!
