### ISSUE TITLE
Allow custom handling of error messages

### ISSUE THREAD

**Issue by victorwtorres** [angelleye/paypal-woocommerce#1269]
**Problem**
We are experiencing some problems using this plugin on our checkout page. When an error occurs in the credit card section, the code in https://github.com/angelleye/paypal-woocommerce/blob/release/classes/wc-gateway-braintree-angelleye.php `unique_form_for_validation.prepend('<ul class="woocommerce-error"><li>' + err + '</li></ul>');` just prepends the error message to the checkout form. We would like to instead display the error with our own javascript error message.

**Expected behavior**
Some kind of option that allows us to handle the error messages ourselves, and then disables the normal error behavior (scroll to, remove).

**Comment by iMansoorAliKhan** [comment]
Hi @victorwtorres ,

Thanks for writing us here, we are looking into it and will get back to you asap.

Thanks!
AngellEYE Customer Care

**Comment by iMansoorAliKhan** [comment]
I'm not sure if that's possible becasue we are displaying what comes in response from Braintree's error aray and having that customized with some external message seems not possible. But I'm going to add this to our backlog and we will look into this and see if there will be any way to add an option like that then ll get that done in a future release.

Thanks for your feedback though.
AngellEYE Customer Care

**Comment by iMansoorAliKhan** [comment]
PFW-351

**Comment by victorwtorres** [comment]
That's understandable, thanks for looking into this!
