### ISSUE TITLE
Payments Pro (PayFlow) - JCB Cards

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#127]
PayFlow supports JCB cards, but the plugin is doing something odd.

When I try to test with a JCB card number the CCV field and all of the logos disappear.  I can still enter the card number, but I can't enter a security code.

If I enter Visa, MC, Amex, Discover, then the CCV stays with just that one logo showing up.  

It's nice validation, but for JCB there is no logo and the security digits field goes away, which isn't good.  Need to look into whether the code is simply ignoring JCB or for some reason specifically removing the logo and CVV when JCB is selected.

I'm thinking it's probably left out and needs to be handled like the others.

**Comment by angelleye** [comment]
I'm getting a merge conflict on this one when I try to merge to my local branch.  In paypal-for-woocommerce.php I'm running into 2 conflicts.

~~~
<<<<<<< HEAD
                echo '<div class="paypal_box_button" style="position: relative;">';
=======
                echo '<div class="paypal_box_button">';
>>>>>>> origin/issue#127
~~~

~~~
<<<<<<< HEAD
                ?>
                <div class="blockUI blockOverlay angelleyeOverlay" style="display:none;z-index: 1000; border: none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; opacity: 0.6; cursor: default; position: absolute; background: url(<?php echo WC()->plugin_url(); ?>/assets/images/ajax-loader@2x.gif) 50% 50% / 16px 16px no-repeat rgb(255, 255, 255);"></div>
                <script type="text/javascript">
                    jQuery(document).ready(function($){
                        $(".paypal_checkout_button").click(function(){
                            $(".angelleyeOverlay").show();
                            return true;
                        });
                    });
                </script>
                <?php
=======
>>>>>>> origin/issue#127
~~~

I'm not sure what needs to stay and what doesn't..??

**Comment by levansy2020** [comment]
Can you give me the line number?
