### ISSUE TITLE
Change the ranking of PayPal on checkout page is not working

### ISSUE THREAD

**Issue by sagitaire123** [angelleye/paypal-woocommerce#1275]
There's a problem with this new version, on payment section of woocommerce there's different Installed payment methods which are listed and can be sorted to control their display order on the frontend, for PayPal we can't sort it, raise or lower it, it's not working, it always remains at the bottom of the list on the checkout page.

**Comment by iMansoorAliKhan** [comment]
Hi @sagitaire123 ,

I'm so sorry for the inconvenience, but I'm not able to understand whats not working? Can you share some screenshot or video may be which explains what issue you are having with our plugin and I will be happy to assist further.

Thanks!
AngellEYE Customer Care

**Comment by iMansoorAliKhan** [comment]
@sagitaire123  Thanks for waiting, we have this adjusted and wil be included in our next update.

I'm going to go ahead and close this now, But feel free to write here again if there will be any other questions or concerns.

Thanks!

**Comment by iMansoorAliKhan** [comment]
fixed : PFW-359

**Comment by sagitaire123** [comment]
Please can you make an update as soon as possible ? we need to fix this issue.

**Comment by iMansoorAliKhan** [comment]
Hi @sagitaire123 
We have closed our February Sprint and we are about to release 1.5.8 update which will have an adjustments for this. Please stay tuned for updates in your dashboard and as soon as you see it , hit update and will be great if you can leave your feedback here.

Make sure to clear all CDN and Plugin caches in your site.

Thanks!
Oliver


*Oliver Green*
Angell EYE Customer Support Specialist
[www.angelleye.com|https://www.angelleye.com] | [Join Our Newsletter|https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature]
[Subscribe to Our YouTube Channel|https://www.youtube.com/user/angelleyeconsulting] | [Like Our Facebook Page|https://facebook.com/angelleyeconsulting/]

**Comment by angelleye** [comment]
@sagitaire123 Please install our Updater plugin so that you can continue to get updates directly from us going forward:  https://www.angelleye.com/product/angelleye-helper-wordpress-updater/
