### ISSUE TITLE
Problem with Mastercard card type

### ISSUE THREAD

**Issue by raphaelsramos** [angelleye/paypal-woocommerce#1282]
I'm having the following problems with the PayPal REST module:

{
	"field":"payer.funding_instruments[0].credit_card.type",
	"issue":"Credit card type must be visa, mastercard, amex, jcb, or discover."
}

The full log can be found on https://gist.github.com/raphaelsramos/01a6232055a1e70a15aaecd87573075e, but using Mastercard cards it always return "Card" type.

For test i've get the **card_type_from_account_number($account_number) ( angelleye-includes/angelleye-utility.php, line 951 )** function and test it with full number and with only the first 4 number, as used on **set_card_type($card_data) ( angelleye-includes/paypal-rest-api-utility.php, line 378 )**

The file used for test can be found on https://gist.github.com/raphaelsramos/11e824053bff8c91f4f818a24431e124

Based on Mastercard regex ( '/^5[1-5][0-9]{5,}|222[1-9][0-9]{3,}|22[3-9][0-9]{4,}|2[3-6][0-9]{5,}|27[01][0-9]{4,}|2720[0-9]{3,}$/i' ), will be needed at least the 5 first numbers to check Mastercard type.

WP Version: 5.0.3
Plugin Version: 1.5.7

**Comment by raphaelsramos** [comment]
I'm having the following problems with the PayPal REST module:

{
    "field":"payer.funding_instruments[0].credit_card.type",
    "issue":"Credit card type must be visa, mastercard, amex, jcb, or discover."
}

The full log can be found on https://gist.github.com/raphaelsramos/01a6232055a1e70a15aaecd87573075e, but using Mastercard cards it always return "Card" type.

For test i've get the **card_type_from_account_number($account_number) ( angelleye-includes/angelleye-utility.php, line 951 )** function and test it with full number and with only the first 4 number, as used on **set_card_type($card_data) ( angelleye-includes/paypal-rest-api-utility.php, line 378 )**

The file used for test can be found on https://gist.github.com/raphaelsramos/11e824053bff8c91f4f818a24431e124

Based on mastercard regex ( '/^5[1-5][0-9]{5,}|222[1-9][0-9]{3,}|22[3-9][0-9]{4,}|2[3-6][0-9]{5,}|27[01][0-9]{4,}|2720[0-9]{3,}$/i' ), will be needed at least the 5 first numbers to check mastercard type.

**Comment by iMansoorAliKhan** [comment]
ref: pfw-369
