### ISSUE TITLE
Order sessions mix up

### ISSUE THREAD

**Issue by moshie** [angelleye/paypal-woocommerce#1288]
Hi,

Plugin Version: 1.5.7
Woocommerce Version: 3.4.4

**Describe the bug**
After a user is redirected back to the site prior to making an order their user session is being mixed up with other guests / logged in users also making an orders.

This results in users orders becoming mixed up and consequently being paid for by other users.

We have been unable to replicate this on staging and we cannot produce the same volume of orders at the same time to try and force it.

It's worth mentioning that on our client's site we have a plugin called jwt-authentication-for-wp-rest-api which when disabled on production no longer causes the issue. We however, need this plugin to communicate with a packing application they have.

Currently we have the Paypal Gateway plugin disabled until we can pinpoint the issue and implement a fix.

Is there a part of this plugin / woocommerce which modifies the session on the return url?

**What have you considered**
- Perhaps it was being cached? (only difference between staging and production)
- Maybe sandbox treats the session differently to live?

**Comment by angelleye** [comment]
@moshie Just to verify, is this the plugin you're using?  https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/

Are you on WP Engine hosting, or who is your host?  

If you are unable to reproduce the problem it's going to very difficult for us to do so as well, but we can certainly take a look at their plugin to see if we can spot any issues that could potentially cause this.

When this happens do the users still see all of the order details they expect to see, but the order total charged is simply different?  I'm having a hard time understanding the experience, and how these orders are getting all the way through under the wrong user.  That is..extremely strange.

Our plugin simply takes what the Woo object feeds it, so we need to figure out how that Woo object is getting its data sessions mixed up.  

Any additional detail you can provide here to help us reproduce would be appreciated.  I'll get it into our workflow here, but it probably will have to wait until our March sprint, as this is the only report we have of this.

**Comment by moshie** [comment]
@angelleye Thanks for getting back so quickly.

That's the correct plugin.

The website is hosted on a litespeed server.

After giving the JWT plugin a once over I did notice it hooked into determine_current_user maybe this can help you while looking through the plugin.

**When this happens do the users still see all of the order details they expect to see, but the order total charged is simply different?**
It's a very strange and complex issue. Of the users who experienced this issue we noticed the shipping method and billing was correct however, the Customer had been set incorrectly under the orders.
I assume since the users where unable to share that information they where presented with the correct information but did not notice the session had changed.

**Any additional detail you can provide here to help us reproduce would be appreciated.**
I appreciate the quick action on this and any further details or information I can produce I will be sure to pass on to you.

**Comment by angelleye** [comment]
Yes, this has to be something to do with what they're doing with determine_current_user.  Have you reached out to them about this at all?  Maybe they could give us an idea of what's going on if we explain that the Express Checkout workflow takes you offsite temporarily, and then returns.

Also, are you using Smart Buttons in our plugin so the login happens on top of your site, or are you using regular buttons that do a full redirect to PayPal and back?

**Comment by moshie** [comment]
I have a github issue open with them at the moment https://github.com/Tmeister/wp-api-jwt-auth/issues/143 no reply as of yet.

The site is using regular buttons implementing the full redirect from paypal.

**Comment by angelleye** [comment]
Okay, we have to stay focused on some other things to wrap up our Feb. Sprint, but I've added this to our March Sprint for review.

Hopefully they'll be able to provide some sort of guidance on what could be the problem.  In any case, we'll install the plugin and review it to see if we can find what's causing this.

**Comment by drewangell** [comment]
@moshie Did this get resolved or are you still having troubles with it?

**Comment by moshie** [comment]
Its been so long I can't remember. Don't think I've run into it since. I'll close this ticket
