### ISSUE TITLE
Undefined index: nonce

### ISSUE THREAD

**Issue by alx359** [angelleye/paypal-woocommerce#1297]
Sporadically I'm getting the following notices in the log (WP_DEBUG=true):

`PHP Notice:  Undefined index: nonce in /plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye.php on line 931`

Line 931 says:

```
if (!wp_verify_nonce($_POST['nonce'], '_angelleye_generate_cart_nonce')) {
    wp_die(__('Cheatin&#8217; huh?', 'paypal-for-woocommerce'));
}
```

An obvious quick-fix would be adding `isset($_POST['nonce'])` to the if-clause, but are those hacking attempts? Please advise.

Thanks.

**Comment by iMansoorAliKhan** [comment]
Hi @alx359 

Thanks for the feedback, although we are not getting any reports of this sort nor we are seeing this on our production and development setup. But we will still look into that and make necessory adjustments .

Can you tell me your server's PHP version that you are using also wordpress and woo versions as well?
That will really help us figure out what caused this notice and we will be happy to make amends accordingly.

Thanks!
Oliver


*Oliver Green*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by alx359** [comment]
Hi Mansoor,

Thanks for your reply. The notice seems an edge case, hence me asking if it might be a hacking attempt.

My production WP is on a DigitalOcean droplet (VPS), fully updated, and generally well taken care of: 

PHP 7.1.27
Woocommerce 3.5.6
WP 5.1.1
  
Thank you.

**Comment by iMansoorAliKhan** [comment]
@alx359 

Thanks, I have updated the ticket with your  feedback, we will look into that and get this adjusted probably my the end of march sprint. If not then not later than the April Sprint.

Thanks!
Oliver


*Oliver Green*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by alx359** [comment]
Thanks you too, Oliver. No worries, it's obviously a tiny mostly cosmetic adjustment. 

BTW, when are you planning to update the updater to support the free stuff too?
