### ISSUE TITLE
Version 2.0.0 doesn't work with Paypal

### ISSUE THREAD

**Issue by MrNghia123** [angelleye/paypal-woocommerce#1313]
When testing payment using a customer Paypal account, I got this error message all the time after logging in:
"We're sorry, things don't appear to be working at the moment. Please try again later."

Log files:
2019-05-04T02:06:22+00:00 INFO Redirecting to PayPal
2019-05-04T02:06:22+00:00 INFO PayPal for WooCommerce Version: 2.0.0
2019-05-04T02:06:22+00:00 INFO WooCommerce Version: 3.6.2
2019-05-04T02:06:22+00:00 INFO Test Mode: 
2019-05-04T02:06:22+00:00 INFO Endpoint: https://api-3t.paypal.com/nvp
2019-05-04T02:06:22+00:00 INFO SetExpressCheckout Request: Array
(
    [USER] => *****
    [PWD] => *****
    [VERSION] => 124.0
    [BUTTONSOURCE] => AngellEYE_SP_WooCommerce
    [SIGNATURE] => *****
    [METHOD] => SetExpressCheckout
    [RETURNURL] => https://teehubble.com/wc-api/WC_Gateway_PayPal_Express_AngellEYE/?pp_action=get_express_checkout_details
    [utm_nooverride] => 1
    [CANCELURL] => https://teehubble.com/cart/?utm_nooverride=1
    [ALLOWNOTE] => 1
    [ADDROVERRIDE] => 1
    [LOCALECODE] => en_US
    [HDRIMG] => https://teehubble.com/wp-content/uploads/2019/05/logo780x90.png
    [BRANDNAME] => TeeHubble
    [SOLUTIONTYPE] => Sole
    [LANDINGPAGE] => Login
    [PAYMENTREQUEST_0_AMT] => 20.99
    [PAYMENTREQUEST_0_CURRENCYCODE] => USD
    [PAYMENTREQUEST_0_PAYMENTACTION] => Sale
    [PAYMENTREQUEST_0_SHIPTONAME] => David Hoang
    [PAYMENTREQUEST_0_SHIPTOSTREET] => 2986 Charmaine Lane,
    [PAYMENTREQUEST_0_SHIPTOCITY] => Odonnell
    [PAYMENTREQUEST_0_SHIPTOSTATE] => TX
    [PAYMENTREQUEST_0_SHIPTOZIP] => 79351
    [PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE] => US
    [L_PAYMENTREQUEST_0_NAME0] => Caticorn Cat Unicorn Rainbow T-Shirt-11 oz. Black Mug - Black, One Size
    [L_PAYMENTREQUEST_0_DESC0] => Color: black Size: one-size
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_AMT0] => 16.00
    [L_PAYMENTREQUEST_0_NUMBER0] => tc-150266-150240-1065-10181-49307
    [PAYMENTREQUEST_0_TAXAMT] => 0.00
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 4.99
    [PAYMENTREQUEST_0_ITEMAMT] => 16.00
)

2019-05-04T02:06:22+00:00 INFO SetExpressCheckout Response: Array
(
    [TOKEN] => EC-0JG78450LU558344X
    [TIMESTAMP] => 2019-05-04T02:06:22Z
    [CORRELATIONID] => 313913281c00f
    [ACK] => Success
    [VERSION] => 124.0
    [BUILD] => 52688019
)

**Comment by angelleye** [comment]
Hi, sorry for the delay replying here.  For future reference, it's best to use our [help desk](https://www.angelleye.com/support) for general questions like this.

The API call here shows successful, so if you were seeing a problem on the PayPal screen, that is not something related to our plugin.

If this continues, try clearing your browser cache / cookies.  This can help if/when that sort of thing happens.

Let me know if you continue to have problems, though, and I can try to help more.
