### ISSUE TITLE
Paying via Paypal Express Checkout ignores discount

### ISSUE THREAD

**Issue by njbarrett** [angelleye/paypal-woocommerce#1328]
Hi there,

We have quite a significant issue where this plugin is removing any discounts applied at checkout once the user reaches the paypal screen.

Here's an example of what the line items are on paypal:
![Screen Shot 2019-06-12 at 3 47 47 pm](https://user-images.githubusercontent.com/241407/59334255-a81c1180-8d2c-11e9-88bc-931ded171e62.png)

As you can see, another line item is added that offsets the intended discount.
Can you please shed some light?

**Comment by iMansoorAliKhan** [comment]
Hi @njbarrett ,

How the discounts are being added there?  Are you using any plugins to offer those discounts?
Do you have logging enabled and can provide logs for our review please?

Thanks!
Oliver


*Oliver Green*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by njbarrett** [comment]
@iMansoorAliKhan Hi Oliver,
The discount in this case is a "store credit" provided by Woocommerce Smart Coupons plugin. https://woocommerce.com/products/smart-coupons/
The store credit is applied by the user entering the voucher code at checkout.

Could you let me know where the logs can be found / enabled for your review?

Thanks

**Comment by iMansoorAliKhan** [comment]
Did you tried disabling our plugin and the see how the line-item is forward to PayPal ( using Standard Paypal ) or Tried disabling your discount plugin and see how that goes?

You can find logging option in express checkout settings > Scroll down to bottom of it ( Above smart button option). Enable it, process an order and then get the updated logs ( date wise ) from **WOO > Status > Logs**.

Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by angelleye** [comment]
@njbarrett Which version of the plugin are you running?  Are you on 2.0?  You should see an option in the Express Checkout settings for Subtotal Mismatch Behavior.  Please set it to not send any line items, like this.

<img width="655" alt="Screen Shot 2019-06-17 at 3 08 26 PM" src="https://user-images.githubusercontent.com/629241/59633308-d37a7400-9111-11e9-8e73-34833a108a6c.png">

Let me know if that helps.  Thanks!

**Comment by angelleye** [comment]
@njbarrett Have you still been having this issue?

**Comment by njbarrett** [comment]
No, I think this can be closed. Thank you for the help.

**Comment by iMansoorAliKhan** [comment]
@njbarrett @angelleye Our last Update 2.1.2 also contains few fixes related to this one. So I am sure things will work smoothly now.

As such, I am going to close this ticket now, but please feel free to respond here again or create a new ticket if you have any more questions or concerns.

Also, we would love to know what you think of our product and customer support. If you have a moment to [leave a review](https://www.angelleye.com/product/woocommerce-paypal-plugin/#tab-reviews) it would be greatly appreciated.

Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by consciousimages** [comment]
This is still happening for us, earlier today tried the fix [mentioned above](https://github.com/angelleye/paypal-woocommerce/issues/1328#issuecomment-502831983), but still happening... we're using v. 1.5.7.

Removing a lot of fields here, but this is the gist of what's happening:

`2019-11-29T16:04:06+00:00 INFO GetExpresscheckoutDetails Response: Array
(    [PAYMENTREQUEST_0_AMT] => 613.00
    [PAYMENTREQUEST_0_ITEMAMT] => 594.00
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 19.00
    [PAYMENTREQUEST_0_HANDLINGAMT] => 0.00
    [PAYMENTREQUEST_0_TAXAMT] => 0.00
    [L_PAYMENTREQUEST_0_AMT0] => 699.00
    [L_PAYMENTREQUEST_0_AMT1] => -105.00
    [L_PAYMENTREQUEST_0_DESC1] => Discount Amount
)`

Those fields are all correct.  But then this:

`2019-11-29T16:05:08+00:00 INFO DoExpressCheckoutPayment Request: Array
(    [PAYMENTREQUEST_0_AMT] => 718.00
    [L_PAYMENTREQUEST_0_AMT0] => 699.00
    [L_PAYMENTREQUEST_0_NUMBER0] => Cu1
    [PAYMENTREQUEST_0_TAXAMT] => 0.00
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 19.00
    [PAYMENTREQUEST_0_ITEMAMT] => 699.00
)`

Followed by this:

`2019-11-29T16:05:08+00:00 INFO DoExpressCheckoutPayment Response: Array
(    [PAYMENTINFO_0_AMT] => 718.00
    [PAYMENTINFO_0_FEEAMT] => 21.12
)`

Both of which are wrong - no discount.

**Comment by angelleye** [comment]
@consciousimages You are quite a bit behind on updates at this point.  Please install our Updater plugin:  https://www.angelleye.com/product/angelleye-updater-wordpress/

Then go to Dashboard -> Updates and click the Check Again button.  You might have to click it a few times, but then you should see our update show up there.  Current release is 2.1.9.

https://github.com/angelleye/paypal-woocommerce/releases

It would be best to get updated, and then if you continue to see problems let me know and we'll get it handled.  Thanks!

**Comment by consciousimages** [comment]
@angelleye Thanks so much for the unbelievable quick response!  Actually right after I commented I noticed the v.2.1.2 tag just above my comment and realized that something wasn't right and went to your site and got everything sorted out -- I installed the updater, didn't work at first (I see you say to refresh a few times), so I just created an account and downloaded it from your site.  I'm sure this fixes it but will definitely report back if not.  Thanks again!

**Comment by angelleye** [comment]
@consciousimages Glad you got it worked out.  If you have any other general problems it's best to submit a ticket to our help desk:  www.angelleye.com/support

If you do anything where you want to submit a pull request then you can do that here, of course.

Thanks!
