### ISSUE TITLE
Conditionals to establish whether one is on order review page

### ISSUE THREAD

**Issue by gbruzzo** [angelleye/paypal-woocommerce#1339]
Dear All,

this is a query: We need to differentiate between **_'being on the checkout page'_** and **_'being on the Checkout page after having returned to it from PayPal Express for Order Review'._**

This would allow us to run code (via functions.php)  **_only_** when the customer is on the Checkout Page, and not when she has returned from PayPal.

What conditional can be used? It would be a refinement if **is_checkout()** (that is trivial of course). 

Thank you in advance for any advice you may be able to impart

Giacomo Bruzzo

**Comment by angelleye** [comment]
Thanks for the suggestion!  We're just about to release a 2.1.0 update, and then I can get this request added to the next version after that.  

We can keep you posted here so that you can grab the release branch just as soon as this is completed if you'd rather not wait for the full update.

**Comment by gbruzzo** [comment]
Dear Mr Angell

thank you for you reply. Do you have a rough idea of the timeframe associated (how many months?). 

thanks again

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
Dear @angelleye 

this works for now 

```
add_action( 'woocommerce_before_checkout_form', 'txt_before_paypal', 4);

function txt_before_paypal() {
	$paypal_express_checkout = WC()->session->get('paypal_express_checkout');
	if(!is_admin() && is_main_query() && in_the_loop() && is_page() && is_checkout() && !empty($paypal_express_checkout)) {
	return;
	}
	else {
CODE
	}
}

add_action( 'woocommerce_before_checkout_form', 'txt_after_paypal', 6);

function txt_after_paypal() {
	$paypal_express_checkout = WC()->session->get('paypal_express_checkout');
	if(!is_admin() && is_main_query() && in_the_loop() && is_page() && is_checkout() && !empty($paypal_express_checkout)) {
	return;
	}
	else {
CODE
	}
}

add_action( 'woocommerce_after_checkout_form', 'txt_at_bottom', 100);

function txt_at_bottom() {
	$paypal_express_checkout = WC()->session->get('paypal_express_checkout');
	if(!is_admin() && is_main_query() && in_the_loop() && is_page() && is_checkout() && !empty($paypal_express_checkout)) {
	return;
	}
	else {
CODE
	}
}

```

```
$paypal_express_checkout = WC()->session->get('paypal_express_checkout');
	if(!is_admin() && is_main_query() && in_the_loop() && is_page() && is_checkout() && !empty($paypal_express_checkout))
```
is straight from the helper - all seems to work, until a more concise and packaged solution is found. 

Cheers!

Giacomo Bruzzo

**Comment by angelleye** [comment]
Glad you got something working.  We'll review this in our August sprint.  Thanks!

**Comment by iMansoorAliKhan** [comment]
PFW-451
Closing this ticket for now but will update here when this issue will be addressed.
