### ISSUE TITLE
Plugin removed from WordPress plugin directory

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1374]
@kcppdevelopers, @angelleye: This plugin isn't available in WordPress plugin directory anymore (https://wordpress.org/plugins/paypal-for-woocommerce/). What is the reason for this?

Related: https://wordpress.org/support/topic/plugin-removed-from-wp/

**Comment by angelleye** [comment]
We moved all of our plugins to our own hosting servers, and most of them are now paid plugins.  

This plugin is still and will remain free.  We still have a few other free plugins as well, but most are now paid, and running from our own systems.
