### ISSUE TITLE
Security error / Security header is not valid

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1377]
Since today all payment attempts fail with a `Security error`:
````
10-18-2019 @ 18:25:55 - SetExpressCheckoutArray
(
    [TIMESTAMP] => [...]
    [CORRELATIONID] => [...]
    [ACK] => Failure
    [VERSION] => 115
    [BUILD] => 53734851
    [L_ERRORCODE0] => 10002
    [L_SHORTMESSAGE0] => Security error
    [L_LONGMESSAGE0] => Security header is not valid
    [L_SEVERITYCODE0] => Error
)
````

**Comment by angelleye** [comment]
This error means that your API credentials are incorrect.  Please double check the values themselves, and also make sure you are not filling in sandbox account credentials in the live fields or vice-versa.

**Comment by strarsis** [comment]
@angelleye: Is it possible that PayPal (production) API credentials need to be renewed from time to time? The issue started today and I hadn't changed anything on the site.

**Comment by angelleye** [comment]
No, that's not something that would be necessary.  One way or another the credentials must simply be incorrect in order for this error to be coming back.

I would suggest clearing any caching / CDN tools you might be running, and then double check the gateway settings and the values entered to be sure they're good.  Maybe re-enter them even if they're already showing up.  Then click Save and that should make everything fresh again.

One thing I know could cause this is if the SALT settings in the config file get adjusted at all.  Do you know if that happened?

**Comment by strarsis** [comment]
@angelleye: Thanks for your answer. I will re-enter the settings and clear available caches.
Are the SALt settings the WordPress salts (like https://roots.io/salts.html)?

**Comment by strarsis** [comment]
@angelleye: I have re-entered all the API fields and now it works!
Apparently characters in one field had been accidentally removed.

**Comment by angelleye** [comment]
Glad you got it worked out!
