### ISSUE TITLE
Third-party support

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1378]
It is possible to give a third party permission to access PayPal. One can then pass to API with ones own account in what name the transaction should be created. Is this also possible with this plugin?

**Comment by angelleye** [comment]
That works well with hosted solutions, but in order to do that here we'd have to ship the plugin with our own API credentials in it.  Of course, that's not something we can do.

**Comment by strarsis** [comment]
@angelleye: Ah, so I misunderstood how it works. I thought my webmaster/dev PayPal account can be authorized to create/manage orders for another PayPal account.
