### ISSUE TITLE
[Feature request] PayPal Integrated Signup

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1379]
The [PayPal Express Checkout Gateway plugin from WooCommerce](https://de.wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/) shows a link that can be clicked, one can then log into PayPal and then the API key is automatically created and the API fields filled with all necessary data. This seems to be some kind of OAuth PayPal feature.
This would be a really awesome feature for this plugin.

**Comment by angelleye** [comment]
Yes, this is done through "Integrated Signup".  It's similar to the 3rd Party Permissions you were asking about, but a little different.  We do plan to get this done, but it hasn't been made a priority as of yet.

**Comment by drewangell** [comment]
We will be integrating the latest version of PayPal's SDK into the plugin as a new gateway soon.  This will include Integrated Signup and a lot of other improved features.
