### ISSUE TITLE
WooCommerce Orders

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#138]
When you create an order (customer invoice) in WooCommerce, and the customer clicks the link to pay for the order, the Express Checkout method doesn't work here.  We need to get that working so people can pay with PayPal when paying for an order/invoice.

**Comment by angelleye** [comment]
This may be related to #34

**Comment by levansy2020** [comment]
Hi Andrew,

Can you check this one? I need it to merge to dev to continue with other PayPal Express issues

**Comment by angelleye** [comment]
This functionality is working in our latest release.
