### ISSUE TITLE
PayPal IPN for WordPress Integration

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#139]
I'm building the "PayPal IPN for WordPress" plugin that will provide hooks for triggering functions based on txn_type's.  When that is ready, this will need to be integrated here so we can automate post-order tasks.

**Comment by angelleye** [comment]
I'd like to provide an option in settings to configure IPN, which will need to download/install PayPal IPN for WordPress.

Then within PayPal for WooCommerce you can choose to update the WooCommerce order status based on the payment_status returned for the IPN.

For example, and option to "enable pending payment management via IPN" would set the WC order as Pending and would also provide the reason for the pending status within the order details (may need to add a new meta-data field for "pending_reason").

Then they could also set what order status they want to set the WC order to when the payment_status gets updated to Completed and that IPN is triggered.

**Comment by angelleye** [comment]
Something to keep in mind here is that if the site owner is using an invoice prefix on their gateway settings then we'll need to look that up and do a str_replace() to remove it so that we can pull the WC order object using the actual ID value without any prefix.

**Comment by angelleye** [comment]
I actually did this in my Hook Tester and was very simple.

```
function update_wc_order_status($posted) {
    $order_id = isset($posted['invoice']) ? str_replace('woo-','',$posted['invoice']) : '';
    $order = new WC_Order($order_id);
    $order->update_status('completed', 'PayPal IPN updated order to completed.');
}
add_action('paypal_ipn_for_wordpress_payment_status_completed', 'update_wc_order_status', 10, 1);
```

**Comment by angelleye** [comment]
@kcppdevelopers I'm a little bit confused looking at this.  I'm not sure you understood what I was thinking here.

From what I see in the commits it seems you basically built a new IPN system into our plugin..??  I was thinking more along the lines of providing the option to install our IPN plugin, and then providing some simple settings based options for them to choose how to handle order status with IPNs coming through to our IPN plugin listener.

Let's talk about this when you get in today.

**Comment by kcppdevelopers** [comment]
@angelleye  I understand your concern, I will resolved this issue and let you know.

**Comment by angelleye** [comment]
@kcppdevelopers We should probably discuss this before you get working on it again.  We may even need to remove these changes and move the issue to 1.4.1 because we gotta get this 1.4.0 update released.
