### ISSUE TITLE
Paypal Express Checkout (new) credit card form causes checkout to hang

### ISSUE THREAD

**Issue by gbruzzo** [angelleye/paypal-woocommerce#1408]
Hello there again

to replicate the issue: 

- paypal smart button among different payment gateways on checkout (at the bottom of checkout therefore).
- select credit card 
- form starts loading - forms appear but the checkout hangs (checkout ajax is stuck)

Tried with most recent WP, WC and Storefront

Giacomo Bruzzo

**Comment by angelleye** [comment]
I believe that part is something that is controled/hosted by PayPal, and I know they did confirm problems on their end when they first introduced those new embedded CC forms.  That's what you're talking about, right?  Instead of the pop-up, it just attempts to load an embedded form?

Can you provide screenshot or small demo video, by chance?  I would like to pass this back to my contacts at PayPal.

**Comment by gbruzzo** [comment]
Hello there @angelleye 

you are correct - I am indeed talking about the new embedded forms. 

Here is a short video [https://www.dropbox.com/s/jqgrwjzsontc1lw/Screen%20Recording%202019-12-28%20at%2010.24.22.mov?dl=0](url)

WP + WC + Paypal for Woocommerce + Angelleye Updater / Storefront theme

As you can see, the checkout hangs after the CC card form is requested. 

How to bypass the problem temporarily? 

I will set the cards not to be shown + request Guest Checkout (so the CC form appears as part of the PayPal popup, as was the case until this latest update).

Kind regards

Giacomo Bruzzo

**Comment by angelleye** [comment]
Thanks for the details.  We'll dive into this and see if there's something on our end we need to adjust, but this was verified a problem on PayPal's side last time we saw it, so I'm guessing that's what it is again.  I'll certainly let them know if we don't find something on our end.

I'll keep you posted here.

**Comment by gbruzzo** [comment]
You are welcome, hope this issue can be solved

**Comment by gbruzzo** [comment]
Hello there 

touching base to see if you had received any feedback about the issue. 

Warm regards

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
Hello @angelleye 

I just noticed another issue involving the new credit card forms: **when the user is logged in, the new forms do not pre-fill with his/her information.** The previous forms (pop-up forms) would instead pre-fill while the previous forms would pre-fill correctly. 

Do you have any news about the matter discussed above?

Thanks in advance 

Giacomo Bruzzo

**Comment by iMansoorAliKhan** [comment]
@gbruzzo ,

We are so sorry for the delay in response here, we are looking into that and will get back to you with more feedback soon.

Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by iMansoorAliKhan** [comment]
@gbruzzo can you tell me what is the version of our plugin that you are using right now? I just tested on our test site and I am not seeing that Layout anymore.  Or may be you can share your site URL with me and I will be happy to take a quick look and see whats going on there.

Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by gbruzzo** [comment]
Hi there!

Latest version of PayPal for Woocommerce

(Near to) Production Site (RareNoiseRecords.com) shows in-page form (which
works on the cart page, but not on the checkout page) - this site is
password protected at the moment.

Staging site shows popup form (old layout, which works)

Are PayPal A/B testing?

Giacomo

**Comment by gbruzzo** [comment]
Plugin is 2.1.12 (latest)

**Comment by gbruzzo** [comment]
Hello @iMansoorAliKhan 

just swapped the regular api credentials (UK PayPal Account) with sandbox api credentials : 

with Sandbox credentials : Credit card form is a popup (and does not cause issues with the WC Checkout)

with regular (production) credentials (UK account) : Credit card form is the ajaxed dropdown (which causes the WC Checkout to hang)

Can you confirm it from your side? 

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
Hello @iMansoorAliKhan 

I spoke too soon - the embedded form has started appearing again with production credentials. 

I wish this hideous form went away! 

1. It causes an ajax **conflict** on the Woocommerce checkout page 

2. font-size on the form is 15px - **this should be at least 16px**, to avoid the the fastidious **zooming in** when you enter text in the form 

3. **it does not pre-populate with the billing address** when the customer is logged in. This means the customer has to **re-enter the data**, which will result in a higher rate of cart abandonment. Good UX would be : pre-populate with such data but offer a button to **'clear the form'** (in case the card's billing address differs from the user's account billing address).

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
Hello there @angelleye @iMansoorAliKhan 

touching base on this issue again. 

For a month clicking on credit cards during checkout resulted in the old popup appearing. 

Two days ago, the new form started appearing again, both on our staging site (with sandbox account) and our production site. 

- PayPal have **not resolved the issue**, the checkout form still hangs 

see [Video](https://www.dropbox.com/s/v4zx5fuhw5kgqlp/Checkout%20Problem%20PayPal%20Angelleye.mov?dl=0)

- the font in the form is 15px - this causes telescoping issues when filling the form (on the cart), 16px is the minimum required to avoid 'zooming in' the forms on mobile (iOS, all browsers). The css lives in an iframe and is therefore inaccessible. 

- The form appears **very slowly** , **bad** UI and **bad** UX

- The form does not pre-fill with customer billing data or provide an option for pre-filling. 

=> We cannot understand why we are being subjected to this A/B testing (if that is the case), and would like to revert to the old popup form  

Could you please assist?

Thanks in advance 

Giacomo Bruzzo

**Comment by angelleye** [comment]
@gbruzzo We will certainly pass this info back to PayPal to show them the experience.  Unfortunately, there's nothing we can do about it from our side.  There isn't any option or anything where we can specify the experience.  That's totally controlled by PayPal.  

They seem to think they had it fixed, but we'll pass along this evidence.  Thanks for the info!

**Comment by angelleye** [comment]
@gbruzzo Well, one option you would have is to turn off the Smart Buttons.  That would make it work the old way, which wouldn't use any of their methods.  Of course, the button doesn't look as good, but you can set your own graphic in that case if you want to.  Just an option to consider.

**Comment by strarsis** [comment]
@gbruzzo: Does the issue still persist?

**Comment by gbruzzo** [comment]
@strarsis Hi there, sorry for delay in answering. 

Just checked now - the **issue still persists**. Selecting the Card option causes the checkout (ajax) to hang. 

Just to be clear, this issue does not occur when using the Standard Woocommerce PayPal Checkout Express plugin. 

I am still convinced, therefore, that this issue is a bug. 

Giacomo

**Comment by drewangell** [comment]
@gbruzzo Sorry, I haven't been keeping up with these issues because my primary focus is our [help desk](https://angelleye.com/support).  Please use that in the future.

If you're still having problems with this go ahead and submit a ticket there and I'll work with you more to resolve this.
