### ISSUE TITLE
Paypal Rest API Version 2.0

### ISSUE THREAD

**Issue by luohui8891** [angelleye/paypal-woocommerce#1426]
Hi guys,

I am doing with the Paypal Rest API to enable payment with credit card on my side.
But the /v1/payment/payment always respond UNAUTHORIZED_PAYMENT.
I google it and found the reason may be this plugin using version 1.0 API which is deprecated.

Do you have plan to upgrade it to [version 2.0](https://github.com/paypal/Checkout-PHP-SDK)?

**Comment by steve-bailey1** [comment]
I am having this issue as well.  Anyone figure out how to upgrade to 2.0 yet?

**Comment by luohui8891** [comment]
> I am having this issue as well. Anyone figure out how to upgrade to 2.0 yet?

Looks 2.0 just a checkout solution. Not rest API solution.

**Comment by steve-bailey1** [comment]
I meant the paypal v2 API

**Comment by angelleye** [comment]
@luohui8891 @steve-bailey1 Actually, REST DCC (direct credit cards) is no longer available at all.  PayPal is now pointing people towards PayPal Pro or Braintree Payments for that.

Our plugin supports both, but you'll need to set that up separately, and then configure the plugin accordingly.

PayPal Pro will drop payments directly into PayPal instantly like anything else, which is nice.  Braintree is more like a typical merchant account which would deposit payments directly to your bank and can take a couple of days to clear.  It would allow you to also add things like Google/Apple Pay, though, which is beneficial.

Let me know if you have any questions or concerns about that.  Thanks!
