### ISSUE TITLE
When i capure an paypal authorization a new mail is sent

### ISSUE THREAD

**Issue by gine** [angelleye/paypal-woocommerce#1427]
I use your last plugin whit the authorization/capture workflow. 

On my site happens that when i capture the amount, a new mail whit subject "new order #XXX" is sent to the seller address and i hope that this mail is not sent to the buyer too.

That's happen since a lot of time but i have the time only now the time to write to you.

Thanks,
g.

**Comment by iMansoorAliKhan** [comment]
Hi @gine ,
Can you share the screenshot? and are you able to run some test based on the buyer as well?  For example adding your email into a dummy order and do a sandbox authorization and see how that goes? 

Please check that and let me know.

Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by drewangell** [comment]
@gine If you're still having any troubles with this please submit a ticket to https://angelleye.com/support/
