### ISSUE TITLE
Why we are calling the same function twice on line 290 and 291

### ISSUE THREAD

**Issue by deepakmaurya** [angelleye/paypal-woocommerce#1428]
https://github.com/angelleye/paypal-woocommerce/blob/88fa473b347f916e02711ce38538034bbc91e449/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-request-angelleye.php#L290

if ($this->angelleye_ec_force_to_display_checkout_page()) {
                    if ($this->angelleye_ec_force_to_display_checkout_page()) {

This should be once, as its unnecessary calling the function twice.

**Comment by kcppdevelopers** [comment]
@deepakmaurya  This issue now resolved.
