### ISSUE TITLE
Merge conflict in 2.1.15

### ISSUE THREAD

**Issue by clifgriffin** [angelleye/paypal-woocommerce#1438]
Hi all,

Looks like 2.1.15 has a merge conflict that was committed:
wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-utility.php

I fixed it on our side, but here's what the diff looks (this is me cleaning it up, hence the red):
https://www.dropbox.com/s/75eam75yzeicsul/Screenshot%202020-04-03%2009.53.47.png?dl=0

**Comment by iMansoorAliKhan** [comment]
Hi @clifgriffin ,

We are so sorry for he delay in response here. Thanks for the report . the conflict has been resolved and released.

Please update to 2.1.16 and you will not see any trouble.
Closing this ticket now.

.Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)
