### ISSUE TITLE
Incorrect data accessors

### ISSUE THREAD

**Issue by clifgriffin** [angelleye/paypal-woocommerce#1439]
Hi there,

PayPal for WooCommerce is currently using `get_post_meta` to access some order values that may or may not actually be in post meta. For example, we use this plugin:
https://github.com/liquidweb/woocommerce-custom-orders-table

Which means `_payment_method` for example is not in post meta. The proper way to get this value is:
`$order->get_payment_method()`

I added a shim to fix this for now:
```
add_filter( 'get_post_metadata', 'maybe_shim_data', 10, 4 );

function maybe_shim_data( $value, $object_id, $meta_key, $single ) {
	if ( $meta_key == '_payment_method' ) {
		$order = wc_get_order( $object_id );

		$value = $order->get_payment_method();
	}

	return $value;
}
```

I don't know if there are other places with the same problem. This would only apply to native fields, so for example, `_payment_action` is fine and doesn't need a shim.

Clif

**Comment by drewangell** [comment]
@clifgriffin Hey, sorry, I just saw this.  I'll get this into our general queue and we'll get any necessary adjustments done soon.  Thanks for the feedback!

**Comment by drewangell** [comment]
@clifgriffin Thanks again for the feedback.  Our guys have verified this, and we will be improving it in the next update.

**Comment by deepakmaurya** [comment]
@clifgriffin This has been resolved in our recent updates, You can update to the latest version using [AngellEYE Updater](https://www.angelleye.com/product/angelleye-updater-wordpress/)
Thanks 🙏
