### ISSUE TITLE
Can use express checkout button on custom product type product page?

### ISSUE THREAD

**Issue by ajayghaghretiya-multidots** [angelleye/paypal-woocommerce#1440]
How we can use the checkout button on the product page of the custom product type?

Express checkout button is showing for the product type simple and variable products, but in our custom product type, it is not showing.

Checked below code of the function `buy_now_button()`:
` if ($_product->is_type('variation') || $_product->is_type('variable') || $_product->is_type('simple')) {`

Can you allow for a custom product? and add a filter to customize it?

Thanks

**Comment by iMansoorAliKhan** [comment]
Hi @ajayghaghretiya-multidots ,

Thanks for writing to us here.

normally the Smart buttons on the delay page will only show when there is a product price involved which comes from woo price object. So it totally depends on how the product type is configured, if it follows standard woo product schema  and the product page has woo price when it loads then this can be customized . As a default, our of those 2 products types, only 2 are that set Product price when the page loads : simple , variable.

So, right now only these are the supported ones.

Let me know if there will be any other concerns.

**### #StayHome #StayAlive Lets fight #Covid19 together by maintaining Social Distancing**

.Thanks!
Mansoor

*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by ajayghaghretiya-multidots** [comment]
Our custom product type is also configured same like variable condition and if we are updating your if condition which checks the product type and display button then the button works properly.

Can we send you a PR to allow custom product type by filter?
Please do let us know your thoughts about the same.
Thanks

#StaySafe

**Comment by iMansoorAliKhan** [comment]
Hi @ajayghaghretiya-multidots ,

Yeah sure, Please submit a PR and our developer will look into that accordingly.

Thanks!

.Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)
