### ISSUE TITLE
Paypal checkout.min.js requested twice when Smart Payment buttons configured

### ISSUE THREAD

**Issue by alanmillo** [angelleye/paypal-woocommerce#1442]
Hi,

I've noticed "https://www.paypalobjects.com/api/checkout.min.js" is loaded twice when I configure the plugin with "Enable Smart buttons", in context checkoutoption and "Paypal express" enabled. The file is a 191KB. This is also reproducible in your website. 

Reproduce: 
https://www.angelleye.com/product/paypal-help/
Check loaded JS files with Chrome developer tools or similar. Looks like the initiator is different, so might be that once the buttons are loaded, they might fire a request for the same file to be loaded.

The file is requested twice on every page where the smart button is displayed.

This is my configuration, in case it helps having the information:
Paypal for Woocommerce version 2.1.15
Woocommerce 3.9.3
Wordpress 5.3.2

I've tried different configurations of the button, but the only thing that prevents from double downloading the file is not using the smart button at all.

Thanks

**Comment by angelleye** [comment]
Okay, strange.  We'll take a look to see what's going on here and adjust accordingly in another update.  I'll update you here soon.

**Comment by deepakmaurya** [comment]
Yes, i just checked, it's not a bug. It's expected behaviour.  Chrome network tab shows the checkout.min.js load twice because 2nd request is triggered through the smart buttons and we can  not stop that. 

> Smart buttons are loaded inside an iframe, so iframe makes their own set of css and JS script calls for the processing. that's different context than the JS we load, We are loading JS for the website. While smart buttons loads different different or same file for their context inside iFrame.
