### ISSUE TITLE
Can't select Country

### ISSUE THREAD

**Issue by alessbn** [angelleye/paypal-woocommerce#1451]
I can´t select the country using PayPal Plus plugin. Usually looks like this, but this time theres no country to select:

![image](https://user-images.githubusercontent.com/10042008/81020899-7eca0f80-8e2f-11ea-80c0-bf7e9d4928d2.png)

I need to change the code for hardcode this?

**Comment by angelleye** [comment]
This repository is for our free "PayPal for WooCommerce" plugin.  PayPal Plus is not included here, as it's a separate paid plugin.

Please submit a ticket to our help desk at https://angelleye.com/support/ and we will get you taken care of.
