### ISSUE TITLE
Express Checkout - shipping address fields used even if "Ship to a different address?" unchecked

### ISSUE THREAD

**Issue by siliconforks** [angelleye/paypal-woocommerce#1461]
### Steps to reproduce

Install WordPress 5.4.1, WooCommerce 4.2.0, and PayPal for WooCommerce 2.2.4.

Enable the "PayPal Express Checkout" payment method.

In the Express Checkout settings:
* Set "Checkout Page Display" to "Display in general list of enabled gateways on checkout page"
* Uncheck "Enable Smart Buttons"

Now, visit your store page, add a product to your cart, and go to the checkout page.

Enter a billing address, then check the "Ship to a different address?" checkbox and enter a shipping address which is different from the billing address.

![ec-1](https://user-images.githubusercontent.com/1156399/84259523-fbb36d80-aaee-11ea-9b83-4db83eedcdd5.png)

Now **uncheck** the "Ship to a different address?" checkbox.  (Suppose, for example, you changed your mind and decided that you don't want to ship to a different address.)  This will hide all the shipping address fields.

![ec-2](https://user-images.githubusercontent.com/1156399/84259540-02da7b80-aaef-11ea-91d6-18ae8283606b.png)

Select "PayPal Express" as payment method and click "Proceed to PayPal".  Log in to PayPal to pay for the order.

![ec-3](https://user-images.githubusercontent.com/1156399/84259544-053cd580-aaef-11ea-9c1e-62a634f827b8.png)

Note that the "Ship to" section displays the address that was entered as the billing address.  This is as expected, because you unchecked the "Ship to a different address?" checkbox, so the billing address was essentially the only address that was submitted.

Now, click the "Continue" button, and you will be returned to the store to view the "Review Order" page.

![ec-4](https://user-images.githubusercontent.com/1156399/84259551-07069900-aaef-11ea-9f1a-ff5f435c3860.png)

Note that the shipping address that you originally entered has returned, even though that address should not have been used at all because you unchecked the "Ship to a different address?" checkbox.

**Comment by strarsis** [comment]
Has this resolves in recent releases?

**Comment by drewangell** [comment]
@strarsis I'm sorry, I never saw this until now.  For future reference, it's best to use our [help desk](https://angelleye.com/support).

@deepakmaurya Did you create a ticket about this?

**Comment by drewangell** [comment]
@strarsis When you login with PayPal and select an address there, that address would then be returned back to the site to be displayed on that review page.  Are you sure this isn't the same address, so it just looks like it's holding, when in reality it's being returned from PayPal?

**Comment by siliconforks** [comment]
> 
> 
> @strarsis When you login with PayPal and select an address there, that address would then be returned back to the site to be displayed on that review page. Are you sure this isn't the same address, so it just looks like it's holding, when in reality it's being returned from PayPal?

It's been a while since I tested this, but I don't think that's what's happening here ... you can see in the screenshot from PayPal that there's no "Ship Shippings" address visible anywhere:

![PayPal screenshot](https://user-images.githubusercontent.com/1156399/84259544-053cd580-aaef-11ea-9c1e-62a634f827b8.png)

**Comment by drewangell** [comment]
@siliconforks The address shown there is considered a shipping address.  You have the name as "Bill Billings", but you can see it's under the "Ship To" label.

One of the advantages of PayPal for buyers is that they don't have to share their actual billing info with all the sellers they buy from.  The only address PayPal provides to sellers is a shipping address.  As such, any address returned from PayPal will be used as shipping in WooCommerce.

This is the address that would be covered by seller protection, but only if you ship to that exact address.

In the API response you would also see that address returned as SHIPTOSTREET, SHIPTOCITY, SHIPTOSTATE, etc.

**Comment by siliconforks** [comment]
> 
> 
> @siliconforks The address shown there is considered a shipping address. You have the name as "Bill Billings", but you can see it's under the "Ship To" label.

Yes, the problem is that when PayPal sends the customer back to the WooCommerce site, the shipping address is now the "Ship Shippings" address again:

![WooCommerce screenshot](https://user-images.githubusercontent.com/1156399/84259551-07069900-aaef-11ea-9f1a-ff5f435c3860.png)

**Comment by drewangell** [comment]
@siliconforks Sorry for delays here.  Are you still having this problem on our latest v2.4.9?  If so, please submit a ticket to [our help desk](https://www.angelleye.com/support) and we'll get you taken care of.
