### ISSUE TITLE
Display deprecated notice for REST Credit Card Gateway

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-woocommerce#1488]
The plugin supports REST Credit Cards.

This is no longer available for new users.

Only still in the plugin, so that people who are grandfathered in from years ago can still use it.

We need to add a deprecated notice so that new users don’t try to set this up.

We can add a message on the gateway list page as well as a the top of the gateway settings page.

Deprecated Message

Gateway List

We can add the deprecated notice at the beginning of the description.

DEPRECATED - PayPal direct credit card payments using the REST API. This allows you to accept credit cards directly on the site without the need for the full Payments Pro.

Gateway Settings

We can add this notice immediately after the gateway description.

DEPRECATED This gateway option is no longer available for new users.  This can only be used if you already have an approved REST Credit Card account, and are grandfathered in so that you can continue using it.  

Acceptance Criteria

When viewing the WooCommerce Payment gateways, I see a message that REST is deprecated.

I also see a deprecated message at the top of the settings page for the REST gateway.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $10.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://app.gitcommits.com/issue/display-deprecated-notice-for-rest-credit-card-gateway).
- Questions? Checkout [GitCommits Help](https://app.gitcommits.com/help)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
**<a href='https://app.gitcommits.com/profile/deepakmaurya'>deepakmaurya</a>, has started work on the bounty.**
<hr />

**Message:** Hi,
I understood the task details. I would like to get started with it. I can finish it within 1 Hour. Please approve me to get started with it.
Thanks


<a href='https://app.gitcommits.com/issue/display-deprecated-notice-for-rest-credit-card-gateway'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://app.gitcommits.com/profile/deepakmaurya'>deepakmaurya</a> Work has been approved by <a href='https://app.gitcommits.com/profile/drewangell'>drewangell</a>.**
<hr />

**Message:** I have reviewed your pull request and it looks good, thanks!


<a href='https://app.gitcommits.com/issue/display-deprecated-notice-for-rest-credit-card-gateway'>Click Here to view more</a> on GitCommits Bounty detail page.
