### ISSUE TITLE
Payments Pro - 3D Secure Problems

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#149]
Problems with 3D Secure returning a blank page with a 1 after the user logs in and is returned back to the site.

I did notice that that 3DSecure still had the following...
~~~~
$_SESSION['Centinel_TermUrl'] = str_replace('http:', 'https:', add_query_arg('wc-api', 'WC_Gateway_PayPal_Pro', home_url('/')));
~~~~

That should be WC_Gateway_PayPal_Pro_AngellEYE instead of just WC_Gateway_PayPal_Pro, but making that adjustment didn't fix the problem.

What's happening is that the user hits Place Order and the screen loads to enter their 3DSecure user/password.  They do that, and then it sends them to the 3dsecure site:  http://gyazo.com/1324395cc15abe4fce80dd3c5bdc1ff4

Then it redirects back to http://www.domain.com/?wc-api=WC_Gateway_PayPal_Pro

That's when we just get the blank white page with a 1, though, like this:  http://gyazo.com/ba43c7e3af97c2fd3f77ca513398c5b3

Again, I tried adding _AngellEYE on the end of that since that's what our class name actually is, but that's not changing anything.

**Comment by levansy2020** [comment]
Need a 3DSercure account to check this issue

**Comment by angelleye** [comment]
Here is a user that is having a problem with 3dsecure because the 3dsecure HTML form is coming back instead of a JSON response, so they're getting a JSON error.

https://wordpress.org/support/topic/json-error-unexpected-token-paypal-payments-pro?replies=6#post-7379231

**Comment by angelleye** [comment]
The user in that WordPress forum thread has provided more details, specifically that he is able to get all the way through a checkout with 3dsecure using WordPress 4.3 and PayPal for Woo 1.1.6.2, but he can't get any plugin version to work on WP 4.4.  

Moving this back to the current milestone to see if the new info can help you resolve the problem..??

**Comment by kcppdevelopers** [comment]
we just need 3DSercure account test credentials to resolved this issue.

**Comment by angelleye** [comment]
Are you unable to create one?

*Andrew K. Angell*
www.angelleye.com
<https://www.angelleye.com/?utm_source=email&utm_medium=signature&utm_campaign=email_signature>
|
Join Our Newsletter
<https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature>
Office:  816.256.3419
Skype: angelleye

**Comment by angelleye** [comment]
I see you made another commit here, so I'm just checking in on this again.  Were you able to get a test account created, or what is stopping us from doing that?

**Comment by kcppdevelopers** [comment]
I have create test account and now it's working fine for me.
