### ISSUE TITLE
Not listed as payment method

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1491]
When solely this plugin is used for payment via PayPal, the list of payment methods is empty with a text that excuses it.
No payment can be performed either. Why isn't it used as default payment method?

**Comment by drewangell** [comment]
Sorry, I never saw this ticket until now.  For future reference it's best to use our [help desk](https://angelleye.com/support/).

If you're still having problems please submit a ticket there and we'll get you taken care of.
