### ISSUE TITLE
Problem with 2.4.0

### ISSUE THREAD

**Issue by gbruzzo** [angelleye/paypal-woocommerce#1498]
Hello there 

installed 2.4.0 - this caused a problem in the cart - Paypal button not appearing 

here is the dev console output : 

[Error] Failed to load resource: the server responded with a status of 400 () (js, line 0)
[Error] ReferenceError: Can't find variable: paypal
	(anonymous function) (angelleye-in-context-checkout.min-v2.js:1:4281)
	forEach
	_ (angelleye-in-context-checkout.min-v2.js:1:3927)
	(anonymous function) (angelleye-in-context-checkout.min-v2.js:1:9499)
	i (jquery.js:2:27368)
	fireWith (jquery.js:2:28123)
	ready (jquery.js:2:29926)
	J (jquery.js:2:30282)

Cheers

**Comment by gbruzzo** [comment]
Hello there - do you have any updates? 

Thanks in advance 

Giacomo Bruzzo

**Comment by drewangell** [comment]
Hey, sorry.  The best place to report things right now is our [help desk](https://angelleye.com/support).  Just now saw this here.

Please make sure you've cleared out any caching / CDN tools after applying update and see if that helps.  

If not, go ahead and submit a ticket at the help desk link and we'll work more with you to get this resolved.

**Comment by drewangell** [comment]
@gbruzzo We have released a few patches, so we're on v2.4.4 now.  Are you still having issues with this latest version?

**Comment by drewangell** [comment]
@gbruzzo Haven't heard back from you, so I'm closing this issue.  If you're still having any problems, please submit a ticket to www.angelleye.com/support
