### ISSUE TITLE
Paypal For WooCommerce v 2.4 caused the stripe disabled

### ISSUE THREAD

**Issue by kevin25** [angelleye/paypal-woocommerce#1499]
It's urgent. Please investigate the issue. When I upgraded this plugin. My stripe's form was disabled. All of my stores have the same issue. I troubleshooted it and found out that was Paypal For WooCommerce v 2.4. I rolled it to 2.3.8 and everything was back to normal.

**Comment by drewangell** [comment]
@kevin25 Which form are you referring to specifically?  Are you talking about a Strip credit card form on your checkout page?

Please submit a ticket to [our help desk](https://angelleye.com/support) and provide a copy of the Stripe plugin you're using so we can take a closer look.  Thanks.

**Comment by kevin25** [comment]
Yes, it isn't not compatible with the Stripe plugin by WooCommerce Team.

**Comment by drewangell** [comment]
@kevin25 This has been resolved in v2.4.4.
