### ISSUE TITLE
SiteGround SG Optimize Conflict

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-woocommerce#1507]
# User Report

>I find out that the incompatibility is between your plugin and SG Optimizer (the website is hosted on sitegroud). I noted that up to 2.3.8 version PayPal for WooCommerce everything is working fine. On later updates of the plugin there is incompatibility between the plugin and SG Optimizer.

# Acceptance Criteria

* When running on SiteGround hosting with the SG Optimizer, I am able to run Express Checkout without failure.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $20.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://app.gitcommits.com/issue/siteground-sg-optimize-conflict).
- Questions? Checkout [GitCommits Help](https://www.gitcommits.com/help)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://app.gitcommits.com/explorer)

**Comment by gbruzzo** [comment]
I can confirm. In our case it occurs when 'Defer Render Blocking JS' is selected

**Comment by angelleye-gitcommits** [comment]
**<a href='https://app.gitcommits.com/profile/deepakmaurya'>deepakmaurya</a>, has started work on the bounty.**
<hr />

**Message:** I am starting work on this issue, will keep you posted with updates. How can we connect in case of any questions?


<a href='https://app.gitcommits.com/issue/siteground-sg-optimize-conflict'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://app.gitcommits.com/profile/deepakmaurya'>deepakmaurya</a> Work has been approved by <a href='https://app.gitcommits.com/profile/drewangell'>drewangell</a>.**
<hr />

**Message:** Thanks for finishing the task quickly, Approving the payment


<a href='https://app.gitcommits.com/issue/siteground-sg-optimize-conflict'>Click Here to view more</a> on GitCommits Bounty detail page.
