### ISSUE TITLE
Buy now button; Order review step

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1516]
Only PayPal Express checkout (using this plugin) should be available.
However, two buttons are shown on the checkout page, the "Buy now" button and the PayPal smart button.
The "Buy now" button should not be shown when PayPal Express Checkout is the only available payment option.

Another issue is that when using "Buy now" (also when using the PayPal smart button?) a further review page is added which basically asks everything what had been enterred, etc. How can I skip this review step completely?

**Comment by drewangell** [comment]
Again, sorry for the delayed reply here.  For future reference, please use www.angelleye.com/support

I'm not sure what "Buy Now" button you're talking about.  Are you referring to the Woo add to cart button?  

For the review page, that is required if you need to calculate shipping/tax but the user skips the Woo checkout page.  If you don't need it then you can enable the **Skip Final Review** option from the EC settings.

Let me know if you have any questions or concerns about that.  

If you do have more questions please submit a ticket to our help desk and we'll get you taken care of one way or another.
