### ISSUE TITLE
Add debit card / giro / other payment icons

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1517]
Currently only credit card icons are shown, but PayPal also supported debit/giro payments (even without a PayPal account).
It would be nice to show these options, too.

**Comment by drewangell** [comment]
Hey, sorry, I haven't been using GitHub for this project for awhile, so I wasn't noticing new tickets.  I didn't mean to leave you hanging!

Those Smart Buttons are controlled by PayPal, and they decide which buttons to display based on a variety of variables like the device being used, the location of the buyer/seller, etc.

If you want to submit a ticket to www.angelleye.com/support with temporary credentials to a staging site I can take a closer look.
