### ISSUE TITLE
Orders weren't put on hold when had disputes

### ISSUE THREAD

**Issue by kevin25** [angelleye/paypal-woocommerce#1518]
I just wonder why i had dispute but the order is still processing? Is that feature?

**Comment by drewangell** [comment]
I'm sorry, I haven't been using GitHub for this plugin for awhile, so I didn't realize I had some new issues posted here.  Didn't mean to leave you  hanging.

I'm not clear on what you're asking about, though.  When you get an order in Woo, the standard procedure is that it switches to Processing once the payment is completed.  You'd have to change it to Completed or something else from there.  

Are you expecting it to automatically update to something else when a dispute occurs?  If so, you could do that using our [PayPal IPN for WordPress](https://www.angelleye.com/product/paypal-ipn-wordpress/) plugin and a little bit of custom code to make that happen.

Let me know if you have any questions or concerns about that.
