### ISSUE TITLE
Express Checkout - Option for admin to have product level EC enabled by default for new products.

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-woocommerce#1525]
# Customer Report

When new products are created, our “Enable Express Checkout” option is not enabled by default.

![image](https://user-images.githubusercontent.com/64537522/105126145-b9e69e80-5aa3-11eb-90d8-8117ed965c2f.png)

# Implementation

I would like to see a new option added as a sub-option for our current gateway level product page setting:

![image](https://user-images.githubusercontent.com/64537522/105126181-c9fe7e00-5aa3-11eb-8541-b854199296ac.png)

When this is enabled, we would see a new secondary option to “Enable by default on all newly created products.”

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $20.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://app.gitcommits.com/issue/express-checkout-option-for-admin-to-have-product-level-ec-enabled-by-default-for-new-products).
- Questions? Checkout [GitCommits Help](https://www.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $5.00 has been added by <a href="https://app.gitcommits.com/profile/pay">pay</a>
Co-Funder Message: I would like to fund this and complete is sooner

**Comment by devchristina2** [comment]
Closing this issue, will revisit in the future.
