### ISSUE TITLE
Payments not completing, GetExpresscheckoutDetails Request isn't firing

### ISSUE THREAD

**Issue by Ojay** [angelleye/paypal-woocommerce#1527]
Hi all,

So I've an issue with the latest version of the plugin. You can create an order, get redirected to PayPal go through that process and submit. Payment doesn't go through however and when returned to the site the order remains 'pending'. Looking at the logs I can see that the `GetExpresscheckoutDetails Request` isn't being generated.

`SetExpressCheckout Request: Array` & `SetExpressCheckout Response: Array` are all present and correct, we're just not getting beyond that to the next step... which is `GetExpresscheckoutDetails Request`.

There's no record of the payment in our store or in the customers activity feed.

Up to date WooCommerce with Subscriptions plugin too.

Anyone experiencing similar??

--- EDIT ---

So I've found these PHP notices in my logs...
```
Undefined property: WC_Gateway_Calculation_AngellEYE::$order_items in .../paypal-for-woocommerce/classes/wc-gateway-calculations-angelleye.php on line 174
Undefined index: request_from in .../paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-request-angelleye.php on line 757

```
That's about all that relates to this plugin. Line 174 of `wc-gateway-calculations-angelleye.php ` refers to this piece of code: `$this->payment['order_items'] = $this->order_items;`. 

Tested with default 2019 theme & my own custom one, issue persists across both.

-- STACK TRACE --

```
Notice:  Undefined property: WC_Gateway_Calculation_AngellEYE::$order_items in /.../wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-calculations-angelleye.php on line 174
Stack trace:
  1. {main}() /.../index.php:0
  2. require() /.../index.php:17
  3. require_once() /.../wp-blog-header.php:19
  4. do_action() /.../wp-includes/template-loader.php:13
  5. WP_Hook->do_action() /.../wp-includes/plugin.php:484
  6. WP_Hook->apply_filters() /.../wp-includes/class-wp-hook.php:311
  7. WC_AJAX::do_wc_ajax() /.../wp-includes/class-wp-hook.php:287
  8. do_action() /.../wp-content/plugins/woocommerce/includes/class-wc-ajax.php:90
  9. WP_Hook->do_action() /.../wp-includes/plugin.php:484
 10. WP_Hook->apply_filters() /.../wp-includes/class-wp-hook.php:311
 11. WC_AJAX::checkout() /.../wp-includes/class-wp-hook.php:287
 12. WC_Checkout->process_checkout() /.../wp-content/plugins/woocommerce/includes/class-wc-ajax.php:465
 13. WC_Checkout->process_order_payment() /.../wp-content/plugins/woocommerce/includes/class-wc-checkout.php:1171
 14. WC_Gateway_PayPal_Express_Subscriptions_AngellEYE->process_payment() /.../wp-content/plugins/woocommerce/includes/class-wc-checkout.php:959
 15. WC_Gateway_PayPal_Express_Subscriptions_AngellEYE->process_payment() /.../wp-content/plugins/paypal-for-woocommerce/classes/subscriptions/wc-gateway-paypal-express-subscriptions-angelleye.php:34
 16. WC_Gateway_PayPal_Express_Request_AngellEYE->angelleye_set_express_checkout() /.../wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye-v2.php:2811
 17. WC_Gateway_PayPal_Express_Request_AngellEYE->angelleye_set_express_checkout_request() /.../wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-request-angelleye.php:210
 18. WC_Gateway_Calculation_AngellEYE->cart_calculation() /.../wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-request-angelleye.php:712
```

**Comment by drewangell** [comment]
Hi,

I just replied to your help desk ticket (https://angelleye.atlassian.net/jira/servicedesk/projects/AHD/queues/custom/99/AHD-12994).

I'll say here as well, we need to try and find whatever is conflicting here, and the best way to do that is on a staging site with all other plugins disabled.   If it works that way, then re-enable each until the problem comes back.  Can you do that and let me know what you find?

**Comment by angelleye-gitcommits** [comment]
A GitCommits contributor has sent an offer to complete this issue.

As the Product Owner, you may Accept, Decline, or Counter the offer to negotiate the price.

**Offer Amount:** $20.00
**Message:** Hi,

I've checked the issue and found the bug in the code. It will take around 1-2 hours for me to push a fix & open a PR.

I will do this only for $20, Please accept my offer to fund the issue.

Thanks

<a target='_blank' href='https://app.gitcommits.com/offers/deepakmaurya-payments-not-completing-getexpresscheckoutdetails-request-isnt-firing?action=accept'>Accept</a> | <a target='_blank' href='https://app.gitcommits.com/offers/deepakmaurya-payments-not-completing-getexpresscheckoutdetails-request-isnt-firing?action=decline'>Decline</a> | <a target='_blank' href='https://app.gitcommits.com/offers/deepakmaurya-payments-not-completing-getexpresscheckoutdetails-request-isnt-firing?action=counter'>Counter</a>
<hr>

- Questions? Checkout [GitCommits Help](https://www.gitcommits.com/faq)
