### ISSUE TITLE
Uncaught Error: Call to a member function get_id() on bool in angelleye-includes/angelleye-utility.php(1325)

### ISSUE THREAD

**Issue by joe704la** [angelleye/paypal-woocommerce#1532]
I keep getting this error the past week after the latest WooCommerce update. 

Version 2.5.1 PayPal for WooCommerce
Version 5.0.0 WooCommerce

HP Fatal error: Uncaught Error: Call to a member function get_id() on bool in /nas/content/live/texastech/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-utility.php:153\nStack trace:\n#0 /nas/content/live/texastech/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-utility.php(1325): AngellEYE_Utility->angelleye_woocommerce_order_actions()\n#1 /nas/content/live/texastech/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-utility.php(1821): AngellEYE_Utility->angelleye_paypal_for_woocommerce_order_status_handler(Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order))\n#2 /nas/content/live/texastech/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-utility.php(1776): AngellEYE_Utility->call_paypal_pro_payflow_docapture(Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order), 'BM1P3BCCB24D', NULL)\n#3 /nas/content/live/texastech/wp-includes/class-wp-hook.php(287): AngellEYE_Utility->angelleye_wc_paypal_pro_payflow_docapture(Object(Automattic\\WooCommerce\\ in /nas/content/live/texastech/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-utility.php on line 153, referer:

**Comment by joe704la** [comment]
I should add this happens when we change the order from Processing to Completed.

**Comment by joe704la** [comment]
Any updates on this?

**Comment by gine** [comment]
Same error here #1531

**Comment by joe704la** [comment]
I hope they fix this soon. It is really holding things up for us

**Comment by deepakmaurya** [comment]
Hi,
We're looking into this issue and an update will be available soon.

**Comment by drewangell** [comment]
@joe704la @gine For future reference it's best to create tickets at our help desk:  https://angelleye.com/support/

We have created a ticket for this there, and we'll get it addressed ASAP.  We actually fixed this problem a few releases back, so it's weird that we're seeing it again.  Have to keep with all these changes Woo keeps making, I guess.  We're on it!
