### ISSUE TITLE
Skip final review page with Terms & Conditions page set

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1546]
On the checkout page the user must confirm the Terms & Conditions and other legal agreements using a checkbox, only then the user can proceed to payment.
I want the review page after PayPal payment authorization to be skipped. However, the skip final review page option has this note:
````
(You currently have a Terms & Conditions page set, which requires the review page, and will override this option.)
````
The note is correct insofar that a Terms & Conditions page is set. However, as stated, these conditions have to be accepted already in the checkout page prior to payment. But the plugin states that a Terms & Conditions page necessitates a final review page.
Is there a deeper reason for the necessity of a final review page when the Terms & Conditions page is set?

**Comment by drewangell** [comment]
I'm sorry, I'm cleaning up stuff I missed here and found this.  If you're still having issues please submit a ticket at https://angelleye.com/support and we'll get you taken care of right away.
