### ISSUE TITLE
Pay now button not initialized/missing without explicit payment method selection

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1547]
@kcppdevelopers, @levansy2020, @jigneshkailam: The Pay now button is missing on fresh page load unless the user explicitly selects the PayPal payment method (e.g. by switching to another payment method).

**Comment by drewangell** [comment]
I'm sorry, I'm cleaning up stuff I missed here and found this.  If you're still having issues please submit a ticket at https://angelleye.com/support and we'll get you taken care of right away.
