### ISSUE TITLE
Payment methods order not honored

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1548]
The PayPal payment method from this plugin is always listed as the last one, even when it is placed as the first payment method order in the payment methods settings.

**Comment by strarsis** [comment]
It would be great if this could be fixed!

**Comment by drewangell** [comment]
I'm sorry, I'm cleaning up stuff I missed here and found this.  I'm pretty sure this was resolved, but if you're still having issues please submit a ticket at https://angelleye.com/support and we'll get you taken care of right away.
