### ISSUE TITLE
Duplicate Order Receipt Email After Capturing

### ISSUE THREAD

**Issue by githelp13** [angelleye/paypal-woocommerce#1555]
When I capture a payment, the plugin causes 2 instances of the woocommerce "order receipt" email to be sent. Any idea how to manipulate whatever setting is causing this? I don't see any option in the plugin settings that would address it.

**Comment by drewangell** [comment]
I'm sorry, I'm cleaning up stuff I missed here and found this.  If you're still having issues please submit a ticket at https://angelleye.com/support and we'll get you taken care of right away.
