### ISSUE TITLE
Disable admin notices (constant; hook)

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1559]
As I manage WordPress plugins using `composer` (roots.io workflow), it would be nice to completely disable the update-related update admin notices.
Is there a constant or hook that can be used to disable it? Currently one has to dismiss the notice and a transient is saved for a limited amount of time, before it expires and the notice pops up again.

**Comment by strarsis** [comment]
@kcppdevelopers: Hey! I know that the issue tracker is not really the primary place for issues. But could you take a quick look at this?

**Comment by drewangell** [comment]
I'm sorry, I'm cleaning up stuff I missed here and found this.  If you're still having issues please submit a ticket at https://angelleye.com/support and we'll get you taken care of right away.
