### ISSUE TITLE
Express Checkout - Stripe Conflict

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#156]
We have a user that is running nothing but the Stripe gateway right now, which is credit cards through the checkout page.  When they enable Express Checkout it's hiding their "Proceed to Checkout" button as if EC was the only gateway enabled even though Stripe is also enabled.

Apparently, our plugin isn't seeing that the Stripe extension is enabled.  We need to figure out why that is and get it resolved.

**Comment by levansy** [comment]
Please upload the Stripe plugin here for me

**Comment by kcppdevelopers** [comment]
it's working fine for me, Please check below images for more details:

Cart page: http://screencast.com/t/nbm5WqkTXJt
Checkout page: http://screencast.com/t/evb6VWoDb

**Comment by angelleye** [comment]
@kcppdevelopers how do you have the payment gateways setup?  The problem would only happen if Stripe and PayPal Express were the only 2 gateways you have enabled.  Is that how you had it..??
