### ISSUE TITLE
Issue with company field (PayPal Express Checkout)

### ISSUE THREAD

**Issue by michaelrimbach** [angelleye/paypal-woocommerce#1565]
Hi!

we have an issue with the latest version (+older versions also affected) of the plugin. I'm using the payment method "PayPal Express Checkout" in sandbox mode. 

If you use the company field (billing or shipping address) the plugin puts the firstname, lastname and company together and sends it to Paypal. If the customer returns from Paypal, the plugins tries to undo this merge but fails. The values are not in the correct fields:

![image](https://user-images.githubusercontent.com/1499365/129173288-7fe14e8f-00f1-4a0e-a751-59e043e549f0.png)

The values from the shipping address should be the same as for the billing address (for this example). 

I've debugged a little bit and it looks like the issue come from this file:
https://github.com/angelleye/paypal-woocommerce/blob/ee393e63bfcddc2a2dce3f6343b070772eacd8ea/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-response-angelleye.php (function FullNameParser())

```
$split_name = $parser->split_full_name($response['SHIPTONAME']);
$shipping_first_name = $split_name['fname'];
$shipping_last_name = $split_name['lname'];

var_dump($split_name);
var_dump($shipping_first_name);
var_dump($shipping_last_name);
var_dump($company);

array(4) {
  ["fullname"]=>
  string(21) "Mr. Webentwickler GmbH - Michael Rimbach"
  ["salutation"]=>
  bool(false)
  ["fname"]=>
  string(3) "Mr. Webentwickler GmbH"
  ["lname"]=>
  string(17) "- Michael Rimbach"
}            

string(3) "Mr. Webentwickler GmbH"
string(17) "- Michael Rimbach"
string(10) "Test Store"
```
Shop information's:
WC Version: 4.9.3
WP Version: 5.6.4
PHP Version: 7.4.21
Plugin: PayPal for WooCommerce: by Angell EYE – 2.5.12

Let me know if you have any questions and thanks in advance for the fix!
Michael

**Comment by michaelrimbach** [comment]
Any news here?

**Comment by hussong** [comment]
Is anyone from Angell EYE reading these tickets?

**Comment by drewangell** [comment]
Hey, sorry, we've been using Jira and I wasn't getting my GitHub notices.  I didn't mean to leave ya hanging!

We're definitely still active, but for future reference please use www.angelleye.com/support and we'll get you taken care of.

At this point I would recommend that you move from Classic Express Checkout to "Complete Payments" which is now available in the latest versin of our plugin.

Sorry again for the lack of reply here.  I'm fixing that problem so it won't happen again!
