### ISSUE TITLE
Express Checkout - Billing Address

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#157]
For EC orders we're only including the shipping address in the WooCommerce order data because that's all PayPal returns to us.  Need to add the option for users to enable the ability to set both the billing and shipping address using this address.

**Comment by levansy2020** [comment]
Hi, this is an option in admin or in review page?

**Comment by angelleye** [comment]
This would be an option in the admin panel for the site owner to enable/disable.
