### ISSUE TITLE
Language template / .pot file not up-to-date

### ISSUE THREAD

**Issue by hussong** [angelleye/paypal-woocommerce#1570]
After creating a language file for German (using the Loco Translate plugin), I noticed that some strings were still untranslated.

I therefore synced the .pot file against the codebase (using Loco) and there were quite a few changes.

After syncing my language file against the updated .pot file, I came a little closer to a full translation.

I'm adding my updated .pot file for reference.
[paypal-for-woocommerce.pot.zip](https://github.com/angelleye/paypal-woocommerce/files/7064776/paypal-for-woocommerce.pot.zip)

It would be great if you could ship the plugin with an up-to-date .pot file, that would make it easier for users to create their own language files.

Hope this helps!

**Comment by drewangell** [comment]
Sorry I never got back to you here!  I really appreciate your effort and feedback.  We'll absolutely do our best to improve that going forward!
