### ISSUE TITLE
Some strings are not gettext ready / translatable

### ISSUE THREAD

**Issue by hussong** [angelleye/paypal-woocommerce#1571]
After synching the .pot file against the codebase and creating a language file with 100% strings translated (both using the Loco Translate plugin), I am still seeing some untranslated strings on the settings screen:

![image](https://user-images.githubusercontent.com/15839259/131086883-177965ce-70d4-4c9b-a84a-022641552024.png)

Quick grep returns two files:

```
$ grep -R 'At the bottom,' paypal-for-woocommerce/
paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye-v2.php:                    'bottom' => 'At the bottom, below the shopping cart details.',
paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye-v1.php:                    'bottom' => 'At the bottom, below the shopping cart details.',

$ grep -R 'Display both at the top' paypal-for-woocommerce/
paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye-v2.php:                    'both' => __('Display both at the top and in the general list of gateways on the checkout page.')),
paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye-v1.php:                    'both' => __('Display both at the top and in the general list of gateways on the checkout page.')),
```

A look into the files surfaces two issues:

**1. Some strings are not gettext ready.** 
Example:
```
'options' => array(
    'top' => 'At the top, above the shopping cart details.',
    'bottom' => 'At the bottom, below the shopping cart details.',
    'both' => 'Both at the top and bottom, above and below the shopping cart details.'
),
```
paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye-v1.php:1039-1043

**2. Some strings are wrapped for gettext, but are missing the text domain.**
Example:
```
'options' => array(
    'no' => __("Do not display on checkout page.", 'paypal-for-woocommerce'),
    'top' => __('Display at the top of the checkout page.', 'paypal-for-woocommerce'),
    'regular' => __('Display in general list of enabled gateways on checkout page.', 'paypal-for-woocommerce'),
    'both' => __('Display both at the top and in the general list of gateways on the checkout page.')),
```
paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye-v1.php:1050-1054

It would be great if you could make all strings translatable, so users can create their own language files for 100% of strings.

Many thanks in advance!

**Comment by drewangell** [comment]
Hey, sorry, I didn't mean to neglect this.  We are using Jira through www.angelleye.com/support and I wasn't seeing my GitHub notices.  Sorry about that!

If you're still having problems please create a ticket at the link above and we'll get you taken care of.  That said, I would suggest you update to the latest version of the plugin and switch from Classic Express Checkout / Payments Pro to the new "Complete Payments" option.  It includes everything in a single stack.

Sorry again for the lack of reply here!
