### ISSUE TITLE
Conflict with woocommerce wishlist plugin

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#161]
https://wordpress.org/support/topic/conflict-with-woocommerce-wishlist-plugin?replies=1#post-6472410

**Comment by levansy2020** [comment]
Can u request for the site url and screenshot?

**Comment by angelleye** [comment]
Ok, I requested this in the WordPress support thread.

**Comment by angelleye** [comment]
http://www.angelleye.com/wp-content/uploads/gravity_forms/2-5537abc77af111c5114bbc61f4a4800c/2015/01/wishlist-paypal-conflict.jpg

**Comment by angelleye** [comment]
Confirmed this is happening on my test server, too:  http://woo.angelleye.com/product/woo-album-1/

**Comment by angelleye** [comment]
"Still happens when I don’t have the swatches enabled, ie variation is controlled via a dropbox"

**Comment by angelleye** [comment]
More details from the user that filed this complaint.

>So, whatever code modification you made worked for when swatches are enabled but for standard drop boxes I am still getting the duplication of the wishlist link.
 
>Hopefully you can shed some light on this otherwise all of my products will need to use swatches, which is less than ideal.  Interestingly, when I go to a default theme everything works fine so I do think it is a compatability issue with the theme and your plugin.  No doubt your plugin is fine and it is an Avada theme issue but they wont help!  Too busy selling over 5 million dollars worth of themes I guess!
 
>So the situation is as follows:
 
>Default theme, your plugin activated, wishlist activated, drop down or swatch variation option = no issue
Avada theme, your plugin activated, wishlist activated, swatch variation option = no issue
Avada theme, your plugin activated, wishlist activated, drop down variation option = issue when selecting out of stock variation
Avada theme, your plugin de-activated, wishlist activated, drop down or swatch variation option = no issue
