### ISSUE TITLE
Using Express button on cart page goes to blank page with "1" at the top

### ISSUE THREAD

**Issue by lightson** [angelleye/paypal-woocommerce#162]
Just updated to 1.1.6.2 and if I add the Paypal Express button to the /cart/ page user gets an almost blank page with just the numeral 1 at the top.

Express button on /checkout/ works as expected.

**Comment by levansy2020** [comment]
Pls provide wp-admin so we can check it for you

**Comment by angelleye** [comment]
@lightson If you want to [submit a ticket here](http://www.angelleye.com/support) we can work with you more directly.  

Please provide temporary FTP credentials for your site as well as a WP admin login.

**Comment by angelleye** [comment]
@lightson I think we spoke directly and you got this resolved, right?

**Comment by angelleye** [comment]
We have not had any reports of this for some time now.  Should be fixed in latest versions.
