### ISSUE TITLE
No payment gateway on WooCommerce Block

### ISSUE THREAD

**Issue by kevin25** [angelleye/paypal-woocommerce#1620]
There is No payment gateway on WooCommerce Block. Is it compatible?

**Comment by nielslange** [comment]
Based on what @kevin25 mentioned before, it appears that this plugin is incompatible with the WooCommerce Blocks plugin at the moment. On https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md, you can find detailed steps  on to make the plugin compatible.

**Comment by kevin25** [comment]
Can you please make it compatilbe for future use please?

**Comment by drewangell** [comment]
Hey guys, sorry for the lack of response.  We're using Jira and the GitHub issues were slipping through the cracks a bit.  Didn't mean to leave ya hanging!

We have a ticket for this in our backlog I know, and we're working on getting it added ASAP.

**Comment by strarsis** [comment]
Please add support for WooCommerce payments block, as it gets harder and harder to keep the legacy checkout page with each update.
