### ISSUE TITLE
Express Checkout - Terms and Conditions / Require Account

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#163]
WooCommerce has an option to force users to accept terms and conditions during checkout.  Express Checkout, though, isn't doing this because our review page doesn't take this into account.

We need to make that work, but we also need to consider our setting/option to "skip final review".  If somebody has both options enabled, the terms and conditions would need to be accepted at some point.  

We may just have to override the "skip" option in those cases and display the review page anyway because the user has to accept the terms and conditions.

In that note, same goes for the WC option to force an account for purchase.  We added that to our review page previously, but I don't think I fully tested that in conjunction with the "skip final review" option.

**Comment by jigneshkailam** [comment]
I am done with this and push to issue branch for your review.

**Comment by angelleye** [comment]
I am having trouble getting this merged.  From the release branch I created a new local Issue-163 branch, and then tried to merge origin/Issue-163 into that, but I'm multiple merge conflicts and I'm not sure what needs to be kept.

**Comment by kcppdevelopers** [comment]
this issue already done in ref #302
