### ISSUE TITLE
Cartflows Pro 1.8.0 FATAL ERROR

### ISSUE THREAD

**Issue by contemplate** [angelleye/paypal-woocommerce#1642]
We just upgraded to Cartflows Pro 1.8.0 & we have PayPal for WooCommerce 3.0.12 which is now causing a fatal error on the site:

[03-Jan-2022 15:22:05 UTC] PHP Fatal error:  Uncaught Error: Class 'Cartflows_Pro_Gateway_Paypal_Express' not found in /home/xxxxx/public_html/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/cartflows-pro/class-cartflows-pro-gateway-paypal-express-angelleye.php:1272
Stack trace:
#0 /home/xxxxx/public_html/wp-content/plugins/cartflows-pro/classes/class-cartflows-pro-gateways.php(115): include_once()
#1 /home/xxxxx/public_html/wp-content/plugins/cartflows-pro/classes/class-cartflows-pro-gateways.php(89): Cartflows_Pro_Gateways->load_gateway('paypal_express')
#2 /home/xxxxx/public_html/wp-includes/class-wp-hook.php(303): Cartflows_Pro_Gateways->load_required_integrations('')
#3 /home/xxxxx/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#4 /home/xxxxx/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#5 /home/xxxxx/public_html/wp-settings.php(600): do_action('wp_loaded')
#6 /home/xxxxx/public_html/wp-conf in /home/freshstartfamily/public_html/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/cartflows-pro/class-cartflows-pro-gateway-paypal-express-angelleye.php on line 1272

**Comment by drewangell** [comment]
Hi, sorry for the delay replying.  Thanks for the feedback!  We got this resolved in v3.0.14.  

https://github.com/angelleye/paypal-woocommerce/releases
