### ISSUE TITLE
is_ajax Deprecated in Woocommerce 6.1

### ISSUE THREAD

**Issue by tarkan123** [angelleye/paypal-woocommerce#1647]
is_ajax has  been deprecated in Woocommerce 6.1, and I noticed this plugin still has many calls to this function.

Not sure if it is breaking anything, but it is filling the php error logs.

**Comment by drewangell** [comment]
@tarkan123 Thanks for the feedback, sorry for the delay replying.  We're looking into this and will get it resolved ASAP (they may have gotten it done already.)

**Comment by drewangell** [comment]
I'm sorry, I'm cleaning up stuff I missed here and found this.  If you're still having issues please submit a ticket at https://angelleye.com/support and we'll get you taken care of right away.
