### ISSUE TITLE
Express Checkout - Checkout page create account.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#165]
With our original Express Checkout integration we have our review page that gets displayed when the user is returned to the site from PayPal.  This page checks the WC setting for guest checkout, and if an account is required it forces them to login or create an account to complete the payment.

We recently added the Express Checkout option to the general list of payment gateways on the checkout page, however, it seems that we didn't cover the guest checkout option here.  

We have complaints that when people choose to create an account from the checkout page, and use Express Checkout, the  new account does not get created.

http://www.angelleye.com/support/scp/tickets.php?id=86

**Comment by angelleye** [comment]
I'm getting a merge conflict on this one when I try to merge into the dev branch.  

Please go ahead and merge our dev branch into this branch and resolve the conflict for me.

**Comment by angelleye** [comment]
Just got done running a test from the issue#165new branch.  

If I'm logged in already the checkout works just fine.  However, if I'm not logged in, I'm able to get all the way up to the review page, but then when I click "Place Order" on that page I end up with a PayPal API error because the Payer ID isn't getting passed correctly for some reason.

![image](https://cloud.githubusercontent.com/assets/629241/6905021/a0e56e72-d6ea-11e4-90df-843ba8437478.png)

This was brought to my attention by another user who downloaded the dev branch to get this functionality and I was able to reproduce the problem on my server.

**Comment by angelleye** [comment]
It looks like it did create a new account for me because I received an email about the new account (even though the checkout wasn't completed successfully).  The username it gave me, though, is "andrewnewaccount" which apparently is just the first name with "newaccount" appended to that.

Is that a WordPress/WooCommerce thing or is that something you did?  I don't like that username.  There's a very good chance we could wind up with conflicts when people with the same name try to checkout.

**Comment by angelleye** [comment]
I just did a test with Express Checkout.  I was forced to create an account as expected, and it seems to have done so successfully, however, it did not fill in most of the actual customer data in the user record in WordPress.

There is a general "First Name" and "Last Name" field in there that didn't get filled in...

![image](https://cloud.githubusercontent.com/assets/629241/7227303/5420de9c-e715-11e4-8995-cc675727735a.png)

The "First name" and "Last name" fields under the Customer Billing Address section did get filled in, but the majority of the fields did not get filled in.

![image](https://cloud.githubusercontent.com/assets/629241/7227386/d0a28fc4-e715-11e4-96ec-9c6b42b1f765.png)

Nothing seems to have gotten saved for shipping at all.

![image](https://cloud.githubusercontent.com/assets/629241/7227391/da37a222-e715-11e4-888b-0f2f6448464f.png)

**Comment by angelleye** [comment]
The information above was from a test that I did using the Express Checkout button from a product detail page.  I just now ran another test using Express Checkout from the checkout page and it did not work.  Here is a video:  http://fiber.angelleye.com/temp/account-create.mp4

I did get an email for the new account that was created in the WP system, however, as you can see from the video I get stranded on the checkout page and it doesn't send me on to PayPal to complete the payment.

**Comment by angelleye** [comment]
My first test here was with WC guest checkout disabled.  I was provided with the login or create account options on the review page as expected.  I used the create account form, but I used an email address that was already associated with an account on my WooCommerce system.  I wound up with a PHP fatal error:

>Fatal error: Uncaught exception 'Exception' with message 'An account is already registered with your email address. Please login.' in /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php:920 Stack trace: #0 /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/paypal-for-woocommerce.php(385): WC_Gateway_PayPal_Express_AngellEYE->paypal_express_checkout() #1 [internal function]: AngellEYE_Gateway_Paypal->woocommerce_paypal_express_review_order_page_angelleye(Object(WP)) #2 /home/angelley/sandbox_woocommerce/wp-includes/plugin.php(571): call_user_func_array(Array, Array) #3 /home/angelley/sandbox_woocommerce/wp-includes/class-wp.php(333): do_action_ref_array('parse_request', Array) #4 /home/angelley/sandbox_woocommerce/wp-includes/class-wp.php(609): WP->parse_request('') #5 /home/angelley/sandbox_woocommerce/wp-includes/functions.php(877): WP->main('') #6 /home/angelley/sandbox_woocommerce/wp-blog-header.php(14): wp() #7 /home/ang in /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 920

**Comment by angelleye** [comment]
If I use an email address that does not already exist, then it seems to create the account just fine and logs me in to complete the checkout, however, I see some PHP notices at the top of the review page at this point:

>Notice: Undefined index: SHIPTOSTREET2 in /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 941

>Notice: Undefined index: SHIPTOSTREET2 in /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 951

**Comment by angelleye** [comment]
Also, from the review page after creating the new account, if I switch the shipping option it's not triggering the update, so the shipping amount and total are not updating when I change shipping methods at this point.  That does seem to work on the review page, though, before I login or create the new account.

**Comment by angelleye** [comment]
I see that the account I created did get setup as "customer" which is good, and most of the customer data seems to be filled in.  The phone number and email address did not get filled in, though.

**Comment by jigneshkailam** [comment]
I have resolved PHP notice and error, regarding total not updated when change shipping methods and The phone number and email address did not get filled are working fine for me.

would be great if I have video to check that particular case.

**Comment by jigneshkailam** [comment]
I have resolved above issue and push to issue #165A branch for your review.

**Comment by angelleye** [comment]
Hmmm...this time I did a checkout and created a new user.  The checkout worked, but now almost nothing made it into the customer profile record in WordPress.  

I think it'll be best if we run through tests with this together and you can probably fix things as we run into them.

**Comment by angelleye** [comment]
I ran a test with Express Checkout from the WooCommerce checkout page.  The new account was created successfully in WooCommerce as a customer, and the billing information was filled out, however, the shipping info was left blank.  I think it might be because I chose the option to use the same address for billing and shipping.  Therefore, there were no actual shipping fields entered, but we need to make sure we populate both in this case.  

The only time shipping should not be filled out is if it's a product where shipping is not required.

![image](https://cloud.githubusercontent.com/assets/629241/7904741/0ff515ec-07ce-11e5-9468-d7207a8c5164.png)

**Comment by angelleye** [comment]
I did another test, this time I filled out both the billing and shipping addresses on the WC checkout form, but I used different addresses for each.  The final order details is showing the shipping address that I entered for both billing and shipping even though I had entered different addresses.

![image](https://cloud.githubusercontent.com/assets/629241/7906075/50da64fc-07e9-11e5-9495-70c2a9562538.png)

This time, though, the billing and shipping details were both entered correctly in the customer profile.

![image](https://cloud.githubusercontent.com/assets/629241/7906086/7e880e0e-07e9-11e5-8bbd-cf1b0b4eb470.png)

So we're close, but not quite there.  We need to make sure of the following.

* If Express Checkout is used from a product page or cart page (so the checkout page is skipped) then we would use the address returned from PayPal.

* In the scenario above, if the user has the setting enabled to use the PayPal address for both billing and shipping in WooCommerce, then we would do so accordingly.

* If the WooCommerce checkout page is used, though, then we need to make sure to use whatever address(es) are entered into the checkout form.  

* In the scenario above (using the checkout page), if the buyer chooses to use the same address for billing and shipping we need to make sure both are entered in the WC customer profile.

* If two separate addresses are entered on the checkout page, then we need to make sure that's reflected correctly on the WC review page that the plugin uses.

**Comment by angelleye** [comment]
Ran a test using the WC checkout page where I only filled in the billing address and chose to use the same address for shipping.  When I was returned from PayPal the review page has the shipping address filled in, however, the Billing address is showing PHP notices.

![image](https://cloud.githubusercontent.com/assets/629241/7954294/d6594bce-0993-11e5-9151-282f10c09549.png)

**Comment by angelleye** [comment]
Also, from the same test above, after completing the order the final receipt page actually shows the Billing Address filled in properly, however, the Shipping Address shows N/A.  

![image](https://cloud.githubusercontent.com/assets/629241/7954313/0a219b6e-0994-11e5-993e-50d727b94b26.png)

**Comment by angelleye** [comment]
Again from the same test above, the customer record was missing the shipping address.

![image](https://cloud.githubusercontent.com/assets/629241/7954331/3782ab52-0994-11e5-9dd7-cae2ef8e9741.png)
