### ISSUE TITLE
PFW-274 - Authorization &amp; Capture - Support for Partial Capture

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-woocommerce#1657]
# Story

As a merchant, I need the ability to use auth and capture with partial captures, so that I can process only the amount I need instead of the full amount.

# Details

In Classic EC we have partial catpure available:

![](blob:https://angelleye.atlassian.net/b2c954dd-7059-40af-b925-8952124d9641#media-blob-url=true&id=204ab04b-34ef-4ab4-adb3-fa333746c7d2&collection=&contextId=31911&mimeType=image%2Fpng&name=image-20220209-130715.png&size=39593&width=1060&height=482&alt=)

We need this same functionality for PPCP.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue has a bounty of $20.00 ready to be claimed!**

- If you are a Contributor and would like to complete this task to claim the bounty you can **Start Work** on the [GitCommits issue details page](https://app.gitcommits.com/issue/pfwma-274-authorization-amp-capture-support-for-partial-capture).
- If you would like to see this issue completed more quickly, please **Add Funding** to the bounty on the [GitCommits issue details page](https://app.gitcommits.com/issue/pfwma-274-authorization-amp-capture-support-for-partial-capture).
- More open bounties are available in the [GitCommits Issue Explorer](https://app.gitcommits.com/explorer)
- Questions? Review our [FAQ](https://www.gitcommits.com/faq)

**Comment by angelleye-gitcommits** [comment]
### Additional Funds Added to the Bounty:
A contribution of $50.00 has been added to the bounty by <a href="https://app.gitcommits.com/profile/danny">danny</a>.
Crowdfunder Message: The ability to adjust capture amounts is important for our online fruit & veg shop. Some items are priced per kg and often it is difficult to get weight 100% correct in processing orders so having the ability to adjust the authorized amount for capture is very beneficial.

**Comment by devchristina2** [comment]
Closing this issue, will revisit in the future.
