### ISSUE TITLE
PayPal for Woocommerce is not passing some customer information to PayPal

### ISSUE THREAD

**Issue by junkjunker** [angelleye/paypal-woocommerce#1658]
Hi Folks,
I ran a couple of live credit card transactions on a staging site to test "real world" functionality.  It seems that PayPal for Woocommerce is not passing some info to PayPal:

customer's last name, 
email address,
shipping names,
phone number,
customer reference number.

Steps:
1) Place order on staging site with actual credit card. (https://hrwp2.a2hosted.com/hrstagingclone/shop/test-product/)

2) Log in to PayPal and download >Reports>Activity Download>"All Transactions" TAB format.

3) Compare to previous transactions done with another plugin, WooCommerce PayPal Payments Advanced Gateway.

What I've seen:
a) The Name field only contains the Billing First Name, not first and last.
b) From Email Address field is blank.
c) Shipping Address contains the Billing Address First and Last Names (not shipping name)
d) Contact Phone Number field is blank.
e) Customer Reference Number field is blank (usually is similar to invoice number).

Thanks for taking a look at this.  Please let me know if you need any additional info.

Here is a sample of the PayPal Transaction Report that highlights the missing information.
[angelleye bug report.xlsx](https://github.com/angelleye/paypal-woocommerce/files/8066099/angelleye.bug.report.xlsx)
.

**Comment by drewangell** [comment]
I'm sorry, I'm cleaning up stuff I missed here and found this.  If you're still having issues please submit a ticket at https://angelleye.com/support and we'll get you taken care of right away.

**Comment by junkjunker** [comment]
Hi Drew,
I've noticed even with the latest update that PPCP is still passing incomplete and incorrect customer info to PayPal.
a) From Email Address field is blank.
b) the Billing Address contains the Shipping Address
c) the Company Name is omitted completely
d) the Contact Phone Number is blank.

I'll submit a ticket at your website as well.  Attached is a sample of the data downloaded from PayPal with the highlighted fields.
Thanks!
[angelleye bug report 2023-02-26.xlsx](https://github.com/angelleye/paypal-woocommerce/files/10836407/angelleye.bug.report.2023-02-26.xlsx)
