### ISSUE TITLE
Express Checkout - Problem with WooCommerce receipt email for digital download items..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#166]
Getting complaints from a customer that when people pay through our EC gateway the customer never gets their WooCommerce receipt email.

http://www.angelleye.com/forum/discussion/comment/103#Comment_103

> I'm saying that unless I capture the email address prior to clicking the PayPal express button the email receipt from Woocommerce with the download link is not sent. The customer receives a receipt from PayPal but not from Woocommerce which has the download link.
> 
> I was thinking that if I had them add their email address on the cart page and only had your Paypal Express button on the checkout page then it would work just fine.

Not sure if it's specific to a digital download product or what's going on there, but we need to see if we can reproduce the problem.

**Comment by levansy** [comment]
I tested and got the email normally

**Comment by kcppdevelopers** [comment]
@angelleye I have tested and it's working fine for me.
