### ISSUE TITLE
PayPal Advanced is not connecting to PayPal

### ISSUE THREAD

**Issue by junkjunker** [angelleye/paypal-woocommerce#1665]
As of 2022-02-25, I have had customers calling saying that they can't enter credit card info to make purchases. Using PayPal Advanced, when all customer info is correctly entered on the checkout page, hitting "Place Order" results in the following error message:

`Error processing checkout. Please try again.`

There is no record of the attempted order in the logs.  Talking with PayPal, they see no indication that a query is being made on their side.  We have tested this on the live site and a staging site using live credentials and sandbox with the same results.

Thanks!

**Comment by drewangell** [comment]
I'm sorry, we were not tracking the GitHub repo like we should have been.  If you're still having issues please submit this to https://angelleye.com/support and we'll get you taken care of.  

The new PayPal Complete Payments system replaces all of the Classic Advanced stuff, so it should work a lot better for you.
