### ISSUE TITLE
Express Checkout - Locale Code

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#167]
Right now we're using the following to set LOCALCODE in SetExpressCheckout.

```
'localecode' => $this->use_wp_locale_code == 'yes' ? substr(WPLANG, -2) : '',
```

This seems to be causing quite a few problems as people aren't getting what they expect from the PayPal pages.  I looked at the [documentation](https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/) again and it states the following for LOCALECODE:

>(Optional) Locale of the pages displayed by PayPal during Express Checkout. It is either a two-letter country code or five-character locale code supported by PayPal.

>Character length and limitations: A [two-letter country code](https://developer.paypal.com/docs/classic/api/locale_codes/) or [five-character locale code](https://developer.paypal.com/docs/classic/api/locale_codes/) supported by PayPal.

I never realized we could send the full 5 char locale code, so instead of only sending country code I'd like to update to send the full locale code instead.

**Comment by angelleye** [comment]
All I need to do is adjust it to use the value that we're pulling for settings...

```
'localecode' => $this->button_locale_code,
```

Which is already setting the value based on 

```
$this->button_locale_code      = defined( 'WPLANG' ) && WPLANG != '' && $this->use_wp_locale_code == 'yes' ? WPLANG : 'en_US';
```

**Comment by levansy** [comment]
This was fixed by https://github.com/angelleye/paypal-woocommerce/commit/68913eac498b3a436f9dc69724ed45358688bd05
