### ISSUE TITLE
User Creation Issues..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#171]
Got this message from somebody through my site...

>Hi, there is a problem with user creation while using this plugin…on the checkout page, I set in the Woocommerce setting where user can insert their username and the password by woocommerce will be sent to user after the payment.

>Now, the payment using Paypal for Wommerce has been received which is great ! BUT the user does not receive any password creation and there is no user details in WP user list although the notification of their purchases received by both ends.

>I thought it was Woocommerce problem but it isn’t because when I tried to pay using BACS selection, the user details are created at WP user list.

>Need your help as there is a buyer who are waiting for their credentials and we need to sort it out. Thanks.

**Comment by levansy** [comment]
Maybe this is the same issue with #165 I will submit the fix soon, still checking it

**Comment by angelleye** [comment]
OK, thanks!

**Comment by angelleye** [comment]
Got another person talking about the same thing here:

https://wordpress.org/support/topic/users-password-registration-not-received-when-using-paypal-express

**Comment by angelleye** [comment]
I just did a test with Express Checkout.  I was forced to create an account as expected, and it seems to have done so successfully, however, it did not fill in most of the actual customer data in the user record in WordPress.

There is a general "First Name" and "Last Name" field in there that didn't get filled in...

![image](https://cloud.githubusercontent.com/assets/629241/7227303/5420de9c-e715-11e4-8995-cc675727735a.png)

The "First name" and "Last name" fields under the Customer Billing Address section did get filled in, but the majority of the fields did not get filled in.

![image](https://cloud.githubusercontent.com/assets/629241/7227386/d0a28fc4-e715-11e4-96ec-9c6b42b1f765.png)

Nothing seems to have gotten saved for shipping at all.

![image](https://cloud.githubusercontent.com/assets/629241/7227391/da37a222-e715-11e4-888b-0f2f6448464f.png)

**Comment by angelleye** [comment]
The information above was from a test that I did using the Express Checkout button from a product detail page.  I just now ran another test using Express Checkout from the checkout page and it did not work.  Here is a video:  http://fiber.angelleye.com/temp/account-create.mp4

I did get an email for the new account that was created in the WP system, however, as you can see from the video I get stranded on the checkout page and it doesn't send me on to PayPal to complete the payment.

**Comment by angelleye** [comment]
I'm moving all these details to #165 and closing this because it's a duplicate.
