### ISSUE TITLE
Stylesheets are enqueued unnecessarily

### ISSUE THREAD

**Issue by galbaras** [angelleye/paypal-woocommerce#1717]
Despite configuring PayPal Complete Payments only to work on the checkout page (all the "enable" settings are off, except coupons on the final review page), I see these stylesheets on every page:

- ppcp-gateway/css/wc-gateway-ppcp-angelleye-public.css
- assets/css/angelleye-cc-ui.css

**Comment by drewangell** [comment]
Hey, sorry, I wasn't tracking the GH repo like I should have been.  If you're still having problems with this please submit it to https://angelleye.com/support and we'll get you taken care of ASAP.  Thanks!
