### ISSUE TITLE
Error: Expected intent from order api call to be capture, got authorize.

### ISSUE THREAD

**Issue by adpeate** [angelleye/paypal-woocommerce#1738]
Hi, thanks for this excellent plugin. I've discovered an issue on one of my client sites using this plugin.

When placing a normal order all works fine.

However if you create an order from the admin side in pending payment status, then trigger the customer invoice email, the email will contain a link to the pre-filled checkout to make payment. Choosing the same paypal options here does not work and logs the following errors in the console:

smart_button_validation_error_incorrect_intent

Expected intent from order api call to be capture, got authorize. Please ensure you are passing intent=authorize to the sdk url.

Payment action is set to Capture in the module.

Other system details:
Wordpress version: 6.0.2
Woocommerce version: 6.9.2
AngellEye paypal version: latest (3.0.36)

Many thanks.

**Comment by kcppdevelopers** [comment]
Hello @adpeate,

We just resolved issue and released new version 3.0.38.
