### ISSUE TITLE
Express Checkout - Digital / Virtual Goods - NOSHIPPING

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#174]
User complaint that even when setting a product to Virtual and Downloadable they were still getting shipping info through the PayPal checkout.

Some people do want shipping even for digital goods, though, so I don't want to base the logic on that.

What we should do is add a "No shipping required" check box next to the Virtual and Downloadable check boxes in the WooCommerce product setup page.  Then, if this box is checked we'll add the NOSHIPPING=1 parameter to our SEC request.

**Comment by jigneshkailam** [comment]
I am done with this issue and push to issue #174J for your review.

**Comment by angelleye** [comment]
Looks like this was already done.  Just need to review the changes that were made and ensure they're still good.

**Comment by kcppdevelopers** [comment]
I have push latest code into the Issue-174-A branch.

**Comment by angelleye** [comment]
I'm getting a merge conflict when I try to merge this into the release branch.  Please merge the release branch into this branch to resolve the conflicts.
