### ISSUE TITLE
Clicking the "paypal" button for payment opens a new window and then closes.

### ISSUE THREAD

**Issue by Berciu** [angelleye/paypal-woocommerce#1740]
After installing the plugin and enabling PayPal Complete Payments, clicking the "paypal" button for payment opens a new window and then closes. Please help

**Comment by Berciu** [comment]
I mean the Checkout Page Setting section, when I have "Display in general list of enabled gateways on checkout page" set, when I click the "PayPal" button, a new window opens and closes after a while. Please help

**Comment by kcppdevelopers** [comment]
@Berciu 

We just resolved issue and released new version 3.0.38.
