### ISSUE TITLE
Design Issue at Credit card fields in complete payments

### ISSUE THREAD

**Issue by MLotfy88** [angelleye/paypal-woocommerce#1745]
I have an design issue at my Credit card fields ( screenshot attached) 

I tried multiple checkout builders and even woocommerce default checkout and the same issue appears

![Untitled1.png](https://user-images.githubusercontent.com/113838543/195239711-58963819-9566-4e53-9204-f3ba4a9f3919.png)

**Comment by MLotfy88** [comment]
You just need to edit the font size of the data inside fields

**Comment by drewangell** [comment]
This has been resolved in the PayPal Complete Payments gateway that is now provided with our plugin.  Please get switched to that and you won't have this issue.  You'll also get cheaper fees for the CC processing.  :)

If you have any questions about any of that please submit a ticket to https://angelleye.com/support
