### ISSUE TITLE
Express Checkout - Digital / Virtual Goods - NOSHIPPING Global

### ISSUE THREAD

**Issue by AsaadQ** [angelleye/paypal-woocommerce#175]
In regards to issue #174 , a global checkbox option in settings for the whole production environment will help those with virtual/downloadable product only stores.

**Comment by angelleye** [comment]
Yes, if we end up doing the option as a product specific option we'll definitely setup toggle buttons so that you can enable it on all products, all downloadable products, all virtual, etc.

**Comment by angelleye** [comment]
Seems to be done already.  Just need to review and ensure it's still good.

**Comment by kcppdevelopers** [comment]
I have push latest code in issue-175-B branch.
