### ISSUE TITLE
Please, make an extension that works in Brazil

### ISSUE THREAD

**Issue by 4n0n1mo** [angelleye/paypal-woocommerce#1755]
We do have a large community that uses PayPal in Woocommerce, but the plugins that are available to us were last updated like 2 years+ ago. 

We really need an updated plugin that works well like this one.

**Comment by drewangell** [comment]
There shouldn't be any issue with our plugin in Brazil.  If you're having a specific problem please submit a ticket at https://angelleye.com/support and I'm sure we can get you taken care of.
