### ISSUE TITLE
Express Checkout - Checkout button logic.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#176]
With the release of WooCommerce 2.3 they've made some adjustments to the location of the Proceed to Checkout button.  This seems to have effected our logic when nothing but EC is enabled.  

We had it so that the EC button would be the only button on the cart page, and it would go straight to PayPal, of course.  Now, the proceed to checkout button is showing up in the new spot regardless of whether or not EC is the only gateway enabled.  Need to get that resolved.

**Comment by Cassiehk** [comment]
Hi Angelleye, all your work is pretty amazing and definitely helped me skip my checkout out page. However I have noticed that with the update as you mention above, that I too have an additional checkout button now showing. Please let me know how to fix this, as it will confuse my clients. Thank you :)

**Comment by angelleye** [comment]
@Cassiehk, I'm glad the plugin is working nicely for you over all.  In order to hide the button for now you should be able to add a rule into your child theme's style.css file (assuming that you're working with a child theme, which is always recommended.)

If you need more direct help with that you could [submit an order for premium support](www.angelleye.com/product/premium-support/) and we could handle it for you.  Alternatively, you could wait for the 1.1.7 update which will resolve this.  I'm hoping to get it launched within a couple of weeks.
