### ISSUE TITLE
Problems with Coupons when PayPal for WooCommerce is enabled..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#179]
https://wordpress.org/support/topic/woocommerce-version-235-update-plugin-not-working?replies=4#post-6645312

> When I enable your plugin the woocommerce coupon system stops finding products. for example if your plugin is enabled and I go to Woocommerce > Coupons and add a new coupon then under Usage Restriction on the Product text box if I try to add a product it keeps looking for a product and then it do not find any product I have tried it many times with different products and every-time if your plug in is enabled it newer finds any product but once i disable your plug in it starts working...
> 
> This happens on the Products and Exclude Products area only..
> 
> Why is that can you help?

**Comment by levansy** [comment]
Seems you posted the wrong reference link?

**Comment by levansy** [comment]
I tested the coupon part and it seems fine http://screencast.com/t/tnP70lGn

**Comment by kcppdevelopers** [comment]
I have checked above issue on our latest version, for me everything is working fine.
