### ISSUE TITLE
CSS Problem with card logos on checkout page..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#182]
Seems to be a CSS issue with card logos from Pro (DDP and PayFlow) conflicting with PayPal Standard icons/graphic.

![image](https://cloud.githubusercontent.com/assets/629241/6681178/25b051be-cc30-11e4-9ff3-c39226dec12d.png)

**Comment by angelleye** [comment]
Eh, I guess the issue here really is that the PayPal Standard graphic is just too big..??

In most cases people using our plugin won't have Standard enabled, so this isn't an issue when that's the case.  May hold off on "fixing" this until I consider it more.

**Comment by levansy** [comment]
I checked and PayPal Standard graphic is too big

**Comment by angelleye** [comment]
Ok, yeah, I removed the milestone that was set on this so we can try to address it later somehow.  Let's focus on wrapping up 1.1.6.3 for now.  Thanks!
