### ISSUE TITLE
HPOS Support

### ISSUE THREAD

**Issue by galbaras** [angelleye/paypal-woocommerce#1840]
When checking for plugins with no HPOS support, PayPal for WooCommerce is listed. I'm not sure whether this is just a formality or the plugin actually needs to be changed, please please declare support for HPOS before WooCommerce switches to it.

**Comment by nburch** [comment]
+1

**Comment by klsdfr** [comment]
+1

**Comment by deepakmaurya** [comment]
Just to update you guys, we already got this thing added to our PayPal for Woocommerce plugin and expect a new update by next week. It's in our release queue scheduled for next week.

**Comment by strarsis** [comment]
@deepakmaurya: Awesome! I am really looking forward to enabling HPOS on production!

**Comment by galbaras** [comment]
Alas, it doesn't seem like this has been released yet 😞

**Comment by deepakmaurya** [comment]
Hi Guys, HPOS support has been added to PayPal for WooCommerce and We just released a new version, please check that.
Thanks
