### ISSUE TITLE
WooCommerce Blocks Compatible

### ISSUE THREAD

**Issue by kevin25** [angelleye/paypal-woocommerce#1957]
Do you have any plan for WooCommerce Blocks support? Right now it doesn't show Paypal on WooCommerce Blocks checkout

**Comment by drewangell** [comment]
@kevin25 I'm sorry for the delayed update, but we did release block compatible a few versions back.  I just noticed this ticket got left open.  You should be good to go now with Woo blocks in PayPal for WooCommerce.  Please let me know if you have any questions or concerns about that, thanks!

**Comment by kevin25** [comment]
Thank you for your update. I'll check it. However, why your javascript files load everywhere on the single product page for example? That will slow down the website.
