### ISSUE TITLE
i18n Update

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#196]
Don't do this yet, because I'm still reviewing other issues to close on this milestone.

As the last we do, though, before releasing this update, I'd like to make sure we provide an updated default.po file because we've made quite a few changes since the last time we generated one.

**Comment by kcppdevelopers** [comment]
Now inbuilt tool available for generate .POT file : https://developer.wordpress.org/plugins/internationalization/localization/#plugin-repository-admin-tools
