### ISSUE TITLE
Express Checkout - In Context Checkout Integration

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#199]
https://developer.paypal.com/docs/classic/express-checkout/ec_integration/

https://wordpress.org/support/topic/in-context-checkout?replies=3#post-8510647

https://www.angelleye.com/support/scp/tickets.php?id=634

https://www.angelleye.com/support/scp/tickets.php?id=776

https://mail.google.com/mail/u/0/#inbox/1588d611105ed03f

https://wordpress.org/support/topic/does-this-plugin-support-in-context-checkout

https://wordpress.org/support/topic/in-context-checkout-3/

https://wordpress.org/support/topic/in-context-checkout-3/#post-9172401

**Comment by Frihet87** [comment]
The current release v1.1.7.5 does not have the in context, 
is there an updated milestone?

**Comment by angelleye** [comment]
This issue was added to our 1.2.1 milestone, so no, it's not available yet.

We're working to get 1.2 finished up and then we'll be moving into 1.2.1.

**Comment by kcppdevelopers** [comment]
@angelleye 
https://developer.paypal.com/docs/classic/express-checkout/in-context/faq/
Important: This integration method is discontinued as of January 1, 2017. For new integrations, see the [Express Checkout integration guide](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/).

**Comment by angelleye** [comment]
@kcppdevelopers That's interesting.  I've sent a message to my PayPal rep asking for further details on this.

I believe InContext should be pretty quick to add to an existing Express Checkout integration, so let's go ahead and see if we can still get it working in the sandbox as expected.  I believe the message may just be for people doing brand new integrations.

Again, I'll get more info on that, but let's see if we can go ahead and get InContext working in the current integration with that original doc.  That said, if it looks like it's going to take more than a few hours we can wait for more details from PayPal.  I think it should be doable pretty quickly inside an existing integration, though.

**Comment by angelleye** [comment]
@kcppdevelopers Let's follow the old doc for now and go ahead and get it integrated into our existing NVP integration.

In the future we will probably start moving things into REST, which is what the notice about being discontinued is trying to do.  We're good to use the NVP doc for now, though.

**Comment by robwatson-intechra** [comment]
I had to drop using the WooCommerce Angell Eye plugin for the Express Checkout and use an alternate plugin because of Angell Eye's lack of support for in-context (modal or popup) checkout in Express payments.

However, I just noticed this other forum thread:

https://www.angelleye.com/forum/discussion/202/in-context-paypal-express-dialog

which promises that 1.4.0 (we’re now in 1.4.2) would support in-context PayPal Express dialogs.

I’ve just re-enabled that checkout method in WooCommerce and set it up to give it a go. However, I don’t see an explicit setting for in-context, nor is in-context working. It still goes to the full page dialog. Everything else works fine.

Was the delivery date postponed for in-context?

**Comment by angelleye** [comment]
Yes, unfortunately it has been getting pushed because we've had some bug reports on 1.4.0 that we've had to address right away. 

Right now we're focused on bug reports and stability, and we're very close to finishing that all up.  Once that's done we'll be focused on the next of feature additions, and that's when we'll be getting this done.

I know you've been waiting a while, and I'm sorry for that.  We're getting close, though, and working hard to make it happen ASAP!

**Comment by robwatson-intechra** [comment]
Just following up today, a week later, and noticed this is now part of a milestone list due by July 31, 2017. Is that the true date by which you think it'll be ready? If so, I may need to find a different plugin until then.

**Comment by angelleye** [comment]
We're hoping to have it done much sooner than that.  Can't say for sure, though.  Sorry.

**Comment by robwatson-intechra** [comment]
Just checking in again as my manager has asked for an ETA on in-context checkout with PPE. Any news?

**Comment by angelleye** [comment]
Still churning a bit on this, but we're prioritizing, and you can see this has been given the "high priority" label here on GitHub.  We're working on one of the other high priority items now, and as soon as it's done we'll be moving to this.

**Comment by angelleye** [comment]
@kcppdevelopers This documentation includes 8 integration steps for In Context including the step for dropping the JS into the page(s) with the PayPal Express button on it:

https://developer.paypal.com/docs/classic/express-checkout/ec_integration/

I think you'll find that most of the steps are already done since we already have Express Checkout itself integrated.  We just need to add the javascript to make it work like In context.

**Comment by angelleye** [comment]
* In-Context is not working from the WC checkout page regular list of gateways.

**Comment by robwatson-intechra** [comment]
Looking through this changelog, it appears you have added In-Context and that it's deemed as working correctly. But I got a separate email notification with this: "•	In-Context is not working from the WC checkout page regular list of gateways." So I'm confused...unless you meant "now" instead of "not". Either way, I downloaded the latest here from Git and tested In-Context checkout, but it doesn't seem to be working. I noticed that it's not yet added as an update to the WP plugin directory, so maybe I need to wait a little longer? Thanks for continuing to work on it.

**Comment by angelleye** [comment]
Hi Rob,

Sorry for the confusion. In Context is working for EC buttons on the product page, the cart page, the mini-cart widget, and the top of the checkout page.  These are considered "Express Checkout Shortcut" because the WooCommerce checkout page is skipped entirely.

If you use the WC checkout page and Express Checkout within the regular list of gateways there, In-Context will not be used.  This decision was made based on discussions with PayPal and following WooCommerce standards.  

Have you tried using any of the Shortcut options?

**Comment by frecklesKarin** [comment]
@angelleye Is it supposed to be changed in the future? There is no option to enable the in-context feature in the checkout page? 
In my browser dev tools, I can see checkout.js is used, but in-context is not working, and there's no error.

**Comment by angelleye** [comment]
@frecklesKarin I'm sorry for the delay responding.  We do have plans to get In Context working from the WC checkout page, but it was being a little tricky with the way WC order management works, so we curbed it for the last release.  We're going to try to get this done i our 1.5.0 update.
