### ISSUE TITLE
Possible issue with new WC update and checkout button...??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#200]
https://wordpress.org/support/topic/proceed-to-checkout-button-is-back?replies=5#post-6856219

**Comment by angelleye** [comment]
I need to provide some detail so you fully understand what's going on here.  

We have some logic surrounding how to display the "Proceed to Checkout" button that WooCommerce provides.  That logic has become broken, though, after the 2.3 update of WooCommerce because they made some changes to how they're outputting the Proceed to Checkout button.  The way it's supposed to work is this...

1. If the ONLY payment gateway enabled in WooCommerce is PayPal Express Checkout, and the "Cart Page" option in Express Checkout settings is enabled, then the Proceed to Checkout button should be replaced by the PayPal Express Checkout button and would use whatever option was set for "Checkout Button Type" in the Express Checkout settings.

When the 2.3 update of WooCommerce was released this seems to have broken, and the "Proceed to Checkout" button shows up even when Express Checkout is the only payment gateway enabled.  This results in people clicking the Proceed to Checkout button, then they see a message that no gateways are enabled (unless the EC settings are configured to include the EC button in the general list of gateways on the checkout page.)

2. If both Express Checkout and either DoDirectPayment or PayFlow are enabled, but no other payment gateways are enabled, and the "Cart Page" option is enabled in Express Checkout settings, then the "Proceed to Checkout" button should say "Pay with Credit Card" instead, but it would still act the same way.

If the "Cart Page" option is disabled, though, so the PayPal Express Checkout button doesn't show up there, then we would leave the "Proceed to Checkout" button alone.

3.  If any other gatways are enabled outside of what's covered above, then the Proceed to Checkout button would function as it does by default.

**Comment by jigneshkailam** [comment]
I have resolved above issue and push to issue #200 branch, Please review it and let me know if any problem still there.
