### ISSUE TITLE
Button Location Options for Cart Page

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-woocommerce#2005]
# Story

As a merchant, I would like the ability to adjust the sort order of PayPal buttons and the Woo "proceed to checkout button" on the cart page, so that I can swap the default position if I want to.

# Description

![image](https://github.com/angelleye/paypal-woocommerce/assets/64537522/d0a92add-dc71-4e1d-80ec-3a8b3f4bf9ff)

**Comment by devchristina2** [comment]
Closing this issue, will revisit in the future.
