### ISSUE TITLE
Move data from order notes to their own meta fields.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#201]
Right now we seem to be saving transaction IDs, customer notes, etc. to the WooCommerce order notes.  It's a little bit "busy" and it's not very easy to manage.

I would like to pull some of this data out of the WC order notes and create meta fields for them instead.  

For example, I would like to make sure the transaction ID (both regular and refunds), the customer notes returned in Express Checkout, the PayPal Payer Status, Address Status, AVS / CVV2 results, etc. all go in their own meta fields.

Of course, I'd like to add these to the order display so they look good and presentable, and we need to make sure the data is always included when WC orders are processed or handled in any way.

Here's a thread where this came up for reference: https://wordpress.org/support/topic/delivery-notes

**Comment by angelleye** [comment]
Looks like the order notes already  have a place that WooCommerce provides, so we need to utilize that instead of sticking them in the right column.

**Comment by angelleye** [comment]
We have also had complaints that when people enter notes into the WooCommerce checkout page and complete payment that way then those notes are not making it through to the saved order or in PayPal.

We need to make sure that any notes added in PayPal during Express Checkout and/or notes left on the WC checkout page get included in the final PayPal request as well as in the final WC order details.

**Comment by angelleye** [comment]
I'm getting reports that when customers enter notes via Express Checkout they are not getting saved to the order in WooCommerce.  We need to make sure this is working as expected.

The customer would enter notes on the PayPal Express Checkout pages, and then the notes they enter would be available in the GetExpressCheckoutDetails response.  We need to make sure we're pulling that correctly and saving it in the WooCommerce order/customer notes.

**Comment by angelleye** [comment]
I watched the video you have in the commit comments (2bb5f37).

I see that the notes people leave on the PayPal Express Checkout page are still getting left in the right column of the WooCommerce order.  What I wanted was for those notes to be moved into the "Customer Note" meta data section where the WooCommerce checkout page notes are getting placed.

For DoDirectPayment and PayFlow the WooCommerce checkout page is always used, so those notes seem to be showing up where we want just fine.

For Express Checkout, though, we need to add some logic to handle different scenarios accordingly.

If the person is using Express Checkout from the cart or product page then they would have never had a chance to enter notes before getting sent to PayPal.  In this case the only notes we will have are from the PayPal Express Checkout page, and then returned in GetExpressCheckoutDetails.  These notes need to be moved into the "Customer Note" meta data field so it shows up there instead of in the right column.

If the person is using Express Checkout from the WooCommerce checkout page, then they would be entering notes on that screen.  In this case, what we need to do is adjust the SetExpressCheckout request to disable notes on the PayPal Express Checkout pages since we already have notes from the WooCommerce checkout page.

You'll notice that the $SECFields array in the wc-gateway-paypal-express-angelleye.php class has a parameter in it called 'allownote'.  We can set this to a 0 to disable the notes

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with the functionality as per above comment. and pushed to "Issue-201B" branch for a review.

**Comment by angelleye** [comment]
I did a test Express Checkout order from the WooCommerce checkout page and entered notes on the checkout page.

The API request to PayPal was correct, and disabled the notes there.  However, the notes that I entered on the WC checkout page did not show up anywhere in the order at all.

Here is a video:  http://fiber.angelleye.com/temp/paypal-for-woocommerce-ec-notes.mp4

**Comment by angelleye** [comment]
I tested using Express Checkout from the product page, so then I was able to enter a note on the PayPal checkout page.  That note did show up where it was supposed to in the WC order, so it's only from the WC checkout page that it's not working.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Here I tested the case for order note from checkout page. and it works fine for me here. Did you pull the latest code from "Issue-201B" . Below is video link from my server.

URL : http://www.screencast.com/t/w2xvgsEZL2I

Please review it and let me know if you have still issue.

**Comment by nishitlangaliya** [comment]
Issue sorted , latest code pushed to " Issue-201C' branch for a review.

**Comment by angelleye** [comment]
Tested EC from cart page, product page, and checkout page.  Also tested DDP and PayFlow.  Notes are working in all areas, so I'm closing this issue.
