### ISSUE TITLE
Set sandbox at product level in addition to global settings.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#204]
Sometimes there are instances when somebody wants to test a single product / order in the sandbox, but they want to do this from their live site without setting the entire thing to run in sandbox mode.

I'd like to add an option in the product settings that allows you to enable/disable "sandbox mode" the same you can enable/disable things like downloadable, virtual, etc.

**Comment by angelleye** [comment]
If any item in the cart is set to sandbox then the sandbox should be used.

**Comment by angelleye** [comment]
@kcppdevelopers I tried testing this in Express Checkout.  In the regular EC settings page I have sandbox disabled, but at the product level I have sandbox enabled.  Then I click the EC button from the product page of this product, but it fails with bad API credentials.  Then I set the regular EC settings page back to sandbox mode and it worked as expected.  The product-level sandbox mode should be overriding the general EC settings.

**Comment by kcppdevelopers** [comment]
@angelleye  Can you please double check for me? I have test this issue and it's working fine for me.
Please enable this option https://www.screencast.com/t/AoICwFW1lk to enable product level sandbox testing.

**Comment by angelleye** [comment]
Yes, that is the option I enabled, but I will try it again.

**Comment by angelleye** [comment]
@kcppdevelopers , Still not working for me.  Here is a video:  http://fiber.angelleye.com/forums/github/paypal-for-woocommerce/gh204.mp4

**Comment by angelleye** [comment]
@kcppdevelopers It's working for me from the cart page, but not from the product page.  Need to make sure it works in all places..

* Product page
* Cart page
* Top of checkout page
* General WC payment gateways on checkout page

**Comment by kcppdevelopers** [comment]
I have followed same step as per above video and it's working fine for me on woo.angelleye.com domain.
Can you please clear cart and browser cache and try one again for me ?
