### ISSUE TITLE
readme.txt not displayed properly

### ISSUE THREAD

**Issue by galbaras** [angelleye/paypal-woocommerce#2043]
In the WordPress back-end, when clicking to view the details for an outstanding update, the first changelog block looks OK, but the rest are indented.

The FAQ tab appears to the left of the Screenshots tab, although its code appears later in the readme.txt file, and there's an empty Other Notes tab, which isn't in the code.

Also, the Requires PHP header item and the Last updated header are missing.

![image](https://github.com/angelleye/paypal-woocommerce/assets/7981897/e26e1481-dff5-4a22-8a83-d710b2861b76)

**Comment by devchristina2** [comment]
Hi @galbaras, 

Thank you for letting us know about this. We've changed our support model, and tickets are now created/tracked on https://angelleye.atlassian.net/servicedesk/customer/portals. I've made a ticket for you on this issue. Would you like me to tie you to the ticket so you're informed of the outcome?

Thanks, Christina.
