### ISSUE TITLE
Billing Country Not Captured

### ISSUE THREAD

**Issue by ReignOfComputer** [angelleye/paypal-woocommerce#2044]
Hi,

I have a store that only collects the user's zip code. I noticed that in later versions of this plugin, the address is no longer being captured. Perhaps there is some logic that doesn't capture the address if the Street Address is empty, or something like that?

Thanks.

**Comment by Brandoning** [comment]
Having the same issue here, all payments that don't use PayPal have the address so I know it's not something with my checkout.

Any PayPal payment has the billing address / details missing. Started since the update to 4.4.33

**Comment by GiovanniGoccia** [comment]
I also have the same problem from 4.4.33, I went back to 4.4.30 waiting for this bug to be fixed

**Comment by Brandoning** [comment]
Still doesn't seem to be fixed. If you go through the checkout you get one of two errors:

- Couldn't create order, Billing first name and last name not defined (then it reloads to an empty checkout)
- You already have an account, please log in (using a fresh email that isn't attached to an account)

Only 10% of my tests actually went through.

**Comment by GiovanniGoccia** [comment]
no news yet? I am still stuck on version 4.4.30 so as not to risk malfunctions

**Comment by ReignOfComputer** [comment]
No news, dev hasn't been responsive here or on tickets either. Unfortunate.

**Comment by drewangell** [comment]
Hello All,

I apologize for the lack of communication here.  I will be fixing that problem so we'll take much better care of you going forward.

I will get this fixed right away, but I need to know how to reproduce it.  Can any of you provide specific examples on when this is happening so I can try to do the same on my test site?

Once we're able to reproduce it we'll get it fixed right away!

**Comment by GiovanniGoccia** [comment]
Hi,
It happened to me straight away from version 4.4.33. On every order paid with paypal, woocommerce would lose some address data like billing country.
I have not tried the new version 5 waiting for confirmation that it is fixed.

**Comment by drewangell** [comment]
Hey guys, we did release an update that should have resolved this, but it wasn't hooked up to this specific Git issue, so it didn't update here.

Please check the latest update to the plugin that you should see now and let me know if you continue to have any problems with it.

**Comment by GiovanniGoccia** [comment]
I tried the latest update today and everything seems OK.

**Comment by drewangell** [comment]
@GiovanniGoccia Thanks for verifying.  Sorry again for the delay.  Please let us know if anything else comes up and we'll get you taken care of much more quickly.  Thanks!
