### ISSUE TITLE
Authorization failed due to insufficient permissions (Action: Setup Tokens)

### ISSUE THREAD

**Issue by galbaras** [angelleye/paypal-woocommerce#2046]
Got this issue on multiple sites lately (I'm guessing this is related to v4.4.33). I received and email notification like this:

![image](https://github.com/angelleye/paypal-woocommerce/assets/7981897/d06d1829-cee4-43d4-8dfb-059015a394bb)

I've looked for "Setup Tokens" in the code, and the only references are in in the [PPCP class](https://github.com/angelleye/paypal-woocommerce/blob/a4efec2cc8236dcb9dbbb141a844d3a4dcec71be/ppcp-gateway/class-angelleye-paypal-ppcp-payment.php), which makes me think the error is coming from the PayPal end.

"Authorization failed due to insufficient permissions" doesn't appear anywhere, so again, likely coming from PayPal.

There are no orders, failed or otherwise, on the respective sites, so this may be happening at some other time outside of checkout.

**Comment by galbaras** [comment]
Still having the problem, and I’m not even sure what’s causing it. Please help!

**Comment by galbaras** [comment]
Still getting those messages, unfortunately 😞

**Comment by hazrpg** [comment]
We have been getting these messages too!

Oddly, looking up the IP is registered to Microsoft based on the `whois` information.

![image](https://github.com/user-attachments/assets/91966036-b1d1-464c-8904-8febe8e46caa)

**Comment by hazrpg** [comment]
@galbaras Oddly, the IP shown in yours is also registered to Microsoft. Is this caused by a bot maybe?

**Comment by galbaras** [comment]
I'm not sure how this happens. That's why I was hoping for some help from the plugin team.

**Comment by knightcott-paul** [comment]
Also getting these with version 4.4.20

Would be nice to know what's going on

**Comment by knightcott-paul** [comment]
Reverse DNS indicates it's MSN search bot, in my case:

> msnbot-52-167-144-224.search.msn.com

A search of the site logs shows no traffic from 52.167.144.224

**Comment by knightcott-paul** [comment]
> A search of the site logs shows no traffic from 52.167.144.224

I'm stupid.  The traffic is proxied.

**Comment by devchristina2** [comment]
Hi all, 

I'm sorry for not getting back to you sooner. Unfortunately, the support process was moved [here](https://angelleye.atlassian.net/servicedesk/customer/portals), and the issues were not turned off within GitHub. 

This may have been fixed for some, maybe not all. Can each of you please reply back and let me know if you still are facing issues? 

Thanks, Christina.

**Comment by drewangell** [comment]
Hey everybody,

Following up on Christina's message - this is something we saw previously and fixed it some time ago.  There is a chance, though, that you fell into a crack because of changes PayPal made on their side and the timing of it with relation to changes made on our side.

If you are still experiencing this issue on the latest v4.5.19 of our plugin, then please submit a ticket at the link Christina provided and we'll get you taken care of.

Thanks!

Drew
