### ISSUE TITLE
CAPTURE_ID_NOT_FOUND: Specified capture ID does not exist. Check the capture ID and try again.

### ISSUE THREAD

**Issue by kaoopro** [angelleye/paypal-woocommerce#2060]
pls fix this when using add tracking to Paypal. your apps using old authorized ID. when i  captured payment later it not using new ID. because of you are using Transaction ID of authorized not captured ID. pls fix

**Comment by devchristina2** [comment]
Hi Kaoopro, 

I'm sorry for the delay in our response. Our support process has changed, and requests go through [here](https://angelleye.atlassian.net/servicedesk/customer/portals). I've created a ticket for the issue you're describing here for our engineers to research. 

Thanks, Christina.
