### ISSUE TITLE
Conflict with Relevanssi Search plugin.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#207]
https://www.angelleye.com/forum/discussion/63/conflict-with-relevanssi-search-plugin

**Comment by angelleye** [comment]
I'm actually not getting the exact same error, but I am getting a message about a bunch of extra output getting included when I activate the Relevanssi plugin.

**Comment by jigneshkailam** [comment]
I have install https://wordpress.org/plugins/relevanssi/ plugin and start finding bug, when I active plugin it's give me some notice related to database, it's plugin problem not our plugin problem.

Then after I have click on "Continue indexing" button it will give me fatal error like "PHP Fatal error:  Call to undefined function wc_print_notices() in /var/www/paypalipn/wp-content/plugins/paypal-woocommerce/paypal-for-woocommerce.php on line 358"

it's not our plugin problem, I have test 2 other WooCommerce plugin with relevanssi, plugin also conflict with other WooCommerce plugin

Finally I have check https://wordpress.org/support/topic/woocommerce-fatal-error-5
plugin here author said like "Expand shortcodes in post content" in setting option just make it diable then automatically error go away

That's mean relevanssi plugin is not working well with WooCommerce shortcode notice related function.
