### ISSUE TITLE
Express Checkout - Adjust button on product details page.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#208]
Right now when you click the Express Checkout button from a product page it adds the item to the cart prior to setting up the PayPal request and redirecting to PayPal.  If the item is already in the cart, it adds an additional unit.

This becomes an issue when the product is set to "sold individually" in WooCommerce.  If this sort of item is already in the cart when you click the PayPal EC button on the product page then it just returns an error about the item already being added to the cart and it doesn't actually move forward to PayPal.

For more details review the following support thread.

https://wordpress.org/support/topic/weird-mix-between-checkout-with-paypal-and-add-to-cart?replies=9#post-6998054

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I see the comment and read "https://wordpress.org/support/topic/weird-mix-between-checkout-with-paypal-and-add-to-cart?replies=9#post-6998054"

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I see the comment and read "https://wordpress.org/support/topic/weird-mix-between-checkout-with-paypal-and-add-to-cart?replies=9#post-6998054" 

from that thread what  I understood is here user has a problem that even if the product is set           as "individual sold" . using our plugin's express checkout button user is able to add that product more than one time am  I right ? if yes then I have prepared one video from my local server and user's website for test the case.

In that testing I was not able to add individual sold product more than one time using our expresschekout button.

Please see below URL when you get a chance and let me know your thoughts for the same.

URL : http://www.screencast.com/t/ODXStPit8kwf

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Here What Other things I understood is. as per your comment you mean that if the product is "sold individual" and already added to cart than instead of giving the error on product page it should redirect to paypal without adding that product second time into cart am  I right ?

and if the product type is not " sold individual" than it should add to cart  and redirect to paypal is it right ?.

so I have done code according to it and pushed code to Issue-208 branch for a review.

**Comment by angelleye** [comment]
Need to review this and see if the commits made are good or if you need to make any adjustments.  Please handle and test accordingly.

**Comment by kcppdevelopers** [comment]
I have push latest code in issue-208-B branch.
