### ISSUE TITLE
Expected currency from order api call to be USD, got GBP. Please ensure you are passing currency=GBP to the sdk url. 

### ISSUE THREAD

**Issue by tigerbiaowithme** [angelleye/paypal-woocommerce#2080]
Only for USD. if web has the currency switch plugin, it couln't work.
![image](https://github.com/user-attachments/assets/3d08e8ee-a3e7-4a28-b61d-3b4184b79f34)
![image](https://github.com/user-attachments/assets/d473666c-259e-467e-8fc2-8b67f31e1c95)

**Comment by devchristina2** [comment]
Hi @tigerbiaowithme, I'm closing this issue since we're working together on the help desk ticket (ahd-22579).
