### ISSUE TITLE
Plugin Settings Panel

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#214]
Currently, our plugin settings are all done through WooCommerce -> Settings -> Checkout tab.  

#174 adds a product specific setting and we need a tool similar to what we did in Offers for WooCommerce to manage it.  It's time for our own settings panel.

For this issue, let's go ahead and get our own settings panel setup under Settings -> PayPal for WooCommerce in the WP admin panel.  Just prepare a "General" tab and maybe a "Tools" tab, and within the general tab we can have links to the current checkout settings pages.

**Comment by jigneshkailam** [comment]
I am done with Plugin Settings Panel and push to issue branch for your review.

**Comment by angelleye** [comment]
I had to resolve a merge conflict here, which I think I did correctly.  Everything seems to be working as expected except for one thing.

When I first enter our new settings panel via Settings -> PayPal for WooCommerce, I see this error under the Express Checkout tab, and the link to the current settings page does not display:

![image](https://cloud.githubusercontent.com/assets/629241/11916101/390327c2-a68d-11e5-964c-bd6d4d1ee643.png)

If I click to one of the other tabs, though, and then click back it works fine:

![image](https://cloud.githubusercontent.com/assets/629241/11916105/4dbd26ae-a68d-11e5-9a0d-3a04744b5b28.png)

Each time I leave the settings page and come back the same thing happens.

**Comment by angelleye** [comment]
We also need to add a new tab for PayPal Plus (Germany) which is now available in the plugin.

**Comment by angelleye** [comment]
I'm getting a conflict when I try to merge Issue-214-A into the release branch.  Please merge the release branch into Issue-214-A and resolve the conflict.

**Comment by kcppdevelopers** [comment]
I have resolved conflict and push issue-214-B branch into the release branch.

**Comment by angelleye** [comment]
I am not getting the error anymore, but now the Express Checkout tab content still does not display when I first load it.

I go to Settings -> PayPal for WooCommerce, and this is what I see:

![image](https://cloud.githubusercontent.com/assets/629241/12004978/0a566aca-ab4b-11e5-8ad7-a0192aa7d3aa.png)

If I then click to one of the other tabs, and back to the Express Checkout tab, then I do get the content I expect, like this:

![image](https://cloud.githubusercontent.com/assets/629241/12004980/1fad6f90-ab4b-11e5-91e8-a39a160a18b3.png)

**Comment by kcppdevelopers** [comment]
I make it correct and push the latest code into the release branch.
