### ISSUE TITLE
Express Checkout - Issues when checking out as a guest..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#216]
I have WooCommerce guest checkout enabled, so I should not have to create an account when checking out.

I have Express Checkout disabled on the cart page and the product pages, so it's only showing up on the WooCommerce checkout page in the regular list of gateways.

During checkout, I'm skipping the option to "create an account" so I should not have to enter any such details, however, when I try to continue I am getting an error that I have to create a password.

![image](https://cloud.githubusercontent.com/assets/629241/8127945/4df5d552-10c0-11e5-881d-eead2528c0de.png)

![image](https://cloud.githubusercontent.com/assets/629241/8127948/5791a4e2-10c0-11e5-8c3a-53861fb26386.png)

![image](https://cloud.githubusercontent.com/assets/629241/8127956/62d440c6-10c0-11e5-9050-dbaa3231eccc.png)

**Comment by angelleye** [comment]
If I choose a payment option other than Express then it doesn't seem to be an issue and it goes through just fine.

**Comment by jigneshkailam** [comment]
I am done with this issue and push to issue branch fro you review.
