### ISSUE TITLE
Express Checkout - Shipping Tables

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#218]
Since Express Checkout skips the checkout page, some shipping rules are not kicking in and allowing people to purchase items they shouldn't be able to.

https://wordpress.org/support/topic/no-shipping-class-allows-customer-free-shipping?replies=3#post-7066835

**Comment by angelleye** [comment]
@kcppdevelopers Marked ready for review, but I don't see any commits or notes..??

**Comment by kcppdevelopers** [comment]
Yes, I have checked this issue with our new express checkout and it's working fine for me.
