### ISSUE TITLE
Express Checkout - Place Order / Cancel Buttons

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#219]
In #200 we adjusted something to fix the Proceed to Checkout button after the WooCommerce 2.3 update, however, it looks like we also need to make an adjustment to our Cancel Order and Place Order buttons on the review page the plugin uses with Express Checkout.

A customer that tried our dev branch already says it fixed their Proceed to Checkout, but this is what their review page looks like.  

![image](https://cloud.githubusercontent.com/assets/629241/8153679/d4be74ee-12f6-11e5-9a5c-d38da3296c51.png)

Need to see what adjustments need to be made to ensure those buttons aren't stretched out like that.

**Comment by jigneshkailam** [comment]
I have looked into this issue and found one issue in "The Retailer - Responsive WordPress" Theme
that theme is using force important CSS attribute like "display: block !important;" in (style.css line 2760)
just need to remove "display: block !important;" CSS attribute.
