### ISSUE TITLE
PayFlow - Empty Card Data Validation Problem

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#220]
When checking out with PayFlow, if I leave the credit card details blank at the bottom of the checkout page and place the order, the validation does tell me that I need to enter a valid card number, however, it also generates and sends the request to PayFlow which results in an "invalid account number" error.

If the form validation on the checkout page fails then we should not be sending any request to PayFlow at all.  Only send the PayFlow request when validation is good.

**Comment by kcppdevelopers** [comment]
I have push latest code into the issue-220-A branch.
