### ISSUE TITLE
PayPal Express Checkout issue with WooCommerce 2.3.0+

### ISSUE THREAD

**Issue by IgorCode** [angelleye/paypal-woocommerce#222]
Angelleye plugin uses `woocommerce_proceed_to_checkout` action to display PayPal button, but if you look at this commit https://github.com/woothemes/woocommerce/commit/ef28c43862b07b3dce52ccdc57183d2823e2e810#diff-97ddb272729b3ec92835746e11f935c1L128 you will see that this action's name is changed to `woocommerce_cart_actions`.

I would create pull request but I don't know how you want to handle old and new versions of WooCommerce with two different action names.

**Comment by angelleye** [comment]
@jigneshkailam Can you please look and see if we've handled this in our 1.1.6.3 milestone already?

**Comment by angelleye** [comment]
@IgorCode I think we may have handled this already in our dev branch, but I'm going to make sure we double check.

**Comment by IgorCode** [comment]
@angelleye, @jigneshkailam It turns out there is no issue after all, I apologize for making a confusion.

In  WC 2.3.0 checkout button has been repositioned bellow totals, so now `woocommerce_proceed_to_checkout` action is moved from `cart` to `cart-totals` template and button is still there. My `cart-totals` template was not updated to latest version, this is way I had the issue with missing PayPal button.

**Comment by jigneshkailam** [comment]
I have look into this and found WooCommerce just change hook place cart.php to cart-totals.php file. no more change is there.
