### ISSUE TITLE
Account is not getting created when using 'PayPal Express Checkout'

### ISSUE THREAD

**Issue by nishitlangaliya** [angelleye/paypal-woocommerce#223]
HI,

I tested below case and I found that user is not getting created when they returns from PayPal.

- WooCommerce general checkout settings - Guest Checkout is enabled.

- User checks out through WooCommerce checkout page and does enter a password to create the account and pay using 'PayPal Express Checkout' but then the account is not getting created. when they are returns from PayPal.

user is expecting account be created and automatically signed in after they're returned from PayPal.

**Comment by jigneshkailam** [comment]
I am done with this issue and push to issue branch for your review.
