### ISSUE TITLE
Another cart totals error.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#226]
The user who grabbed it early is still running into cart total issues.  Here's a log that just produced it.

06-21-2015 @ 15:18:37 - Redirecting to PayPal
06-21-2015 @ 15:18:52 - Start Express Checkout
06-21-2015 @ 15:18:52 - Test Mode: no
06-21-2015 @ 15:18:52 - Endpoint: https://api-3t.paypal.com/nvp
06-21-2015 @ 15:18:52 - Request: Array
(
    [USER] => *****
    [PWD] => *****
    [VERSION] => 112.0
    [BUTTONSOURCE] => AngellEYE_SP_WooCommerce
    [SIGNATURE] => *****
    [METHOD] => SetExpressCheckout
    [RETURNURL] => http://testmango.com/checkout/review-order/?pp_action=revieworder
    [CANCELURL] => http://testmango.com/cart/
    [NOSHIPPING] => 1
    [SOLUTIONTYPE] => Sole
    [LANDINGPAGE] => Login
    [PAYMENTREQUEST_0_AMT] => 0.60
    [PAYMENTREQUEST_0_CURRENCYCODE] => USD
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0.00
    [PAYMENTREQUEST_0_TAXAMT] => 0.00
    [PAYMENTREQUEST_0_PAYMENTACTION] => Sale
    [L_PAYMENTREQUEST_0_NAME0] => 2013 Essentials of Life-Span Development, 3rd Edition Test Bank
    [L_PAYMENTREQUEST_0_AMT0] => 25
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_NAME1] => 2010 Contemporary Nursing, 5th Edition Test Bank
    [L_PAYMENTREQUEST_0_AMT1] => 25
    [L_PAYMENTREQUEST_0_QTY1] => 1
    [L_PAYMENTREQUEST_0_NAME2] => 2010 Clinical Manifestations 
    [ Assessment of Respiratory Disease, 6e Test Bank&L_PAYMENTREQUEST_0_AMT2] => 25&L_PAYMENTREQUEST_0_QTY2=1&L_PAYMENTREQUEST_0_NAME3=Cart Discount&L_PAYMENTREQUEST_0_NUMBER3=deals&L_PAYMENTREQUEST_0_QTY3=1&L_PAYMENTREQUEST_0_AMT3=-15.00&L_PAYMENTREQUEST_0_NAME4=Cart Discount&L_PAYMENTREQUEST_0_NUMBER4=free99&L_PAYMENTREQUEST_0_QTY4=1&L_PAYMENTREQUEST_0_AMT4=-59.40&PAYM
    [L_PAYMENTREQUEST_0_AMT2] => 25
    [L_PAYMENTREQUEST_0_QTY2] => 1
    [L_PAYMENTREQUEST_0_NAME3] => Cart Discount
    [L_PAYMENTREQUEST_0_NUMBER3] => deals
    [L_PAYMENTREQUEST_0_QTY3] => 1
    [L_PAYMENTREQUEST_0_AMT3] => -15.00
    [L_PAYMENTREQUEST_0_NAME4] => Cart Discount
    [L_PAYMENTREQUEST_0_NUMBER4] => free99
    [L_PAYMENTREQUEST_0_QTY4] => 1
    [L_PAYMENTREQUEST_0_AMT4] => -59.40
    [PAYMENTREQUEST_0_ITEMAMT] => 0.59
)

06-21-2015 @ 15:18:52 - Response: Array
(
    [TIMESTAMP] => 2015-06-21T19:21:07Z
    [CORRELATIONID] => 12c6bb7f737bb
    [ACK] => Failure
    [VERSION] => 112.0
    [BUILD] => 17098556
    [L_ERRORCODE0] => 10413
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => The totals of the cart item amounts do not match order amounts.
    [L_SEVERITYCODE0] => Error
)

**Comment by jigneshkailam** [comment]
I have fully tested all the cases related to rounding problem and push to issue branch for your review.
