### ISSUE TITLE
Express Checkout - WC checkout page gateways graphic.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#235]
The current graphic we have is...

![image](https://cloud.githubusercontent.com/assets/629241/8415667/25c485c0-1e66-11e5-8281-a3fc2cc90f9f.png)

I've had complaints that it doesn't include credit card logos.  

I'd like to change the graphic to something a little better, and possibly also an option or maybe a hook so people can easily add their own graphic.

**Comment by kcppdevelopers** [comment]
We have already provide hook for filter icon for payment gateays.

http://pastebin.com/arXXJVM8
