### ISSUE TITLE
Express Checkout - Add PayPal account email to API request.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#239]
When using Payments Standard if you specify a secondary email address on a PayPal account in the button code it will use that email to send PayPal notifications to for the payment.

Within Express Checkout there is a parameter for PAYMENTINFO_n_SELLERPAYPALACCOUNTID that is used with parallel payments to specify which PayPal account the payment should go to.

I have tested this with a single payment to a 3rd party account and it works, but I've never tested with the email account that belongs to the same account as the API credentials.  I also haven't tested it with a secondary email address on that account to see if that work, and then if PayPal notifications would go to that email instead.

Need to run tests of these scenarios and if it works as hoped then we can add an option into the plugin where people could enter the email address they would like to use for their account, which would then be included in the SetExpressCheckout and DoExpressCheckoutPayment requests.

**Comment by kcppdevelopers** [comment]
I have tested with an email account that belongs to the same account as the API credentials and it works. but when I try with to add a secondary email address on that account, it added as successfully with Unconfirmed status. PayPal is not sending confirmation link on that account.

I have tested with the secondary email address to the  same account as the API credentials and it does not work, payment sent to the primary email address instead of secondary email address.

Is there any way to confirm secondary email address in PayPal sandbox?

**Comment by angelleye** [comment]
Log in to http://developer.paypal.com, go to your dashboard, and then click on Accounts under sandbox to view your sandbox accounts.

Under each one you should see a link that says "Notifications".  If you click into that you would see any emails that would typically be sent out to actual emails.  The sandbox just sends everything there.  Hopefully you'll find the confirmation email in there.

**Comment by kcppdevelopers** [comment]
I have already checked there. I have not found any URL, email body just contain encrypted text messages.

Please see the screenshot for more details: http://screencast.com/t/jt8mC3nlkS

**Comment by angelleye** [comment]
Is the whole thing like that if you scroll down?  You might be able to find the confirmation URL.  

Does the subject of that email look like what you're looking for?

**Comment by kcppdevelopers** [comment]
Yes, I have check whole thing and not able to find confirmation URL. 

Here is Full body of confirmation email: http://pastebin.com/bGY8r3YA

It seems Base64 Encode text, I have to try to  Base64 Decode of that text: http://pastebin.com/ewebf8CT but HTML is broken.
