### ISSUE TITLE
Express Checkout - Custom checkout fields.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#240]
Not exactly sure how we're handling this, so we need to look into it and possibly make an adjustment.

I have a customer adding custom fields to their checkout.  These fields are not getting saved with the order when users pay with Express Checkout.

The custom fields don't have matching data parameters in PayPal, of course, so we're not sending the custom data to PayPal.  The problem is that the WC order doesn't get created until the user has returned from PayPal (I think).  This would mean that custom data is never getting saved, which is why it's not showing up on the order when checkout is complete.

**Comment by angelleye** [comment]
@kcppdevelopers I see this marked ready for review, but I don't see any commits or notes..??

**Comment by kcppdevelopers** [comment]
I have checked this issue with our new express checkout and it's working fine.
