### ISSUE TITLE
Order Total Missing Errors

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#241]
Since the release of the plugin we've had many complaints about "order total missing" errors from PayPal.  Disabling cache plugins always resolved the issue, but I never got more info than that from anybody.  Wasn't sure if they were able to adjust the caching plugins to make it work, or what.

In a support ticket at our help desk (ref. 502291) I was given the following details.
- W3 Total Cache
- Page Caching Enabled (no problems)
- Database Caching Enabled (causes order total missing error)
- _wc_session_ listed in the "ignore query stems" section of the database cache settings WAS enabled and the problem still occurred.
- PayPal Standard does NOT have this problem.

We need to research this and figure out what's causing to see if we can resolve it.

**Comment by nishitlangaliya** [comment]
Hi,

I have started to look into this ticket and looking with one by one plugin as mention above. I am in middle of it , once I finished with above plugin will Get back to you.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I have tested below cases with w3-total-cache plugin :
" -> W3 Total Cache
-> Page Caching Enabled (no problems)
-> Database Caching Enabled (causes order total missing error)
-> wc_session listed in the "ignore query stems" section of the database cache settings WAS enabled and the problem still occurred."

But I did not get an error of a cart total. I think that was an issue of general cart total error which is now handled with #243 so I did not got an error .

Please let me know your thoughts and suggestions for the same.

**Comment by angelleye** [comment]
This issue wasn't for "cart total" problems.  It was for "order total missing" which is a different issue.

The "cart total" problems we've had are when we have values, but the values simply do not calculate correctly.

This particular issue is that the order total itself is simply blank...no value at all.  It happens to lots of people, and it's always because they're running db caching.  

I hear this from lots of people, and they say they don't have the problem with PayPal Standard or other gateways, so we need to look into this more. We may need to adjust some of the settings in the W3 Total Cache plugin to see if we can reproduce the problem.

**Comment by angelleye** [comment]
I'm waiting on details about how exactly they have W3 Total Cache configured so we can try to reproduce the problem.  Until then we should just try various settings, especially regarding database caching.

**Comment by angelleye** [comment]
![image](https://cloud.githubusercontent.com/assets/629241/9029197/9a9b2c9c-3954-11e5-9291-9baeeb75b5e1.png)

![image](https://cloud.githubusercontent.com/assets/629241/9029201/a3372234-3954-11e5-8dfc-468b2f4be63e.png)

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I did above setup in my local server in w3-total cache plugin. but the cart total error was not generated. please let me know your thoughts for the same.

**Comment by angelleye** [comment]
I'm going to go ahead and move this to our next update because I don't want to delay this one any more.  We'll work on it more later.
