### ISSUE TITLE
Cart Totals Error

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#243]
We have a report of a cart totals error when using a gift card / discount on the order.  

https://www.angelleye.com/support/scp/tickets.php?id=154

I'm waiting for details on which gift card plugin they're using so we can try to reproduce it.

**Comment by angelleye** [comment]
Another example from Sy, the original developer on this.

[7/13/15, 2:06:23 PM] Sy Le (Paul): Coupon is a percent discount
[7/13/15, 2:06:28 PM] Sy Le (Paul): 10%
[7/13/15, 2:07:15 PM] Sy Le (Paul): The product is 149.95
[7/13/15, 2:07:35 PM] Sy Le (Paul): Discount 10 percent is $15
[7/13/15, 2:07:57 PM] Sy Le (Paul): But the total is 134.96
[7/13/15, 2:08:18 PM] Sy Le (Paul): So it causes this issue

149.95 - 15.00 = 134.95, but is calculating 134.96 for some reason.

**Comment by angelleye** [comment]
To review, in this case, we have...

149.95 * .1 = 14.995.  This gets rounded and displayed as 15.00 by WooCommerce.

Our line items then become 149.95 - 15.00, which is 134.95.  

The subtotal that we're calculating (ITEMAMT) is using 149.95 - 14.995 = 134.955, which then gets rounded to 134.96, so we're a penny off.

Seems like we didn't round the discount amount prior to calculating our ITEMAMT value.

**Comment by angelleye** [comment]
Here's another user with the problem.  In this case it seems the math for the order items is simply coming up a penny off...

07-03-2015 @ 07:48:28 - Request: Array
(
    [USER] => *****
    [PWD] => *****
    [VERSION] => 112.0
    [BUTTONSOURCE] => AngellEYE_SP_WooCommerce
    [SIGNATURE] => *****
    [METHOD] => SetExpressCheckout
    [RETURNURL] => http://www.creepheart.com.au/checkout/review-order/?pp_action=revieworder
    [CANCELURL] => http://www.creepheart.com.au/shop/
    [LOCALECODE] => en_AU
    [LOGOURL] => https://static.e-junkie.com/sslpic/147826.9e400d0a8d2f10258c144904077eb521.jpg
    [BRANDNAME] => Creep Heart
    [SOLUTIONTYPE] => Sole
    [LANDINGPAGE] => Login
    [PAYMENTREQUEST_0_AMT] => 181.82
    [PAYMENTREQUEST_0_CURRENCYCODE] => AUD
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0.00
    [PAYMENTREQUEST_0_TAXAMT] => 0.00
    [PAYMENTREQUEST_0_PAYMENTACTION] => Sale
    [L_PAYMENTREQUEST_0_NAME0] => 'Skull Planchette' Ear Studs
    [L_PAYMENTREQUEST_0_AMT0] => 6.82
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_NAME1] => 'Batty Heart' Ear Studs
    [L_PAYMENTREQUEST_0_AMT1] => 6.82
    [L_PAYMENTREQUEST_0_QTY1] => 1
    [L_PAYMENTREQUEST_0_NAME2] => 'Broken Mirror' Necklace
    [L_PAYMENTREQUEST_0_AMT2] => 27.27
    [L_PAYMENTREQUEST_0_QTY2] => 1
    [L_PAYMENTREQUEST_0_NAME3] => 'Hasten Back' Fine Art Print - Size: A4 (297x210mm/11.7x8.3")

    [L_PAYMENTREQUEST_0_AMT3] => 18.18
    [L_PAYMENTREQUEST_0_QTY3] => 1
    [L_PAYMENTREQUEST_0_NAME4] => 'Batty Coffin' Fine Art Print - Size: A4 (297x210mm/11.7x8.3")

    [L_PAYMENTREQUEST_0_AMT4] => 18.18
    [L_PAYMENTREQUEST_0_QTY4] => 1
    [L_PAYMENTREQUEST_0_NAME5] => 'Feline Spooky' Fine Art Print - Size: A4 (297x210mm/11.7x8.3")

    [L_PAYMENTREQUEST_0_AMT5] => 18.18
    [L_PAYMENTREQUEST_0_QTY5] => 1
    [L_PAYMENTREQUEST_0_NAME6] => 'Witchy Animals' A5 Print Set
    [L_PAYMENTREQUEST_0_AMT6] => 36.36
    [L_PAYMENTREQUEST_0_QTY6] => 1
    [L_PAYMENTREQUEST_0_NAME7] => 'Planchette Girl' Necklace
    [L_PAYMENTREQUEST_0_AMT7] => 27.27
    [L_PAYMENTREQUEST_0_QTY7] => 1
    [L_PAYMENTREQUEST_0_NAME8] => 'Ghost Rose' Brooch
    [L_PAYMENTREQUEST_0_AMT8] => 22.73
    [L_PAYMENTREQUEST_0_QTY8] => 1
    [PAYMENTREQUEST_0_ITEMAMT] => 181.82
)

07-03-2015 @ 07:48:28 - Response: Array
(
    [TIMESTAMP] => 2015-07-02T21:48:29Z
    [CORRELATIONID] => 5ade1a1c236e1
    [ACK] => Failure
    [VERSION] => 112.0
    [BUILD] => 17235934
    [L_ERRORCODE0] => 10413
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => The totals of the cart item amounts do not match order amounts.
    [L_SEVERITYCODE0] => Error
)

**Comment by nishitlangaliya** [comment]
Done with cart total #243 with all three payment getway and pushed code to Issue-243 branch.
-> Regarding #243 I am facing cart total issue in one case which is mention below:

Product price : 149.95
discount 10% : 15.00

Order total : 134.96

Regarding This case I will required to discuss the whole scenario when you get a chance.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Rounding Issue regarding above case we discussed in skype is now sorted. And latest code pushed to Issue-243A branch for a review. Please check for the same when you get a chance.
