### ISSUE TITLE
Currency Switcher Causes PayPal Errors..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#245]
Getting reports that the currency switcher plugins are not pulling the correctly converted currency value in PayPal for Woo, but PayPal Standard with WooCommerce works fine.

https://www.angelleye.com/support/scp/tickets.php?id=157

The support ticket has a copy of the currency switcher plugin so we can try to reproduce this.  It also has more detail about exactly what the user is experiencing.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with the currency switcher plugin issue with paypal and pushed code to Issue-245 branch.
Please review it when you get a chance.

I test the case which is discuss in "https://www.angelleye.com/support/scp/tickets.php?id=157"  and prepare video for it please check for the same when you get a chance and let me know your thoughts and suggestions.

Video Link: http://www.screencast.com/t/v1FwcItJ

**Comment by angelleye** [comment]
I see quite a few changes were made to Express Checkout, but nothing was updated in DDP or PayFlow..??  Was everything in those already working, or did you forget to look into those as well?

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Yes I forgot to look currency switcher with DDP and payflow . Now I have also done with DDP and payflow with currency switcher plugin. and pushed latest code to " Issue-245C " branch for a review.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Express checkout is now  compatible with currency switcher plugin. pushed to 'Issue-245D' for a review.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with all three getway and pushed to "Issue-245E" branch for a review.

**Comment by angelleye** [comment]
It seems like a lot of work went into this issue, and I'm a little bit confused about why that is.

Did the adjustments resolve this problem for any currency switcher that may or may not be getting used, or is this update only fixing this one specific currency switcher plugin?

Was plenty of testing done to ensure all of these adjustments don't cause problems with regular orders where people aren't using currency switchers of any kind?

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I tested the cases with "Currency Switcher" Plugin which is given in "https://www.angelleye.com/support/scp/tickets.php?id=157"  and in that I tested with three currency 1. euro, 2. pound, and 3. dollar and it worked fine for all. and yes I also test the case without that plugin and it did not affected the regular order.

I had to add some function of wc standard paypal getway because in cart object loop I was not getting the switcher currency amount. so that functions worked for me for preparing line items with currency switcher.

**Comment by angelleye** [comment]
I'm going to go ahead and close this, but I'm still waiting on confirmation from the user that reported this that it fixed his problem.  For now I'm going to trust the testing that we've done and hopefully we won't get bad news from him when he tries it.
