### ISSUE TITLE
Express Checkout - Possible bug with saving shipping address in WC order..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#246]
We have a report from a user (Shaan Nicol) that the WC orders are not getting saved with the PayPal address that is returned in GetExpressCheckoutDetails.

I was able to confirm via his log file that the address is indeed coming back...

```
    [PAYMENTREQUEST_0_SHIPTONAME] => CHEE KELLY
    [PAYMENTREQUEST_0_SHIPTOSTREET] => #03-02 Heritage Place
    [PAYMENTREQUEST_0_SHIPTOSTREET2] => 21 Tan Quee Lan Street
    [PAYMENTREQUEST_0_SHIPTOZIP] => 188108
    [PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE] => SG
    [PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME] => Singapore
```

He says the address is not getting included with the WC order, though.  We need to test an order with an address like this and see if we can reproduce the issue.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I have tested the case with above address and also test with different shipping address . and its working fine here. 

<pre> [PAYMENTREQUEST_0_AMT] => 149.95
    [PAYMENTREQUEST_0_CURRENCYCODE] => GBP
    [PAYMENTREQUEST_0_INVNUM] => 29
    [PAYMENTREQUEST_0_SHIPTONAME] => Chee Kelly
    [PAYMENTREQUEST_0_SHIPTOSTREET] => #03-02 Heritage Place
    [PAYMENTREQUEST_0_SHIPTOSTREET2] => 21 Tan Quee Lan Street
    [PAYMENTREQUEST_0_SHIPTOZIP] => 188108
    [PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE] => SG
    [PAYMENTREQUEST_0_PAYMENTACTION] => Sale
    [PAYMENTREQUEST_0_ITEMAMT] => 149.95
    [L_PAYMENTREQUEST_0_NAME0] => Product2
    [L_PAYMENTREQUEST_0_AMT0] => 149.95
    [L_PAYMENTREQUEST_0_QTY0] => 1</pre>

<pre> [PAYMENTREQUEST_0_SHIPTONAME] => Rav Vaghela
    [PAYMENTREQUEST_0_SHIPTOSTREET] => P.O. Box 3700
    [PAYMENTREQUEST_0_SHIPTOCITY] => Eureka
    [PAYMENTREQUEST_0_SHIPTOSTATE] => CA
    [PAYMENTREQUEST_0_SHIPTOZIP] => 95502
    [PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE] => US
    [PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME] => United States
    [PAYMENTREQUEST_0_ADDRESSSTATUS] => Confirmed</pre>

Please Let me know if any issue. and suggestions for the same.

**Comment by angelleye** [comment]
I've responded back to Shaan to see if he has any other plugins that may be interfering with the WC order data or if he has a caching/CDN that could be causing an issue.  I'm going to go ahead and cloes this for now since we can't reproduce it and haven't had any other reports of this problem.
