### ISSUE TITLE
Express Checkout - PayPal graphic on WC checkout page not secure.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#251]
Report from Tom Chambers via email.

>One of your paypal images isn\'t resolving secure on our secure site, like the others.

>This page;
https://www.greaterthangatsby.com/checkout/

>This image
http://www.greaterthangatsby.com/wp-content/plugins/paypal-for-woocommerce/assets/images/paypal.png

>Don\'t understand why one image isn\'t while the others are?

**Comment by nishitlangaliya** [comment]
Done, Pushed latest code to Issue-251B for a review.
