### ISSUE TITLE
Shipping information returned from PayPal are not being saved as order metadata

### ISSUE THREAD

**Issue by mserious** [angelleye/paypal-woocommerce#253]
Hi there,

It took me some time to analyze the code, but I believe the problem I'm facing is a bug.

WooCommerce Version 2.3.11
PayPal for WooCommerce Version 1.1.6.3.3
* Checked. Set billing address in WooCommerce using the address returned by PayPal.
* Checked. Enables the option to skip the final review page.

Using hooks a have disabled both, shipping and billing, forms at checkout, leaving checkout as a list of purchased products and a "Place Order" button.
The only payment options is PayPal Express.

The data flow goes like this:
* User comes to checkout presses "Place Order".
* User is redirected to PayPal Express checkout page.
* Makes a payment at PayPal.
* User is redirected back to "Order Received" page. ("Enables the option to skip the final review page")

**Unexpected behavior:** Order Received page does not have Shipping and/or Billing information returned from PayPal.

**Expected behavior:** Shipping and Billing information should be the same ("Set billing address in WooCommerce using the address returned by PayPal") and **present**.

By checking wc-logs, I can see that PayPal is returning shipping information.
By checking order metadata in database, I see that shipping information is missing.

[The code responsible of writing thisinformation.](../blob/release/classes/wc-gateway-paypal-express-angelleye.php)
**LINE: 1059**

I believe the bug is in the IF statement, which will never be FALSE.

```php
$checkout_form_data = maybe_unserialize($this->get_session('checkout_form'));
if (isset($checkout_form_data) && !empty($checkout_form_data)) {
```

**$checkout_form_data** is being READ from a session here.
**$checkout_form_data** is being WRITTEN to a session at **regular_checkout** method, **LINE: 2347**
The data being written is being passed from WooCommerce via hook:
```php
add_action('woocommerce_after_checkout_validation', array($this, 'regular_checkout'));
```
In my example the array passed from WooCommerce looks like this:

```php
array(5) {
  ["terms"]=>
  int(0)
  ["createaccount"]=>
  int(0)
  ["payment_method"]=>
  string(14) "paypal_express"
  ["shipping_method"]=>
  array(1) {
    [0]=>
    string(13) "rp_table_rate"
  }
  ["ship_to_different_address"]=>
  bool(false)
}
```
Keep in mind I have both forms disabled, so this data is pure WooCommerce defaults.

Analyzing WooCommerce I can see that array will always have this default data, making the IF statement never to jump to FALSE and thus save shipping information saved to order metadata.

If I overwrite **$checkout_form_data** to an empty array, I get the expected behavior:

```php
$checkout_form_data = maybe_unserialize($this->get_session('checkout_form'));

$checkout_form_data = array();

if (isset($checkout_form_data) && !empty($checkout_form_data)) {
```

Of course, this is not a fix but just a confirmation that this might be a problem here.

Thoughts?

**Comment by nishitlangaliya** [comment]
Done, Pushed latest code to Issue-253 for a review. Please check for the same and let me know your thoughts and suggestions.

**Comment by angelleye** [comment]
@mserious Would you be able to pull the current 1.1.6.3.5 branch and see if it resolves your issue please?

**Comment by angelleye** [comment]
@mserious I'm going to go ahead and close this issue because we ran tests with those fields disabled and it seems to be fine.  

If you get a chance, though, and want to grab the 1.1.6.3.5 branch to confirm that would be great.  Thanks!
