### ISSUE TITLE
DoDirectPayment - Discount not getting added correctly to API request.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#255]
I've had multiple reports from people that say this started happening with one of our last updates.

The PayPal API is returning the following error/warning:  15008 - This transaction has been completed, but the total of items in the cart did not match the total of all items.  

The result is actually coming back as SuccessWithWarning and includes that warning.  [Refer to this support ticket](https://www.angelleye.com/support/scp/tickets.php?id=175) for a look at the log from when this error happened.

The important part to note is here...

```
[L_NAME0] => Strong Roots Red Pimento Hair Growth Oil
[L_AMT0] => 10.99
[L_NUMBER0] => til-625548374
[L_QTY0] => 3
[L_NAME1] => Jamaican Black Castor Oil - 8 oz
[L_AMT1] => 11.99
[L_NUMBER1] => Jbco8oz
[L_QTY1] => 1
[L_NAME2] => Black Castor Oil Protein Conditioner
[L_AMT2] => 13.99
[L_NUMBER2] => jbcopcon
[L_QTY2] => 1
[NAME3] => Total Discount
[QTY3] => 1
[AMT3] => -5.9
```

As we've discussed, the discount has to be added to the order as a line item in order for it to work correctly.  You'll see that the line item parameters each start with L_, but the discount item that is added here does not.

That's causing PayPal to ignore that discount item so it thinks the cart items don't add up and it throws the warning.

My PayPal library handles generating this for you as long as you pass the order items into it correctly, so it looks like that's the part we need to fix.

The discount item should have been added to the $OrderItems array which is then loaded into the $PayPalRequest.  It seems they were added outside of that as their own parameters..??

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with the sending discount item with prefix "l_" and it worked for me. success with warning error removed when I tested the above and other cases with DDP. 

I have pushed latest code to "Issue-255" branch for a review. and also I am sending my log file in skype. please let me know if still any issue in request.

**Comment by nishitlangaliya** [comment]
Done, Qty parameter added and pushed latest code to "Issue-255A" branch.

**Comment by angelleye** [comment]
I tested this and was able to confirm that the discount item is getting included as it should now.
