### ISSUE TITLE
SuccessWithWarning Handling..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#256]
While discussing #255 with a user he reported that when he ran a test order and this happened he actually saw the error/warning from PayPal.

Our plugin should be handling both Success and SuccessWithWarning as a successful transaction, and the buyer experience should look the same either way...like the order was completed successfully.

We need to double check this and make sure that it is indeed doing that.  This user seems to think it's not doing that.

The PayPal class library actually includes a $PayPal->APICallSuccessful() function which will handle checking both values and return true if either case comes back, so if we're not using that we probably should.

It may be that all of this is already setup and the customer was wrong about what he saw.  We need to check, though.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

-> I see our class files in that we are already using $PayPal->APICallSuccessful($PayPalResult['ACK']).
in express checkout and do direct payment. and for paypal flow we are using $PayPalResult['RESULT'] to check request response.

-> so should we also use APICallSuccessful() for payflow or it is ok as it is right now ? 


Please let me know your thoughts and suggestions for the same.

**Comment by angelleye** [comment]
Sorry, no, PayFlow is a little different.  I should have mentioned that.  It sounds like we're already using what we should be.

Let me ask you this.  When you ran tests to reproduce the 15008 error (SuccessWithWarning) did the order complete for you just like any other order would or did you see that error during checkout?

**Comment by angelleye** [comment]
Seems that we were already handling this correctly, so no action is necessary here.
