### ISSUE TITLE
Duplicate Orders in WooCommerce

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#257]
When I complete an order using PayPal Express Checkout from the WooCommerce checkout page I end up with 2 orders in WooCommerce for the same order.  One is saved as Pending and later expires automatically in the WooCommerce system.  The other is saved as Processing as expected.

Here is a video to see:  http://fiber.angelleye.com/temp/11635.mp4

The only closed issue I see that seems related to this is #253.  I think this may have started happening within that issue's commits, but I'm not 100% sure.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Duplicate Orders in WooCommerce Issue is sorted and Pushed to " Issue-257" branch for a review.

**Comment by angelleye** [comment]
The orders I have been running are no longer adding duplicates, so I think we're good here now.

**Comment by angelleye** [comment]
I'm re-opening this because I'm still seeing canceled orders come through a while later after running test transactions.  Seems like maybe this is still going on, although it's not quite the same as it was before.  Need to run some more tests here.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I did test but case was not reproduced. please let me know your thoughts for the same.

**Comment by nishitlangaliya** [comment]
As we have discussed in skype. Duplicate order due to  might be of canceled order or  broken order. so it was showing. so please let me know your thoughts for the same.
