### ISSUE TITLE
Express Checkout - Terms and Conditions

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#259]
I'm getting reports that Express Checkout (from cart or product page) is not requiring that you accept the terms and conditions the way it would if you pay through the WooCommerce checkout page.

So, if the site has a Terms and Conditions page configured in WooCommerce checkout settings, and Express Checkout is used for payment from the cart or product page, then we need to display the check box on the PayPal review page that the user has to check to agree to terms in order to complete the order.  

If the user pays with Express Checkout from the WooCommerce checkout page, though, then we would not need to enforce this requirement on our review page because it would have already been done on the WooCommerce checkout page.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with this issue and pushed to 'Issue-259' branch and also merged that issue to '1.1.6.3.5' branch as well for a review.

Please review it and let me know your thoughts for the same.

**Comment by angelleye** [comment]
You missed something I explained in the original notes for this issue.

I ran a test checkout using Express Checkout from the WooCommerce checkout page.  The terms and conditions checkbox showed up on this page as expected, so I had to check the box in order to continue.  

Then I signed into PayPal and was returned back to the site, but on the review page I had to once again accept the terms and conditions even though I already done that from that WC checkout page.

So as I mentioned in the original notes, if the user checks out from the WC checkout page then we do not need to show the Terms and Conditions check box on our Express Checkout review page.  That would only be necessary if they used Express Checkout from the product page or cart page and skipped the WC checkout page.

**Comment by angelleye** [comment]
On the review page the checkbox is under the sentence instead of next to it...

![image](https://cloud.githubusercontent.com/assets/629241/9159728/b98c0f8c-3ef3-11e5-9d2b-1807e8a33e84.png)

Needs to be right next to it instead of on its own line.

**Comment by nishitlangaliya** [comment]
Done, Pushed to 'Issue-259A' branch and also merged to '1.1.6.3.5' branch for a review.

**Comment by angelleye** [comment]
Something got messed up with the form validation in this last update.  Now when I try to submit an order from the WooCommerce checkout page I get this error...

![image](https://cloud.githubusercontent.com/assets/629241/9190267/da0373ac-3fb8-11e5-9d78-9565227f613b.png)

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with the php notice handled for get_formatted_lagacy in all our payment getway. and pushed latest code to 'Issue-259C'  branch and also merged to '1.1.6.3.5' branch for a review.

please review it when you get a chance and let me know if any issue.

**Comment by angelleye** [comment]
This seems to be working as expected now.
