### ISSUE TITLE
Potential problem with checkout image..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#260]
https://wordpress.org/support/topic/mixed-content-in-checkout?replies=2#post-7268681

Need to see if we're able to find the same problem and get it resolved if so.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Done, Pushed code to Issue-260 branch and merged that branch to 1.1.6.3.5 branch for a review.

I was able to reproduce this case. in console error was showint
 'wp-content/plugins/woocommerce/assets/images/ajax-loader@2x.gif' not found . 

after that I see it after disabled our plugin and that error was removed. so I see the woocommerce assets but that image was not there. 

but there was select2-spinner.gif there so I have copy and paste that image to our assets folder and changed ajax-loader@2x.gif to select2-spinner.gif where ever we have used ajax-loader@2x.gif and now error has sorted.

**Comment by angelleye** [comment]
Looks good.
