### ISSUE TITLE
PayFlow : Deprecated function removed wc_get_page_id('thanks')

### ISSUE THREAD

**Issue by nishitlangaliya** [angelleye/paypal-woocommerce#261]
PHP Notice:  wc_get_page_id was called with an argument that is <strong>deprecated</strong> since version 2.1! The "pay" and "thanks" pages are no-longer used - an endpoint is added to the checkout instead.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Done , Pushed to Issue-261 branch and merged to 1.1.6.3.5 branch for a review.

While I was testing , I found the php notice
" PHP Notice:  wc_get_page_id was called with an argument that is <strong>deprecated</strong> since version 2.1! The "pay" and "thanks" pages are no-longer used - an endpoint is added to the checkout instead."  in my php error log file so I have sorted it and merged to 1.1.6.3.5 milestone.

**Comment by angelleye** [comment]
Nice catch, thanks for finding that and resolving it.
