### ISSUE TITLE
Express Checkout - Shipping address not displayed on receipt page..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#262]
While running some test orders I noticed that the shipping address is no longer showing up on the receipt page like it should.

I used Express Checkout from the shopping cart page.  I have the option to "Set billing in WooCommerce using the shipping address PayPal returns" enabled, so what I expect to see is both addresses on the order.

When I got to the receipt page on the website, though, the only address displayed is the billing address:

![image](https://cloud.githubusercontent.com/assets/629241/9159549/08faa320-3ef0-11e5-91db-9ee660839326.png)

However, the order in WooCommerce did get both billing and shipping details saved:

![image](https://cloud.githubusercontent.com/assets/629241/9159554/25d1ffd4-3ef0-11e5-80b0-f65050d97019.png)

**Comment by angelleye** [comment]
This isn't something that happened before, so I think something we did in this 1.1.6.3.5 update has caused this.

**Comment by angelleye** [comment]
I just ran another test where I checked out from the WooCommerce checkout page instead of the cart page.  This time both addresses were displayed on the receipt page:

![image](https://cloud.githubusercontent.com/assets/629241/9159570/98db91a2-3ef0-11e5-8fb7-209fc865faf9.png)

So it seems the problem is only happening when the WC checkout page is skipped.  I'm thinking this may have something to do with the fix applied to #257 but I am not sure.

**Comment by nishitlangaliya** [comment]
Done, Pushed to 'Issue-262E' branch and merged to 1.1.6.3.5 branch for a review.

**Comment by angelleye** [comment]
The address shows up now, but now we have PHP errors happening on the receipt page.

![image](https://cloud.githubusercontent.com/assets/629241/9266938/5fd4de48-420d-11e5-8db3-b76eccd6afa9.png)

**Comment by nishitlangaliya** [comment]
Done, Error sorted , Pushed to 'Issue-262G'  and merged to 1.1.6.3.5 branch for a review

**Comment by angelleye** [comment]
Seems to be working nicely now.
