### ISSUE TITLE
Express Checkout - WC guest checkout (optional)

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#264]
With WooCommerce guest checkout disabled, and the user checks out from product or cart pages, then our review page (after returned from PayPal) requires you to login or create an account prior to completing payment.

However, if WooCommerce guest checkout is enabled, then the user is never given the option to create an account at all.  In this case they should still have the option to create an account with the site if they want to, but it simply wouldn't be required.

The WC checkout page provides a "create account" checkbox that you can check to enable creating an account and entering a password.  We need to add a similar option to our review page.

Just like with other features, though, this would only be applicable if they checkout from a PayPal button on the product page or cart page.  If they checkout with the WooCommerce checkout page then this would be handled there, and we would not need to display this option on our review page.

**Comment by nishitlangaliya** [comment]
Done, Pushed to 'Issue-264A' branch and merged to 1.1.6.3.5 branch for a review.

**Comment by angelleye** [comment]
This seems to be working as expected.
