### ISSUE TITLE
Need to fix deprecated function..??  get_cart_discount()

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#266]
While browsing around in the wc-gateway-paypal-express-angelleye.php class I noticed that we're using get_cart_discount() quite a bit and it seems to be deprecated.

We need to make sure that orders with discounts are working as expected, and probably go ahead and get this updated to whatever the new function is we're supposed to be using instead.

Of course we'll need to test again after making this change to ensure discounts are getting handled properly.

**Comment by angelleye** [comment]
I'm not sure if these were deprecated as of 2.4 or not, but I'm a little confused by the info I'm seeing.

Both get_cart_discount() and get_order_discount() are showing up as deprecated in PHPStorm.  I found [this document](http://docs.woothemes.com/wc-apidocs/deprecated.html) which seems to reflect the same.  I am confused because the document states the following...

>in favour of get_total_discount() since we now only have one discount type.

When I look in WooCommerce -> Coupons, though, I see that we can still add separate "cart discounts" or "product discounts" so I'm not sure how to handle this.

**Comment by angelleye** [comment]
While testing with WooCommerce 2.4.2 and our current 1.1.6.3.5 branch the coupons seem to be working as expected.  As such, I'm going to move this issue to our 1.2.1 milestone.

**Comment by kcppdevelopers** [comment]
Yes right, get_cart_discount and get_order_discount both function are deprecated as 2.3 version, but our plugin still provide backward compatibility of previous version. our plugin only used this function for old previous version of woo.

**Comment by kcppdevelopers** [comment]
Should we remove backward compatibility of previous version?

**Comment by angelleye** [comment]
Ok, no, we can leave it for backwards compatibility.
