### ISSUE TITLE
Negative shipping amount with 0.00 order amount..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#269]
Here is the support ticket for the guy having this issue that we discussed in Skype where the shipping amount is coming out to negative.

https://www.angelleye.com/support/scp/tickets.php?id=183

You'll notice he provided a our plugin log where this is happening, and then he also provided a log from another Express Checkout plugin where this is not happening.  We must be doing something to the data after pulling it from the WC object to cause this problem..??

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I see the error log provided by user. at 'https://www.angelleye.com/support/scp/tickets.php?id=183' from that error log I tried to reproduce that case in my local server but I could not reproduced it. I am sending  my error logs in skype as file text attachment is not allowed please review it and let me know your thoughts for the same.

**Comment by nishitlangaliya** [comment]
Errol log sent in skype

**Comment by angelleye** [comment]
Ok, we'll move this to a different milestone and research it further at that time.

**Comment by angelleye** [comment]
Moving this back to 1.1.6.3.6 because I have another report about the same thing from another user.

This user says it only happens on products that have a shipping class set, so we need to see if we can reproduce that and get it resolved.

**Comment by angelleye** [comment]
I just ran a test checkout for a product that has a shipping class and did not have this problem.  Asked the user to provide more details about how they have their classes configured.

**Comment by angelleye** [comment]
We have another report here where the shipping isn't negative, but sort of the opposite.  The shipping is coming out to some very large number for some reason even though it shows correct in the WC cart page.  Here's what the user says.

>Hello, after the last update of your PayPal-Plugin for WooCommerce, I\'ve got a failure in the Shippingcosts. In the Frontend are the right costs of 3,90 €, but when they\'re  committed, I\'ve got costs between 500 and 10000 € at the PayPal Page...

>I’ve got the shipping by weight/country. But thats also with the WooCommerce Standard-Plugin international Shipping. Yes, I’ve got Shipping classes. But I only use one of them...

>
![image](https://cloud.githubusercontent.com/assets/629241/9457407/94482764-4aa7-11e5-83b5-5f701f86c08d.png)

**Comment by angelleye** [comment]
Here's another report of the 0.00 order amount, and they say it only happens when shipping is included on the order.

https://www.angelleye.com/support/scp/tickets.php?id=193

This has to be something about our calculations that we added to try and resolve the cart total errors.  We need to review that code and figure this out ASAP.

**Comment by angelleye** [comment]
Here's another:  https://wordpress.org/support/topic/10401-order-total-is-invalid-for-unsupported-currencies?replies=2

**Comment by angelleye** [comment]
Here's another report where this is happening.  This user provided login credentials to a test version of their site we can look at their settings and try to reproduce the issue on our test servers.

https://www.angelleye.com/support/scp/tickets.php?id=200
