### ISSUE TITLE
Terms and Conditions CSS Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#270]
I realize that different themes could cause issues, however, I am running on very basic themes and this seems to be happening a lot.

On the Express Checkout review page the check box for the Terms and Conditions is floating out on its own, not next to the actual T&C line:

![image](https://cloud.githubusercontent.com/assets/629241/9351098/13796196-461c-11e5-9b00-d1ccdd5e9e42.png)

Seems there should be something we can do to improve that by default.  Some people may need to adjust it for their unique theme, but it should be pretty standard for these basic themes, and it should line up nicely for the most part.

**Comment by angelleye** [comment]
Looks good!

**Comment by angelleye** [comment]
Not sure what happened, but I just ran another test order and the check box is floating out on its own again.  Same as the screenshot above.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Currently in your woo.angelleye.com there is 'Issue-188G' branch is uploaded. 

Yes this might be because of code merged of dev and 1.1.6.3.5 branch . and while merging that code from my end i think i have missed to put that css changes I did for 1.1.6.3.5 . 
if you upload 1.1.6.3.6 branch to your site. it will display as we want.

I will cover it up in 1.2 when I start on it.

**Comment by angelleye** [comment]
Ok.  I uploaded the 1.1.6.3.6 branch files back to the server, so now we're basically running 1.1.6.3.5 again.

I guess you'll need to go ahead and get your test server's PHP version updated.  Working together on my server isn't going to work because of this sort of problem.  I didn't realize you had uploaded the Issue-188G branch files to my server.

**Comment by angelleye** [comment]
With the 1.1.6.3.6 branch the checkbox looks good again.  Definitely need to make sure we don't lose stuff like this when merging changes back into the dev branch and 1.2 issues.
