### ISSUE TITLE
Express Checkout - Create Account Problems

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#275]
In the last update we added the ability to create an account (optionally) during an Express Checkout from the review page.  

The check box to create an account brings up a password field, and then it should create the new account when the order is completed.

We're getting reports that the password field is showing the value that's typed in as opposed to masking it like a password field should.

Also, reports that the order is not actually getting processed when this option is used to create an account.

I have not been able to test this myself yet, but here is the ticket where this is being reported:  https://www.angelleye.com/support/scp/tickets.php?id=178

**Comment by nishitlangaliya** [comment]
Hi Andrew,

From the above comments what I understood is as user is  talking about issue in final review page and it has issue with below points

1.'Account password' field is normal text filed instead of password field' is it right ?

2.  if create account is checked and password is blank. It logs an order with payment pending, but the items remain in the cart. 

For the above points I have tried to reproduce the case and prepared one video for that , which I am sending you in skype .

Please let me know if I am wrong about user requirement.

->  For php notice : does user is facing 'PHP Notice:  A non well formed numeric value encountered'  if this or any other notice user is facing can we have that notice text so that we can get exact idea what causing.

**Comment by angelleye** [comment]
I'm sorry, I told you incorrectly.  I just re-read his original information and I see I misunderstood something.

First, what he's saying is that if you click the create account button the password field shows up, but there is no validation ensuring that the user actually enters a password.  As such, the form can be submitted without a password to create the account. 

He is saying that when he does this the order gets stuck and doesn't move past pending, however, when I tried it the order does complete, but the user account does not get created.

Either way, we need to add validation to the password field to ensure that people actually enter one when choosing to create an account from the Express Checkout review page.

**Comment by nishitlangaliya** [comment]
Done as per our skype discussion, Pushed to 'Issue-275' for a review

**Comment by angelleye** [comment]
This is not working for me.  I pulled the changes and uploaded to my server, however, when I go through a checkout without entering the password at this point it still moves on without any error, and no account gets created.  Same as before.  

I'm using Firefox.

**Comment by nishitlangaliya** [comment]
Hi Andrew as per our discussion what , I handled is simply add required field validation if the checkbox is checked. the cases I handled for that I have prepared video for it please see below link and let me know if i am missing something.

Url : http://www.screencast.com/t/xlOJhkp2

**Comment by angelleye** [comment]
Somehow you have this validation for the password attached to the Terms and Conditions.

If I set a T&C page in WooCommerce settings so that I have to accept the terms on the review page, then the password validation for creating a new works as expected, which is what you've shown in your video.

If I remove the T&C page from the WC settings, though, so that no acceptance is required, then the validation no longer works on the password field for creating a new account.

**Comment by angelleye** [comment]
I just noticed something else going on, too, that I'm thinking must be from this issue's changes.

I am checking out while already logged in, so I don't get the option to create an account from the review page.  I do have Terms and Conditions set, so it's requiring me to accept.  

If I leave the T&C unchecked and click Process the validation works and tells me I have to accept.  When I check the box to accept, though, the Process button simply becomes inactive and will not submit at all.

**Comment by angelleye** [comment]
I reverted back to the 1.1.6.3.6 copy of the review page template and the Process button works again as expected, so something in this issue caused that problem as well.

Need to make sure the button and validation works with all different types of settings regarding T&C and Create Account from review page.

**Comment by nishitlangaliya** [comment]
Done, Pushed to 'Issue-275' branch.
