### ISSUE TITLE
Express Checkout - Review Page PHP Syntax Error

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#276]
User reporting a syntax error on the review page:  https://wordpress.org/support/topic/empty-review-order-page

>Parse error: syntax error, unexpected 'endif' (T_ENDIF) in ...\wwwroot\wp-content\plugins\paypal-for-woocommerce\template\paypal-review-order.php on line 304

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Done, pushed to 'Issue-276' branch for a review,

**Comment by angelleye** [comment]
Ah, yes, that'll do it.  We really need to remember to never use short tags.
