### ISSUE TITLE
Currency Switcher bug

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#300]
This is one of the issues that was done on 1.1.6.3.5 that seemingly caused a lot of problems.

Please review the notes for what needs to be done, and also review the code that was adjusted to accomplish the task.

Not sure if you'll be able to re-use any of the completed code or not.

**Comment by levansy2020** [comment]
Need check line line 1013 file wc-gateway-paypal-express for missing shipping issue
 //WC()->cart->calculate_totals();

**Comment by angelleye** [comment]
The last commit here actually belongs to #305
