### ISSUE TITLE
Express Checkout - WC Guest Checkout (optional)

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#303]
This was done in 1.1.6.3.5 (#264) but was removed in the rollback update for 1.1.6.3.7.  

Please review the initial info about the task, and then see if we can re-use/merge the code.  If not, code accordingly to complete the task.

**Comment by angelleye** [comment]
I'm wondering if maybe some of the changes here didn't get rolled back completely and that's why I'm having the problem I'm having in #306..??

**Comment by angelleye** [comment]
Not sure if it matters, but might be good to ensure #306 is working as expected prior to getting this one done, too..??

**Comment by angelleye** [comment]
When running from the issue-303 branch the jQuery on the review page is not working to update the order totals when shipping options are adjusted.  The order does seem to process with whichever one I have set, but the order totals on the review page aren't updating correctly when it's changed.

[Here is a video](http://fiber.angelleye.com/temp/303.mp4).

**Comment by levansy2020** [comment]
Please check again
