### ISSUE TITLE
Bug reports from Multidots.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#304]
1) [28-Aug-2015 12:47:53] PHP Notice:  get_formatted_legacy is <strong>deprecated</strong> since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /var/www/ipnsupport/wp-includes/functions.php on line 3406 

2) If we disable guest checkout and checkout from cart or product page it . is not asking for     login or even create account. 

3) Billing address not showing while direct checkout .

4) Cart total error 149.95 cart discount 10%.

**Comment by levansy2020** [comment]
Ok Will work on it this afternoon

**Comment by angelleye** [comment]
1) This one was fixed in the .5 update but was not re-applied in the .7 rollback update.  Here is the commit where it was fixed.  We can hopefully just re-apply it:  https://github.com/angelleye/paypal-woocommerce/commit/d73ad76ce82c404b56a7520ac67565c742f2e194

2 & 3) I have not had any reports of these and I don't remember running into them myself, but we should check them out.

4) This is the one that you had informed us about.  In our tests of the .5 update this was no longer failing, but this is one of the big problems with the .5 update so it was rolled back.  It doesn't surprise me that it's happening again because of that.  So, we just need to troubleshoot it and get it resolved.

I still think the best thing to do is add some "checks and balances" right before generating the API request.  If the cart totals do not add up to the order total then we should adjust the values that get passed into the PayPal request.  For example, if the totals are a penny off (like what usually happens when this occurs) we should add/subtract that penny from the shipping amount so that it will add up and PayPal will accept it.  If there is no shipping amount on the order, then we should adjust the tax value instead.  If neither shipping nor tax are included on the order, and we still end up with cart totals that are invalid then we should adjust the line item(s) accordingly.

I understand that this will mean the PayPal details will not match the WooCommerce details, but since WC is simply wrong and it's only a penny I think it'll be ok.

**Comment by levansy2020** [comment]
[28-Aug-2015 12:47:53] PHP Notice: get_formatted_legacy is deprecated since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /var/www/ipnsupport/wp-includes/functions.php on line 3406
 
"get_formatted_legacy"

I can't find this one in our plugin
