### ISSUE TITLE
Express Checkout - WooCommerce Guest Checkout Bug

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#306]
This used to work just fine, so I'm not sure when it stopped, but I just noticed it while testing some random orders.

I have WooCommerce -> Settings -> General -> Guest Checkout disabled, so a login / account creation should be required when checking out.

Using Express Checkout, though, I reach the review page and I am not forced to login or create an account like I used to be.

**Comment by levansy2020** [comment]
I just did some tests but not see this issue. Please give me step to replication it. Thanks

**Comment by angelleye** [comment]
Check out this video:  http://fiber.angelleye.com/temp/306.mp4

**Comment by angelleye** [comment]
This ticket is a related issue:  https://www.angelleye.com/support/scp/tickets.php?id=205

In his case, the review page is displaying the login / create account on the review page, and things seem to work fine if you just login to an existing account.  However, if you create an account at this point it's moving him to a 404 not found page.  The account does seem to get created, but the order is not created in WC and the final DoExpressCheckoutPayment request to PayPal does not get made.

I think we may have some sort of a conflict going on based on themes or something..??  Need to try different themes and see if we can reproduce any of this.

**Comment by levansy2020** [comment]
I did test again. But it seems fine

**Comment by angelleye** [comment]
I just made [another video showing that the problem is still happening for me on woo.angelleye.com](http://fiber.angelleye.com/temp/306-2.mp4).  I don't know if we have a conflicting plugin or what, but we need to figure it out.

**Comment by angelleye** [comment]
I'm going to go ahead and close this because it's being done within #303 and in the issue-303 branch.
