### ISSUE TITLE
Add new filter for enable/disable guest checkout base on  Activation plugin

### ISSUE THREAD

**Issue by kcppdevelopers** [angelleye/paypal-woocommerce#309]
AngellEYE Activation, Issue-26.

What we need to do is add some logic so that if a product included in the shopping cart requires activation, then we should also require account creation / login during checkout regardless of what the WooCommerce Guest Checkout option is set to.

**Comment by angelleye** [comment]
Wouldn't we need to do something similar in DDP and PayFlow, too?

**Comment by angelleye** [comment]
I'm a little bit confused what's going on here.  If we've made some new change that should be done in a new issue that can be included on our next milestone for this plugin.  This issue is already closed from a previous version.

**Comment by angelleye** [comment]
I went ahead and got this merged, but next time please create a new issue in our current milestone for something like this.
