### ISSUE TITLE
Express Checkout - Error 10486

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#311]
We visited this already in #72, however, I don't think it's working the way we planned because I'm still getting reports where people are saying users are getting stopped with this error.

Should revisit [this guide](https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/) and double check how we're handling this particular error.

**Comment by kcppdevelopers** [comment]
I have test <a href="https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/#testing">this</a> exact scenario, it's working fine.

**Comment by angelleye** [comment]
Ok, but you did have to make a commit..??

**Comment by angelleye** [comment]
Also, is this ready for review then?  Didn't see the label..??

**Comment by kcppdevelopers** [comment]
In commit, I just correct error log text.
