### ISSUE TITLE
Possible adjustment to cart buttons..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#312]
https://wordpress.org/support/topic/force-button-into-div-on-cart-page

**Comment by levansy2020** [comment]
Can you ask for screenshot?

**Comment by angelleye** [comment]
I've updated that WP support ticket requesting one.

**Comment by angelleye** [comment]
The WP thread has been updated with a screenshot.

**Comment by angelleye** [comment]
I provided some info to the user in that thread, too, that I'd like you to double check and see if I'm accurate or not.

**Comment by levansy2020** [comment]
Can we ask for URL to check the html structure?

**Comment by kcppdevelopers** [comment]
![cart_page_issue_312](https://cloud.githubusercontent.com/assets/13145461/13600384/73dec298-e54e-11e5-8447-b16d0eafb140.png)

**Comment by angelleye** [comment]
I am getting a small merge conflict on this one when I try to merge it into my "dev" branch.  

Please merge the "dev" branch into this "Issue-312" branch and resolve that merge conflict.  

Looks like a real simple one, I'm just not sure about it.
