### ISSUE TITLE
PayPal Plus - Layout Settings

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#313]
I was wondering about the Layout Settings in PayPal Plus because the Credit Card option displayed is not styled and hard to see.

I also notice that we're getting messages like this in our log file:

>09-21-2015 @ 18:43:33 - Show payment form redirecting to  for the order 6355 as it is not configured to use Layout C

Need to figure out how to setup layouts properly so that PayPal Plus looks good and runs well.

**Comment by angelleye** [comment]
One of the first users to try this has the same question I have, which is that we are curious if there is a way to embed the iframe directly into the WooCommerce checkout page so that you don't have to choose "PayPal Plus", click the Place Order button, and only then see the different payment options.

Could we generate the iframe and load it directly below (or maybe above) the general list of enabled gateways that WooCommerce displays by default?

**Comment by angelleye** [comment]
One user attempting to use the release branch with PayPal Plus is getting this error back in the API log...

>09-30-2015 @ 15:33:45 - Show payment form redirecting to  for the order 126 as it is not configured to use Layout C

So there has to be something going on with the layouts that need to address..??

**Comment by angelleye** [comment]
Have we specified layout C somewhere in our calls?

**Comment by levansy2020** [comment]
I commited it here https://github.com/angelleye/paypal-woocommerce/commit/9ee97c4ccd9234ee90127c7f39ccac94ff369c2e

Please check

**Comment by angelleye** [comment]
Running into a problem with PayPal Plus cookie and ModSecurity (https://www.hostivate.com/blog/how-to-allow-jquery-cookie-min-js-to-be-run-by-mod-security/)

Need to make sure we mention this potential problem in our docs.
