### ISSUE TITLE
Logic to ensure PHP 5.3

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#326]
The PayPal Plus stuff that we added requires PHP 5.3+ because of the namespacing included in the PayPal SDK.

After our 1.1.7 update I'm getting reports that "my site is crashing".  The problem is that PHP prior to 5.3 has a syntax error that does indeed bring on a "white screen of death" in WordPress.

Would be good to add some logic to check for PHP 5.3+ and only load PayPal Plus only if they have correct PHP version.

**Comment by angelleye** [comment]
If they have something prior to PHP 5.3 we could just disable PayPal Plus in the plugin similar to what you're doing based on the currency code that is set.  

So we could display a message that "PayPal Plus is currently disabled because it requires PHP 5.3 or higher.  Please contact your hosting provider or server administrator to upgrade PHP on your server."

**Comment by angelleye** [comment]
We also need to make sure that the include files for the PayPal SDK are skipped if the PHP isn't compatible because that's what's throwing the error.  

If it's easier to simply remove Plus entirely based on the PHP version that's fine.  We don't need to display an error like mentioned above.

**Comment by levansy2020** [comment]
Ok I'm working on it
