### ISSUE TITLE
PayPal Plus Language

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#328]
I think we need to do something about the language.  Right now when it redirects to PayPal it's using English, and then I can choose between other languages from a drop down list, but a user is complaining...

>You offer paypal plus for germany without german language viewed.
Are you serious? ;-)
--redirect normal pay via paypal plus to german translated site:
(at the momemt: https://www.paypal.com/webapps/hermes?country=US&useraction=commit&token=EC-00459546TH2455211#/checkout/login)

>paypal standard handover the country and language in the URL to change native/german language

(https://wordpress.org/support/topic/paypal-plus-integration?replies=32)

We need to look into how we're handling the language with PayPal Plus and make sure we're passing the currency code in the redirect URL or in the API call or whatever is necessary to make the language use the site's locale code.

**Comment by angelleye** [comment]
Re-opening this because I think maybe we need to also add the language parameter..??

"country":'DE',
"language":'de_DE',

**Comment by levansy2020** [comment]
It doesn't have language paramete
