### ISSUE TITLE
Express Checkout - Invalid Token

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#337]
We made some adjustments in #318 to try and handle this, but I think we missed something because I'm still getting reports of the problem.

Maybe we aren't checking for the session everywhere it needs to be..??  I know we're checking it before creating the SetExpressCheckout request, but are we also checking it prior to creating the GetExpressCheckoutDetails and DoExpressCheckoutPayment requests?

**Comment by levansy2020** [comment]
I have checked again but seems GetExpressCheckoutDetails and DoExpressCheckoutPayment  have the condition to check Token is empty or not. Do you have any log or something else?

**Comment by angelleye** [comment]
Here is a ticket where this happened to a user recently.  https://www.angelleye.com/support/scp/tickets.php?id=274

**Comment by levansy2020** [comment]
https://github.com/angelleye/paypal-woocommerce/commit/a0e74cac9462d7f3d30b3cffb6f3e28c60f13974 remove debug code

**Comment by angelleye** [comment]
Looks like you've added more logic to try and catch when the token isn't available, but I'm curious why this is happening in the first place..??  It seems that the SEC and GECD calls are fine, but then for some reason the DECP request is not including a token.

**Comment by angelleye** [comment]
Here's another ticket where somebody is getting invalid token:  https://www.angelleye.com/support/scp/tickets.php?id=261

It's happening enough that I don't think it's simply a matter of sessions timing out.  Somehow we're losing our data when building the DECP request.

**Comment by angelleye** [comment]
This seems to happen a lot from people on WPEngine because of their caching tools.  If you contact WPEngine they are able to fix it.

I discussed this once with @kcppdevelopers and you seemed to think you might be able to disable caching of our stuff within the code to eliminate this problem.

**Comment by angelleye** [comment]
@kcppdevelopers You seemed to have an idea of how to address this when we discussed it before.  Why did you mark it wontfix now?

**Comment by kcppdevelopers** [comment]
I have try to find out solution to disable caching of our stuff within the code to eliminate this problem but WPEngine not allowed us using code.

**Comment by kcppdevelopers** [comment]
Now we have used woo session database table for store custom data, now everything is working fine.
