### ISSUE TITLE
Disabling #place_order button via jQuery doesn't work

### ISSUE THREAD

**Issue by DoomDesign** [angelleye/paypal-woocommerce#339]
Hello!
Great and wonderful plugin (and thanks for implementing PayPal Plus for us! )

I had the following issue.
With the plugin enabled and PayPal Plus enabled, in the checkout the following happens:

If I de-choose a payment method in the Paypal Plus iFrame, the following happens:
- In the PayPal Plus iFrame, no method is selected for the moment
- the Checkout Submit button (#place_order) gets disabled (greyed out)
- in the hidden original WooCommerce Payment method Chooser, nothing changes

So far, so good (as expected). Now comes the trouble:
When I (then) choose a payment method in the Paypal Plus iFrame:
- in the iFrame, the method is selected (good)
- if I have other payment methods activated and choose them in the iFrame, they get also selected in the hidden original payment method chooser (good)
- the Checkout Submit button (#place_order) won't be enabled again (BAD!)

I fixed this for my instance the following way:
In [classes/wc-gateway-paypal-plus-angelleye.php , Line 289](https://github.com/angelleye/paypal-woocommerce/blob/release/classes/wc-gateway-paypal-plus-angelleye.php#L289) :
```
jQuery('#place_order').disable(false);
```

When I replace this line with the following (Method recommended by [jQuery itself](https://learn.jquery.com/using-jquery-core/faq/how-do-i-disable-enable-a-form-element/) ):
```
jQuery('#place_order').prop("disabled",false);
```

, everything works as expected.

Best regards!

**Comment by angelleye** [comment]
@levansy2020 Please look into this.

**Comment by levansy2020** [comment]
Already fixed in https://github.com/angelleye/paypal-woocommerce/commit/dda5ea5f5de59403552e0f15085bb3b101230004

**Comment by angelleye** [comment]
@DoomDesign, Seems we already had this fixed in our release branch, but thank you for the feedback!
