### ISSUE TITLE
Paypal payment demands adding credit card

### ISSUE THREAD

**Issue by Benman2005** [angelleye/paypal-woocommerce#344]
First off, I'm fairly new to this, but let me quickly explain my issue.

I installed the Paypal (Express Checkout) for Woocommerce plugin to have the option of paying with creditcard without the need to create a Paypal account. I think that's working fine so far, but

Now if i want to pay with just a Paypal account it tells me I need to add a credit card to my PP acount, while the Paypal standard option that comes with Woocommerce doesn't oblige me to do so. You might imagine my confusion. 

Do I now really need to enable both PP Standard for paying without credit card and also enable your Express Checkout to pay without PP account?

My PP account is verified and connected to a bank account, just a not a credit card. 

I'm not sure where i would need to change a setting or just use the two paypal applications at the same time. Could you offer a helping hand? Thx

**Comment by angelleye** [comment]
No, Express Checkout alone handles both.  I've never run into any issue where it would tell you that you have to add a credit card to your PayPal account.  Can you provide a screenshot of exactly what you're seeing there?

**Comment by Benman2005** [comment]
Thx for the quick reply! Here's a screenshot.. It might seem that there's something wrong with  my pp account, but it works fine with the Paypal Standard thingy. Oh yeah.. it's in Dutch, but it says "add credit card to complete payment"
![pp cc](https://cloud.githubusercontent.com/assets/15366042/10819649/87c2a7be-7e49-11e5-9004-4d3b927b4495.PNG)

**Comment by angelleye** [comment]
I'm sorry for the delay getting back to you.  I did not see the notification that you had responded here.

The screenshot seems to be the Express Checkout / Guest Checkout method.  Do you have everything configured to use Guest Checkout?

It might be best if you [submit a ticket here](http://www.angelleye.com/support) and include temporary login credentials for your site so I can take a quick look.
