### ISSUE TITLE
Error Message Hooks

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#345]
Right now we have an option in the plugin where you can display "generic" vs. "detailed" error messages to the user.  Detailed will display the actual message from the PayPal API response.  

Some users would like to write their own logic and display custom messaging depending on what the error code is.  I would like hooks to make this possible.

**Comment by levansy2020** [comment]
I found that we are already have those filter in payment classes.

**Comment by angelleye** [comment]
What are the filters that should be used for this?  Can you provide a sample here please?

**Comment by kcppdevelopers** [comment]
List of filters for error message: http://pastebin.com/0EprZUTj

Example: https://www.angelleye.com/support/scp/tickets.php?id=273

**Comment by angelleye** [comment]
I don't see an example in that support thread..??

**Comment by kcppdevelopers** [comment]
http://pastebin.com/0EprZUTj

**Comment by angelleye** [comment]
The hook names in use right now are not very good.  We need to rename them so they make sense with what they do and can be easily distinguished between each other.

Seems some logic improvements could also be done here.

**Comment by angelleye** [comment]
I'd like to rename hooks like this...

angelleye_ec_error_email_notify_subject -> ae_ppec_error_email_subject
angelleye_ec_error_email_notify_message -> ae_ppec_error_email_message
angelleye_ec_display_type_message -> ae_ppec_error_user_display_message
angelleye_ec_refund_message -> ae_ppec_refund_error_message

angelleye_pc_error_email_notify_subject -> ae_ppddp_error_email_subject
angelleye_pc_error_email_notify_message -> ae_ppddp_error_email_message
angelleye_pc_display_type_notice -> ae_ppddp_error_user_display_message
angelleye_pc_display_type_error -> ae_ppddp_error_exception
angelleye_pc_refund_message -> ae_ppddp_refund_error_message

angelleye_fc_error_email_notify_subject -> ae_pppf_error_email_subject
angelleye_fc_error_email_notify_msg -> ae_pppf_error_email_message
angelleye_fc_empty_response -> ae_pppf_paypal_response_empty_message  (is that right..??)
angelleye_fc_dp_error_display_type -> ae_pppf_error_user_display_message
angelleye_fc_refund_error -> ae_pppf_refund_error_message

**Comment by kcppdevelopers** [comment]
angelleye_pc_empty_response -> ae_ppddp_paypal_response_empty_message

**Comment by kcppdevelopers** [comment]
Yes, "ae_pppf_paypal_response_empty_message" hook name ok as per what they do.

**Comment by angelleye** [comment]
@kcppdevelopers Can you provide an updated usage sample now that we've renamed the hooks?

Also, please include an example that shows how to display a particular messaged based on the error code.  I'm not sure how to get the value of the error code into the hook function..??

**Comment by angelleye** [comment]
@kcppdevelopers I never did see a usage sample for these after renaming them..??

**Comment by kcppdevelopers** [comment]
@angelleye 

Here is latest code sample : https://pastebin.com/25QG57XX
