### ISSUE TITLE
replace get_the_permalink() with get_permalink()..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#354]
Umar Sheikh (via email) reports the following:

>I am getting following error during checkout:

>Fatal error: Call to undefined function get_the_permalink() in /home/kashmi7/public_html/kashmirpillows.com/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 621

Initial info I'm finding online says get_permalink() should be used instead, but I'm curious why we haven't had any reports of this until now..??

**Comment by angelleye** [comment]
Apparently he's running WP 3.8.11.  I've asked him to see if he can get updated to see if the problem goes away.

**Comment by angelleye** [comment]
This may be the same as #367

**Comment by kcppdevelopers** [comment]
we have already resolved #367
