### ISSUE TITLE
Smart Coupons Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#356]
User reporting that coupons from the Smart Coupons are not working when Express Checkout is used, but it works fine with built in PayPal Standard.

https://wordpress.org/support/topic/after-payment-not-generate-coupon?replies=2#post-7721157

**Comment by digimiles** [comment]
I'm running a site experiencing this problem also. Let me know if you need any diagnostics.

**Comment by angelleye** [comment]
Any detail you can provide would be great to save us time when we get to this.  We're currently working on the 1.2 release, and I've got this planned for the 1.2.1 follow up to that.

**Comment by digimiles** [comment]
OK great. I'm not sure if the status report is of use but here it is anyway.

WC Version: 2.4.12
Log Directory Writable: ✔  /nas/content/live/wp-content/uploads/wc-logs/
WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
Language: en_AU

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.9-1ubuntu4.14
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 6000
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.12
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (34) ###

Gravity Forms: by rocketgenius – 1.9.15
Advanced Custom Fields: Gallery Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: Repeater Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: by Elliot Condon – 4.4.4
Autoptimize: by Frank Goossens (futtta) – 1.9.4
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.16
Envato WordPress Toolkit: by Envato – 1.7.3
Essential Grid: by ThemePunch – 2.0.9.1
Gravity Forms User Registration Add-On: by rocketgenius – 2.4
jQuery Mega Menu: by Lee Chestnutt | Modified by MPC Team – 1.4
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.9
Lazy Load: by  – 0.6
MailChimp for WordPress: by ibericode – 3.0.7
MPC Extensions: by MassivePixelCreation – 3.6.5
MPC Shortcodes: by MassivePixelCreation – 3.6
MPC Widgets: by MassivePixelCreation – 3.6
PayPal for WooCommerce: by Angell EYE – 1.1.7.5
WooCommerce Cart Notices: by WooThemes / SkyVerge – 1.4.1
WooCommerce Chained Products: by Store Apps – 2.3.6
WooCommerce Checkout Add-Ons: by WooThemes / SkyVerge – 1.6.2 – 1.6.4 is available
WooCommerce Dynamic Pricing: by Lucas Stark – 2.10.5 – 2.10.11 is available
Follow-Up Emails: by 75nineteen Media LLC – 4.4 – 4.4.9 is available
WooCommerce Stripe Gateway: by Mike Jolley – 2.6.5 – 2.6.7 is available
WooCommerce Google Trusted Stores Integration: by enollo – 1.0.0
WooCommerce Print Invoice/Packing list: by WooThemes / SkyVerge – 2.6.1
WooCommerce Google Product Feed: by Lee Willis – 4.0.3
WooCommerce Sequential Order Numbers: by SkyVerge – 1.5.1
WooCommerce Smart Coupons: by WooThemes – 3.0.6 – 3.0.9 is available
WooCommerce Social Login: by WooThemes / SkyVerge – 1.6.0
WooCommerce: by WooThemes – 2.4.12
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 3.0.6
WP Smush: by WPMU DEV – 2.1.2
YITH WooCommerce Wishlist: by Yithemes – 2.0.12

### Settings ###

Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #15 - /shop/
Basket: #16 - /cart/
Checkout: #17 - /checkout/
My Account: #18 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: TC Child
Version: 3.5.1
Author URL: http://www.blog.mpcreation.pl
Child Theme: ✔
Parent Theme Name: Blaszok
Parent Theme Version: 3.6.5
Parent Theme Author URL: http://mpcreation.net
WooCommerce Support: ✔

**Comment by olivercastle** [comment]
I also seem to be having this issue.
Paypal express doesn't issue the coupon, but PayPal Pro (PayPal Payments Pro 2.0 (PayFlow)) works just fine.

Maybe it has something to do with the actions that are used and paypal express doesn't trigger one?

**Comment by angelleye** [comment]
Thanks for the update.  We're currently working on our 1.3.0 release, and then we'll be moving to this 1.4.0 release.  We'll get this all taken care of ASAP!
