### ISSUE TITLE
Payments Pro PayFlow - Line Items

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#359]
Even with line items enabled in the PayFlow settings they are not getting included in the PayPal request.  

I had a report of this recently, and I just noticed the same thing happened on my own angelleye.com website.  

Need to look into this and get it resolved.

**Comment by kcppdevelopers** [comment]
For me, it's working fine, but I have changed the logic for preventing the problem in case of setting is not saved.

**Comment by angelleye** [comment]
So is this ready for review?

**Comment by angelleye** [comment]
We have confirmed that the API request is getting the itemized params as outlined in the PayFlow developer guide documentation.  I've posted a ticket to PayPal MTS about this because the items aren't showing up in the PayPal Manager transaction details.
