### ISSUE TITLE
Authorization / Order, Capture, Reauthorization, Void

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#36]
Right now both Express Checkout and Payments Pro are hard-coded to run everything as a Sale.  We need to tie in options for doing Auth/Order and Capture.

Express Checkout settings page should have option to process orders as Sale, Authorization, or Order.  

Payments Pro would have the option to set Authorization or Sale (no Order option for Pro).  

Orders or Authorization orders in the WooCommerce Orders screen would then need buttons for Capture, Void, Reauthorize, and these would be hooked up to PayPal's DoCapture, DoVoid, and DoReauthorization API's respectively.  

When running these API calls we'll pass in the transaction ID that we got back from PayPal on the original order/authorization.  The notes in WooCommerce will need to follow this entire flow, of course, and keep authorization transaction ID's and capture ID's separate from each other in the history.

**Comment by angelleye** [comment]
#210 added the option to set the payment action, but I forgot to add the Order option, so we still need to add that and then follow through with the rest of this issue.

**Comment by angelleye** [comment]
Were you able to fully test an "order" after setting this up?  I may have been incorrect in the procedure I mentioned for that.  It could be that we actually have to run an Authorization against an order, and then capture that authorization.  

I'm actually not 100% clear on that myself, so I'll have to review the documentation again on that...unless you were able to fully test an order, and then auth/capture it through WooCommerce already..??

**Comment by kcppdevelopers** [comment]
Yes, I have tested above functionality and it's working fine.

**Comment by angelleye** [comment]
Ok, I'm a little confused.  It looks like you did have to make some adjustments based on my last comment..??  So then you tested after that adjustment..??

**Comment by kcppdevelopers** [comment]
Actually I forget to add Authorization for order payment action, I have just add new function for that.

**Comment by angelleye** [comment]
This guy is trying to use this and getting errors on the DoAuthorization and DoCapture API calls:  https://www.angelleye.com/support/scp/tickets.php?id=416
