### ISSUE TITLE
Express Checkout - Phone Number not included in WC order..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#360]
User report:  https://www.angelleye.com/support/scp/tickets.php?id=309

Might have something to do with country and validation of the phone number value..??

**Comment by kcppdevelopers** [comment]
I have checked this issue and found that it's working fine for me, As I remember we have already resolved this issue.

**Comment by otherprod** [comment]
Hi, just to inform that i had the bug too, i made it work by unselect the option: 

 Set billing address in WooCommerce using the address returned by PayPal.

**Comment by angelleye** [comment]
@kcppdevelopers Just want to make sure you see what @otherprod said here.

**Comment by strarsis** [comment]
> Hi, just to inform that i had the bug too, i made it work by unselect the option:
> 
> Set billing address in WooCommerce using the address returned by PayPal.

Still have this issue, and the option was already disabled, the phone number in order is still empty, despite the phone number being shown in the logs.
