### ISSUE TITLE
Free Orders where shipping is all that needs to be paid...

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#361]
We may have another issue for this already, but I have a report of it happening now and couldn't find it.

https://www.angelleye.com/support/scp/tickets.php?id=284

Basically, we need to handle orders where the discount makes the subtotal 0.00, but then shipping needs to be paid.  PayPal rejects the $0.00 ITEMAMT.

Suggested fix from the ticket is:

> 3) We could set the actual shipping amount to 0.00 and then add the shipping as an additional line item on the order.

**Comment by kcppdevelopers** [comment]
I have checked above issue, it's working fine for me.
