### ISSUE TITLE
PayPal Plus - user reports item amt and tax problems.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#362]
https://wordpress.org/support/topic/item-amount-must-add-up-to-specified-amount-subtotal?replies=5#post-7754731

**Comment by kcppdevelopers** [comment]
I have test above issue for me it's working fine. I think our plugin conflict with other plugin.

**Comment by logtainment** [comment]
In Woocommerce Germanized is it the same.,
