### ISSUE TITLE
Payments Pro PayFlow - Problems with Line Items..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#364]
User reporting that they are getting 10413 error when using a coupon code with PayFlow, but it works fine with Express Checkout.

Also reporting that it still happens even with "send line items to PayPal" disabled, so that's odd.

Need to look into this and get it resolved.

https://www.angelleye.com/support/scp/tickets.php?id=324

**Comment by angelleye** [comment]
This may be a duplicate of #359

**Comment by kcppdevelopers** [comment]
I have tested above exact scenario with different test cases, it's working fine for me.
