### ISSUE TITLE
Local Pickup Plus Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#365]
User requesting compatibility with the "Local Pickup Plus" plugin.  They say it works fine with the built in PayPal Standard in WooCommerce, but Express Checkout (and probably Payments Pro, too) is not passing the selected shipping option to PayPal.

https://wordpress.org/support/topic/local-pickup-plus-support?replies=1

**Comment by angelleye** [comment]
Need to make sure to test this with all of our payment gateways.

**Comment by tejasm-itpath** [comment]
@angelleye  Plugin required

**Comment by kcppdevelopers** [comment]
@tejasm-itpath I already have latest version, I will send on Slack.

**Comment by tejasm-itpath** [comment]
@angelleye It is working with Express checkout and PayPal Pro gateways.
PayPal standard and PayPal Express checkout both showing same option for PayPal and Also in Woocoomerce and it's Order. Also showing shipping details and shipping amount the way it showing in PayPal standard.
Also Custom field is showing shipping value in meta field we have shown in #865
