### ISSUE TITLE
Payments Pro PayFlow - Cart Totals Error

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#366]
User reported problem:  https://www.angelleye.com/support/scp/tickets.php?id=324

They have a coupon code that discounts the same amount as the item, so then all they're paying for is shipping.  This is causing PayFlow to return a cart totals error.  

I think it's happening because the API request includes AMT and SHIPPINGAMT but it does not include ITEMAMT, HANDLINGAMT, TAXAMT, etc.  

The user says that Express is working fine, but it's only happening with PayFlow.  Not sure if it happens in DoDirectPayment or not.

**Comment by angelleye** [comment]
It looks like #359 and #364 could be duplicates of this..??

**Comment by kcppdevelopers** [comment]
duplicate issue #364
