### ISSUE TITLE
PayPal Plus - Enable / Disable Bug

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#368]
We have it setup so that if the WooCommerce currency is not set to a compatible value, then when you try to load the PayPal Plus settings panel it gives you a message that you can't use it because you aren't using the proper currency.

However, if we have EUR set, for example, and then we enable PayPal Plus...but then we go and change the currency to USD...PayPal Plus remains active and still overrides the payment gateways on the WooCommerce checkout page.

At that point I have to change the currency back to EUR so that I can load the PayPal Plus settings to disable it, and then change my currency back again.

We need to handle this somehow.  Maybe automatically disable PayPal Plus if it is enabled and the currency is adjusted..??  Of course, we should display a notification that this will happen and let them say OK or Cancel before submitting the currency adjustment.

**Comment by kcppdevelopers** [comment]
I have applied above changed expect display Java script OK or Cancel pop when WooCommerce currency is not supported to PayPal Plus. I have display admin notice instead of a Java script popup.

**Comment by angelleye** [comment]
I see this...

>__( 'Gateway Disabled: PayPal Plus does not support your store currency (Supports: EUR, CAD).', 'woocommerce-gateway-paypal-pro')

Shouldn't that second parameter be 'woocommerce-gateway-paypal-plus' instead?
