### ISSUE TITLE
Braintree Integration

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#370]
Woo has a [Braintree plugin](https://www.woothemes.com/products/braintree/) we can probably use to merge into our plugin.  Then we'll just need to get our partner code in there like this example:

    $result = Braintree_Transaction::sale([
      'amount' => '100.00',
      'paymentMethodNonce' => nonceFromTheClient,
      'channel' => 'AngellEYEPayPalforWoo_BT'
    ]);

**Comment by angelleye** [comment]
The documentation PayPal provided for this is:  https://developers.braintreepayments.com/reference/request/transaction/sale/php

**Comment by angelleye** [comment]
Kiril Kirilov (from my email) is ready to use this when it's completed.  Need to follow up with him.

**Comment by angelleye** [comment]
Looks like we forgot to add Braintree to our own settings panel under Settings -> PayPal for WooCommerce in the WP admin panel.

**Comment by angelleye** [comment]
I think we should probably mask the API credential values as password fields.  Right now they are displayed on screen unmasked.

**Comment by angelleye** [comment]
In the log file, I see the request got saved, but the response data seems to be empty...

>02-08-2016 @ 09:49:44 - Braintree_Transaction::sale Response code: 
>02-08-2016 @ 09:49:44 - Braintree_Transaction::sale Response message:

**Comment by angelleye** [comment]
When I enable the Drop-In Payment UI, I still get the warning message about needing an SSL on my site.  I think one of the advantages of the drop-in UI is that you don't need your own SSL, so we should probably hide that warning message if that's what they're using, but still show it if they aren't using the drop-in, of course.

**Comment by angelleye** [comment]
The Drop-In UI looks good, but it seems similar to PayPal Plus.

So the way this is now, from the WC checkout page, I have to choose the Braintree payment gateway, and then it sends me to another page where I have to choose again which type of payment I'm going to use...PayPal or credit card.

It seems like we should be able to do this the same way we did PayPal Plus, where the drop in UI actually replaces the WooCommerce checkout page gateway options, but then you can inject any additional payment gateway options that are enabled in WooCommerce into the braintree UI.  

This way the UI simply shows up on the checkout page, but it includes PayPal, credit card, and any other gateways you have enabled within it.

Again, the idea is that the only other gateways somebody might have enabled would be cash, check, COD, etc.  If they were using a different credit card option then they wouldn't be using the Braintree drop in UI, so there would be no conflict there. 

I am not 100% sure the Braintree UI allows you to inject your own payment gateway options, but I know Plus did, and this seems to be very similar, so I'm hoping it's the same.

Do you agree with this assessment, @kcppdevelopers?

**Comment by kcppdevelopers** [comment]
Have you check Braintree credit card UI without enable Enable Drop-in Payment UI?

**Comment by kcppdevelopers** [comment]
I have checked Braintree UI not allow us to inject own payment gateway options like PayPal Plus. also we can't used Drop-in Payment UI in default WooCommerce Payment gateways list, because Drop-in Payment UI generate iframe using braintree.js

Actually WooCommerce does not support iFrame based payment gateway in default WooCommerce Payment gateways list like Example: SagePay Form, PayPal Advanced.

**Comment by angelleye** [comment]
Yes, I checked Braintree without the drop in UI and that looks just fine.  It's just the experience with the drop in UI that I'm not completely thrilled with.  You're saying there is just no way to make it work the way PayPal Plus is working on the checkout page, though..??

**Comment by kcppdevelopers** [comment]
I have push latest code in issue-370 branch.
