### ISSUE TITLE
Buy Now button appended multiple times when using multiple [product_page] shortcodes

### ISSUE THREAD

**Issue by lucxaw** [angelleye/paypal-woocommerce#372]
If a page has multiple [product_page] shortcodes, and that product has Variations, the Javascript "appendTo" code gets inserted and executed multiple times resulting in duplicate Buy Now buttons

Line 448 in paypal-for-woocommerce.php is inserted for each [product_page] shortcode:
jQuery(document).ready(function(){
                        jQuery('input.single_variation_wrap_angelleye').appendTo(".variations_button");
                    });

This results in the Buy Now button being appended n^n times; where n=number of [product_page] shortcodes.

ie, for 4 products: 4^4=256 buttons inserted for each product

![clipboard-1](https://cloud.githubusercontent.com/assets/16487186/12048755/6784cf76-ae9c-11e5-8d6f-fe26e80dd1a5.jpg)

**Comment by angelleye** [comment]
This was from Malcom Krebbs.  Need to follow up with him after this is fixed.
