### ISSUE TITLE
Buy Now button doesn't submit correct form with multiple [product_page] shortcodes in Safari

### ISSUE THREAD

**Issue by lucxaw** [angelleye/paypal-woocommerce#376]
If a page has multiple [product_page] shortcodes, the Buy Now button will always submit the form of the first product in Safari. Using the button in the 2nd, 3rd, 4th etc product will result in an error. The attached shows "Please choose a product option" because Safari doesn't query the correct product.

The javascript in question is line 487 in paypal-for-woocommerce.php 
jQuery('form.cart').submit()

The code queries the first form in Safari rather than querying the form the Buy Now button belong to.

Firefox and Microsoft Edge will query the button's parent form and behave as expected. This is untested in Chrome, but assumed to be a Webkit issue.

![cid_122e8950-a22c-4675-acac-878b20782eff cg_shawcable](https://cloud.githubusercontent.com/assets/16487186/12107841/9a38c46e-b32d-11e5-97eb-b1b6c81a0ccf.png)

**Comment by angelleye** [comment]
Did you get a chance to see if #372 resolves this?  It's included in the release branch now and fixed the problem with the multiple buttons.

**Comment by lucxaw** [comment]
Sorry, I didn't realize it solved the Safari bug. I'll follow up if there's
any issues.

Thanks

**Comment by angelleye** [comment]
I'm not 100% sure it does, but I just want to make sure. He may have killed 2 birds with one stone.

**Comment by kcppdevelopers** [comment]
I have checked in Safari and Chrome browsers, for me it's working fine. @lucxaw let me know if any.

**Comment by angelleye** [comment]
@lucxaw Were you able to verify everything is good now?
