### ISSUE TITLE
Problems with PayPal Plus

### ISSUE THREAD

**Issue by spirit1977** [angelleye/paypal-woocommerce#377]
1. After payment the customer is redirected to homepage not to order received confirmation page
2. eMail order confirmation says "pay now with PayPal Plus" although payment is made.

ModSecurity is not enabled, you can have a look at the settings here: http://test.emoose.de/phpinfo.php

Here are two screenshots, one that shows that I only have three active plugins for testing purposes and the other one with the order confirmation and the notice to pay now.

https://www.dropbox.com/s/jqrunxjedrrqwsl/Best%C3%A4tigung%20Ihrer%20Bestellung%20bei%20Testshop%20vom%204.%20Januar%202016%20%20%20markvfritschen%20gmail.com%20%20%20Gmail.png?dl=0

https://www.dropbox.com/s/dpq7k7imemsnhde/Plugins%20%E2%80%B9%20Testshop%20%E2%80%94%20WordPress.png?dl=0

**Comment by kcppdevelopers** [comment]
Above image does not open, gives error 404 Not found.

**Comment by spirit1977** [comment]
Now they should open again

**Comment by kcppdevelopers** [comment]
You can disable/enable "pay now with PayPal Plus"  link, using this option http://screencast.com/t/I5j9NAKHX1Rf

**Comment by spirit1977** [comment]
OK, thanks. Then there is only the point open with the redirection to the homepage after purchase.

**Comment by angelleye** [comment]
@jigneshkailam did you look into why it's redirecting to his home page instead of a receipt page upon order completion?

**Comment by kcppdevelopers** [comment]
I have push latest code in to the issue-377 branch.

**Comment by spirit1977** [comment]
When I download and upload the files from the 377 branch I get the follwing error
Fatal error: Can't use method return value in write context in /www/htdocs/w0123bbf/Entwicklungen/test.emoose.de/wp-content/plugins/paypal-for-woocommerce/paypal-for-woocommerce.php on line 1038
