### ISSUE TITLE
WooCommerce 2.5 Preparation

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#379]
WC 2.5 is coming out soon:  https://woocommerce.wordpress.com/2016/01/05/woocommerce-2-5-release-candidate/

We need to test our plugin against the current release candidate and see if there are any problems we need to address before it's officially released.

**Comment by kcppdevelopers** [comment]
I have test this plugins against WooCommerce 2.5, it's working fine.
