### ISSUE TITLE
Express Checkout Error 10427

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#383]
Getting a report that they are getting this error in 1.1.8

> 01-11-2016 @ 14:13:22 - Response: Array
> (
>     [TIMESTAMP] => 2016-01-11T14:13:22Z
>     [CORRELATIONID] => 428017517b96a
>     [ACK] => Failure
>     [VERSION] => 124.0
>     [BUILD] => 18308778
>     [L_ERRORCODE0] => 10427
>     [L_SHORTMESSAGE0] => Invalid Data
>     [L_LONGMESSAGE0] => Shipping total is invalid.
>     [L_SEVERITYCODE0] => Error
> )

This could be related to changes we made in #352, but I'm not sure.  Need to take a look at those changes, and run some tests with discount codes to double check all order scenarios.

Here is the thread where the user reported this:  https://www.angelleye.com/forum/discussion/101/error-10427-shipping-cost-when-coupon-is-used

**Comment by angelleye** [comment]
User says this was happening on 1.1.7.5 so he updated to 1.1.8 hoping it would fix it, but it didn't.  So it must not be anything we did in 1.1.8.

>Now after turning off the return to checkout page option it seems to work.

I am actually not sure what the user is referring to, so waiting on an answer to that.

**Comment by angelleye** [comment]
This was happening because the user had "Skip Final View" enabled, which was skipping the shipping calculation altogether.

**Comment by angelleye** [comment]
Re-opening because now the user is saying it's still happening even with the skip final review disabled.

**Comment by angelleye** [comment]
More info:  turns out he was running on 1.1.7.5, so the problem was already there.  He has updated to 1.1.8 but the same problem remains.

**Comment by kcppdevelopers** [comment]
I have try to reproduce this issue, but everything is working fine for me. Can you please ask user to provide error log file, it will help us to reproduce this issue very quickly.

**Comment by angelleye** [comment]
The user [provided the log in the forum thread](https://www.angelleye.com/forum/discussion/comment/390#Comment_390).  We can see they are getting negative shipping amount for some reason.

**Comment by angelleye** [comment]
I'm going to move this to the next milestone so I can go ahead and release the current one.
