### ISSUE TITLE
Express Checkout - Potential problem with inventory control / backorders.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#389]
Customer provides lots of details about the issue here:  https://www.angelleye.com/support/scp/tickets.php?id=359

Need to check to see if this is something we can (and should) adjust in our plugin.  

Also, need to make sure it's a subtle adjustment if we're going to include it in 1.1.8.1.  If this looks like it's going to require a pretty big code adjustment we'll need to wait until 1.2.0.

**Comment by kcppdevelopers** [comment]
This looks like it's going to require a pretty big code adjustment.

**Comment by angelleye** [comment]
@kcppdevelopers You mentioned this one looked like a big adjustment, but I think #403 may have been a duplicate of this and we now have that one closed.

Can you verify whether or not this was the same issue?

**Comment by kcppdevelopers** [comment]
Yes, this is duplicate of #403
