### ISSUE TITLE
WooCommerce Memberships Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#390]
https://wordpress.org/support/topic/customer-name-deleted-in-woocommerce-subscriptions-plugin-with-paypal-express?replies=4#post-7890328

If this is something we can get done quickly we can include it with 1.1.8.1.  Otherwise, we should move it to 1.2.0.

**Comment by kcppdevelopers** [comment]
This looks like it's going to require a pretty big code adjustment. because our plugin is not compatible with WooCommerce Subscriptions.

**Comment by angelleye** [comment]
@kcppdevelopers I thought this would now be compatible with our latest updates.  We got Subscriptions working, right?  What about Memberships?

**Comment by kcppdevelopers** [comment]
@angelleye I have tested with latest update and it seems working well.
