### ISSUE TITLE
Payments Pro (DoDirectPayment) - 10413 Cart Totals Error

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#393]
User report (Matthew Wolter via email)...

>We are having an issue with some transactions and wondering if you can help? We use a coupon plugin by woocommerce and when a coupon is used in conjunction with the PayPal Website Payments Pro (DoDirectPayment) option, the transaction fails. We receive an error similar to the following:

>PayPal Pro payment failed (Correlation ID: 1a91ed532fb75). Payment was rejected due to an error: (10413) “10413-The totals of the cart item amounts do not match order amounts.” Order status changed from Pending Payment to Failed.

>Interesting thing is that we don't have an issue when PayPal Express Checkout is used instead. 

>01-18-2016 @ 12:24:04 - Request: Array
(
    [USER] => *****
    [PWD] => *****
    [VERSION] => 112.0
    [BUTTONSOURCE] => AngellEYE_SP_WooCommerce
    [SIGNATURE] => *****
    [METHOD] => DoDirectPayment
    [PAYMENTACTION] => Sale
    [IPADDRESS] => 162.144.76.10
    [CREDITCARDTYPE] => Visa
    [ACCT] => *****
    [EXPDATE] => *****
    [CVV2] => *****
    [EMAIL] => ****
    [FIRSTNAME] => Flow
    [LASTNAME] => Joe
    [STREET] => 231 Bogus Ave
    [STREET2] => #134
    [CITY] => Miami
    [STATE] => FL
    [COUNTRYCODE] => US
    [ZIP] => 33126
    [PHONENUM] => 506-72098425
    [AMT] => 15.90
    [CURRENCYCODE] => USD
    [SHIPDISCAMT] => 0.00
    [HANDLINGAMT] => 0.00
    [INVNUM] => 18574
    [SHIPPINGAMT] => 15.90
    [ITEMAMT] => 0.00
    [L_NAME0] => Tekno RC T-Shirt (vertical design, navy blue) - Shirt Size: Large
    [L_AMT0] => 11.99
    [L_NUMBER0] => TKRTS05L
    [L_QTY0] => 1
    [L_NAME1] => Total Discount
    [L_AMT1] => -11.99
    [L_NUMBER1] => team_shirt
    [L_QTY1] => 1
    [SHIPTONAME] => Joe Flow
    [SHIPTOSTREET] => 231 Bogus Ave.
    [SHIPTOSTREET2] => CR129X2491N
    [SHIPTOCITY] => Doral
    [SHIPTOSTATE] => FL
    [SHIPTOZIP] => 33195-6503
    [SHIPTOCOUNTRY] => US
)

>01-18-2016 @ 12:24:04 - Response: Array
(
    [TIMESTAMP] => 2016-01-18T20:24:04Z
    [CORRELATIONID] => 4424fd825398b
    [ACK] => Failure
    [VERSION] => 112.0
    [BUILD] => 18308778
    [L_ERRORCODE0] => 10413
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => The totals of the cart item amounts do not match order amounts.
    [L_SEVERITYCODE0] => Error
    [AMT] => 15.90
    [CURRENCYCODE] => USD
)

**Comment by kcppdevelopers** [comment]
Could you please ask user which plugin he is using for coupon code?

**Comment by angelleye** [comment]
He's using the [Woo Store Credit](http://fiber.angelleye.com/temp/woocommerce-store-credit-2.0.6.zip) plugin.

**Comment by angelleye** [comment]
More details from the user:

>Hello Andrew, the coupon is used for store credit. It basically applies a uniform discount across all items for the value of the coupon. It also retains the remaining amount in the coupon for use later. Attached is a screen shot of the cart contents and how the discount is applied. Hope this helps and thank you for the assistance with this issue. 

![image](https://cloud.githubusercontent.com/assets/629241/12439849/2b3b174a-befb-11e5-802c-e8430360979f.png)

**Comment by angelleye** [comment]
User's current plugin versions...

WooCommerce - 2.4.12
PayPal for WooCommerce - 1.1.7.5
WooCommerce Store Credit - 2.1.4

**Comment by kcppdevelopers** [comment]
This issue already resolved in PayPal for WooCommerce - 1.1.8, please update latest version and let me know if any.
