### ISSUE TITLE
PayPal Plus - Payment Options iFrame Styles

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#399]
The iFrame looks pretty dull, and the additional payment options don't have any logos or anything.

![image](https://cloud.githubusercontent.com/assets/629241/12507249/2a4baafa-c0ba-11e5-8769-b591a74c6b25.png)

Need to add some logos for the credit card option and make this look better.

**Comment by angelleye** [comment]
A heading above the iFrame would be nice, too.  Something like "Please choose your payment option."

**Comment by kcppdevelopers** [comment]
In PayPal PLUS iFrame thirdPartyPaymentMethods provide 4 parameters like below: 

- redirectUrl
- methodName
- description
- imageUrl

we are already used parameters except imageUrl, there are few restriction for imageUrl:

- The imageUrl must be a secure (https) URL.
- The image size must be maximum 100 x 25 px

**Comment by angelleye** [comment]
For the image URL we can do like we did in Express Checkout.  You'll see I have settings where people can upload their own image(s) using the WP uploader/media tool.  It specifies the dimensions in the setting description and it also provides a link to an SSL image host that is free in case they don't have their own https:// server.

**Comment by kcppdevelopers** [comment]
Yes, I know we already did in did in Express Checkout. but here we are talking about **additional payment options don't have any logos**, so we can provide this for other additional payment? because other payment methods have own setting panel.

**Comment by angelleye** [comment]
Not completely clear about this one myself.  Moving to future version.

**Comment by kcppdevelopers** [comment]
duplicate #453
