### ISSUE TITLE
PayPal Plus - Invoice Number

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#400]
Need to get the invoice number from WooCommerce transferring to PayPal in the API request.  I'm getting reports from a user that it is not currently getting included.

**Comment by angelleye** [comment]
I am getting a small merge conflict on this one.  

Please checkout the Issue-400 branch and then merge the dev branch into that.  The conflict should appear for you so that you can get it fixed for me in the issue branch.

So this should be an example where this popped up, but it should be a pretty quick fix for you...hopefully.

**Comment by kcppdevelopers** [comment]
I have push latest code into the issue-404A branch and my dev branch for your review.
