### ISSUE TITLE
PayPal Plus - Payment Method Options..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#401]
User is saying there are options showing up in his Plus iframe that he doesn't want, but they aren't from woocommerce gateway options.  

Says he thinks we're missing options in our plugin settings that would allow him to adjust what payment options he wants PayPal to include in the iframe (apart form what we're embedding with woocommerce options).  

Need to check into this.

**Comment by kcppdevelopers** [comment]
When we enable PayPal Plus gateway, it will display two payment methods like "PayPal" and "Credit Card". it's default behavior of PayPal Plus, there is no any option is available to enable/disable specific payment method in PayPal Plus Iframe.

**Comment by angelleye** [comment]
I'm pretty sure there are supposed to be more than just the two options available, though.  A PayPal rep mentioned there are some additional settings we should be able to pass into our request to make different payment options show up in the iframe.

Please double check the documentation for something like that and let me know if you can't find it.

**Comment by kcppdevelopers** [comment]
Yes, you are right. PayPal Plus iframe allow us to add additional payment methods using "thirdPartyPaymentMethods" parameter. But here I am talking about when we enable PayPal Plus it will automatically enable "PayPal" and "credit card" two payment methods ( both are come from PayPal Plus)  and also we can add more payment method using "thirdPartyPaymentMethods" parameter like BACS, Cheque, Cash on Delivery and more ..

Which payment methods user want to hide?

**Comment by angelleye** [comment]
Ok, so now you're talking about injecting the other gateways into the iframe (which is what I was hoping we could do with Braintree, but I guess we can't).

What I'm talking about here is that according to PayPal there is supposed to be a way for us to set additional flags in our request to include more than just PayPal or Credit Card in their iframe by default.  I think there are some other payment options specific to Germany that would only show up (or not) based on how you pass in the options.

For example, with PayPal Advanced there is a setting where you pass in a "layout" like A,B,C and then it would show different things in the iframe depending on which layout you specify.  

Are you not seeing anything like that in the documentation for the Braintree UI drop in?

**Comment by kcppdevelopers** [comment]
No, I am not seeing anything like that in the PayPal Plus document.

**Comment by angelleye** [comment]
I am not completely sure on this myself, so we'll move to this to a later version.
