### ISSUE TITLE
Express Checkout - Refund Transaction ID

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#405]
On my live angelleye.com site I processed a refund for an order, and I realized that the refund transaction ID is not getting saved anywhere in the order.  

We need to add a meta data value for "Refund Transaction ID" when refunds are processed and add the transaction ID we get back from the refund API transaction here.

**Comment by kcppdevelopers** [comment]
![refund_405](https://cloud.githubusercontent.com/assets/13145461/12977617/cba9b2ec-d0f1-11e5-9d23-125faa9564dc.png)

**Comment by kcppdevelopers** [comment]
it seems we are strong refund transaction in order note.

**Comment by chrisp1001** [comment]
May I ask why this issue has been closed? Yes, of course, the refund transaction ID is logged in the notes, however it makes sense to save it as a structured value in wp_postmeta.

We are currently having the problem that we need to read the refund paypal transaction id out for secondary use of the data in our process of book keeping. Would you mind implementing that feature?

**Comment by angelleye** [comment]
@chrisp1001 I agree we should go ahead and take the next step to do that.  I'll re-open this and put it on our next update list.

**Comment by kcppdevelopers** [comment]
https://www.screencast.com/t/rj9H4HDaBX
