### ISSUE TITLE
PayPal Plus Bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#407]
User reporting failures after updating to 1.1.9.1.  

https://www.angelleye.com/support/scp/tickets.php?id=385

**Comment by angelleye** [comment]
Another user with same problem:  https://www.angelleye.com/support/scp/tickets.php?id=384

Both users are saying everything worked perfectly until our 1.1.9 update.

**Comment by kcppdevelopers** [comment]
I have checked PayPal Plus, everything is working fine for me.

**Comment by angelleye** [comment]
Sent a response to the users who reported to have them grab the current release branch and see if they still have problems.

**Comment by angelleye** [comment]
I'm going to close this since we've heard from others saying Plus is working fine for them now.  If these guys come back saying it's still not working we need to look into POODLE (openssl and php version).
