### ISSUE TITLE
PayPal express checkout random create new account or pay with debit card

### ISSUE THREAD

**Issue by SavaTom** [angelleye/paypal-woocommerce#412]
When PayPal express checkout is the ONLY option selected as payment it will randomly either choose "create a new account" or "pay with debit or card" below the "Pay with PayPal" option.

Under these circumstances shouldn't it default to "Pay with PayPal" with the option to "pay with debit or credit card" and NEVER ask to "create an account"?

It should be noted that shipping is disabled and the product is not subscription based. Also, all browser cache cleared. Additionally, PayPal standard is disabled in woocommerce and "PayPal Account Optional" within paypal.com is "enabled".

Screenshot attached

![paypalrandom](https://cloud.githubusercontent.com/assets/4883740/12891764/b116db06-ce91-11e5-8b5b-e3a892c00fed.jpg)

How to "force" the option to "pay with debit or card" and NEVER have "create an account" visible?

Thank you

**Comment by angelleye** [comment]
Make sure you have followed [these steps](https://www.angelleye.com/support/kb/faq.php?id=1).  It sounds like you have if you're getting what you expect sometimes.

Guest checkout is simply not available for all customers in all countries.  Is it possible that the buyers who aren't getting the option are in other countries?

**Comment by SavaTom** [comment]
Thank you, the issue was I didnt have "billing" for landing page.

Thank you

**Comment by angelleye** [comment]
Glad you got it worked out!

**Comment by SavaTom** [comment]
Strange actually, it appears to work on desktop with "Pay with debit or credit card" but not on mobile (safari with latest ios9). Same IP address.
