### ISSUE TITLE
PayPal Plus Bug

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#413]
User report:  https://wordpress.org/support/topic/special-server-requirements-for-paypal-plus?replies=11#post-7996483

Comment from PayPal MTS:

>I was able to find the point of failure. It looks like after you receive back the EC token and other links, the cart is sending in an update with the buyer's shipping address. It also includes an update to shipping, which is where the bug is. It looks like it modifies the subtotal to be that of only one item:

    {"op":"replace","path":"/transactions/0/amount","value":{"total":"20.40","currency":"EUR","details":{"subtotal":"0.42","shipping":"16.72","tax":"3.26"}}}

>However, it still has the item details indicating that the total of the items should be 13.03.

**Comment by kcppdevelopers** [comment]
I have look into this and try to regenerate issue, but it seems everything working fine for me.

**Comment by angelleye** [comment]
Waiting for more details from the user that reported this.
