### ISSUE TITLE
Bug with discount plugin..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#416]
User report:  https://wordpress.org/support/topic/error-code-10413-cart-item-amounts-do-not-match-order-amounts-1?replies=8#post-8022368

We should look to ensure this gets resolved in all payment gateways included with our plugin (if necessary).

**Comment by kcppdevelopers** [comment]
I have look into this and try to regenerate issue, but it seems everything working fine for me.

**Comment by angelleye** [comment]
Did you set one up the same way he shows in his screenshot?

**Comment by kcppdevelopers** [comment]
Yes, I have setup same way he shows in his screenshot.

**Comment by kcppdevelopers** [comment]
We have develop new calculation class, now everything is working fine.
