### ISSUE TITLE
Missing localization entry in version 1.1.9.2

### ISSUE THREAD

**Issue by digitalbreed** [angelleye/paypal-woocommerce#418]
In `paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php`, this string `$this->order_button_text  = __( 'Proceed to PayPal', 'paypal-for-woocommerce' );` is not contained in the original localization `paypal-for-woocommerce/i18n/languages/paypal-for-woocommerce.pot`.

**Comment by kcppdevelopers** [comment]
Now inbuilt tool available for generate .POT file : https://developer.wordpress.org/plugins/internationalization/localization/#plugin-repository-admin-tools

**Comment by angelleye** [comment]
@digitalbreed thanks for letting us know.  We will get this included in a fresh pot file when we release the 1.2.0 update here soon.
