### ISSUE TITLE
Localization on review order page hardcoded in version 1.1.9.2

### ISSUE THREAD

**Issue by digitalbreed** [angelleye/paypal-woocommerce#419]
The "Processing" value for the submit button on the over review page `paypal-for-woocommerce/template/paypal-review-order.php` is hardcoded: `<input type="submit" onclick="jQuery(this).attr(\'disabled\', \'disabled\').val(\'Processing\');...`.

**Comment by angelleye** [comment]
This has been merged into the release branch and will be included in the 1.2 update.
