### ISSUE TITLE
Payments Pro American Express Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#420]
I've been getting reports lately from users trying to accept Amex with currency codes other than USD.  Those are getting rejected with invalid currency code errors.  Apparently Amex only supports USD.

We need to verify that USD is the only one it supports (maybe it supports a few others, too..??) and then make sure the Amex option doesn't show up if the currency in WooCommerce is set to an unsupported Amex value.

**Comment by kcppdevelopers** [comment]
You are talking about credit card drop-down right? Here I am little bit confused, Can you please explain more details?

**Comment by angelleye** [comment]
Yes, it would be in the drop down box that allows people to select their card type on the checkout page.  If the currency code is not supported we need to hide Amex from the options in that drop down.

**Comment by kcppdevelopers** [comment]
as you know we already remove credit card drop down box and currently we are used woo default credit card interface. so we need to add it again?

**Comment by angelleye** [comment]
Ah, right, I forgot the new method does not have a drop down for the card type. 

As such, we must have some logic that is setting the card type based on the credit card number, right?

Can we add some validation so that if the card type ends up being Amex but the currency is not USD we return a validation error?

**Comment by angelleye** [comment]
I'm a little confused here.  It looks like you're only throwing the validation error if the currency is CAD..??

**Comment by angelleye** [comment]
Also, I think we need to do the same thing to PayFlow.

**Comment by kcppdevelopers** [comment]
Amex card type only support AUD and USD currency as per [this](https://developer.paypal.com/docs/classic/api/currency_codes/#creditcard) table. please correct me if I am wrong.

**Comment by angelleye** [comment]
You're correct.  I was reading it incorrectly before.
