### ISSUE TITLE
Payments Pro PayFlow - Discount Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#424]
With most of the PayPal APIs there is no "discount" parameter.  As such, to include a discount we have always added the discount as a cart/line item with a negative amount.

Users are reporting that with PayFlow they are getting "invalid format error" returned, and PayPal is telling me that "upon quick glance it looks like it's an amount format error."

Looking at this PayFlow doc (https://developer.paypal.com/webapps/developer/docs/classic/payflow/integration-guide/) it seems they do have a DISCOUNT parameter, so we need to adjust PayFlow so that it uses this parameter for discounts instead of adding a discount line item with a negative amount.

User reported via email:  Adrian Fraim

**Comment by angelleye** [comment]
On hold for now because the user that reported this fixed the problem by disabling the option to send line items to PayFlow.

**Comment by kcppdevelopers** [comment]
We have develop new calculation and now everything is working well.

**Comment by angelleye** [comment]
I'm going to move this to next milestone since it's not urgent, but I do want to revisit this.  Our new calculation may help fix cart total errors, but we still need to utilize the DISCOUNT field that PayFlow provides so things show up nicely in the PayFlow transaction details.

**Comment by kcppdevelopers** [comment]
#908
