### ISSUE TITLE
Braintree Partner API

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#426]
In #370 we added Braintree.  This is working fine, but PayPal really wants us to use their Partner API to onboard new people signing up for Braintree.  This will allow them to get signed up and ready to process directly from within the plugin flow.

We need to implement this based on the [partner API documentation](https://developers.braintreepayments.com/guides/partner-api/overview).

I believe there is a snap-in UI that comes with this, too, that we would implement as well.  I'm still not 100% clear on whether it's different than the one we already implemented or not.  We'll need to look into that more.

Woo has actually done this already in a free extension they are providing:  https://wordpress.org/plugins/woocommerce-gateway-paypal-powered-by-braintree/

We can use that as a reference for what we need to be doing here, too.

If we can, we should just tie this into the Braintree integration we already have.  So the final product would be that we can onboard new merchants using this partner API, and then use the stuff we've already done (plus potentially an additional one here) to use the service accordingly.

**Comment by kcppdevelopers** [comment]
I have read [partner API documentation](https://developers.braintreepayments.com/guides/partner-api/overview) guide and found that this is little bit different.

To use the Partner API we must register an OAuth application with Braintree. This process will result in a $clientId and a $clientSecret that must be securely stored on our server [Read more](https://developers.braintreepayments.com/guides/partner-api/overview#configuration)

**Comment by angelleye** [comment]
Ok, let's go ahead and proceed however we need to.  We need a sandbox ID and secret hosted on my test server that we hit, and a live ID and secret on my live server, right?

Please confirm and I can get that from my developer account.

**Comment by kcppdevelopers** [comment]
Yes right! please provide $clientId and $clientSecret from  your developer account.

**Comment by angelleye** [comment]
I actually just got word that we are not required to add this partner API the way they originally said.  It looks like you already have a lot of progress made on this, though, so we might as well finish it up.

That said, I'm not exactly sure how you've gone about this, but I don't want to add this as a completely separate gateway option.  

We already have our Braintree tab in our settings page.  Within that we just have a link to the WooCommerce checkout settings like all the others.  What we can do is go ahead and add a way to "Sign up for Braintree Credit Card Processing" from within our Braintree settings tab.  We can build the process of signing up through the partner API into this.

Once they've signed up we should be able to have them grab their credentials and plug them in themselves just like they would now.  No need for hosted credentials or any of that.

Does that all make sense?

**Comment by kcppdevelopers** [comment]
I am little bit confused here, Can you please review changes what we have done right now?

**Comment by angelleye** [comment]
Were you already done with what you did?  Officially ready for review anyway?

**Comment by kcppdevelopers** [comment]
I have already applied changes as per partner API originally said, but for now I have used woo login URL.

if we add a way to "Sign up for Braintree Credit Card Processing" from within our Braintree settings tab using signing up through the partner API then we need $clientId and $clientSecret from developer account right?

**Comment by angelleye** [comment]
I'm going to push this to future release.
