### ISSUE TITLE
Hook to set CUSTOM parameter in PayPal API requests.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#431]
I have gotten requests in the past for a way to set the CUSTOM parameter in the DoDirectPayment and DoExpressCheckoutPayment APIs calls so that people can include their own data if necessary. 

I don't remember if we have a hook place that will allow somebody to do this..??  If so, please point it out to me.  If not, we need to go ahead and build that in.  

So people need the ability to calculate their own value, whatever they want it to be, and then push that value into the CUSTOM parameter of DoExpressCheckoutPayment and/or DoDirectPayment.

Need to follow up with **Robert Brooks** from email inbox once this is completed.

**Comment by kcppdevelopers** [comment]
I have added hook for CUSTOM parameter in PayPal API requests, below are hook for CUSTOM parameter.

- DoExpressCheckoutPayment -> ae_ppec_custom_parameter

- DoDirectPayment -> ae_ppddp_custom_parameter

**Comment by kcppdevelopers** [comment]
code sample: http://codepaste.net/xpkn78

**Comment by angelleye** [comment]
For PayFlow we should be able to do this using the COMMENT1 paramter.  Let's go ahead and add that, too, please.

**Comment by angelleye** [comment]
@kcppdevelopers The codepaste link above has expired.  Can you provide a sample directly in here so it doesn't expire please?
