### ISSUE TITLE
PayPal Plus Invoice ID Commented Out..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#433]
User reports that invoice ID is not getting sent to PayPal:  https://www.angelleye.com/support/scp/tickets.php?id=418

Upon review of our code, I can see we commented this line out for some reason..??  (https://github.com/angelleye/paypal-woocommerce/blob/master/classes/wc-gateway-paypal-plus-angelleye.php#L446)

Is there some particular reason we did that, and can we add it back?  

The user is trying to use IPN to update the WooCommerce order status automatically, but without the Invoice ID that is not working.

**Comment by kcppdevelopers** [comment]
I have check PayPal Plus code and found that we have already added invoice ID code. please check below URL:

https://github.com/angelleye/paypal-woocommerce/blob/release/classes/wc-gateway-paypal-plus-angelleye.php#L551
https://github.com/angelleye/paypal-woocommerce/blob/release/classes/wc-gateway-paypal-plus-angelleye.php#L555

![invoice](https://cloud.githubusercontent.com/assets/13145461/14010039/94675b7c-f1b7-11e5-91e7-0c2b78f451c1.png)

**Comment by kcppdevelopers** [comment]
Above screenshot is displaying Invoice number.

**Comment by kcppdevelopers** [comment]
Issue #400
