### ISSUE TITLE
Express Checkout - Checkout Page Custom Button

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#435]
User is requesting that they be able to set a custom button for the button that shows up on the checkout page.  

Apparently, right now our custom button only works for the product details page and cart page.

More details here:  https://www.angelleye.com/support/scp/tickets.php?id=441

**Comment by kcppdevelopers** [comment]
I have check and found that custom button also work on checkout page, please check screenshot for more information.


![checkout_page](https://cloud.githubusercontent.com/assets/13145461/14043537/5597090c-f2ab-11e5-815b-e2cb3c0eec0e.png)
 
Not sure, you are talking about payment gateway icon? 

![express_checkout_checkout_icon](https://cloud.githubusercontent.com/assets/13145461/14043569/c452ca8e-f2ab-11e5-9e88-45f8ee25f60f.png)

**Comment by angelleye** [comment]
The PayPal graphic there.  Looks like you have PayPal Standard enabled, and then also our Express Checkout.  When the user sets a custom button for EC in our plugin settings, it's not using that button here.  It's just using this same thing you have shown.

Would be good to include this as a separate option from the current one, so people can set their own custom button for product and cart pages (which is what currently works) and then they would have a different setting for using a custom image on the checkout page.
