### ISSUE TITLE
PayPal Plus redirects to checkout page

### ISSUE THREAD

**Issue by BatenkovT** [angelleye/paypal-woocommerce#436]
After "order submit" it just redirects me to the checkout page, not to PayPal. Prompt me, what's the problem? 
Works with enabled PayPal sandbox only.

![paypal](https://cloud.githubusercontent.com/assets/10506522/14016371/856f968c-f1c8-11e5-8867-8577f5f14b57.png)

Thx

**Comment by angelleye** [comment]
I'm a little confused.  You're saying this works fine in the sandbox but not when you switch to live..??

**Comment by BatenkovT** [comment]
Sorry for your time... The problem was in my theme, because I enqueued jQuery with 'true' last argument (in footer), so your plugin didn't see it.
Now everything works fine:) but I always try to connect all the JavaScript in the footer.
Thank you for your quick responses!

**Comment by Rohitsaini000** [comment]
After "order submit" it just redirects me to the checkout page, not to PayPal. Prompt me, what's the problem?

**Comment by angelleye** [comment]
@Rohitsaini000 Are you using our PayPal Plus plugin specifically?  If so, please [submit a ticket to our help desk](https://www.angelleye.com/support) and we'll get you taken care of.  This repo is not for the PayPal Plus plugin specifically.

**Comment by Rohitsaini000** [comment]
how can i submit a ticket 
Is this issue

**Comment by Rohitsaini000** [comment]
okay i submited

**Comment by Rohitsaini000** [comment]
sorry but the problem only with guest user

**Comment by Rohitsaini000** [comment]
there ?

**Comment by angelleye** [comment]
We will get back to you through the help desk.  Thanks.
