### ISSUE TITLE
PayPal Plus for Mexico / Brazil

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#439]
We currently have PayPal Plus for Germany.  Need to add it for Mexico / Brazil.

Preston Alexander from PayPal provided a class file for this that he already has working for some live users in Mexico.  When we get to this I can find more details and provide the class.  Just need to find Preston's email in my inbox.

**Comment by johnhenderson** [comment]
Hi @angelleye, do you have some updates for this feature request? I need PayPal Plus integration here in Brazil.

**Comment by angelleye** [comment]
We haven't had a chance to focus on this yet.  I need to check with PayPal about a few things, and then I may end up building PayPal Plus into a separate plugin altogether.  It'll probably be a couple of months before it's ready.  Sorry I don't have better immediate news.
