### ISSUE TITLE
Adjust digital goods order status update.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#440]
User reports an adjustment in logic is necessary:  https://www.angelleye.com/support/scp/tickets.php?id=452

**Comment by kcppdevelopers** [comment]
We already done with Seller Protection: https://github.com/angelleye/paypal-woocommerce/pull/429/commits in dev branch.

**Comment by angelleye** [comment]
I think we may still need to make an adjustment here, though.  For example, the way things are right now, it seems that even on my site when I sell a digital item with Express Checkout, if an e-check was used and the payment is Pending, the user would still get their digital goods right away because the order would be considered "Completed" when it's really not.

**Comment by kcppdevelopers** [comment]
Yes right, eChecks are not instant, they basically function same as paper checks and can take 7 to 10 days to clear. I think we should add PayPal IPN to changed payment status after check is clear.

**Comment by angelleye** [comment]
Yes, exactly.  When this comes up we'll recommend that people use our IPN plugin to add that functionality.  

What we need to do here, though, is just make sure that a pending payment is not treated as completed in WooCommerce.  We should be able to add the payment status as one of the variables getting checked in that logic.
