### ISSUE TITLE
PayPal Plus - Currency Issue..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#446]
User report:  https://wordpress.org/support/topic/missing-the-order-number-on-paypal-confirmation-email-when-using-paypal-plus?replies=6#post-8279709

I had them update to the release branch because the order ID wasn't getting passed in PayPal Plus orders.  He says when he updated, though, he's getting the message that it's not compatible with his currency even though he's set to EUR..??

Need to double check and make sure we aren't going to cause problems for people already using Plus.

**Comment by kcppdevelopers** [comment]
I have double checked PayPal Plus is working fine, notice is from PayPal Advanced.

**Comment by angelleye** [comment]
So did we fix any notices from PayPal Advanced that were showing up under PayPal Plus then?

**Comment by kcppdevelopers** [comment]
Yes, we fixed this issue on #449
