### ISSUE TITLE
PayPal Advanced - Error / Notice displaying under PayPal Plus..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#449]
User report:  https://wordpress.org/support/topic/missing-the-order-number-on-paypal-confirmation-email-when-using-paypal-plus?replies=14#post-8296828

He provided some screenshots which seems to show that PayPal Advanced notices / messages are showing up under PayPal Plus settings screen..??

**Comment by kcppdevelopers** [comment]
No, That PayPal Advanced notices / messages are showing up under checkout tab of WooCommerce.
