### ISSUE TITLE
PayPal Plus sandbox setting affecting PayFlow transactions..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#456]
I have a user reporting that they have having problems getting PayFlow to work.  They keep getting errors about invalid merchant data even though everything was correct.

He says that he went into PayPal Plus, and it was not enabled, but the Sandbox option was enabled for it.  He says that he unchecked the sandbox option for PayPal Plus, and then his PayFlow transactions started working as expected.

I think there's a chance he was just doing something incorrect and isn't passing the details to me correctly, but we need to check and make sure there is no conflict with PayPal Plus sandbox setting and other gateways.

**Comment by kcppdevelopers** [comment]
I have checked and make sure there is no conflict with PayPal Plus sandbox setting and other gateways.
