### ISSUE TITLE
Authorization / Order Capturing

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#462]
In #36 we added functionality so people can capture authorizations / orders directly within WooCommerce.  There are a couple of things we need to address with this.

1)  I noticed that our description in the settings doesn't say anything about Order, and it still says that the person would need to capture through the PayPal account.  With this update that should no longer be necessary, so we need to adjust this description / tooltip.

![image](https://cloud.githubusercontent.com/assets/629241/15162402/54698eba-16c8-11e6-8dcd-57019481851a.png)

2)  I still need to test this myself, but I want to make sure that people can do multiple captures against a  single order.  For example, if they choose Order in the settings and the order comes through at $100, they should be able to do a capture of, for example, $50, and then another capture of $25, and then another at $25.  Or they could do $50 and $50, or whatever.

We need to make sure this ability exists and it doesn't just capture the full amount.

**Comment by angelleye** [comment]
I just ran a test Order, and then when I view the order screen all I see for capturing or voiding is...

![image](https://cloud.githubusercontent.com/assets/629241/15162520/f242d6b4-16c8-11e6-9a36-2defbe80523f.png)

We need to adjust those lables so they say "Capture Authorization", "Void Authorization" instead of the actual API call  names.

Also, does DoAuthorization need to be here as an option at all?

**Comment by angelleye** [comment]
What I'm seeing is that there is indeed simply an option to capture the full order.  We need to add the ability to run multiple captures against a single order.  In fact, I think we need to make sure of DoAuthorization and DoCapture with an order.

Here is a good document on how the process should work:  https://developer.paypal.com/docs/classic/express-checkout/ht_ec-orderAuthPayment-curl-etc/

So what I think we need is to move those actions out of that drop down and make buttons for them.

For example, if an "order" is placed, then that order in WooCommerce would have a section where you can enter the amount you'd like to go ahead and authorize/capture against that order, and do so, but then leave the remaining order balance available for future capture if necessary.  That's the document above outlines.

If the original order is submitted as an "authorization" then there would only be a single capture, but the seller should still be able to enter the amount they want to capture in case they aren't capturing the full order amount.  For example, somebody might place an order for two items, but the seller can only fulfill one item.  In this case the original order might have been for $100, but the seller would only capture $25 or whatever the item price is for what they have available.

Again, though, I think this functionality needs to be moved outside of that drop down box because it's more than a single step.

**Comment by elharony** [comment]
Hey @angelleye,

Is there a way to keep it `Authorize` for orders > $15 for example, and if the order amount is less than $15 - `Capture` automatically the money? So, I need small orders to get processed without auth, and larger orders stay pending until I approve them.

Thanks!

**Comment by angelleye** [comment]
@elharony I'm sorry for the delay replying.  My GitHub notices were getting filtered away in my inbox and I just now realized I wasn't seeing some stuff.  I didn't mean to leave you hanging!

Yes, we could certainly do that sort of thing, but it would require some customization.  

Please submit a ticket at https://angelleye.com/support for a feature request, and I can work with you more directly on that.  Thanks!
