### ISSUE TITLE
PayPal Plus Coupon (100%) can't process cart with value 0

### ISSUE THREAD

**Issue by lucasjahn** [angelleye/paypal-woocommerce#465]
Hey there,

I just had to create coupon codes for user testings with a value of 100% (including shipping costs). But if I want to use the coupon code in the order itself I get the following error in the log:

`{"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].amount","issue":"Amount cannot be zero"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/#VALIDATION_ERROR","debug_id":"40a7cc4a1f3d7"}`

It seems like this error comes from PayPal directly, so it maybe needs a switch to not call to PayPal if the order value is 0? Anyway I cant process any orders.

Someone else has maybe a issue or solution for this?

BG

Luc

**Comment by angelleye** [comment]
So you are applying a coupon that makes the order total $0?  So it's essentially a free order?

**Comment by lucasjahn** [comment]
Yes excatly. So I think it should bypass the paypal plus in this case? I was not sure if maybe another one had this problem.

**Comment by angelleye** [comment]
We'll get this resolved in the 1.2.1 update which will be a quick follow up after we get 1.2.0 released.

**Comment by angelleye** [comment]
Here's another user reporting the same issue:  https://wordpress.org/support/topic/error-processing-checkout-please-try-again-1?replies=1#post-8434470

**Comment by angelleye** [comment]
Another user reporting the same:  https://wordpress.org/support/topic/using-plugin-with-free-coupon?replies=2#post-8442656

**Comment by klsdfr** [comment]
I have the same issue. Can't reach the checkout with a cart value of 0

**Comment by angelleye** [comment]
Yes, this is a known issue that we'll get resolved as soon as we can.

**Comment by kcppdevelopers** [comment]
I have already resolved this issue in issue #442
