### ISSUE TITLE
Credit Card Gateways - Adjust CC number field for better mobile experience.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#466]
User feature request:  https://wordpress.org/support/topic/feature-suggestion-70?replies=2#post-8401819

I'm pretty sure that should just be a matter of setting the correct field type or adding an additional attribute maybe..??

**Comment by kcppdevelopers** [comment]
We are using woo default credit card form.

https://github.com/woothemes/woocommerce/issues/7827

**Comment by kcppdevelopers** [comment]
We have already resolved this issue #585 

![issue-462](https://cloud.githubusercontent.com/assets/13145461/21009055/a388d20a-bd6a-11e6-8cfa-370819cf98c1.png)
