### ISSUE TITLE
Avoid fatal error when use PSR 4 loading through ClassLoader

### ISSUE THREAD

**Issue by lgnap** [angelleye/paypal-woocommerce#468]
Hello,

The class loader integrated into code is a old version and support only PSR-0 and doesn't support PSR-4.
Indeed the ClassLoader (retrieved from composer) is now supporting PSR-4 loading and the version provided with this package not.

This is blocking PSR-4 loading with the following Fatal
> Fatal error: Call to undefined method  Composer\Autoload\ClassLoader::setPsr4()

In PHP, it's impossible to exchange a already loaded class with a newest version.

I 'll update the file and will do a merge request when I have this ticket id.

**Comment by angelleye** [comment]
Thanks, we'll get this tied into the 1.2.0 update that we'll be releasing soon.  Appreciate the help!

**Comment by shippingmanager** [comment]
Hi Angelleye,

When will be the version 1.2.0 available ? We definitely need the fix ASAP because some clients have the issue and we 're dependent on you. We do really hope to get it for this week.

Thanks for your understanding ;)

**Comment by angelleye** [comment]
@shippingmanager The fix has already been merged into our release branch.  We'll be releasing it soon, but if you want to grab it early you can [download it here](https://github.com/angelleye/paypal-woocommerce/archive/release.zip).
