### ISSUE TITLE
Express Checkout - Skip Review vs. Terms and Conditions

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#471]
As it stands now we have an option for "skip review", but if you have a terms and conditions page set in WooCommerce then this overrides the skip review and displays that review page anyway so that the user is forced to accept the terms.

We have some user feedback (https://wordpress.org/support/topic/skip-final-review-option-enabled-in-express-checkout-but-not-working?replies=3#post-8450341) where they require terms and conditions for other payment methods, but they don't want it enabled for Express Checkout, and they would rather skip details.

We should go ahead and add an option into the Express Checkout settings to allow for people to set this up however they want.

For example, if they check the box to enable the skip payment options we could have some ajax check to see if they have a terms and conditions page enabled.  If they do, we could display a message that it would override and force the review page anyway, but then we can provide the option there to disable T&C for Express Checkout only so that the review page could indeed be skipped.

**Comment by angelleye** [comment]
@kcppdevelopers I'm getting a small merge conflict on this one as well.  Please take a look and merge into dev for me.

**Comment by kcppdevelopers** [comment]
I have merged into dev branch.
