### ISSUE TITLE
 Call to undefined method InvalidArgumentException::getData()

### ISSUE THREAD

**Issue by scrobbleme** [angelleye/paypal-woocommerce#472]
`Got error 'PHP message: PHP Fatal error:  Call to undefined method InvalidArgumentException::getData() in .../paypal-for-woocommerce/classes/wc-gateway-paypal-plus-angelleye.php on line 556`

The problem there is, that you catch generic exceptions, but the getData is only defined on PayPalConnectionException.

Maybe getMessage would be better in this case.

**Comment by angelleye** [comment]
@scrobbleme Thanks for the feedback!

@kcppdevelopers You agree with this?  If so, please go ahead and take care of it.

**Comment by kcppdevelopers** [comment]
Yes I am agree with this.
