### ISSUE TITLE
PayPal Plus not working on "Pay" checkout endpoint

### ISSUE THREAD

**Issue by scrobbleme** [angelleye/paypal-woocommerce#473]
WooCommerce has the ability to send users directly to a payment page, without cart or anything else. I.e. we use this for quotes, where the user shouldn't be able to edit the cart anymore.

The problem is, that PayPal Plus is not working on this page. It seems the needed Javascript/iFrame is not loaded.

**Normal Checkout through cart**

![2016-06-10 10_29_17-checkout _ woocommerce demo](https://cloud.githubusercontent.com/assets/504835/15958585/c387877a-2ef6-11e6-9dfe-bf5eee4ae10b.png)

**Pay checkout endpoint**
![2016-06-10 10_28_50-checkout _ woocommerce demo opera](https://cloud.githubusercontent.com/assets/504835/15958591/ce306dea-2ef6-11e6-9619-67acd26a9458.png)

![image](https://cloud.githubusercontent.com/assets/504835/15958657/35b5f4bc-2ef7-11e6-901e-6652a18d1d85.png)

**Partial Stacktrace**

```
object(InvalidArgumentException)#1292 (7) {
  ["message":protected]=>
  string(17) "Id cannot be null"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(140) "/PATH_TO_FILES/wp-content/plugins/paypal-for-woocommerce/classes/lib/PayPal/Validation/ArgumentValidator.php"
  ["line":protected]=>
  int(25)
  ["trace":"Exception":private]=>
  array(29) {
    [0]=>
    array(6) {
      ["file"]=>
      string(123) "/PATH_TO_FILES/wp-content/plugins/paypal-for-woocommerce/classes/lib/PayPal/Api/Payment.php"
      ["line"]=>
      int(462)
      ["function"]=>
      string(8) "validate"
      ["class"]=>
      string(35) "PayPal\Validation\ArgumentValidator"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(2) {
        [0]=>
        NULL
        [1]=>
        string(2) "Id"
      }
    }
    [1]=>
    array(6) {
      ["file"]=>
      string(133) "/PATH_TO_FILES/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-plus-angelleye.php"
      ["line"]=>
      int(518)
      ["function"]=>
      string(6) "update"
      ["class"]=>
      string(18) "PayPal\Api\Payment"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(2) {
        [0]=>
        object(PayPal\Api\PatchRequest)#1284 (1) {
          ["_propMap":"PayPal\Common\PayPalModel":private]=>
          array(1) {
            ["patches"]=>
            array(1) {
              [0]=>
              object(PayPal\Api\Patch)#1287 (1) {
                ["_propMap":"PayPal\Common\PayPalModel":private]=>
                array(3) {
                  ["op"]=>
                  string(7) "replace"
                  ["path"]=>
                  string(22) "/transactions/0/amount"
                  ["value"]=>
                  object(stdClass)#1286 (3) {
                    ["total"]=>
                    string(7) "5609.90"
                    ["currency"]=>
                    string(3) "EUR"
                    ["details"]=>
                    object(stdClass)#1285 (3) {
                      ["subtotal"]=>
                      string(7) "4500.00"
                      ["shipping"]=>
                      string(1) "0"
                      ["tax"]=>
                      string(7) "1109.90"
                    }
                  }
                }
              }
            }
          }
```

**Comment by angelleye** [comment]
Thanks for the feedback.  We're probably going to be moving PayPal Plus out to its own separate plugin, so we'll definitely get this resolved and ready to go in a stable 1.0.0 of that plugin.

It's probably going to be a couple of months before we're able to focus on that, though, unfortunately.  I'm sorry I don't have better immediate news for you on that.

**Comment by kcppdevelopers** [comment]
PayPal Plus is working fine on "Pay" checkout endpoint.

http://screencast.com/t/4kVmheoI7c

**Comment by scrobbleme** [comment]
@kcppdevelopers This doesn't look like the pay endpoint. This just looks like the normal checkout after going from the cart to pay.

See https://docs.woothemes.com/document/woocommerce-endpoints-2-1/ -> "Pay page" for more information. This is a special page where you can only pay and not edit anything else.

**Comment by angelleye** [comment]
Reopening for further review...

**Comment by scrobbleme** [comment]
Why is this closed?

**Comment by angelleye** [comment]
Because we are making all of these adjustments in the separate plugin that we are building for PayPal Plus and closing them here as we move them into the separate repo and get them resolved there.

The new plugin should be ready in a couple of weeks.

**Comment by scrobbleme** [comment]
Ah, thanks for clarification. (If not obviously there should always be a short note, why an issue was closed).
