### ISSUE TITLE
PayPal Express conflict with Woothemes WooCommerce Product Add-ons

### ISSUE THREAD

**Issue by Automated1** [angelleye/paypal-woocommerce#477]
Everything works fine right the way through selecting item, shopping basket, logging into PayPal and then you are returned to the website to the review order page as expected, however when you accept terms and click place order an error page appears instead of the order received page and it looks as if payment and order have been unsuccessful when in fact they have gone through fine. If you checkout using card payment (we use Sagepay) then everything works as expected).. I have reported the problem to Woothemes too but thought I would report it here as error is only in relation to final step of PayPal process. Error text that appears on the site is attached.
[addon errors.txt](https://github.com/angelleye/paypal-woocommerce/files/320331/addon.errors.txt)

**Comment by angelleye** [comment]
Ok, we'll look into this and get any necessary adjustments made in the next update.  Thanks for the feedback!

**Comment by kcppdevelopers** [comment]
I have checked above issue now it seems working fine for me. This warning from woocommerce product addons plugin, Now latest version has been resolved this issue.

**Comment by angelleye** [comment]
@Automated1 Did you see the info @kcppdevelopers provided here about their plugin?
