### ISSUE TITLE
1.2.0 Update Breaks WooCommerce Settings Panel..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#478]
User report:  https://wordpress.org/support/topic/version-120-breaks-woocomerce-settings-page?replies=4#post-8538898

**Comment by angelleye** [comment]
Another user report providing some more detail that looks like it could be related to this:  https://wordpress.org/support/topic/upgrade-to-woocommerce-261-causing-paypal-express-error-in-settings?replies=1#post-8538305

**Comment by kcppdevelopers** [comment]
PayPal Plus and PayPal Credit Card (REST) requires PHP 5.3 or above and it looks like this error is caused by not having at least 5.3.
