### ISSUE TITLE
Strip PayPal Plus

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#481]
We need to strip PayPal Plus out of this plugin since we're moving it to its own separate plugin.

We can keep the tab here for people that are expecting to find it, but within that tab we'll explain that it's been moved and just link to the PayPal Plus product page on angelleye.com

**Comment by logtainment** [comment]
Do you have a Beta Plugin of this Standalone version?

**Comment by angelleye** [comment]
Not quite ready, but it will be soon.

**Comment by kcppdevelopers** [comment]
@angelleye  you can write something about how we've moved it to its own plugin and provide a link / button to go to the product page. 

Write text [here](https://github.com/angelleye/paypal-woocommerce/blob/release/template/admin.php#L56)

**Comment by angelleye** [comment]
This isn't merged into dev/release yet, so I'm reopening it.
