### ISSUE TITLE
PayPal Advanced - User reported bug.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#484]
User report:  https://wordpress.org/support/topic/paypal-advanced-whatever-button-double-charge?replies=2#post-8547100

**Comment by kcppdevelopers** [comment]
For me it's working fine http://screencast.com/t/yk6O6LipVAWx

**Comment by angelleye** [comment]
Do you have any idea where the "whatever" value is coming from that he's showing in his screenshot?

**Comment by kcppdevelopers** [comment]
Yes, I found that.  

First login to https://manager.paypal.com website then navigate to navigate to Service Settings -> Set Up

http://screencast.com/t/FkTqz9DUWDsA

**Comment by angelleye** [comment]
User was able to get this worked out in their PayPal manager layout settings.
