### ISSUE TITLE
Order / Auth / Capture

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#487]
I ran an order with a total of $42.69.  When I go to Authorize a payment against the order, though, it shows a message about making sure I enter an amount less than $49.09.  

Shouldn't those numbers match?  Why would it let me authorize 49.09 if the order total was 42.69?

![image](https://cloud.githubusercontent.com/assets/629241/16216199/a162bb9a-371d-11e6-85d6-ba680cd1ade2.png)

**Comment by angelleye** [comment]
Also, we need to make sure the new setting for Order / Auth / Sale in the plugin defaults to Sale even if the settings page has not fully been saved yet.  Seems that some people are having "orders" go through instead of "sale" when they never switched it to that.

**Comment by kcppdevelopers** [comment]
In Express Checkout Authorization user can capture less than the original authorization amount, the full amount, or up to 115% of or $75 more than the original authorization, whichever is less.

order total was 42.69,  user can capture 115% of 42.69 = 49.09

**Comment by angelleye** [comment]
Are we sure that's the same with an order, though?  Did you test that specifically?  I know that's true for original Authorizations, but with an order where Authorizations are happening against it I'm not sure that's true.

**Comment by kcppdevelopers** [comment]
Yes I am sure.

**Comment by kcppdevelopers** [comment]
I have already test this functionality and it's working fine for me.

**Comment by angelleye** [comment]
Ok, thanks for checking.

**Comment by angelleye** [comment]
Ah, well, I shouldn't close it yet because I had that other comment about the default setting.  Have you looked into that already?

**Comment by kcppdevelopers** [comment]
I have already applied changes in issue #486
