### ISSUE TITLE
Express Checkout - Order / Auth / Capture Problem..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#494]
User is reporting that they are able to run Order transactions through the plugin just fine, but then when attempting to capture they are getting "security header invalid" errors as if the API credentials were wrong.

The same credentials are working for the Order transaction, though, so we must be doing something wrong with the pulling of those credentials for the final capture..??

Here is the ticket the user posted with log details:  https://www.angelleye.com/support/scp/tickets.php?id=555

**Comment by kcppdevelopers** [comment]
I have checked above issue in my dev server, for me it's working fine.
