### ISSUE TITLE
Payments Pro PayFlow - Comment Fields

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#498]
PayFlow provides COMMENT1 and COMMENT2 parameters for passing custom data.  

Right now we are using COMMENT1 like this...

`'comment1'=> apply_filters( 'ae_pppf_custom_parameter', $customer_note , $order ),`

We are not doing anything with COMMENT2, though.

We have a [request to allow more flexibility with how these parameters are used](https://wordpress.org/support/topic/paypal-payments-pro-20-payflow-edit-comments-send-to-paypal?replies=1#post-8597188).

We need to add filters into both of these so people can put whatever they want in them.

**Comment by kcppdevelopers** [comment]
Here is example http://pastebin.com/8UnaetTi for comment1 and comment2.

**Comment by angelleye** [comment]
Hook names are `ae_pppf_comment1_parameter` and `ae_pppf_comment2_parameter`
