### ISSUE TITLE
PayPal Plus - Payment Method PayPal

### ISSUE THREAD

**Issue by logtainment** [angelleye/paypal-woocommerce#505]
Hey,
when I use PayPal as Payment Method it redirects me to the PayPal WebApps Hermes site. There I must click to go to to the PayPal Account Payment. Can I fix this?
![paypal](https://cloud.githubusercontent.com/assets/10811118/16775084/47c7d4b4-485f-11e6-818a-0b9e27a41712.PNG)

**Comment by angelleye** [comment]
I'm not sure what you're trying to show me here.  Can you do a quick video demo maybe..??

**Comment by logtainment** [comment]
If I use the PayPal method i land on the Site for Creditcard or Direct Debit. Not directly on the PayPal login

**Comment by angelleye** [comment]
Ok, but you mentioned PayPal Plus and the screenshot and what you're explaining sounds like Express Checkout.  So what is it that you're using?

**Comment by logtainment** [comment]
PayPal Plus. I'll make a video.

**Comment by logtainment** [comment]
https://youtu.be/4Eq5eDJAqLo

**Comment by logtainment** [comment]
And Now?

**Comment by angelleye** [comment]
@kcppdevelopers Please take a look at this and make sure we've resolved this in our new version.

@logtainment We are just about to release a separate plugin for PayPal Plus that resolves all of the issues people have reported from using it in our current plugin.

Keep your eye out for the updates which should be coming soon.

**Comment by nicib83** [comment]
@angelleye 
will the new paypal plus plugin be situated in a new repository ?

**Comment by logtainment** [comment]
Did you know a date where the Plugin gets Published? @angelleye

**Comment by angelleye** [comment]
The new plugin is done except that I'm doing final review and simple adjustments.  Also putting together the readme files, documentation, etc.  I'm hoping to have it officially released within the week.

The repo for the new plugin will be private because it's going to be a paid plugin.  

Unfortunately, I have no other choice but to do that because PayPal is not supporting me with PayPal Plus the way they are the other PayPal products.  This will allow us to dedicate resources to it so that we can maintain it and support it properly.

We're working hard to get it done ASAP.  Stay tuned.

**Comment by nicib83** [comment]
@angelleye 
so you would generally recommend not to use the free version of this plugin, since there won't be any further maintenance ?

do you have an estimate for the price already ?

**Comment by angelleye** [comment]
Yes, we'll be stripping PayPal Plus out of the current PayPal for WooCommerce plugin and moving it to its own paid plugin.

I am not sure what I'm going do with the price yet, but whatever I price it at, I will provide some sort of a discount code for people that have been using it here.

**Comment by logtainment** [comment]
@angelleye Would be the Price over 100€?

**Comment by angelleye** [comment]
It may end up being right around that price, actually.  

The only other option I'm seeing for Plus right now has a price tag of $220.  We're going to start with a lower price than that, and again, we will provide a coupon code for PayPal for WooCommerce users, too.
