### ISSUE TITLE
Applied in Core PHP

### ISSUE THREAD

**Issue by pulkitintech** [angelleye/paypal-woocommerce#509]
Hello Sir,
  Greetings of the Day!

i am implement you woocommerce plugin paypal plus coding in my core php site, but when its redirected to paypal for payment then its says "You are inactive for a while, we automatic logout.."
can you help me for this problem

Thanks in Advance
Pulkit

**Comment by angelleye** [comment]
Hi Pulkit,

We are actually working to get a 1.0.0 released of a new, separate plugin we're building for PayPal Plus.  We're very nearly done with it, and we've addressed all the issues that have been reported from the people that have been using what we currently have built in as beta with the PayPal for WooCommerce plugin.

Within just another week or two we'll be releasing that.  You'll see an update to PayPal for WooCommerce, and within that you'll see information about obtaining the new PayPal Plus plugin.

It would be best to just wait until we release that, and then if you continue to run into problems we can help you more directly then.

**Comment by angelleye** [comment]
PayPal Plus is now available separately: https://www.angelleye.com/product/woocommerce-paypal-plus-plugin/
