### ISSUE TITLE
Paypal Plus "replacing" all other payment methods

### ISSUE THREAD

**Issue by danielvonmitschke** [angelleye/paypal-woocommerce#512]
If I enable the Paypal Plus gateway it replaces all payment options (also the non paypal related) with an iframe and makes the checkout unusable.
Please see attached screenshots.

Before activating Paypal Plus:
![bildschirmfoto 2016-07-19 um 12 49 34](https://cloud.githubusercontent.com/assets/1579746/16947437/51d67208-4daf-11e6-9ad8-05049aef7924.png)

After activating Paypal Plus:
![bildschirmfoto 2016-07-19 um 12 47 48](https://cloud.githubusercontent.com/assets/1579746/16947388/1123da84-4daf-11e6-8a90-36feb0f68e8c.png)

**Comment by logtainment** [comment]
Hey,
benutze doch Kreditkarte über PayPal? 
Use CreditCard with PayPal instead of Stripe

**Comment by danielvonmitschke** [comment]
hi, we got better transaction fees with stripe. 
and this also doesn't solve the problem of using other payment methods like bacs, cash in delivery, sofortüberweisung...

**Comment by angelleye** [comment]
We are just about to release a separate plugin for PayPal Plus that will make adjustments to resolve this for the people having the issue, and it also resolves everything we've had reported from people using this beta for a little while now.

When you see the PayPal for WooCommerce 1.2.4 update you'll find details about obtaining our new PayPal Plus plugin.  We're splitting it away from this one so we can focus on the different features and functionality it requires for the different countries it supports.

Keep your eye out for that in the next week or two.

@danielvonmitschke I highly doubt that you're getting lower rates with Stripe.  Both Stripe and PayPal start at 2.9% + .30, but PayPal will take you as low as 1.9% depending on the volume you're processing.  I've never seen a Stripe account that low.  Stripe also makes you wait a week for your money.  

Stripe is simple, and that's what people like.  It's nothing more than a credit card account and a quick snippet of code to process your credit cards.  There is value there, but the actual rates are not cheaper, and in fact usually the opposite.

That said, PayPal provides EXACTLY the same thing Stripe does with their REST API direct credit card processing feature.  PayPal's problem is that they bury that inside all their other stuff like PayPal Standard, Payments Pro, Adaptive Payments, Express Checkout, PayPal Plus, PayPal Advanced, etc. 

Stripe just has the one thing, so it's a lot easier for people who aren't familiar with PayPal's system or willing to dig and find what you're after.

Just my two cents.  :)

**Comment by angelleye** [comment]
Just to clarify, though, our separate PayPal Plus plugin will fix this by adding the iFrame in addition to the WC gateways instead of replacing it and injecting them into the iframe (which is the recommended way by PayPal, but just doesn't work well in reality with WC).

So if you want to stick with Stripe that will be just fine, and will work just fine with the 1.0.0 release of our new plugin.

The interesting thing is that this only seems to happen to some people.  Others are able to use all the gateways they have enabled (injected into the PayPal Plus iframe) just fine.

Must be theme/plugin conflicts, but rather than bang our heads against the wall over that we just added the iframe in addition to the others.

**Comment by danielvonmitschke** [comment]
@angelleye thanks andrew. the dedicated paypal plus plugin sound great and seems to be exactly what we are looking for. looking forward to it. :)

about the stripe rates:
at least in Europe you only pay 1.4% (+25ct) for transactions. and these are the non-negotiated standard rates: https://stripe.com/de/pricing .

best,

daniel

**Comment by angelleye** [comment]
Ah, cool, didn't know that about the rates in Europe.  Good to know.  

We're looking to get the new Plus plugin released within a week.  Stay tuned.
