### ISSUE TITLE
Braintree - Repeating PayPal Button

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#513]
PayPal rep (Will) reporting that one of their merchants is having an issue with Braintree where the PayPal button is getting displayed multiple times.

![image](https://cloud.githubusercontent.com/assets/629241/16967844/d523bf3c-4dd0-11e6-94b7-3a0caa3d8ab2.png)

I said that it looked like a theme issue repeating our image, but they installed another Braintree plugin and it's not happening.

**Comment by kcppdevelopers** [comment]
It seems user not using our plugin, Can you please confirm with user ? above screenshot is not our plugin interface.

**Comment by angelleye** [comment]
Yeah, it does seem that way.  I've asked them about this.  Closing for now.
