### ISSUE TITLE
Payment gateways are not following sort order set in WC settings..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#518]
User (Chris Anson) reporting via email:

>I am using your PayPal for WooCommerce plugin on my website and would like to make it the default choice for checkout. I also have the Offline Credit Cards For WooCommerce plugin. I have your plugin first in the list in Woocommerce, but what happens is show below. 

>How do I get your payment option to be selected (radio button active) so that users will see this as the suggested first option?

>
![image](https://cloud.githubusercontent.com/assets/629241/17122244/7089f36a-529f-11e6-84a5-5d4aa00cbfdd.png)

**Comment by kcppdevelopers** [comment]
I have test above issue and it seems working fine for me.

Gateway Display Order Admin setting: http://screencast.com/t/lo2ssydI
Payment Gateway List: http://screencast.com/t/aPMl3Koeq
