### ISSUE TITLE
Express Checkout - Survey Question

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#52]
Express Checkout provides the ability to include a survey question on the PayPal pages during checkout. You can pass the question and the available answers into SetExpressCheckout and the customer response will come back in GetExpressCheckoutDetails.

We need to make this available to people as an option.  They could enable it, insert a question, and include multiple answers.  Need an easy way to do this from the settings panel.  

Then we'd pull the result from GEC and load it in the database so we could pull reports for the users later.  We can build a nice screen where they can manage their survey question and see percentages of people that filled it out, what the results were, etc.

**Comment by kcppdevelopers** [comment]
@angelleye survey question deprecated since Sept. 8, 2016

![52](https://user-images.githubusercontent.com/13145461/34295725-d77478ae-e734-11e7-8b12-a152268ff4ae.png)

**Comment by angelleye** [comment]
These fields have been deprecated.
