### ISSUE TITLE
Shipping Calculation Issue

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#522]
We've seen this quite a bit in the past where people get negative shipping amounts.  I think it's because of all the calculations we're doing in our attempts to avoid the cart total errors with PayPal.

This could be related to #516, and maybe you already fixed this there, but here's a simple example of when shipping is coming out negative:  https://www.angelleye.com/forum/discussion/comment/617#Comment_617

The subtotal is $21 and then shipping is $10 for a total of $31, but then they're adding a flat rate $25 discount.  For some reason this is causing the following to be sent to PayPal:

ITEMAMT=21
SHIPPINGAMT=-15.00
AMT = 6.00

So technically, it's correct, but PayPal isn't going to accept a negative shipping amount just like they won't accept a negative item amount.

What we may need to do is check for a negative shipping amount after we've done our calculations.  If we find a negative shipping amount, then we could actually zero out the shipping and then apply the rest of the discount to the itemamt.

So in this case if we follow that procedure we'd end up with:

ITEMAMT=6.00
SHIPPINGAMT=0.00
AMT = 6.00

There may be a better way to handle this, but we need to take care of this scenario one way or another.

**Comment by kcppdevelopers** [comment]
I have read this discussion https://www.angelleye.com/forum/discussion/comment/617#Comment_617

Now I am litlle bit confused about calculation, becuase when user applied coupon greter then Subtotal then woo simply reduce coupon amout make same amout as Subtotal.

Please see the scresnhot for more information:

![coupon25](https://cloud.githubusercontent.com/assets/13145461/17393580/31e2298e-5a42-11e6-8b84-a94d53709eff.png)

I have applied coupon code test25 with $25 amount but woo calculation reduce it and used same as Subtotal.

May be user have used other plugin for coupons?

**Comment by angelleye** [comment]
Hmmm...ok, I'll ask and update when I get more info.

**Comment by angelleye** [comment]
Actually, that wouldn't be right either, because now they're only getting $21 off instead of $25 that the coupon should be giving them..??

**Comment by angelleye** [comment]
Here's another guy having this problem and he mentioned the coupon plugin they're using:  https://www.angelleye.com/forum/discussion/comment/631

**Comment by angelleye** [comment]
Here is another person having this issue:  https://www.angelleye.com/support/scp/tickets.php?id=614

**Comment by kcppdevelopers** [comment]
I have install Smart Coupons plugin and try to reproduce the error and found that Smart Coupons plugin handles discount line item different way. Now our plugin are compatibility to Smart Coupons plugin.
