### ISSUE TITLE
PayPal Advanced - Conflict with WC checkout page..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#523]
I was about to start reviewing all of the 1.2.4 stuff when I discovered that my checkout page was not functioning properly.

It seemed like jQuery was not loading properly, and the gateway would not update when I switched to different options as well as a few other theme related jQuery problems on the page.

After disabling PayPal Advanced the problems went away, so it seems we have some sort of a conflict going on there.

**Comment by kcppdevelopers** [comment]
I have enabled PayPal Advanced method in woo dot angelleye dot come, but I am unable to reproduce above issue. It would be great if you provide screnshot for this issue.

**Comment by angelleye** [comment]
Well, yeah, seems to be working fine for me now.  Must have been a conflict with something that was cached and wasn't clearing for me or something.  I even ran it in incognito mode, though, so not sure why that would have been happening.
