### ISSUE TITLE
Express Checkout - Skip Final Review Problem

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#525]
As I've been reviewing 1.2.4 I've been running some tests.  I just now ran a test of Express Checkout after merging #492, but then when I was returned back from PayPal I didn't get sent to the return (review) URL, I just went back to the order completed page.

I was thinking I must have had the option to "skip final review" enabled, but when I went to check I noticed I did NOT have this enabled, so I'm not sure why it's getting skipped.

I don't know if the merge of #492 is what caused this or not, unfortunately.  I do know that when I merged #492 it brought in changes in 2 files (angelleye-utility.php and wc-gateway-paypal-express-angelleye.php) but the commit shown in that issue only has a single file changed.

Not sure if any of that is related, but we do need to figure out why my review page is getting skipped even though that option is not enabled.

**Comment by angelleye** [comment]
What's interesting about this, too, is that the button on the PayPal site says "Continue", which is what I expect when the skip options feature is disabled.  If it was enabled then the PayPal button would say "Pay".

But then somewhere within our return code it's kicking that back on and pushing me straight to the completed page without ever showing a review.

Not sure if we have some other setting I could have enabled that could be overriding..??  I can't think of anything that would be doing that...

**Comment by angelleye** [comment]
I'm running more tests and discovering some other weird things.

First, I ran a test using the EC button from a product page.  In this case everything worked as expected.  I was returned to the review page at the site, and then I was able to complete the order successfully.

For some reason when I checkout using EC through the WC checkout page, though, it's skipping the review page.  Also, I'm getting 10001 Internal Error back from PayPal on the final DECP request, but only when checking out from the checkout page.

If I checkout directly from the product page using EC I don't get the 10001 error on DECP.  I also don't get that error when I test from my regular PayPal library test bed, but it is consistently happening when I test through the WC checkout page.

So again, seemingly 2 problems from the WC checkout page using EC.  It does not return to the review page when it should, and the DECP is consistently failing with 10001 (but only from the WC checkout page).

**Comment by angelleye** [comment]
I went ahead and enabled the Skip Final Review option and ran another test from the WC checkout page using EC.

This time the button at PayPal says "Pay Now" as expected when that option is enabled, and it did skip straight to DECP, but again failed with 10001.

I know the 10001 happens randomly when PayPal's sandbox is missed up, but right now it's ONLY happening when I checkout from the WC checkout page using EC.

10001 can sometimes be caused by invalid parameters or data in the request, so I guess we need to look into that as well as why the review is getting skipped even when it's not enabled.

**Comment by kcppdevelopers** [comment]
I have reviewed above issue  it not related to #492. It seems having issues related to "skip final review" which I have resolved, but I am not able to reproduce 10001 error it myself.

**Comment by angelleye** [comment]
I closed this before testing it.  Unfortunately, upon testing my review page is still getting skipped even though I don't have that option enabled in the settings.

**Comment by kcppdevelopers** [comment]
I am  done with this issue and push to issue-525-A branch.
