### ISSUE TITLE
Info about PayPal Plus

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#526]
We still have a tab included under Settings -> PayPal for WooCommerce for PayPal Plus, and within that I am explaining that we have moved it to its own plugin.

Since it doesn't show up under WooCommerce -> Checkout settings anymore I'm afraid it's going to confuse some people.

We need to add some sort of a notification for people that were using PayPal Plus letting them know about the new one without forcing them to find the note from the settings page.

Is there a way that upon updating, the plugin can check to see if they had PayPal Plus enabled, and if so, display a general notice at the top of the admin panel?

**Comment by angelleye** [comment]
I will also need to add some information about this in the readme.txt file.

**Comment by kcppdevelopers** [comment]
http://screencast.com/t/S0Xbf1UP4
