### ISSUE TITLE
PayPal Plus "The requested experience profile ID was not found" issue

### ISSUE THREAD

**Issue by puresilk** [angelleye/paypal-woocommerce#529]
Hi,

we're trying to integrate PayPal Plus using the angelleye Plugin. 

I've disabled all other payment methods in the shop except Invoice (cheque), Bank transfer (bacs), and Cash on Delivery (Cash_on_delivery). 

I've entered the Sandbox data and the live data, the data was created using the PayPal Developer page (new REST API).

While the sandbox mode was active ( "Enable PayPal sandbox" checked), all payment methods showed up. However: if I selected the PayPal plus methods, the last page would inform me, that I placed an order using "Bank transfer" (bacs). 

Following the advice of the PayPal Plus Integration team, I have then switched to the normal mode (disabled "Enable PayPal sandbox" checkbox). 

"Billing Address" is set to non-checked (Set billing address in WooCommerce using the address returned by PayPal.)

Landing Page is set to "Login" 

see the attached files for other settings.

When I am on the /cart/ page (after adding the product to the cart), and click on "Weiter zur Kasse" (go to checkout), instead of continuing with the checkout process, WooCommerce displays an error message. "error processing checkout"

![image](https://cloud.githubusercontent.com/assets/4606111/17486103/dc21afaa-5d8f-11e6-9f72-3777d132042e.png)
This image shows the error which I see on the checkout. 

In the log, I can see the following error messages:

08-08-2016 @ 16:04:45 - {"name":"INVALID_EXPERIENCE_PROFILE_ID","message":"The requested experience profile ID was not found","information_link":"https://developer.paypal.com/docs/api/#INVALID_EXPERIENCE_PROFILE_ID","debug_id":"55ba540ef0862"}
08-08-2016 @ 16:05:27 - {"name":"INVALID_EXPERIENCE_PROFILE_ID","message":"The requested experience profile ID was not found","information_link":"https://developer.paypal.com/docs/api/#INVALID_EXPERIENCE_PROFILE_ID","debug_id":"eadd1140466c4"}
08-08-2016 @ 16:07:07 - {"name":"INVALID_EXPERIENCE_PROFILE_ID","message":"The requested experience profile ID was not found","information_link":"https://developer.paypal.com/docs/api/#INVALID_EXPERIENCE_PROFILE_ID","debug_id":"4bf3cd20c5605"}

PayPal Plus integration support asked me to get in touch with you about this error. It has been seen before by them, but they are not sure what the cause could be - apparently there is also nothing to be configured in the developer login. 

Thanks in advance for your help!

[PayPalPlusProblem.pdf](https://github.com/angelleye/paypal-woocommerce/files/409290/PayPalPlusProblem.pdf)

Configuration of WooCommerce:
[woocommerce-installation-pub.pdf](https://github.com/angelleye/paypal-woocommerce/files/409311/woocommerce-installation-pub.pdf)

**Comment by angelleye** [comment]
We are actually just about to release a new plugin for PayPal Plus separate from this plugin, and this issue has been resolved in it along with any others we've had reported from users of the beta here.

We're hoping to have it released within a week, so keep your eye out for that.
