### ISSUE TITLE
Missing second argument for woocommerce_checkout_order_processed

### ISSUE THREAD

**Issue by michaelbeil** [angelleye/paypal-woocommerce#530]
We noticed that the second argument on the `woocommerce_checkout_order_processed` action hook was missing, so we went ahead and added it on a customer's site. We use this hook in AffiliateWP, so it was causing a fatal on checkout since there was conflict between how we are using the hook and your plugin. 

Lines in question: 
- https://github.com/angelleye/paypal-woocommerce/blob/master/classes/wc-gateway-paypal-express-angelleye.php#L1119
- https://github.com/angelleye/paypal-woocommerce/blob/master/classes/wc-gateway-paypal-express-angelleye.php#L1375 

Should be `do_action( 'woocommerce_checkout_order_processed', $order_id, array() );`.

**Comment by angelleye** [comment]
Thanks!  We'll review and get it merged accordingly.

**Comment by michaelbeil** [comment]
Sounds good!

**Comment by kcppdevelopers** [comment]
issue #502

**Comment by michaelbeil** [comment]
Looks like it should be:

do_action( 'woocommerce_checkout_order_processed', $array );

**Comment by michaelbeil** [comment]
Well, what branch is the latest version of the plugin? I noticed master still has the second argument as array().

**Comment by angelleye** [comment]
The master branch is the currently released version, which as of now is 1.2.3.

The release branch is our default branch here and typically contains everything that has been completed and tested for the next update that we're working on.

The dev branch is where we work on that next update and resolve things.

**Comment by kcppdevelopers** [comment]
Look like it should be:

do_action( 'woocommerce_checkout_order_processed', $order_id, $this->posted );

**Comment by michaelbeil** [comment]
Oh, good catch. I noticed that the second argument was `$this->posted` in WooCommerce core, but was not familiar with your codebase, but glad this got resolved. 

Thanks all!
