### ISSUE TITLE
Braintree - PHP Fatal Error

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#533]
Our rep from PayPal is running into a PHP fatal error both with and without the drop-in UI enabled:

>PHP Fatal error:  Uncaught Error: Call to undefined method WC_Gateway_Braintree_AngellEYE::str_to_ascii() in /var/www/html/wp-content/plugins/paypal-woocommerce-release/classes/wc-gateway-braintree-angelleye.php:462
Stack trace:
#0 /var/www/html/wp-content/plugins/paypal-woocommerce-release/classes/wc-gateway-braintree-angelleye.php(404): WC_Gateway_Braintree_AngellEYE->str_truncate('4025559876', 14, '')
#1 /var/www/html/wp-content/plugins/paypal-woocommerce-release/classes/wc-gateway-braintree-angelleye.php(346): WC_Gateway_Braintree_AngellEYE->angelleye_do_payment(Object(WC_Order))
#2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(663): WC_Gateway_Braintree_AngellEYE->process_payment(11)
#3 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(472): WC_Checkout->process_checkout()
#4 /var/www/html/wp-includes/plugin.php(525): WC_AJAX::checkout('')
#5 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(82): do_action('wc_ajax_checkou...')
#6 /var/www/html/wp-i in /var/www/html/wp-content/plugins/paypal-woocommerce-release/classes/wc-gateway-braintree-angelleye.php on line 462, referer: http://woo-angelleye-3881.ccg21.dev.paypalcorp.com/index.php/checkout/

**Comment by kcppdevelopers** [comment]
I found issue, above PHP error only occur when php mbstring extension is not enabled.
