### ISSUE TITLE
PayPal Advanced - $0 subtotal with paid shipping failing.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#543]
Need to adjust PayPal Advanced request in cases where the subtotal is $0 but there is still shipping/tax/handling to be paid.  Right now we're ending up with the 10413 error in these cases...

>I’m using Paypal Advanced. When doing some testing I’m getting this error: “Field format error: 10413-The totals of the cart item amounts do not match order amounts.” I’m doing a free promotional giveaway where I offer a free product and the customer just pay shipping. I know Paypal doesn’t accept free $0 amount. Is there any way around this? I need this to work.

**Comment by kcppdevelopers** [comment]
I have checked and found that it's working for me http://screencast.com/t/OY5oKEZdgzuF

**Comment by angelleye** [comment]
I will get WP admin and cPanel credentials from the user where this is happening.

**Comment by angelleye** [comment]
I got credentials from the client so we can test directly on their site:  https://www.angelleye.com/support/scp/tickets.php?id=625

**Comment by kcppdevelopers** [comment]
I have test directly on their site, I am getting Error: "cURL error 6: Couldn't resolve host 'pilot-payflowpro.paypal.com'"

**Comment by angelleye** [comment]
Hmmm...that's odd.  He acts like everything works fine except for these $0 orders.

Are you able to get anything working on his site or is everything failing with this?  

Sounds like a DNS issue...

**Comment by kcppdevelopers** [comment]
I am not able to fully test  due to cURL error, it seems request parameter is ok. I will fully test after DNS issue resolved.
