### ISSUE TITLE
PayFlow - Line Item Details

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#547]
Seems that we are not including line item details with our PayFlow transactions.  I always thought we were, so this was a bit of surprise for me to see.

Need to get line item details added to PayFlow requests.

Of course, we'll want to add the option to "send line item details to PayPal" in the PayFlow settings like we've done elsewhere.

**Comment by kcppdevelopers** [comment]
It seems we already passing line item details in Payflow request. here is screenshot for more information: http://screencast.com/t/d03FAlnbHYiO

I have also checked request and response in Payflow log file.

**Comment by angelleye** [comment]
I see that we have the option there, but I don't see where in the code we're actually adding line items in the request..??

**Comment by angelleye** [comment]
Ah, nevermind, I do see them showing up in my log.
