### ISSUE TITLE
Gift Cards Pro Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#550]
https://www.angelleye.com/support/scp/tickets.php?id=639

**Comment by kcppdevelopers** [comment]
I have checked and found that there are lot of [error and notice](https://www.screencast.com/t/DsTDzgk8fPZ) in the Gift Cards Pro plugins. I have checked with Version: 1.3.0 of Gift Cards Pro plugins.

**Comment by angelleye** [comment]
So are you saying those errors/notices are keeping us from being able to make our plugin play nicely with it?  Typically errors/notices wouldn't display unless error reporting was enabled, so even with error reporting disabled you can't make this work?

**Comment by kcppdevelopers** [comment]
I have download Gift Cards Pro 1.3.0 from support ticket but 1.3.0 version not working well with woo latest version even disable error reporting. It would be great if we have latest version of Gift Cards Pro. Can you please ask for latest version?

**Comment by kcppdevelopers** [comment]
I have test with Gift Cards plugin, everything is working fine in with new reconstructed express checkout method.
