### ISSUE TITLE
Express Checkout - Replace button at top of checkout page.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#556]
The button at the to of the checkout page doesn't look good on a colored background...

![image](https://cloud.githubusercontent.com/assets/629241/18469297/48bc5252-796d-11e6-9009-2c9b85801bf8.png)

Need to replace that with a better image.

**Comment by kcppdevelopers** [comment]
Issue #573 and #623

**Comment by kcppdevelopers** [comment]
Now we are used https://www.screencast.com/t/ynRGBs6vRVP image
