### ISSUE TITLE
Express Checkout - Order Flow Adjustments

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#560]
I've had a few different requests for this.  Here is the [most recent one](https://mail.google.com/mail/u/0/#inbox/15764434c0f31c9b).

With PayPal Standard in WooCommerce, the customer fills out the checkout page prior to being sent to PayPal.  WC saves the order as pending at this point.  If the user cancels from the PayPal screen or doesn't complete the order, the seller can still see that pending order data and can follow up with the person to try and complete the sale.

With Express Checkout it seems we are not saving any order data in WC until the user is returned back from PayPal.  This makes sense because we don't have any buyer info until that point.

Some people are deliberately disabling EC from the product page and cart page to force people through the checkout page, so the user does have to fill out the info before being sent to PayPal, but we are still not saving the order at that point, it seems, because people aren't getting a saved pending order / canceled order in cases the user cancels from the PayPal pages.

We need to add some logic so that if the WC checkout page is used with Express Checkout, go ahead and get the order created in WC as pending and then update it after being returned from PayPal.

Of course, if EC is used from product pages or the cart page, etc. then we'll still need to do the same way we are now since we don't have any customer data yet.

**Comment by gine** [comment]
I use EC from checkout only and I will test what happens because if you user report this.. and this is true, I need this implementation too.

see you tomorrow.

**Comment by angelleye** [comment]
We will be completely revamping the Express Checkout integration to work better with WC in general in this 1.4.0 update.

This will also allow us to finish up other issues, too, like Woo Subscriptions compatibility, the ability to checkout with EC from saved / pending orders, In-Context checkout, and lots of other things.

That will all be coming in the 1.4.0 update.

**Comment by kcppdevelopers** [comment]
issue #447
