### ISSUE TITLE
Add button to clear log files.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#562]
When people have logging enabled in production the log files can grow very large and cause server performance issues.

We should add a button under our Settings -> PayPal for WooCommerce -> Tools to "Clear All Log Files".  

When the button is pushed, verify "Are you sure you want to permanently delete all log files?"

Proceed accordingly.

**Comment by kcppdevelopers** [comment]
http://www.screencast.com/t/QAWt4hLO7p
