### ISSUE TITLE
Braintree - Ability to replace credit card icons on checkout page.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#563]
https://wordpress.org/support/topic/change-credit-card-logos/#post-8233782

**Comment by kcppdevelopers** [comment]
http://pastebin.com/XuWqFjZH

**Comment by angelleye** [comment]
Is not now ready for review?

**Comment by kcppdevelopers** [comment]
Yes, this issue is ready to review. it would be great if we write document for how change the credit card icons.

**Comment by angelleye** [comment]
Yeah, looks like you found the label for documentation.  Eventually I'll go through and get docs for all of those added.

Any particular reason you haven't added the ready for review label?
