### ISSUE TITLE
Express Checkout - WC Social Login Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#568]
WooCommerce provides a social login extension so people can login/create accounts on the site without filling out forms.

https://woocommerce.com/products/woocommerce-social-login/

[woocommerce-social-login-1.8.0.zip](https://github.com/angelleye/paypal-woocommerce/files/514814/woocommerce-social-login-1.8.0.zip)

Our Express Checkout system typically skips the checkout forms anyway, but then if the WC settings require login login we are requiring them to do that on our review page after they're returned from PayPal.

We need to see how that would work out with this plugin installed.  

Are we using the data returned from PayPal to create the new account?  Do we need to build this plugin into our review page somehow?

**Comment by kcppdevelopers** [comment]
I have testing with our reconstructed express checkout gateway, now everything is working fine with WC Social Login plugin.
