### ISSUE TITLE
Braintree - Pay Pending Order Bug

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#570]
https://www.angelleye.com/support/scp/tickets.php?id=694

**Comment by kcppdevelopers** [comment]
We have already resolved this issue, for me it's woring fine.

**Comment by angelleye** [comment]
I've asked the user that reported this to verify what version of our plugin they are using.  If they're on an old version I'll assume we got it fixed in one of our updates.  If they're on 1.2.4 then I'll want to look into this a little more closely.

**Comment by angelleye** [comment]
Merchant said it wasn't our plugin causing their problems.
