### ISSUE TITLE
Express Checkout - Default Checkout Button Options

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#574]
In #573 we set a new default image to be used from the [PayPal hosted button options](https://www.paypal.com/webapps/mpp/logos-buttons). 

I'd like to add the ability for people to easily see all of these options from within the settings, and choose the one they'd like to use.  

So right now we have Checkout Button Type, and then the options are PayPal Image, Text Button, and Custom Image.

Those options will remain the same, but if you choose PayPal Image, it will display all the different PayPal images you can choose from and select one accordingly.

**Comment by kcppdevelopers** [comment]
@angelleye Can you please look into #623? Now we are using Dynamic Image Integration: https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECButtonIntegration/

Let me know your suggestion.

**Comment by angelleye** [comment]
@kcppdevelopers Are you saying this issue no longer makes sense because of the way our images are working?

**Comment by kcppdevelopers** [comment]
Yes right!
