### ISSUE TITLE
PayFlow - 10413 - cart item totals error.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#581]
This used to be a much bigger problem that we mostly resolved, but it still pops up sometimes.  Here's one example:  https://www.angelleye.com/support/scp/tickets.php?id=709

```
09-03-2016 @ 12:06:36 - PayFlow Endpoint: https://payflowpro.paypal.com
09-03-2016 @ 12:06:36 - PayFlow Response: Array
(
    [RESULT] => 7
    [PNREF] => BX1PEBD8083F
    [RESPMSG] => Field format error: 10413-The totals of the cart item amounts do not match order amounts.
    [HOSTCODE] => 10413
    [TRANSTIME] => 2016-09-03 09:06:35
    [BILLTOFIRSTNAME] => joe
    [BILLTOLASTNAME] => jones
    [AMT] => 5.00
    [ACCT] => 6111
    [EXPDATE] => 0821
    [CARDTYPE] => 1
    [RAWREQUEST] => BUTTONSOURCE[24]=AngellEYE_SP_WooCommerce&VERBOSITY[4]=HIGH&USER[11]=*****&VENDOR[14]=*****&PARTNER[6]=PayPal&PWD[8]=*****&TENDER[1]=C&TRXTYPE[1]=S&ACCT[16]=****&EXPDATE[4]=***&AMT[4]=5.00&CURRENCY[3]=USD&FREIGHTAMT[4]=5.00&CVV2[3]=***&ORDERID[13]=mm_@dmin18804&ORDERDESC[30]=Order 18804 on Military Muscle&BILLTOEMAIL[23]=joejones@yahoo.com&BILLTOFIRSTNAME[6]=joe&BILLTOLASTNAME[5]=jones&BILLTOSTREET[20]=123 Test Ave &BILLTOCITY[6]=suisun&BILLTOSTATE[2]=NC&BILLTOZIP[5]=94585&BILLTOCOUNTRY[2]=US&CUSTIP[12]=50.161.92.41&INVNUM[13]=mm_@dmin18804&SHIPTOFIRSTNAME[6]=joe&SHIPTOLASTNAME[5]=jones&SHIPTOSTREET[20]=123 Test Ave &SHIPTOCITY[6]=suisun&SHIPTOSTATE[2]=NC&SHIPTOCOUNTRY[2]=US&SHIPTOZIP[5]=94585
    [RAWRESPONSE] => RESULT=7&PNREF=BX1PEBD8083F&RESPMSG=Field format error: 10413-The totals of the cart item amounts do not match order amounts.&HOSTCODE=10413&TRANSTIME=2016-09-03 09:06:35&BILLTOFIRSTNAME=russel&BILLTOLASTNAME=baker&AMT=5.00&ACCT=6111&EXPDATE=0821&CARDTYPE=1
)
```

**Comment by angelleye** [comment]
What's interesting is that we added the option to "send line item details to PayPal" as a fallback in case this error was happening to somebody.

In this case, the person already has this option disabled, and from the log above I do not see individual line item details included in the request, so not sure how we're still getting this error.

They did mention that coupons codes are involved here, and this happens when the order comes up as $0.00 but there is still $5.00 shipping.

From the log, though, it has 5.00 as the AMT, and again, no line item details.  So..??

**Comment by angelleye** [comment]
Is there any chance our log file is saving without the line items as expected, but the data getting sent to PayPal actually does include it?

I can see in their logs that they were getting this error a lot, and in those cases they did indeed have the ITEMAMT included, which was coming out as a negative amount.

They disabled the line items, though, and I don't see them in the log anymore, yet we're still getting this error.

**Comment by angelleye** [comment]
I think I see what's going on here.  Here's a fresh log from the support ticket.

```
    [RAWREQUEST] => BUTTONSOURCE[24]=AngellEYE_SP_WooCommerce&VERBOSITY[4]=HIGH&USER[11]=*****&VENDOR[14]=*****&PARTNER[6]=PayPal&PWD[8]=*****&TENDER[1]=C&TRXTYPE[1]=S&ACCT[16]=4552250197661114&EXPDATE[4]=1119&AMT[4]=2.95&CURRENCY[3]=USD&FREIGHTAMT[4]=5.00&CVV2[3]=030&ORDERID[13]=mm_@dmin18640&ORDERDESC[30]=Order 18640 on Military Muscle&BILLTOEMAIL[18]=ltmattyd@gmail.com&BILLTOFIRSTNAME[7]=Matthew&BILLTOLASTNAME[7]=Daniels&BILLTOSTREET[16]=7204 Tanager St &BILLTOCITY[11]=Springfield&BILLTOSTATE[2]=VA&BILLTOZIP[5]=22150&BILLTOCOUNTRY[2]=US&CUSTIP[12]=209.95.50.11&INVNUM[13]=mm_@dmin18640&SHIPTOFIRSTNAME[7]=Matthew&SHIPTOLASTNAME[7]=Daniels&SHIPTOSTREET[16]=7204 Tanager St &SHIPTOCITY[11]=Springfield&SHIPTOSTATE[2]=VA&SHIPTOCOUNTRY[2]=US&SHIPTOZIP[5]=22150&ITEMAMT[5]=-2.05
    [RAWRESPONSE] => RESULT=7&PNREF=BP0PD8317FC9&RESPMSG=Field format error: 10413-The totals of the cart item amounts do not match order amounts.&HOSTCODE=10413&TRANSTIME=2016-08-23 16:13:25&BILLTOFIRSTNAME=Matthew&BILLTOLASTNAME=Daniels&AMT=5.00&ACCT=1114&EXPDATE=1119&CARDTYPE=0
```

So we can see that it does not have any line item details since she disabled those via the settings, however, it is still included ITEMAMT which is getting a negative amount.

In cases where line item details are disabled, we should not be including the ITEMAMT.

**Comment by angelleye** [comment]
I think we need to move [this line](https://github.com/angelleye/paypal-woocommerce/blob/master/classes/wc-gateway-paypal-pro-payflow-angelleye.php#L457) down into the `if($this->send_items)` logic.

**Comment by angelleye** [comment]
It may actually be that all 3 of those params need to be moved (shipping, tax, and itemamt).  Need to do some testing on that.

**Comment by robwatson-intechra** [comment]
I'm here in this thread because I've been working directly with PayPal on this very issue. I've unset and set the "Send line item details to PayPal." checkbox, but this doesn't resolve the issue. Just adding my voice to the need for this to be fixed.

**Comment by angelleye** [comment]
@robwatson-intechra Thanks for the follow up.  We'll be working to make necessary adjustments on this for the 1.4.6 update we're working on now.

**Comment by kcppdevelopers** [comment]
We have already resolved this issue, now We have develop new calculation class. everything is working fine.

**Comment by angelleye** [comment]
@robwatson-intechra Can you verify that things are working well for you now?  Or are you still having issues?

**Comment by robwatson-intechra** [comment]
I think we're ok on this. Thanks for checking in again.
