### ISSUE TITLE
Filter hook for currency code.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#587]
https://www.angelleye.com/support/scp/tickets.php?id=754

https://wordpress.org/support/topic/pp-express-and-multi-currencies/#post-8476780

**Comment by angelleye** [comment]
>I have edited the function buy_now_button() in paypal-for-woocommerce.php adding

>if(get_woocommerce_currency() != &quot;EUR&quot;) {
                return false;
 }

>but don't want to hack your code like that.

**Comment by kcppdevelopers** [comment]
We have added below supported currencies filters:

- woocommerce_paypal_express_supported_currencies
- woocommerce_paypal_advanced_supported_currencies
- woocommerce_paypal_rest_api_supported_currencies
- woocommerce_paypal_pro_supported_currencies
- woocommerce_paypal_pro_payflow_supported_currencies

Also we have added Aelia Currency Switcher compatibility to our plugin.

**Comment by daigo75** [comment]
Thanks everybody, excellent work! :+1:
