### ISSUE TITLE
Express Checkout - Error 10486 Adjustment Necessary..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#589]
In #311 we confirmed that our flow is working per PayPal's documentation for handling this error.

We are getting a report, though, that when this happens WooCommerce ends up with two separate orders for the same checkout:  one that shows it failed and one that shows it completed.

https://wordpress.org/support/topic/compatibility-of-plugin-with-wordfence/#post-8436323

We should not be creating an entirely separate order for the re-attempt when this happens.

**Comment by gine** [comment]
I have wordfence enabled on my site and I have not this kind of problem with with and capture.

**Comment by angelleye** [comment]
@gine, thanks for the feedback.  We haven't had any other reports either, so we'll take a quick look as well just to see if we can reproduce any issue, and then likely close this out without any change unless we can get some more details from the original user that reported this.
