### ISSUE TITLE
Payments Advanced - Currency Issues

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#590]
https://www.angelleye.com/support/scp/tickets.php?id=746

**Comment by kcppdevelopers** [comment]
@angelleye I am little bit confused on this issue, PayPal Advanced only work with USD and CAD currencies right?

**Comment by angelleye** [comment]
Yeah, I'll move this one and we can look at it more later.  I'll double check with the user what exactly they're doing.
