### ISSUE TITLE
Credit card icons are not responsive on mobile devices.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#593]
https://mail.google.com/mail/u/0/#inbox/15764434c0f31c9b

>I just noticed that the credit cards icon are not responsive on mobile phone (iphone 5), please check out the screenshot attached herewith. It would be great if there is a fix. Thank you.

![image](https://cloud.githubusercontent.com/assets/629241/20342580/ad073496-abb0-11e6-8218-f3534dbe890a.png)

**Comment by kcppdevelopers** [comment]
It seem WordPress Theme CSS Issue, we have not provide any style for payment method listing or icon. I have checked this issue with Woo default theme and it's working fine for me.
