### ISSUE TITLE
Remove Gift Wrap option

### ISSUE THREAD

**Issue by kcppdevelopers** [angelleye/paypal-woocommerce#594]
https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECCustomizing/
The gift and survey question options are discontinued as of Sept. 8, 2016 with no replacement.

**Comment by angelleye** [comment]
@kcppdevelopers I don't see any commits.  Did anything happen with the code here?

**Comment by kcppdevelopers** [comment]
I have already remove Gift Wrap option in the issue #630
