### ISSUE TITLE
Autoship -> Guest Checkout Adjustments

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#598]
We have more feedback from the guys using Autoship.  

I am not sure if it makes sense to make further adjustments with what we've done here, or go ahead and begin making adjustments in a separate plugin that would customize things to suit this individual client's needs at this point.  

Please review all of the comments below which are [pulled from an email chain](https://mail.google.com/mail/u/0/#inbox/15852247d3e39e64).  I will add separate comments here to separate the email responses between the client and his developer reviewing what we've done.

**Comment by angelleye** [comment]
>1. I see it triggered the “New Account” email with the username. Is there a way we can also include their password? (I guarantee you this customer base won’t know how to get back into their account) Is it as simple as clicking the "Automatically generate customer password” on the WC Account settings?

>2. The Payflow form has a "save to account” checkbox. If I purchase an Autoship product and DON’T click that box, theres no payment method saved. Can we do something where if they have an Autoship in their account, automatically save to account and hide the checkbox option?

**Comment by angelleye** [comment]
>re #1
are we talking about when people chose to create a user account upon checkout,
or
those people CHOSE to checkout as guests? 


>because if they chose guest, we dont want to be sending them an email saying we made an account for them.
no thanks if that is what you are saying, just stifle the notifications in this regard.



>re#2

>we ALWAYS want their CC or paypal, regardless of what they buy, and we dont want to show them the option,
Always checked, ALways Hidden, please - > regardless of product type or Autoship etc.

**Comment by angelleye** [comment]
>#1. Talking about when they checkout as a guest. As of right now, we’re not “showing” them any registration on checkout. So their options are:
	A. "I already have an account. I want to login first, then checkout with my account and any saved data to my account."
	B. "I don’t have an account. I checkout like any normal website. Oh look at that, they created an account for me.”

>The reason for Option B sending notifications is: once we create that account, if they go to purchase again with the same email, its going to tell them they already have an account (because we created it for them). If we haven’t told them that, they’ll be thinking “no I never made an account… what the heck…”


>#2. Sure - lets always save their info. Andrew can you do that?

**Comment by angelleye** [comment]
>I take that back on #1… apparently it will let you use the same email again without a warning… lemme see something…

**Comment by angelleye** [comment]
>Ok… so it let me create another order with the same email address without logging in again and without prompting me to do so.

>However, here’s my concern: on a fresh incognito browser, it recognized that I already had an account and associated the Autoship order to that same account WITHOUT ever needing a password. After checkout, I am definitely logged in as that user now, and can see my Autoship schedule from the previous order. 

>So in theory, someone can make an order under someone else’s email, and now they’re dropped into their account - can change passwords, shipping details, payment methods, etc. Thats major security flaw. We need a password gateway at some point through this process.

>Worse… I just tried that same process using my admin email without logging in, and after checkout, I’m now logged in with my admin account. That won’t work.

**Comment by angelleye** [comment]
>guest accounts should be appended with guest_ when created
or g_
or whatever you want to denote the guest creation operation,

>upon verification, they should then have the appended stuff removed in the database and become the user account once password verified

>that work?

**Comment by angelleye** [comment]
>Something like that, yes.

**Comment by angelleye** [comment]
@kcppdevelopers Your thoughts after reading the interaction above?

**Comment by kcppdevelopers** [comment]
I see it triggered the “New Account” email with the username. Is there a way we can also include their password? (I guarantee you this customer base won’t know how to get back into their account) Is it as simple as clicking the "Automatically generate customer password” on the WC Account settings?

**[yes, we can also include password on “New Account” email using "Automatically generate customer password" checkbox clicking.]**

The Payflow form has a "save to account” checkbox. If I purchase an Autoship product and DON’T click that box, theres no payment method saved. Can we do something where if they have an Autoship in their account, automatically save to account and hide the checkbox option?

**[Payflow used reference transaction, so we no need to save CC details, we will save PPREF value for reference transaction.]**
