### ISSUE TITLE
Braintree - Apple Pay / Android Pay

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#603]
* https://mail.google.com/mail/u/0/#inbox/15973e76644f01f0

Braintree supports Apple and Android payment platforms, but I'm not sure if it's included in the default Braintree integration that we have included in the plugin right now.

Need to look into this and get both of these integrated if necessary.

- [Apple Pay Documentation](https://developers.braintreepayments.com/guides/apple-pay/client-side/javascript/v3)
- [Android Pay Documentation](https://developers.braintreepayments.com/guides/android-pay/overview)

**Comment by simon-3t** [comment]
Hello,
Any news on Apple Pay and Android Pay integration?
Thanks

**Comment by angelleye** [comment]
@simon-3t It should work in the current integration of Braintree, but we're just about to release the 1.4.9 update which upgrades the Braintree SDK we're working with now so it might work a little better.

As long as you have those features enabled in your BT account, though, they should show up during checkout on a mobile device.  Have you tried it yet?

**Comment by simon-3t** [comment]
@angelleye Thank you for your reply. I will delete my actual plugin and start to use yours today.
I think this is a feature that can be add on the wordpress plugin description so people can be aware.
Thanks again for your fast support.
Simon
