### ISSUE TITLE
PayFlow - Silent POST

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#604]
PayFlow has a system called "silent POST" which is basically the same thing as PayPal IPN except that it's specific to PayFlow.  

For example, PayFlow includes COMMENT fields, but PayPal IPN would not include these comment fields.  PayFlow silent POST would, though.

We need to add a setting in the PayFlow page to configure a Silent POST URL that the user can set.

If this setting has a value, then it would need to be included as `SILENTPOSTURL={url}` in the PayFlow API request.

**Comment by kcppdevelopers** [comment]
I have added SILENTPOSTURL parameter in the PayFlow API request, but I am not getting any response like PayPal IPN.

**Comment by angelleye** [comment]
I think it has to be enabled at the PayFlow side along with adding it to the API call.  I'll double check with PayPal on that.

**Comment by angelleye** [comment]
It turns out that Silent POST does not work with PayFlow Pro, but instead it's intended for Payments Advanced / PayFlow Link and would be enabled in the account profile settings.

I'm going to move this to 1.4.0 so we can look into it more then, but we may end up ditching this altogether.
