### ISSUE TITLE
Undefined index?

### ISSUE THREAD

**Issue by dyluck07** [angelleye/paypal-woocommerce#608]
I have error reporting turned on in my test environment.  Why is this plugin throwing a bunch of undefined index errors?  Is something wrong that I need to be aware of?

Notice: Undefined index: title in/test/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-pro-angelleye.php on line 77

Notice: Undefined index: description in /test/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-pro-angelleye.php on line 78

Notice: Undefined index: enabled in /test/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-pro-angelleye.php on line 79

Notice: Undefined index: api_username in /test/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-pro-angelleye.php on line 80

Notice: Undefined index: api_password in /test/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-pro-angelleye.php on line 81

Notice: Undefined index: api_signature in /test/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-pro-angelleye.php on line 82

Notice: Undefined index: testmode in /test/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-pro-angelleye.php on line 83

**Comment by angelleye** [comment]
We haven't had that reported from anybody else, and I'm not seeing it myself on our test servers.  Do you have any caching / CDN services in WordPress or on the server that could be conflicting?  Have you tried disabling other plugins temporarily to see if any of those were conflicting?

**Comment by gine** [comment]
I haven't test it now. But this is a classic notice php error that you can see if you turn to true the definition of the constant debug on wp-config.php and if you have correct errors setting on your php.ini.

This means that you are trying to access at an index undefined of your array. For example: 

$a = array();
$b = array['myloc'];

when we assign $b you will see a notice.. sometimes this kind of error are not important, but for a better code is useful to correct them. To avoid this notice you need to check the array at that index with the empty() or isset() function before.

$b = isset(array['myloc']) ? array['myloc'] : '';

Looking at your code you have this problem at the line reported.

if you check few line after you will see that you use this technic with other variables.

**Comment by angelleye** [comment]
@gine, thanks for the feedback!  We'll take a look and make any necessary adjustments on the next update.

**Comment by gine** [comment]
@angelleye Today i have coded on this code so i have seen well. You have this little problem not only on that file wc-gateway-paypal-pro-angelleye.php but on all gateway class. On EC too.

Nothing, i like cooperate.

**Comment by kcppdevelopers** [comment]
We have already resolved above bug in the issue  #10

**Comment by angelleye** [comment]
Ah, ok, but that has been pushed to 1.4.0 since we have lot of adjustments to make with Express Checkout, right?

**Comment by kcppdevelopers** [comment]
Yes right!
