### ISSUE TITLE
Express Checkout - Potential lead on the -1 problem..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#613]
For a long time now I've been curious about how/why some people end up with a blank white page and a -1 at the top sometimes when using Express Checkout.  We've always chalked it up to a plugin or theme conflict and I never really was clear about why we don't a better error or anything.

Anyway, this is happening again with a merchant, and a PayPal tech support team has provided the following info:

>ECS button in the cart will go here: https://www.cariscloset.ie/?wc-api=WC_Gateway_PayPal_Express_AngellEYE&pp_action=expresscheckout
which is giving us -1 page.
 
>While if the cart folder is added, it seems to work ok.
https://www.cariscloset.ie/cart/?wc-api=WC_Gateway_PayPal_Express_AngellEYE&pp_action=expresscheckout

https://www.angelleye.com/support/scp/tickets.php?id=812

I mentioned to them that it could possibly be a permalinks configuration issue, but I'm not sure about that..??  @kcppdevelopers Can you think of any reason this would happen?

**Comment by kcppdevelopers** [comment]
Yes, There are two possiblity like permalinks configuration issue or any higher priority hook/action/function is called before our function and prompt error. I need FTP detail for more troubleshooting issue.

**Comment by angelleye** [comment]
I have requested WP and FTP access.

**Comment by angelleye** [comment]
We haven't had any reports of this for a while now, so I'm closing this issue.
