### ISSUE TITLE
Express Checkout - Settings Issue..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#615]
I'm running on the current dev branch with everything merged.  In Express Checkout settings, I noticed that if I check the box to enable "Skip Final Review", it's hiding the next option below that, which is "Payment Action".  I don't know why we would be hiding the Payment Action option if Skip Final Review is enabled..??

Also, I have a Terms and Conditions page set in WC, so I'm getting the message that "Skip Final Review" is not available since it's necessary to provide the T&C checkbox.  It's still allowing me to check/uncheck the box, though.  I was expecting this to be disabled (grayed out) in cases where it's unavailable.

**Comment by kcppdevelopers** [comment]
I am little bit confused here, Can you please  double check for me?

if we check the box to enable "Skip Final Review", it's hiding the next option below that, which is "Skip Terms and Conditions" not "Payment Action", we are never hiding "Payment Action".

**Comment by angelleye** [comment]
Okay, yes, I was incorrect in the way I was seeing this.  I still think we need an adjustment here, though, because now I'm a little bit confused at the way these 2 fields are working together.

We have Skip Final Review, and I have a message that it's not available since I have T&C enabled, and another message that it's not available because I have tokenized payments available.  

It still lets me check the box, though, and when I do I get the additional option to Skip T&C.  The tip it provides, though, is exactly the same as the Skip Final Review option, where it says...

> By default, users will be returned from PayPal and presented with a final review page which includes shipping and tax in the order details. Enable this option to eliminate this page in the checkout process.

Our Skip Terms and Conditions option, if enabled, would allow me to go ahead and Skip Final Review, right?  

Although, in my case it still wouldn't because I also have payment tokens enabled.  On that note, though, if we adjust like I said in #616 then it wouldn't matter whether payment tokens were enabled or not, and this functionality could be stripped from the settings.

So it seems like this could be the cause for some confusion.  I need to get it all documented, of course, but I would be confused how to even write this up.

I think we need to do this...

1. Finish #616 
2. Remove the logic that checks if payment tokens are available and displays the message that Skip Final Review is not available.
3. Adjust the message that says "This is not available because your WooCommerce orders require accept Terms & Conditions." to say "You currently have a terms and conditions page set in WooCommerce.  This will require our review page, but you may disable this with the Skip Terms and Conditions option below."
4. Update the tip for Skip Terms and Conditions that currently says "By default, users will be returned from PayPal and presented with a final review page which includes shipping and tax in the order details. Enable this option to eliminate this page in the checkout process." and change it to say "Check this to disable your terms and conditions for Express Checkout orders so that you can use the Skip Final Review option."
5. Make sure the "Skip Terms and Conditions" option doesn't show up unless a terms and conditions page is indeed set.

Does this all make sense to you or would you disagree with any of this?

**Comment by kcppdevelopers** [comment]
Yes it make sense to me.

**Comment by angelleye** [comment]
We're moving #616 to 1.4.0, so that affects some of what we planned with our steps above.  

I will look into this one myself and make some adjustments to the verbiage we currently have.  Then we can improve upon it more in 1.4.0 along with #616 and the rest of the EC rebuild.
