### ISSUE TITLE
Express Checkout - Payment Token Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#616]
Our checkout flow for Express Checkout with payment tokens enabled is a little confusing.

Currently, if I have items in the cart and I click to checkout with Express Checkout, we're enabling the billing agreement in the SEC request, which forces this sort of a message at PayPal...

![image](https://cloud.githubusercontent.com/assets/629241/21302478/d85f0dea-c57c-11e6-858c-f3e2621f0154.png)

When I click Agree and Continue, I'm sent back to the review page where I see the option to save the billing agreement to my account...

![image](https://cloud.githubusercontent.com/assets/629241/21302499/05ae6e44-c57d-11e6-809c-0164308cc53f.png)

This seems backwards.  If I don't want to save my account details with the site, then I should not have to agree to a billing agreement with PayPal.

If payment tokens are enabled in EC, I think we need to output our "Save PayPal account for future use." option right there next to the EC button on product pages and the cart page.  Or maybe underneath it...whatever fits best in most cases.  We can have this in its own div, of course, so people can easily move it around if they need to.

This way, the buyer can choose whether or not they want to save the PayPal account to their account prior to ever getting sent to PayPal.  If they do NOT choose this, then we would leave the billing agreement parameters out of the SEC request so that they would not have to agree to a billing agreement on the PayPal pages.  If they do choose to save it, then we could include the BA parameters as necessary.

Once they get to the review page they won't need a check box to save because they've already done that.

**Comment by kcppdevelopers** [comment]
I have one question: if user is logged in website and Tokenized Payments Enable in this note how can we handle SEC request parameter?

**Comment by angelleye** [comment]
Not sure I understand why that would change the flow I outlined above..??

**Comment by kcppdevelopers** [comment]
In the Express Checkout payment method, if guest checkout is enable then we are not forcing customer to create an account right? If user will not create an account or if user is logged in website, how can we save billing agreement details to account?

**Comment by kcppdevelopers** [comment]
If payment tokens are enabled in EC, I think we need to output our "Save PayPal account for future use." option right there next to the EC button on product pages and the cart page. Or maybe underneath it...whatever fits best in most cases. We can have this in its own div, of course, so people can easily move it around if they need to.

[Regarding  "Save PayPal account for future use." option  next to the EC button on product pages and the cart page, currentlly we have just URL for Ajax request. so can't pass option value of "Save PayPal account for future use." SEC request. If we want to pass ""Save PayPal account for future use." option value then we need to change that logical part used Form ajax insted to just URL. ]

I think we should invest much time on this issue, becuase we have already paln to rebuid Express Checkout payment.

Let me know your suggestion.

**Comment by angelleye** [comment]
Can we set it up so that if they click the option to save their account it would then force them to create an account / login?

**Comment by kcppdevelopers** [comment]
Yes, we can force them to create an account / login. but option next to the EC button on product pages and the cart page it will take more time. for implementing option next to the EC button on product pages and the cart page we have to used Form ajax, currentlly we have just used url.

**Comment by angelleye** [comment]
Okay.  I guess we can just leave it this way for now so that we can get 1.3.0 released, and then we can improve upon this when we redo EC altogether in 1.4.0.

**Comment by kcppdevelopers** [comment]
Issue #630
