### ISSUE TITLE
Problem with the way we're using WC cart session data..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#619]
https://www.angelleye.com/support/scp/tickets.php?id=771

>The developer has also noticed some issues in plugin related to woocommerce session. The payment id is not stored in woocommerce session and that's why it redirects to cart page(From catch block in code). Woocommerce session is not used properly with the plugin so its behavior is unusual sometimes.

**Comment by kcppdevelopers** [comment]
I have checked above support ticket and found that this issue related to PayPal Plus for WooCommerce pluging.

**Comment by angelleye** [comment]
so does that mean we need to fix something here?

**Comment by angelleye** [comment]
Oh, I see.  I put this in the wrong repo.  I'll close it here and move this to the Plus repo.
