### ISSUE TITLE
API Credentials Storage Improvements..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#622]
* https://wordpress.org/support/topic/passwords-stored-in-the-clear/

We should be able to encrypt all of the API credential values that get stored in the DB so that if people pull  values from there they wouldn't do them any good.

Seems we should be able to do this with mcrypt, where we'd encrypt the value that gets saved to the database, and decrypt it when we pull it back out to include in the API request.

This should be done for all gateways.

**Comment by kcppdevelopers** [comment]
I have checked and found that WooCoomerce does not provide any hook or filter to the changed setting value and retrieve original value to display in the setting panel.

**Comment by angelleye** [comment]
Not sure what you mean..??  We can't encrypt the value entered by the user prior to saving it to the DB, and then when we pull it back out of the DB, decrypt it so it matches the original value before adding it to the API request?

**Comment by kcppdevelopers** [comment]
Yes, we can encrypt the value entered by the user prior to saving it to the DB, but we can't encrypt to decrypt back and display in the payment gateway setting panel.

**Comment by angelleye** [comment]
Ok, I think that's fine.  We'll just need to figure out a way to make that flow nicely for people.

So if the credentials aren't set, the fields would be there like normal to populate and save.  Once saved, the encrypted value would be saved to the DB, and in the settings page we could just disable those fields with a message in them that says "encrypted value saved".  

So then I guess we would also need a little button or check box to clear those out if you need to adjust them.

Does that sound like a viable solution?

**Comment by kcppdevelopers** [comment]
Finally I find the way to encrypt the value entered by the user prior to saving it to the DB, and then when we pull it back out of the DB, decrypt it so it matches the original value before adding it to the API request.

**Comment by angelleye** [comment]
Excellent!  👍

**Comment by angelleye** [comment]
@kcppdevelopers Is this going to require anything special for people updating the plugin?  

The current values in their database won't be encrypted, and then after they update it will pull the non-encrypted value, but then attempt to decrypt it which would change the value and cause it to break.

We need to make sure that sort of thing is handled appropriately with this update.  Somehow force any current values to be pushed through the encryption tool and re-save with the encrypted value..??

**Comment by kcppdevelopers** [comment]
No, this will work for our existing users as well new users without anything special for people updating the plugin. We are not automated encrypt old setting values, once they re-save setting value then we applied encrypt the value entered by the user prior to saving it to the DB and then when we pull it back out of the DB, decrypt it so it matches the original value before adding it to the API request. we are only decrypt setting value if it already it encrypted.

**Comment by gine** [comment]
1) If you can encrypt then you can decrypt the value entered from the user, a cracker can do that too. 

Maybe I don't understand well. 

But normally for password value that you need to logi on a service, On first insertion or user creation you hash the password and save it on db. 

Then when the user login, you don't decrypt the saved password(that is impossible by hash design) to compare but you hash the new once inserted on the login process.

@kcppdevelopers Here how do you think to work? Like (1) it is useless.

my cents
