### ISSUE TITLE
Express Checkout - Broken Image URLs

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#623]
* https://wordpress.org/support/topic/broken-checkout-buttons

Seems that not all locale codes have a matching button with PayPal's system, so sometimes we end up with a broken (404) image URL.

For example, the user in the post above has the site set to en_GB, so our code is using https://www.paypalobjects.com/webstatic/en_GB/i/buttons/checkout-logo-medium.png as the button image URL, but that URL results in a 404 not found.

We either need to find a list of supported locale codes for EC buttons, or we need to run some sort of a check to see if a 404 response comes back on the current image.  If so, it should fall back to the default image without any locale code specified.

For example, https://www.paypalobjects.com/webstatic/en_GB/i/buttons/checkout-logo-medium.png does not load, but https://www.paypalobjects.com/webstatic/i/buttons/checkout-logo-medium.png loads just fine.

**Comment by kcppdevelopers** [comment]
PayPal supported below local code:
 
'da_DK', 'de_DE', 'en_AU', 'en_GB', 'en_US', 'es_ES', 'fr_CA', 'fr_FR','he_IL', 'id_ID', 'it_IT', 'ja_JP', 'nl_NL', 'no_NO', 'pl_PL', 'pt_BR',	'pt_PT', 'ru_RU', 'sv_SE', 'th_TH', 'tr_TR', 'zh_CN', 'zh_HK', 'zh_TW',

I have checked above all the local code with button image URL but only one local code "en_US" is work. like "https://www.paypalobjects.com/webstatic/en_US/i/buttons/checkout-logo-medium.png" URL.

I found another solution for Dynamic Image Integration: https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECButtonIntegration/

Please let me know your suggestions.

**Comment by angelleye** [comment]
Looks like that's what we should be using.  Go ahead with that please.

**Comment by angelleye** [comment]
On this current image set, if the background isn't white the text and edges looks very bad...

![image](https://cloud.githubusercontent.com/assets/629241/21901994/b7f9a686-d8bf-11e6-9a64-e614f73fd29a.png)

Is there a better image with this method we can use?

**Comment by kcppdevelopers** [comment]
No, there is only one method to get dynamic Image.

**Comment by angelleye** [comment]
Ok, then how about we leave the dynamic URLs in place for all local codes besides en_US.  If it's en_US (or nothing / default) then we could use the image I had before that looked better on colored backgrounds.  Will that work?
