### ISSUE TITLE
Braintree Issues..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#625]
* https://wordpress.org/support/topic/braintree-cc-payment-and-paypal-ko-since-new-braintree-protocol/#post-8637148

User reporting that our Braintree integration is failing for them, but another Braintree plugin is working fine.  

Please review the ticket and then check our Braintree integration to see if there's anything we need to adjust.

**Comment by angelleye** [comment]
Not sure if this is related or not, but here's another Braintree problem we're getting details about...

**Client sent this and also called:**
None of our credit card transactions are able to process. I reached out to Braintree and you can see their response below. Can you take a look? It's been over a week since we have been able to process any rentals. A bit of a problem :)
 
**Braintree responded with this:**
 
I was able to locate an example of the error you are encountering within our server logs, which is as follows:

```
[VALIDATION ERRORS] 91508 (Cannot determine payment method.)
Parameters: {"transaction"=>{"type"=>"sale", "billing"=>{"first_name"=>"Brenda", "last_name"=>"Glazer", "company"=>nil, "street_address"=>"525 Wilson Ave", "extended_address"=>"Suite 1108", "locality"=>"Toronto", "region"=>"ON", "postal_code"=>"M3H 0A7", "country_code_alpha2"=>"CA"}, "shipping"=>{"first_name"=>"Brenda", "last_name"=>"Glazer", "company"=>nil, "street_address"=>"525 Wilson Ave", "extended_address"=>"Suite 1108", "locality"=>"Toronto", "region"=>"ON", "postal_code"=>"M3H 0A7", "country_code_alpha2"=>"CA"}, "amount"=>"1616.00", "order_id"=>895, "options"=>{"submit_for_settlement"=>true, "store_in_vault_on_success"=>"true"}, "channel"=>"AngellEYEPayPalforWoo_BT"}, "merchant_id"=>"qpqnhdfv3wpw86ff"}
```

Upon reviewing the transaction call above, it looks like there is no payment method being passed or included, which would indeed trigger this kind of validation error.  This is likely an issue with the extension you are using to connect your website to Braintree.  The channel parameter is being passed as AngellEYEPayPalforWoo_BT, which leads me to believe you may be using the PayPal for WooCommerce extension.  Can you confirm if this is the case, or if there is a different extension you may be using?  If you are indeed using the PayPal for WooCommerce extension, you will likely need to reach out to AngelEye for more information.

**Comment by angelleye** [comment]
@kcppdevelopers Please double check this one as we have a user claiming the release branch isn't working for him.

**Comment by kcppdevelopers** [comment]
I have checked every possible test cases and resolved the issue. Now everything is working fine.
