### ISSUE TITLE
Cart Totals - Coupon conflict with WP-Ronin gift cards.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#626]
* https://mail.google.com/mail/u/0/#inbox/159954e411b9e81d
* https://wordpress.org/support/topic/paypal-error-code-10413/

>I have a gift card plugin by WP-Ronin, and it is saying that the totals do not equal when I try to checkout. Is there a way to fix this?

>I found this from 2015 that is a similar issue:

>https://github.com/angelleye/paypal-woocommerce/issues/277

>Is there any way to hotfix this, or for a possible future integration so that it works together?

**Comment by kcppdevelopers** [comment]
issue #550
