### ISSUE TITLE
Order / Auth / Capture bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#627]
This is different from #621.

Here, the user reports that they had an order go through for 9.98.  They then adjusted the shipping or a discount on the order, which took the price down to 9.79.  When they capture, though, it still captures the full 9.98 instead of the adjusted order price.

**Comment by gine** [comment]
Hi am the user which have reported this bug. I have posted on WordPress support some idea how to resolve capture when there are partial refund or/and discount.

here the link with all the story: 
https://wordpress.org/support/topic/doauthorize-docapture/

refer only at the 1th point.

**Comment by kcppdevelopers** [comment]
I am little bit confused about partial refund, partial refund is not possible when PayPal transaction status is Authorization. refund or partial refund only possible when PayPal transaction status is completed.

**Comment by gine** [comment]
refund is a wc action and if the seller apply it on order, it need to capture a partial amount(not refund a partial amount) on paypal. auth & capture is born for that.

try to think if someone buy 2 object by authorization. the seller doesn't have 1 object so it need to capture only a partial amount. But to let wc make stats for you and send a correct email to bite,  it need to refund the order on wc. So the order amount must be reduced and the amount captured by doCapture too using the old amount-wc_refunded.

**Comment by angelleye** [comment]
@gine, I'm a little confused by what you're saying here, too.  If you're working with Authorization, then no payment has been processed yet, so there is no payment to refund.  In that case you simply adjust the order amount and capture it when it's ready, so only that amount would ever be captured at all.

It sounds like you're saying you want to charge the full amount that was authorized, and then refund the difference..??  That's overkill, and would actually end up costing you additional transaction fees.

Maybe we're not fully understanding what you're trying to say here..??

**Comment by gine** [comment]
did you try to do what I have illustrated with screenshots?

buyer use EC authorization for 83$. 

seller see the order with authorization id for 83$. he see order on wc order page. 

now the seller want use wc order page and its functions to decrease the amount for various reasons.

he can do that putting the order in suspend and making discount or using the manually refund button present on the order page. This is not a paypal refund but only a wc refund or a wc discount.

we suppose that he refunds 10$.

what I fix on my pull request is that when the buyer want capture the amount. the amount must be decreased by 10$. 

Capturing the amount from the order page the buyer must capture 73$(paypal partial capture). Before fix your plugin capture 83$.
