### ISSUE TITLE
Adding custom class at order page

### ISSUE THREAD

**Issue by gine** [angelleye/paypal-woocommerce#632]
To do a better customization(css and js) for each payment type, i think that can be a good idea adding at root div of the admin order page(for example, but on review order page too) a class where you write what kind of payment was  used.

In this mode an user on his custom css or you can do things like:

```
.angelleye-paypal-express-checkout .review-order .button {
 color: black;
}

.angelleye-paypal-advanced .review-order .button {
 color: yellow;
}
```

or
```

var root = $('.angelleye-paypal-advanced');
if(root) {
  $('button .review-order .button').remove();
}
```

[Ionic framework](https://github.com/driftyco/ionic) work in this mode to permit customization and optimization for each operating system(.android, .ios...)

**Comment by angelleye** [comment]
@gine, thanks again for the feedback.  I've added this one to our 1.4.0 milestone.  I don't want to delay 1.3.2 any more than necessary.

**Comment by kcppdevelopers** [comment]
@angelleye Can you please explain with more details?

**Comment by angelleye** [comment]
@gine, maybe you can provide some more information on this for @kcppdevelopers..??

**Comment by angelleye** [comment]
@gine Can you elaborate a little bit on this for us?
