### ISSUE TITLE
CC Processing - Soft Descriptor

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#634]
* https://mail.google.com/mail/u/0/#inbox/159f0009bdd9f1a4

For DDP, PayFlow, Braintree, REST credit cards...we need to add an option in the gateway settings where you can set the soft descriptor, which is what the buyer will see on their CC statement.

This is important to set at the transaction level, because otherwise it defaults to the PayPal account holder's primary business name, which is a problem when people are using a single PayPal account and selling from multiple websites.  User's don't recognize the name on the statement, and they submit disputes because of it.

**Comment by kcppdevelopers** [comment]
Can you please suggestion me which value we assign to softdescriptor filed? or just need to add filter for dependability?

**Comment by kcppdevelopers** [comment]
can you please suggest me which value we should assign to softdescriptor field? or just need to hook/filter to extend purpose or add new setting field for Soft Descriptor.

**Comment by angelleye** [comment]
@kcppdevelopers This would just be an additional option/field on the settings page.  So the label would be "Credit Card Statement Name" and then they could fill in whatever value they want.

**Comment by angelleye** [comment]
@kcppdevelopers I see that we've added the Credit Card Statement Name option to the settings for each of the credit card gateways, but it looks like most of them aren't actually including that value in the API request at all..??

**Comment by kcppdevelopers** [comment]
@angelleye  I have checked code and it seems already include in the API request. Please check : https://pastebin.com/raw/mLJf5gUi
