### ISSUE TITLE
Log File Extension Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#637]
Right now our log files get saved as .log.  My support ticket system does not accept .log attachements, though, so I always have to instruct people to rename it to .txt or zip it before they attach it.

I'm thinking we could just adjust the log files so they get saved with .txt instead of .log and then I wouldn't have to worry about that anymore.

**Comment by kcppdevelopers** [comment]
I think we should wait for [Improved logging in WooCommerce 2.7](https://woocommerce.wordpress.com/2017/01/26/improved-logging-in-woocommerce-2-7/)

**Comment by angelleye** [comment]
Ok, sure, makes sense.

**Comment by kcppdevelopers** [comment]
Now our support system work well with .log file attachments.
