### ISSUE TITLE
WC Version Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#640]
Previously, we had some PHP failures happening when our plugin was enabled if people were on old versions of WC or PHP.  As such, we've apparently added some logic that disables all of our gateways if one of those versions is bad.

Some of our gateways work just fine on the older versions, though, so I'd like to figure out exactly which of our gateways require which versions of PHP and WC, and then fine tune the logic so that any gateways compatible on the current server environment will be available, and the rest will be disabled.

Also, if we can, it would be better to still show the gateways in the Checkout settings, but if a gateway is disabled we would add a message notifying them why it's not available.

**Comment by kcppdevelopers** [comment]
@angelleye  yes, we've apparently added some logic that disables all of our gateways if Woo version is below 2.6 version. PayPal Rest SDK required 5.3.0 >= PHP version and Braintree SDK required 5.4.0 >= PHP version.

Please let me know your feedback on this.

**Comment by angelleye** [comment]
@kcppdevelopers Okay, so in this example I don't want to completely hide the REST and Braintree gateways.  Instead, I'd like to continue to display them, but show them as disabled with a message that "This gateway requires WooCommerce 2.6 or higher and PHP 5.3 or higher."

Also, it seems that all of the other gateways are getting hidden as well even though they don't have this requirement..??  Any gateways that would be compatible should still be available at all times.
