### ISSUE TITLE
Authorization / Sale

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#642]
Right now we have a setting under each gateway that lets you choose whether or not the checkout should use Authorization / Sale / Order.  It would be nice to have this at the product level instead of the gateway setting level.

For example, I may want to have most of my stuff run as Sale, but I may have 1 particular product that I'd like to setup as Authorization with a billing agreement just so I can generate a billing agreement ID.  In fact, with that example we should be able to create a billing agreement without an authorization at all.

The point is I think I'd like to see something like leaving the setting under the gateway options like we have now, but then also add a product level option that would override the gateway option if that product is included in the cart.

**Comment by gine** [comment]
nice idea but.. what if a product have auth and what  if one order?

**Comment by angelleye** [comment]
Not sure I understand your question..??

**Comment by gine** [comment]
if you set the payment at gateway configuration you have a unique gateway payment method. if you set the payment at each product, if a buyer buy more than 1 product, you can have more than 1 gateway payment method.

**Comment by angelleye** [comment]
Ah, yeah.  We'll have to look into this more.  I just wanted to get the issue created so I didn't forget about it altogether.  :)
