### ISSUE TITLE
Express Checkout - Woo Smart Coupons Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#643]
* https://mail.google.com/mail/u/0/#inbox/15aa0d5c45245857

>1. If they pay via paypal express (using your plugin), they never see the 'where to send the coupon' form so the store credit is never generated. I can get the form to show on the cart page, however it still does not trigger the store credit coupon to be created if using Paypal Express.

>2. Even if they fill in the 'where to send the store credit' form on the checkout page and use the Paypal Express payment option, the store credit coupon is not generated.

**Comment by kcppdevelopers** [comment]
#356
