### ISSUE TITLE
Add "Custom Class" field for the Buttons/Links 

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/paypal-woocommerce#644]
Right now I am facing problem with Button styles.
I look into the code and found that there are **Inline CSS**  in the A tag and Img tags
Here is the File I found inline css 
**/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php**
It may be in other files also.

Because of the inline css , custom css is not working without adding **!important** .

If we remove all the inline css , and give user to add just Classes according to the theme they used then it will be very easy to use this images/links in every themes.
they can easily move and place the img/links also it will match with themes.
For every Button we can add Custom CSS input field where user add class name of particular theme and no need to worry about css work.

**Comment by angelleye** [comment]
@kcppdevelopers Thoughts on this?

**Comment by kcppdevelopers** [comment]
Yes, it would be great to have class attribute instead of inline CSS. I will change it soon.
