### ISSUE TITLE
Braintree - Translation Fix Necessary..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#649]
* https://mail.google.com/mail/u/0/#inbox/15b1ebeff89efddd

>	Dear Sir or Madam,
I just found a tiny bug in your "wc-gateway-braintree-angelleye.php" file of the "PayPal for Woocommerce"-plugin.
Please update following changes, so the credit-card form is correctly translated by the woocommerce language packs. Otherwise the translation does not work and the form remains in English.
Thank you!
Christoph

>( 'Card code', 'woocommerce' )
to
( 'Card Code', 'woocommerce' )

>( 'Card number', 'woocommerce' )
to
( 'Card Number', 'woocommerce' )

**Comment by kcppdevelopers** [comment]
https://github.com/woocommerce/woocommerce/blob/master/includes/gateways/class-wc-payment-gateway-cc.php#L54

https://github.com/woocommerce/woocommerce/blob/master/includes/gateways/class-wc-payment-gateway-cc.php#L60

@angelleye we have used same credit card field name as Woo, still need to change as per user request?

**Comment by angelleye** [comment]
In that case we will leave it as-is.
