### ISSUE TITLE
WooCommerce Autoresponder Compatibility..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#650]
* https://www.angelleye.com/support/scp/tickets.php?id=1025

**Comment by tejasm-itpath** [comment]
@angelleye 
I installed linked plugin but it is full of errors , https://www.screencast.com/t/O4aBABIwYMX

**Comment by angelleye** [comment]
@tejasm-itpath Those look like notices that may just be from the fact that you haven't saved any settings yet.  Did you try to go ahead and configure the plugin and run some tests with it?

**Comment by tejasm-itpath** [comment]
@angelleye 
No , I haven't configure that plugin, But when I installed this plugin shows "Headers already sent" error and then I moved to the setting page it display  notices so that I thought that older version have some errors like this. 
I am going to configure and let you know.

**Comment by angelleye** [comment]
@tejasm-itpath Yeah, I think this is a case where they were a little bit slippy with their development, and just expect that most people aren't going to have PHP notices being displayed (which is the case on most live servers) so they didn't bother cleaning up those problems.  I think you may find after you configure the plugin those notices will go away since it now has data filled in to their settings, and then we can see if we're able to reproduce problems with compatibility here.

**Comment by tejasm-itpath** [comment]
@angelleye  
I have tested our plugin with WooCommerce Autoresponder. And it is working for Mailchimp but not working with GetResponse.
My setup is with Mailchimp and Getresponse https://www.screencast.com/t/1brucmZEw7m
In global Setup I have selected **Subscribe user when Order Created**
It shows my user in the Mailchimp list 
Mailchimp : https://www.screencast.com/t/TSfWBzg6D

**Comment by tejasm-itpath** [comment]
@angelleye  
GetResponse is also not working with PayPal Standard so I think it is not issue from our plugin

**Comment by angelleye** [comment]
Okay, I'll just close the issue then.  I also updated the customer in our help system.
