### ISSUE TITLE
Woocommerce 3.0 

### ISSUE THREAD

**Issue by Ketique** [angelleye/paypal-woocommerce#654]
Now that I installed the new update for Woocommerce I cannot add new products.  When creating a new product, you cannot add the Inventory number or id.  You cant add an image like before it's totally different.  I cannot add the product tags.  I cannot make changes to any product with this new update.

Also, the cart page no longer has the word checkout on it.  In order for a customer to find checkout they need to search on my menu.

**Comment by angelleye** [comment]
Those don't sound like issues that would involve our plugin.  Are you saying that if you disable our plugin all of that stuff works again?

**Comment by angelleye** [comment]
Ref #653
