### ISSUE TITLE
paypal-for-woocommerce.pot is not working translate button

### ISSUE THREAD

**Issue by lukasprelovsky** [angelleye/paypal-woocommerce#655]
Hi, I wanted to translate button proceed to PayPal but it does not work. paypal-for-woocommerce.pot is wrong, it does not translate over poedit.

Try.

I need to translate only this one phrase, it requires by law.

**Comment by angelleye** [comment]
We are currently working on the 1.4.0 update which will include quite a few changes to the default.po file.  I would wait until that's ready, which should be within a week or so.  We'll be testing the new .pot file that comes with it, of course, to ensure it's ready to go.

**Comment by angelleye** [comment]
We have not had any reports of problems with our language files since latest updates, so closing this issue.
