### ISSUE TITLE
PayPal Express Checkout not picking up address

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#656]
@tejasm-itpath  can you please add this to our fix list for version 1.4.0?

 I have enabled Express Checkout again, but the problem persists: multiple addresses are configured on the sandbox individual account, but they are not captured during the checkout route Cart -> PP Gateway -> return to Order Review. The Account Holder name is captured, but not the address. 
Thanks

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial For this plugin the lead developer is @kcppdevelopers.

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial During checkout, are you choosing one of the addresses listed on the account?  Do you  happen to be testing with a product that does not require shipping?

**Comment by angelleye** [comment]
I think we just fixed this in #722
