### ISSUE TITLE
PayPal Express: shipping name change to billing name after successful order

### ISSUE THREAD

**Issue by LeopoldKing** [angelleye/paypal-woocommerce#658]
Hi folks,

whenever I'm buying sth. in my demo shop, I figure out that PayPal is returning the right information about the shipping & billing address. But whenever I hit the button "Buy now" to process the payment, sth. changes the shipping name, so that billing and shipping name are identical.

I was searching for any clue the last few days but couldn't find a helping straw to fix this. Any ideas?

Cheers,
Leopold

**Comment by angelleye** [comment]
Sorry for the delay responding.  Just saw this message.  In the Express Checkout settings there is an option to set the billing to the same address PayPal gives you.  Please check to see if this is enabled or not.

**Comment by angelleye** [comment]
@kcppdevelopers This may be related to some of the billing/shipping address problems we adjusted in 1.4.5, but please review this and make sure it's good now.  If so you can't mark it as "wontfix" and close it please.

**Comment by kcppdevelopers** [comment]
I double checked and found it's working fine for me.
