### ISSUE TITLE
Payments Pro (PayFlow) - Invalid Vendor

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#661]
* https://wordpress.org/support/topic/payment-error-26-invalid-vendor-account-2
* https://wordpress.org/support/topic/merchantvendor-credentials-not-saved-in-1-4-0/
* https://mail.google.com/mail/u/0/#inbox/15bc5fe67ceda4d9

Reports that after the 1.4.0 update the PayFlow API calls started failing with Error 26 - Invalid Vendor Account, but they never had this error using the same settings before.

Sounds like we need to check if we messed something up with sandbox vs. live settings maybe..??

**Comment by angelleye** [comment]
@kcppdevelopers I was able to confirm this with a simple test.  Seems that when we save the PayFlow settings page now the API credential values are getting stored as tokenized values of some sort..??

**Comment by kcppdevelopers** [comment]
@angelleye #622 we have applied API Credentials Storage Improvements to all the payment methods of our payment gateway. somehow in the Payflow payment method hooks called twice so Payflow payment method credentials encrypt two times. Now I have resolved issue and it's working fine.
