### ISSUE TITLE
Express Checkout - Button not showing up on cart page..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#662]
* https://wordpress.org/support/topic/help-paypal-express-button-disappeared-from-cart
* https://wordpress.org/support/topic/the-express-button-doesnt-show-on-cart-page/
* https://www.angelleye.com/support/scp/tickets.php?id=1118
* https://wordpress.org/support/topic/address-not-obtained-from-paypal-during-express-checkout/

**Comment by kcppdevelopers** [comment]
I have try no. of time to reproduce issue, but  I’m not able to reproduce this. it would be great to have website login credentials to more troubleshot.

**Comment by angelleye** [comment]
We've got multiple people in this thread saying it's happening, and I believe I've already seen other threads with the same issue, too.  We're going to need to dig deeper here.

**Comment by angelleye** [comment]
Here is a ticket where more details have been provided and I have asked for login credentials:  https://www.angelleye.com/support/scp/tickets.php?id=1104

**Comment by angelleye** [comment]
@kcppdevelopers I see a commit here.  Is this one done?

**Comment by kcppdevelopers** [comment]
No, issue is not resolved. I just added logic for mini cart ( widget express checkout button )

**Comment by angelleye** [comment]
I have responded to the original reports of this asking if somebody can give us direct access to their site for troubleshooting.  I agree this is odd since we can't reproduce it, but we have numerous reports of this in these linked tickets as well as others.
