### ISSUE TITLE
Express Checkout - Problem with hiding regular checkout button..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#665]
* https://wordpress.org/support/topic/problem-with-update-15

Remember we had logic in place where if EC was the only gateway enabled it would turn the "checkout" button into the "PayPal" button and send them straight to PayPal.  Seems something is wrong there with our 1.4.0 update.

**Comment by angelleye** [comment]
Re-opening because the user that reported this says it's still happening in our release branch.

**Comment by kcppdevelopers** [comment]
@angelleye Can you please submit support ticket with website login credentials?

**Comment by angelleye** [comment]
@kcppdevelopers I've asked for it, waiting for reply.

**Comment by angelleye** [comment]
Going to go ahead and close this for now since the commits we've done here have been included in release.
