### ISSUE TITLE
Express Checkout - Review Page Issues

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#666]
* https://wordpress.org/support/topic/redirect-to-review-order-issue
* https://www.angelleye.com/support/scp/tickets.php?id=1102

User reporting that if the buyer is logged in to the website then the review page works fine and checkout can complete, but if the buyer is not logged in to the site the review page does not load properly.

**Comment by kcppdevelopers** [comment]
https://wpml.org/forums/topic/rest-api-doesnt-work-with-use-directory-for-default-language/#post-562786

It seems this issue is from WPML  or Woocommerce Multilingual plugin.

I have checked support ticket and found that if we add /en/ after website URL then it's working fine for me.

**Comment by angelleye** [comment]
@kcppdevelopers Why is this something that wasn't an issue in 1.3.3 then?

**Comment by kcppdevelopers** [comment]
we have rebuild express checkout and follow WooCoomerce standard. 

https://wordpress.org/support/topic/there-is-no-listener-at-wc-apiwc_gateway_paypal-but-works-at-wc-apiwc_gateway/
https://wordpress.org/support/topic/polylang-conflicting-with-woocommerce-paypal-checkout/?replies=5
https://wordpress.org/support/topic/polylang-put-an-en-on-my-home-page-and-it-unreachable/  

I have read above support ticket and found that WC()->api_request_url not working well with Polylang plugin.
