### ISSUE TITLE
Express Checkout - PHP Notices about Undefined Variable ec_html_button

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#672]
* https://www.angelleye.com/support/scp/tickets.php?id=1103

Lots of reports, too, that the buttons simply aren't showing up for people.  So I think those people are having this same problem, but they just don't have PHP  notices enabled so they aren't seeing it.  

So something seems to be up with our ec_html_button setting in general.

**Comment by kcppdevelopers** [comment]
I am sure she is using our 1.3.3 version or lower version with latest WooCoomerce version. Can you please ask to upgrade PayPal for Woocommerce version to resolved issue?
