### ISSUE TITLE
Express Checkout - Create Order missing argument..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#673]
* https://www.angelleye.com/support/scp/tickets.php?id=1084
* https://www.angelleye.com/support/scp/tickets.php?id=1085

![image](https://cloud.githubusercontent.com/assets/629241/25645569/f401d9bc-2f74-11e7-84e8-9680d5624825.png)

**Comment by kcppdevelopers** [comment]
@angelleye we have already resolved this issue in the 1.4 version. I am sure they are using 1.3.3 version of PayPal for Woocommerce.

**Comment by kcppdevelopers** [comment]
I am sure she is using our 1.3.3 version or lower version with latest WooCoomerce version. Can you please ask to upgrade PayPal for Woocommerce version to resolved issue?

**Comment by angelleye** [comment]
@kcppdevelopers I thought our 1.4.0 update was backwards compatible..??

**Comment by kcppdevelopers** [comment]
yes you are right, our plugin also backwards compatible but our 1.3.3 version is not compatible with latest version of Woocommerce plugin.

**Comment by angelleye** [comment]
Oh, sorry, I misunderstood.  I'll check.
