### ISSUE TITLE
Express Checkout - Button overlapping with Add to Cart..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#683]
* https://wordpress.org/support/topic/after-update-on-product-pages-chrome-browser-button-overlap/
* https://www.angelleye.com/support/scp/tickets.php?id=1115

I let him know this could be a theme issue, but since he didn't have the problem before we may want to see if there's something we did that can be adjusted or not.

**Comment by kcppdevelopers** [comment]
@angelleye  

I have tested with below browser and it's working fine for me.

Google Chrome: https://www.screencast.com/t/dIkkrJRRV6bA
Firefox Mozilla: https://www.screencast.com/t/WzTESekXVQuB
Microsoft Edge : https://www.screencast.com/t/JhsVGaMMEyiL

Please ask user to clear browser cache and re-check again?
