### ISSUE TITLE
Express Checkout - Displaying on checkout page when it shouldn't..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#688]
* https://wordpress.org/support/topic/do-not-display-on-checkout-page/

**Comment by angelleye** [comment]
I think this guy is confusing PayPal Plus and Express Checkout because he has both plugins installed.  May not be anything we need to fix here.

**Comment by angelleye** [comment]
Looks like you saw it...I didn't realize EC was indeed displaying on his checkout page even with it disabled in the settings.

**Comment by kcppdevelopers** [comment]
@angelleye  yes I am already working on.. will resolve it very soon
