### ISSUE TITLE
Styling Issue

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#689]
@angelleye 

Please take a look at following screen, using flatsome theme button placement is not proper, it's overriding the SKU border. Please take a look at screenshot, here is URL for testing too
Browser Chrome 64-bit Latest
https://goo.gl/zY1WIp

![image](https://cloud.githubusercontent.com/assets/11312949/25742949/60c30cc8-31ab-11e7-92f5-c342d7f5eaf3.png)

**Comment by angelleye** [comment]
@kcppdevelopers Not sure if there's something we can do about this or if we need to tell them to adjust it in their theme..??

**Comment by MansoorAliKhanOfficial** [comment]
On MS EDGE 
Theme Twenty Seventeen

![image](https://cloud.githubusercontent.com/assets/11312949/25743448/e4173124-31ad-11e7-916e-7a3c0f23092f.png)
Cart Page:
![image](https://cloud.githubusercontent.com/assets/11312949/25743496/24397f50-31ae-11e7-9b43-8c14978fa9ca.png)

Both button should be same style and on cart page top: both should be inline. Its showing same on chrome ( 64 bit latets ) and Firefox ( latest )

**Comment by MansoorAliKhanOfficial** [comment]
@kcppdevelopers 
using with flat some team the top button takes Float left, I think the class name for paypal credit shout be Paypal_checkout_credit_button not paypal_checkout_button and then it should not have float left
![image](https://cloud.githubusercontent.com/assets/11312949/25769634/4ba1812a-3238-11e7-8f61-bbb802112707.png)
