### ISSUE TITLE
Express Checkout - Lots of styling issues being reported.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#692]
* https://wordpress.org/support/topic/problem-with-update-15/

I'm seeing lots of stuff like this after our 1.4.x updates.  Previously this would come up sometimes, and I would tell people they need to fix the styling in their theme, which they could usually do just fine.  Somehow, though, we had our stuff working well in most themes without the need for adjustment.  Something we've done seems to be causing the need for more adjustments in more themes.

>It’s OK – I disabled my caching plugin and cleared the cache and the problem has gone.

>The only issue I now have is that the PayPal Express checkout button on the product page has moved.

>It should underneath the “Add to Basket” button.

>Also on one site is has made the custom image tiny and on the other site it has put a purple border round the image.

>See here:

>http://ibb.co/cuvVJ5

>http://ibb.co/mvpCWQ

It’s not a massive problem as I have disabled itnow on the product page, but it would be nice to get a fix.

**Comment by angelleye** [comment]
@kcppdevelopers I wonder if we could add some simple options into settings that would give you the ability to easily add padding/margin/height/width attributes to the PayPal buttons..??

* https://mail.google.com/mail/u/0/#inbox/15bab6ef49b59a3b

**Comment by MansoorAliKhanOfficial** [comment]
I agree to this, and also if we could enhance the interface for our payment gateways that will also be great, and another important thing  , just like woocommerce, if we were able to make a basic setup navigator to jumps start the basic setup soon after our plugin is activated.

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial A setup navigator is a good idea, but not something we'll do in 1.4.3.  1.4.3 needs to focus on stability with current features.  Then we can improve documentation, setup wizards, etc. in future updates.

**Comment by kcppdevelopers** [comment]
https://www.screencast.com/t/qaeV8t22AUn

I have test with above screenshot themes and applied some CSS changes.

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial  Can you please test with some other themes and re-generate CSS issue?

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial Did you get a chance to test this after Jignesh made these last changes?

@kcppdevelopers It looks like you tested with quite a few different themes.  I would guess that you're confident things are working smoothly at this point..??

**Comment by kcppdevelopers** [comment]
@angelleye yes, now I am confident things are working smoothly at this point. I have checked this issue with 26+ developed by woo themes.  @MansoorAliKhanOfficial still working on it.
