### ISSUE TITLE
PayPal Credit Button not showing on product detail page

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#694]
this button only show on cart / checkout page only? I think it should also be displayed on product detail page as well. What do you think?

![img_05052017_161950_0](https://cloud.githubusercontent.com/assets/11312949/25769695/e6395112-3239-11e7-98c2-b51442eb7c21.png)

**Comment by angelleye** [comment]
It tends to get a little busy on the product detail page, especially if/when you also have things like Offer buttons enabled.  People can still use PayPal Credit when clicking on the normal button, so we left the actual Credit button off here.

It's a good idea to add it back, though, and provide the option for people, so we'll do this in a future milestone.

**Comment by angelleye** [comment]
Duplicate #741
