### ISSUE TITLE
Express Checkout - PHP Fatal Error - call to a member function get()

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#697]
* https://wordpress.org/support/topic/fatal-error-call-to-a-member-function-get

**Comment by MansoorAliKhanOfficial** [comment]
HI @angelleye  I tried to install 1.3.2 first then , using normal update from plugins, updated it to latest version and not issue found, the issue seems like a server side issue which shows 500 internal server error. may be he is using someother plugins which might be using the same function which might be conflicting.

need to check on client site specifically. right @kcppdevelopers ??

**Comment by kcppdevelopers** [comment]
right, I followed same step but everything is working. but I have changed some logic to prevent this type of error.

**Comment by MansoorAliKhanOfficial** [comment]
okay thats great.

**Comment by kcppdevelopers** [comment]
In the WordPress support ticket cdixonsu said Fatal error: Call to a member function get() on null in /wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye.php on line 276  I have checked and found that get function is not available on 276 line.

**Comment by MansoorAliKhanOfficial** [comment]
yes, sometime the issue is different that the debugger showing...

if you try to reverse engineer from line 276 to the origina you may get something....

**Comment by angelleye** [comment]
@kcppdevelopers I'm a bit confused.  Another issue is marked as duplicate and references this issue, and this issue does show a commit, but it's almost marked as "wontfix"..??

**Comment by kcppdevelopers** [comment]
@angelleye me and @MansoorAliKhanOfficial  both have try to re-generate issue but it's working fine. but I have changed some code to prevent this type of error.

**Comment by kcppdevelopers** [comment]
@angelleye issue 697 and issue-693 both are same. please read support details for more information.

**Comment by angelleye** [comment]
@kcppdevelopers So is this one ready for release then?

**Comment by kcppdevelopers** [comment]
@angelleye yes
