### ISSUE TITLE
Improvement: Page Styling options under express checkout and All Other

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#700]
![image](https://cloud.githubusercontent.com/assets/11312949/25779186/eb5423dc-332b-11e7-9628-05482e0a4f26.png)

As you can see in screenshot, these options should have a better presentation like
in page style: option 
{ 1= Default ( preselected)
  2= Custom }
On selecting custom the custom logo and other settings should show

Also, the page style Input field doesn't explain anything except seeing a link may be a better documentation could help clients use it a better way.

**Comment by angelleye** [comment]
Yup, better user experience in general in all of our gateway settings is needed.  Thanks for the feedback.  I think we may have some similar issues posted already.  We'll add this to a future milestone.
