### ISSUE TITLE
Express Checkout - EC button showing up on WC checkout page even when disabled..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#703]
* https://wordpress.org/support/topic/paypal-express-2-bugs/

**Comment by kcppdevelopers** [comment]
@angelleye  I double checked express checkout settings and it seems working fine.

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial Can you test this to verify that you are unable to reproduce this as well?

**Comment by MansoorAliKhanOfficial** [comment]
@angelleye  I Have tested all option and it seems to be working for me. tested on dev branch provided by Jignesh.

**Comment by angelleye** [comment]
Okay, I will move this to 1.4.4 for now.  I'd like to hear back from the user that reported this before we officially close it.
