### ISSUE TITLE
Express Checkout - Minicart 

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#704]
I think we need to move the check box option to save the payment method below the PayPal button instead of above it...

![image](https://cloud.githubusercontent.com/assets/629241/25834573/81b2447c-343e-11e7-81f5-3c58d27d54b8.png)

**Comment by angelleye** [comment]
Same for the product detail page:

![image](https://cloud.githubusercontent.com/assets/629241/25834627/e72dd578-343e-11e7-8022-78eed24a6129.png)

**Comment by kcppdevelopers** [comment]
@angelleye I think everywhere right? cart and checkout page as well.
