### ISSUE TITLE
Express Checkout - Cancel button missing from review page..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#705]
* https://www.angelleye.com/support/scp/tickets.php?id=1111

Towards the end of the ticket he tells us that before the 1.4.1 release he had this Cancel button on the review page:

![image](https://cloud.githubusercontent.com/assets/629241/25838914/fb368526-345a-11e7-9429-719acf557da0.png)

1.4.2 and release branch are missing the Cancel button..??

**Comment by kcppdevelopers** [comment]
I have miss order cancel button since 1.4.0 version.

**Comment by kcppdevelopers** [comment]
https://www.screencast.com/t/neKH5yuRi
