### ISSUE TITLE
Express Checkout - Bug in WC 3.0.6..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#712]
* https://wordpress.org/support/topic/paypal-error-at-checkout-from-woocommerce

Odd error and people are saying it's also happening with PayPal Standard.  I'm thinking this is on PayPal's end.

**Comment by kcppdevelopers** [comment]
I have checked everything from my end, but it seems working for me.

**Comment by kcppdevelopers** [comment]
https://github.com/woocommerce/woocommerce/issues/14956
