### ISSUE TITLE
Express Checkout - Payment method left off email notifications..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#713]
* https://www.angelleye.com/support/scp/tickets.php?id=1099

>I re-enabled EC and (very happily) received an EC order this afternoon. But the email has no “Payment Method” listed. Screenshot attached.

![image](https://cloud.githubusercontent.com/assets/629241/25931816/4341818e-35d4-11e7-8cf1-1dafc8531a16.png)

**Comment by kcppdevelopers** [comment]
#710

**Comment by angelleye** [comment]
@kcppdevelopers I'm a little confused.  #710 is about an error saying Invalid Payment Method as if the order failed.  This issue is for a user reporting that the order did work, but it simply left the payment method off the email notification.  So does #710 fix both of those things?  If so, how is this guy getting a successful order without the #710 fix in place?

**Comment by kcppdevelopers** [comment]
@angelleye when user has disable Skip Final Review then order review page display 'Invalid Payment Method' error message, but when user has enable Skip Final Review then  it simply left the payment method off the email notification. both issue are same.
