### ISSUE TITLE
Lots of PHP Notices in 1.4.3 related to incorrect usage of WC methods..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#715]
* https://www.angelleye.com/support/scp/tickets.php?id=1135

**Comment by kcppdevelopers** [comment]
I have checked everything and it's working fine for me. Can you please ask user to provide admin login details for more troubleshot?

**Comment by angelleye** [comment]
Asked for credentials...

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial Can you please help to generate issue?

**Comment by kcppdevelopers** [comment]
In the support ticket user said: 'I copied website to different URL and I don't get any error message now.'
