### ISSUE TITLE
Express Checkout - Styling issues with Flatsome theme in 1.4.3..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#716]
* https://wordpress.org/support/topic/theme-issues-after-updating-to-1-4-3/
* https://wordpress.org/support/topic/the-problem-after-update-to-1-4-2

**Comment by kcppdevelopers** [comment]
live site with 1.4.1 is: http://www.baremetics.com: https://www.screencast.com/t/sPzntNt8LVi
dev site with 1.4.3 is: dev.baremetics.com: https://www.screencast.com/t/PV86joFL87

It seems both website header html structure are different.

**Comment by angelleye** [comment]
@kcppdevelopers Take a look at the WP thread again please.  User provided a video showing that our plugin does seem to be causing his header issue.

**Comment by angelleye** [comment]
@kcppdevelopers Also added another report of this in the links above.
