### ISSUE TITLE
CSS stylesheet asset in header - extra slash

### ISSUE THREAD

**Issue by FrogStoneMedia** [angelleye/paypal-woocommerce#717]
`<link rel='stylesheet' id='angelleye-express-checkout-css-css'  href='https://www.domain.com/wp-content/plugins/paypal-for-woocommerce//assets/css/angelleye-express-checkout.css?ver=1.4.3' type='text/css' media='all' />`

Noticed there is an extra slash before //assets which shouldn't be there.

**Comment by angelleye** [comment]
Okay, thanks, we'll look into it!
