### ISSUE TITLE
Credit Card Validation Bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#719]
* https://mail.google.com/mail/u/0/#inbox/15bf909764362496

>We are using your plugin PayPal for WooCommerce.

>One of your recent updates corrupted the credentials we had entered for PayPal Pro Payflow.

>We have since restored those credentials.

>BUT, credit card checkout still isn't working.

>If there is a typo in the 3-digit security code, the website shows this error:

>SyntaxError: Unexpected token o in JSON at position 0

>If the credit card information is correct, the website shows this error:

>SyntaxError: Invalid character

**Comment by angelleye** [comment]
I have asked specifically which CC gateway they are working with and I'm waiting for a response on that, but we should probably just check each of them.

**Comment by kcppdevelopers** [comment]
I have checked website and found that they are using PayPal Pro payment gateway and not using our plugin.

**Comment by kcppdevelopers** [comment]
User telling us they are finding similar errors outside of payments, so they're looking into it
