### ISSUE TITLE
Express Checkout - More CSS Adjustments Necessary..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#720]
* https://www.angelleye.com/support/scp/tickets.php?id=1138

User mentions the following:

>After update 1.4.3 I'am only able to proceed payment throught Paypal express checkout button on cart page. Proceed to checkout button are not availabe(invisible). If I through css change that button to display: block, then I'am able to get to checkout

**Comment by kcppdevelopers** [comment]
@angelleye Remember we have logic in place where if EC was the only gateway enabled it would turn the "checkout" button into the "PayPal" button and send them straight to PayPal.

if user select below option we are not display express checkout in the general list. 
https://www.screencast.com/t/8N3gKJ2w
https://www.screencast.com/t/OQkmcQf5W7u

Can you please confirm above thing with user?

**Comment by angelleye** [comment]
Oh, I think I read his issue incorrectly.  I will follow up with the user on that.  Thanks.

**Comment by kcppdevelopers** [comment]
@angelleye Can you please follow up with the user?
