### ISSUE TITLE
Braintree - Company Name / DBA section must be 3, 7, or 12 characters..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#724]
* https://wordpress.org/support/topic/company-namedba-section-must-be-either-3-7-or-12-characters/

>I’m trying to collect money using the following: http://sanghata.net/shop/

>When I try to put an order through, I get the following error message:

>Error: PayPal Powered by Braintree was unable to complete the transaction. Please try again later or use another means of payment. Reason: Company name/DBA section must be either 3, 7 or 12 characters and the product descriptor can be up to 18, 14, or 9 characters respectively (with an * in between for a total descriptor name of 22 characters).

>I’ve searched high and low and can’t find how to fix this. I have no clue where the company name and product descriptor are. The one product has a short name Any ideas?

**Comment by kcppdevelopers** [comment]
Credit Card Statement Name:

The descriptor name is made up of two parts, company/DBA name and product separated by an asterisk (*). Some examples of valid descriptor names are:

• cmp*productdescription
• company*product name
• company name*myurl.com

Company name/DBA section must be either 3, 7 or 12 characters and the product descriptor can be up to 18, 14, or 9 characters respectively (with an * in between for a total descriptor name of 22 characters). You can only use alphanumeric characters, spaces, and periods in your dynamic descriptors. URLs can use alphanumeric characters and periods.
