### ISSUE TITLE
Credit Card Processing - Security code error handling failing.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#726]
* https://mail.google.com/mail/u/0/#inbox/15bf909764362496

Not sure if this is only related to security code field or any JSON result at all that would include an error, but this is how we can reproduce it.

Run a test for PayFlow, but enter an incorrect value for the security code.  For example, just enter a single character instead of 3.  What's happening is that we're getting an error back from PayPal because of the mis-matching CSC.  The JSON result looks like this:

`{"result":"failure","messages":"<ul class=\"woocommerce-error\">\n\t\t\t<li>Payment error: 114-CVV2 Mismatch: 15004-This transaction cannot be processed. Please enter a valid Credit Card Verification Number.<\/li>\n\t<\/ul>\n","refresh":false,"reload":false}`

So the error from PayPal is 15004 - Please enter a valid Credit Card Verification Number, which is what should be getting displayed back on the screen instead of that weird JSON error.  It looks like the error value in the JSON string is including some extra HTML junk, though, and that's causing the JSON string itself to be invalid. 

We need to fix this in PayFlow and also check all the other gateways, too, to make sure the same thing isn't happening there.

**Comment by kcppdevelopers** [comment]
For me it's working well: https://www.screencast.com/t/JLcx7FcEpuVT

**Comment by kcppdevelopers** [comment]
It seems other plugins conflict with our plugin, Can you please ask user to provide website URL for more troubleshoot?

**Comment by angelleye** [comment]
@kcppdevelopers maybe the form validation form #735 fixes this..??

**Comment by angelleye** [comment]
I guess we'd still need to know why the JSON result was invalid.  I'll ask them to provide info for us to test that.

**Comment by angelleye** [comment]
Responded to the user asking for direct access.
