### ISSUE TITLE
PayFlow - Refunds Failing

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#727]
* https://wordpress.org/support/topic/issue-refunds-paypal-pro/

>I may have overlooked this information somewhere. But, for PP Pro, are we allowed to issue refunds through the Admin? I can issue refunds for PP Express but not PP Pro. For PP Pro, the plugin says “Invalid Account Number”.

**Comment by kcppdevelopers** [comment]
@angelleye I have checked PayPal Pro and PayPal Payflow both payment method are working well with refund. Can you please ask to user to provide Website admin login details for more troubleshot?
