### ISSUE TITLE
Auth & Capture Adjustments Necessary..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#730]
* https://www.angelleye.com/support/scp/tickets.php?id=1157

>I just set up Paypal Express and, after checking out with a sandbox account, in the order screen, I can choose "capture" or "void" transaction. There is no option for partial capture. There is also no option to create a new transaction (after capturing an order in full).

Seems EC lost the ability to do multiple partial captures..??

**Comment by angelleye** [comment]
Same user says they are having the same problem with Payments Pro:

>Thank-you so much!  I also wanted to let you know that I successfully set up Paypal payments Pro (Payflow) and there is no option to capture at all in the order(I'm hoping to be able to capture, partial capture, and create new transactions for this one as well).

**Comment by kcppdevelopers** [comment]
@angelleye we have developed DoAuthorization, DoReauthorization, DoCapture, DoVoid functionality in the admin order screen only for express checkout and PayPal Pro not for others payment method like (PayPal Payments Pro 2.0 (PayFlow) and PayPal Advanced).

**Comment by angelleye** [comment]
@kcppdevelopers Oh, wow, I wasn't aware of that.  I thought we had it built in for all gateways.  How long would it take to get this done for PayFlow?
