### ISSUE TITLE
Express Checkout - PayPal Email Custom Field Missing in 1.4.x

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#733]
* https://wordpress.org/support/topic/paypal-email-not-saved-to-order

In previous versions of our plugin we were saving the PayPal email address for the buyer to a custom field in WC called paypal_email:

![image](https://cloud.githubusercontent.com/assets/629241/26034166/f7e68ce6-387d-11e7-877f-488ceca5f689.png)

With 1.4.x this is no longer getting saved that way.

**Comment by kcppdevelopers** [comment]
https://www.screencast.com/t/0PTNstO3
