### ISSUE TITLE
Express Checkout - Variations not passing over to PayPal like they did before..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#734]
* https://wordpress.org/support/topic/woocomerce-checkout-options/

**Comment by kcppdevelopers** [comment]
Product Page: https://www.screencast.com/t/JXJa1Q7OTda
PayPal Page: https://www.screencast.com/t/mWY1Svw76ap
Order Page: https://www.screencast.com/t/K29wiifVgn
@angelleye  for me it's working fine. Can you please ask user to provide website public URL?

**Comment by angelleye** [comment]
I have responded to the original thread asking for more details.

**Comment by turbokris** [comment]
I believe I may have encountered this scenario as well after a recent upgrade of multiple plugins.  Variable product variation details don't appear to be passed to paypal in the name(s) field.  However, strangely enough composite products do.  Standard paypal plugin also works as expected on all products types.

http://turbokeychains.com/express/order.jpg
http://turbokeychains.com/express/beforeupgrade.jpg
http://turbokeychains.com/express/afterupgrade.jpg
http://turbokeychains.com/express/log.jpg

Current environment:
PayPal for WooCommerce 1.4.5
WooCommerce 3.0.7
WooCommerce Composite Products 3.9.4

**Comment by angelleye** [comment]
Thanks for the feedback.  We just released the 1.4.5 update, and we'll be started on 1.4.6 very soon.  Keep your eye on this issue and you can pull the update as soon as you see it if you don't want to wait on the official 1.4.6 release.
