### ISSUE TITLE
Payments Pro - Invalid Payment Method

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#740]
In #710 we fixed this for Express Checkout, but we're seeing reports of the same thing in other gateways now.  We need to check all of our gateways to ensure this is fixed for good.

* https://www.angelleye.com/support/scp/tickets.php?id=1173

In this ticket the user is attempting to use Payments Pro (DoDirectPayment) with Woo Subscriptions, but they are getting the Invalid Payment Method error.

**Comment by kcppdevelopers** [comment]
@angelleye #710 and #740 both are different issue. this issue is related woocommerce subscriptions 2.2.6 compatibility issue. Can you please provide woocommerce subscriptions 2.2.6  version?

**Comment by angelleye** [comment]
@kcppdevelopers [woocommerce-subscriptions-2.2.6.zip](https://github.com/angelleye/paypal-woocommerce/files/1016757/woocommerce-subscriptions-2.2.6.zip)

**Comment by angelleye** [comment]
Update from user:

>We only want to use PayPal Pro. When it is the only payment method enabled, I see an Invalid payment method error on the checkout page. So far, I have only set up a subscription with one product for testing:

>http://dswidev.com/register/test-health-coach-certification-families-payment-plan/

>I have also tried disabling all plugins except WooCommerce, WooCommerce Subscriptions, and your PayPal plugin.
