### ISSUE TITLE
Express Checkout - Shipping Address Problems

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#743]
* https://wordpress.org/support/topic/dreaded-address1-is-required-error
* https://www.angelleye.com/support/scp/tickets.php?id=1185  <----  This one has credentials for site's WP admin, sandbox credentials, etc. so we can run tests directly and try to find the problem.
* https://www.angelleye.com/support/scp/tickets.php?id=1191

Seems to be more of the same as reported in previous issues that I thought we had resolved, but even on current release branch they're saying it's still not working.

**Comment by angelleye** [comment]
Another update from Tarkan in my email:

>One customer who is a repeat customer has told me that if he changes the shipping option on the cart page, and clicks on the Paypal express button but below the checkout button - this causes the error for him. He cleared the cookies and switched to another browser - and still he can trigger it by doing that.

**Comment by angelleye** [comment]
@kcppdevelopers Now another follow up from Tarkan, who was struggling to reproduce the problem himself but had customers reporting it...now he reproduced it himself:

>I managed to trigger the problem. Here are my steps -
 
>Visit site, add product to cart.
 
>Click on checkout - Do not fill in any details.  click on pay with paypal button at the bottom of the checkout form.
 
>You should get the 'There was a problem paying with PayPal. Please try another method.' error message.
 
>Now close the browser window, and re-open - visit site and click on any of the paypal express buttons (within products or direct from the mini-cart).
 
>You should get the 'There was a problem paying with PayPal. Please try another method.' error message.

**Comment by kcppdevelopers** [comment]
@angelleye It seems issue already resolved in the issue #735 branch. Can you please ask user to if they want to grab it early from here?

**Comment by angelleye** [comment]
I have responded to each thread asking them to apply our current release branch and verify whether or not it resolves their issue.
