### ISSUE TITLE
Express Checkout - Address still not getting saved after update that should have fixed it..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#745]
* https://www.angelleye.com/support/scp/tickets.php?id=1094

In #671 we made adjustments that were supposed to solve this, but the user says he updated and it's still not fixed.  WP credentials for the client site are available in the ticket if we need to troubleshoot directly.

**Comment by kcppdevelopers** [comment]
It seems issue already resolved in the issue #735 branch. Can you please ask user to if they want to grab it early from here?

**Comment by angelleye** [comment]
Asked user to apply current release branch to see if the issue is resolved.
