### ISSUE TITLE
Tools - Log Trash

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#750]
Under our Tools tab in the plugin settings we have the option to delete all log files saved by the plugin.  When you do this there is no message telling you that it's complete when finished.  It just reloads the page and you're left a little unsure if it actually did anything.  I'd like to add a basic admin note that says "Log files have been successfully deleted." when it's finished.

**Comment by kcppdevelopers** [comment]
@angelleye Now Woo provide functionality to delete log file: https://www.screencast.com/t/c7RBaDHOeHV2

Still need to remain our functionality or remove it?

**Comment by angelleye** [comment]
@kcppdevelopers Okay, yeah, we can remove ours then.
