### ISSUE TITLE
Braintree - Kount Fraud System

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#751]
* https://articles.braintreepayments.com/guides/fraud-tools/advanced/overview

**Comment by angelleye** [comment]
Kount has a "basic" and "advanced".  We need to tie in both and let people choose which option to use.

**Comment by angelleye** [comment]
@kcppdevelopers I see that we have a Fraud section and we have options for Basic or Advanced.  Does this correspond to the Standard and Custom options that they show in the Kount documentation?  Basic = Standard and Advanced = Custom?

Also, I don't see any way to leave Kount disabled entirely.  It seems I can only choose Basic or Advanced.  I think we should add "Disabled" which would be our default option.   Then they can specifically enable Basic or Advanced.

**Comment by kcppdevelopers** [comment]
@angelleye 

Basic = https://articles.braintreepayments.com/guides/fraud-tools/basic/overview
Advanced = https://articles.braintreepayments.com/guides/fraud-tools/advanced/kount-standard

**Comment by angelleye** [comment]
@kcppdevelopers Okay, thanks.  So we just need to add the "Disabled" option then as the default, so people have to turn on Basic or Advanced.
