### ISSUE TITLE
WPML Locale issue

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#754]
https://www.angelleye.com/support/scp/tickets.php?id=1198

Please take a look at this ticket , when WPML is activated a notice stating invalid index Locale in
plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 1160
shows. If deactivated WPML , this notice disappears.

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial This has been resolved and merged into release branch.  Please respond to the ticket link above.

**Comment by MansoorAliKhanOfficial** [comment]
@angelleye Thanks, I have sent the release branch to client n now waiting for reply. will update you soon on this.
