### ISSUE TITLE
Issue with woocommerce subscriptions

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#755]
Please take a look at the following ticket, 
https://www.angelleye.com/support/scp/tickets.php?id=1173

when both plugins are active WC-> settings show 500 internal server error.

> [31-May-2017 15:08:37 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Cart->init, WC_Cart->get_cart_from_session, WC_Product_Subscription->is_purchasable, WC_Product->is_purchasable, apply_filters('woocommerce_is_purchasable'), WP_Hook->apply_filters, call_user_func_array, my_woocommerce_is_purchasable, WC_Product_Subscription->__get, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
> [31-May-2017 15:10:38 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Cart->init, WC_Cart->get_cart_from_session, WC_Product_Subscription->is_purchasable, WC_Product->is_purchasable, apply_filters('woocommerce_is_purchasable'), WP_Hook->apply_filters, call_user_func_array, my_woocommerce_is_purchasable, WC_Product_Subscription->__get, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
> [31-May-2017 15:11:53 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Cart->init, WC_Cart->get_cart_from_session, WC_Product_Subscription->is_purchasable, WC_Product->is_purchasable, apply_filters('woocommerce_is_purchasable'), WP_Hook->apply_filters, call_user_func_array, my_woocommerce_is_purchasable, WC_Product_Subscription->__get, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
> [31-May-2017 15:12:00 UTC] PHP Fatal error:  Access level to WC_Gateway_PayPal_Pro_PayFlow_Subscriptions_AngellEYE::is_subscription() must be public (as in class WC_Gateway_PayPal_Pro_PayFlow_AngellEYE) in /home/drsear6/public_html/wp-content/plugins/paypal-for-woocommerce/classes/subscriptions/wc-gateway-paypal-pro-payflow-subscriptions-angelleye.php on line 87

**Comment by MansoorAliKhanOfficial** [comment]
we have already provided this client our release branch on 24th may, and she tested and reported the issue still not solved. Can you please take a look again?

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial #752 was just closed 7 days ago, so if the person downloaded the release branch on the 24th then they probably didn't have this fix included yet.  Please make sure they grab a fresh copy of the release branch and give it another try.

**Comment by MansoorAliKhanOfficial** [comment]
@angelleye Thanks for the update, I have replied to the client now waiting for their response. Will update if the issue is resolved or not.

**Comment by MansoorAliKhanOfficial** [comment]
The client has not replied so far, so shall we close this?

**Comment by angelleye** [comment]
Yes, closing for now.
