### ISSUE TITLE
WooCommerce Germanized: Compatibility

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#757]
@kcppdevelopers Please take a look at following tickte and th thread mentioned in the ticket.

https://www.angelleye.com/support/scp/tickets.php?id=1214

When Germanized plugins are enabled email sending is stopped somehow. and if disabled it works fine.

**Comment by kcppdevelopers** [comment]
I have checked staging website and found that order status is on-hold dua to Multi-currency payment. Reason is: ' You do not have a balance in the currency sent, and you do not have your Payment Receiving Preferences set to automatically convert and accept this payment. You must manually accept or deny this payment'


Need to changed account settings: Payment Receiving Preferences set to automatically convert and accept this payment

**Comment by angelleye** [comment]
@kcppdevelopers Can you clarify where it was that you saw this error information so that @MansoorAliKhanOfficial knows how to find that sort of thing in the future?

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial  https://www.screencast.com/t/2CPxleo4lD

**Comment by MansoorAliKhanOfficial** [comment]
hi I m going to reopen this issue again as I have received a new comment from the client. Please take a look here in the ticket.

https://www.angelleye.com/support/scp/tickets.php?id=1214
