### ISSUE TITLE
Woocommerce cart fields data format and duplication

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#759]
Can you please take a look at this.
https://www.angelleye.com/support/scp/tickets.php?id=1099

Client specific issue.

> 1. When a customer enters engraving text with LINE BREAKS, I do not see the line breaks in the order emails. Neither does the customer. Take a look at ***figurine urn*** orders in the WP Mail log and you will see examples of this.
> 
> 2. When customers order figurine urns, the list of options (add-ons) appears TWICE in the order emails. Again, have a look at the WP Mail log. Actually, “plate color” does not appear in the proper place, so some reason, only at the top of the email.
> 
> Issue 1 does not happen for Amazon payment orders
> Issue 2 does not happen for Amazon payment orders
> 
> Issue 1 does happen for Express Checkout orders
> Issue 2 does not happen for Express Checkout orders
> 
> Issue 1 does happen for credit card orders
> Issue 2 does happen for credit card orders

their dev site details are available in the ticket if you need to take a look.

**Comment by kcppdevelopers** [comment]
Issue #723

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial  I have already resolved above issue. I have used latest dev branch code in client website and issue has been resolved.
