### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#762]
* https://wordpress.org/support/topic/internal-server-error-on-latest-update

>Using WooCommerce 2.6.14 and utilizing PayPal standard checkout, and PayPal Pro for credit cards I am getting the following issue (causing checkout to break) when updating to 1.4.5.

>[07-Jun-2017 20:12:56 UTC] PHP Warning: Missing argument 2 for Angelleye_PayPal_Express_Checkout_Helper::angelleye_paypal_express_checkout_redirect_to_paypal() in /home/***/public_html/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye.php on line 157
[07-Jun-2017 20:12:56 UTC] PHP Fatal error: Call to a member function get_error_messages() on null in /home/***/public_html/wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye.php on line 158

**Comment by angelleye** [comment]
They said they reverted back to 1.4.4 and it's fine, so something in 1.4.5 caused this..??

**Comment by marpstar** [comment]
Seeing the same issue here after upgrading tonight. Reverting to 1.4.4 seems to be working for me.

**Comment by angelleye** [comment]
Okay, we'll get it fixed ASAP, thanks for the feedback!
