### ISSUE TITLE
Express Checkout - Review Page Adjustments

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#763]
* https://mail.google.com/mail/u/0/#inbox/15c833ebd723251a

In the 1.4.4 release (I can't seem to find the specific issue now) we adjusted the review page with Express Checkout so that it simply displays the billing and shipping details, but won't let you make any adjustments.  We did this because the review page was confusing for Express Checkout shoppers since it was showing the shipping under the billing address section, and then had a check box for "Ship to a different address" but they already selected the address...so this was confusing.

Now, though, I'm getting feedback that when people use Express Checkout Shortcut (from product page or cart page) then they  have no way to ever override the PayPal shipping address.  So they actually do want the option to "ship to a different address" at this point, but we just need to make sure the page as a whole makes sense for people.

So maybe we can do something like this..??  What if we display the billing information as static data the way it is now, but we let the shipping address form be displayed here and pre-populate it with the shipping address returned by PayPal.  This way the user can make adjustments if they want to, and of course if they do adjust the address at this point the shipping / tax calculations need to update accordingly.  Then when they submit the review page the final DECP request would include whatever address was currently filled out in that form.

**Comment by kcppdevelopers** [comment]
@angelleye  I have added new option in setting panel for 'Order Review Page Title' and added Edit link in order review page for edit billing address.

**Comment by kcppdevelopers** [comment]
https://www.screencast.com/t/rR9RewCGDZ

https://www.screencast.com/t/IZw43sPUKs

**Comment by angelleye** [comment]
@kcppdevelopers I think this will still be confusing.  In the second screenshot...

![image](https://user-images.githubusercontent.com/629241/29946767-3c7b5b40-8e6c-11e7-8262-33a068a28b0f.png)

Would I have to check the "Ship to a different address" box and click "Edit" to change the address?  What happens if I just click Edit without checking the box?  Why do we need both?  

I still think it would make more sense to display the shipping address as editable text fields pre-populated with the address returned by GECD.  Then if the user wants to make an adjustment they can just adjust the text fields.  Is that not doable?

**Comment by kcppdevelopers** [comment]
@angelleye Edit link we have added for edit billing address not for shipping address.

**Comment by kcppdevelopers** [comment]
@angelleye  

1) Screenshot for after click on 'Ship to a different address?' checkbox  : https://www.screencast.com/t/GB9ZHVjM

2) Screenshot for after click on Edit link : https://www.screencast.com/t/TsEytgt7p

**Comment by angelleye** [comment]
@kcppdevelopers It seems a little bit stranded right there in the middle of them.  Hard to tell what exactly that Edit link is for.  Is that something we're controlling placement of?  If so, shouldn't it go under the billing address?

**Comment by angelleye** [comment]
@kcppdevelopers okay, yeah those last screenshots look better.

**Comment by angelleye** [comment]
@kcppdevelopers Seems this one is related to #848 so I'm going to wait to review this one until that's cleared up.  Please mark this ready for review again once the EC review page is working properly.

**Comment by angelleye** [comment]
@kcppdevelopers This looks good now except that we don't have a label for "Shipping Details"...

![image](https://user-images.githubusercontent.com/629241/30156563-a049792c-9385-11e7-8b4a-caea253d337b.png)

I'd also like the labels to be adjusted for capitalization.

- Billing Details
- Shipping Details

**Comment by kcppdevelopers** [comment]
I have added "Shipping Details" label in  issue #793 https://www.screencast.com/t/rHSanz2mTIu

Billing Details and Shipping Details capitalization is not possible because it's default text of woo. https://www.screencast.com/t/x2bo8zijG8bU
