### ISSUE TITLE
Still having problems with Address1..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#765]
* https://mail.google.com/mail/u/0/#inbox/15c8962d7fcef8a3

>	How do resolve this issue? We get an email without any customer information? How are we suppose to troubleshoot or even call the customer.

>Our customer can't even place an order on our website without entering the Shipping Address.

>PayPal SetExpressCheckout API call failed
Detailed Error Message: The field Shipping Address1 is required
Short Error Message: Shipping Address1 Empty
Error Code: 10727
Error Severity Code: Error

They verified they are running 1.4.5 and they have cleared all cache / CDN tools.

**Comment by angelleye** [comment]
>We are using Paypal Express only from your Plugin.
 
>We have it enabled have another Plugin to disable Paypal and Authorize.net if the shipping is not in the United States.
 
>We have about 10+ emails throwing the error and 1 customer called us.
 
>We have a lot of orders that processed ok. 
 
>I dumped the cache one more time…
 
>We are going to see if it occurs again.
 
>We have been getting these errors before the Plugin installed mentioned above.

**Comment by angelleye** [comment]
They seem to be unable to reproduce this themselves, and they didn't have logging enabled, so we can't review a log file.  They have now enabled logging so they're going to send me the log if it happens again.

**Comment by angelleye** [comment]
More users reporting the same problems on 1.4.5

* https://wordpress.org/support/topic/paypal-express-checkout-error-notification-4/

**Comment by MansoorAliKhanOfficial** [comment]
https://wordpress.org/support/topic/paypal-express-checkout-error-notification-4/#post-9239441

This client replied back again, with the same issue as reported before, Is this linked to some cache issues? as He said it worked for one then pop up again.?

**Comment by angelleye** [comment]
It sounds like it could either be a caching issue or something about different methods of checking out with Express Checkout.  For example, maybe it's working fine when checking out from the product page or cart page, but fails when the WC checkout page is used, or vice-versa..??
