### ISSUE TITLE
Express Checkout - PayPal Credit on product pages needs CSS adjustment..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#766]
In #741 we added the PayPal Credit button to the product pages, but the CSS isn't aligning things very well...

![image](https://user-images.githubusercontent.com/629241/26952968-6dff70b6-4c6d-11e7-922c-79468a6024f3.png)

I know some theme CSS could affect this, but by default it seems we should be able to make those line up more evenly next to each other..??

**Comment by kcppdevelopers** [comment]
![766](https://user-images.githubusercontent.com/13145461/33201847-37d8af10-d120-11e7-8c91-91f8af7b97ad.png)
