### ISSUE TITLE
Payments Pro - Odd Problems Reported by User

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#776]
* https://mail.google.com/mail/u/0/#inbox/15c8e8d3a76866a9

I think we dealt with some of this on #740 but they've come back with more feedback...

> I tried several times today to checkout with the test product I set up ($1.00/day for 5 days): 
> https://dswidev.com/register/test-health-coach-certification-families-payment-plan
> 
> When I tried to check out, it looked like it didn't go through at all and I got an error: "Invalid or missing payment token fields."
> 
> So, I played around with a couple of the settings that I thought might be interfering. I'm attaching screenshots of each of the different changes I tried to the "Send line item details to PayPal" & "Enable Tokenized Payments" settings. I got a couple of different error messages with each change, as follows:
> 
> Settings 1 results in "Invalid or missing payment token fields."
> 
> Settings 2 results in "Invalid payment method."
> 
> Settings 3 results in "Invalid payment method."
> 
> Settings 4 results in "Invalid or missing payment token fields."
> 
> I also noticed that if I if turn off "Enable Tokenized Payments" that the credit card fields disappear on the checkout page.
> 
> Now here is where it gets truly odd. Despite the checkout not completing, we got 4 payment notifications from PayPal as the vendor, but as a customer we didn't receive any notification from PayPal or WooCommerce. This will be a real problem, because customers will think the payment didn't go through and will likely try to submit their order several times; resulting in several potentially large transactions.
> I am also attaching a copy of the PayPal Pro log ( wp-content/uploads/wc-logs/paypal-pro-7571872a998379783d67ee9fe1969648.log)
> 
> Please let us know if there are settings we need to change or how to fix this latest error.

The screenshots and log they referenced are available here:  [resubscriptioninvalidpaymentmethod545907.zip](https://github.com/angelleye/paypal-woocommerce/files/1068371/resubscriptioninvalidpaymentmethod545907.zip)

**Comment by kcppdevelopers** [comment]
We have already resolved this and confirm it is working well on client dev site.

**Comment by angelleye** [comment]
@kcppdevelopers Actually, these people are still having issues, but at this point we'll probably charge them for premium support.  (https://mail.google.com/mail/u/0/#inbox/15de78910301dbdb)

I'll move this to next milestone to avoid delays with this milestone.

**Comment by kcppdevelopers** [comment]
@angelleye Again I try multiple time but for me it's working..
