### ISSUE TITLE
Payment error: 15008

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#777]
**https://wordpress.org/support/topic/internal-server-error-on-latest-update/**

the client seen **Payment error: 15008** error when paying with credit card and the log shows 2 errors.

>     [L_ERRORCODE0] => 15008
>     [L_ERRORCODE1] => 10527
>     [L_SHORTMESSAGE0] => Invalid Data
>     [L_SHORTMESSAGE1] => Invalid Data
>     [L_LONGMESSAGE0] => This transaction has been completed, but the total of items in the cart did not match the total of all items.
>     [L_LONGMESSAGE1] => This transaction cannot be processed. Please enter a valid credit card number and type.
>     [L_SEVERITYCODE0] => Warning
>     [L_SEVERITYCODE1] => Error

I think client should get the correct error.

**Note:** this client have used the current release branch which fixed his previous error but this one popup.

**Comment by angelleye** [comment]
It seems two separate errors happened here, so PayPal returned both.  The first one is obvious.  They need to fix the credit card details.  For the cart total error we would need to see the log file provided by the plugin.  @MansoorAliKhanOfficial Please see if you can get that from the user.

**Comment by MansoorAliKhanOfficial** [comment]
@angelleye Previously he added the log transactions in the ticket from there I copied the message and sent it here, But I have requested full log, I will update you here when I will get that.

**Comment by kcppdevelopers** [comment]
Issue #781
