### ISSUE TITLE
Express Checkout : Order Review page

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#779]
Why I m seeing the Paypal Plus iframe on order review page?
Both Plugins are active PP for WOO and PP Plus for WOO.

![image](https://user-images.githubusercontent.com/11312949/27125550-1468a8e2-510e-11e7-9375-7bae6f09e590.png)

**Comment by angelleye** [comment]
Interesting indeed...
