### ISSUE TITLE
PHP Warnings and a Fatal Error in PayFlow..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#781]
* https://wordpress.org/support/topic/internal-server-error-when-submitting-credit-card-details-in-checkout

> Jun 15, 10:46:21
> 
> PHP Warning: Division by zero in /srv/users/serverpilot/apps/cleardog/public/wp-content/plugins/paypal-woocommerce-release/paypal-for-woocommerce.php on line 571
> 
> Jun 15, 10:46:21
> 
> PHP Warning: Division by zero in /srv/users/serverpilot/apps/cleardog/public/wp-content/plugins/paypal-woocommerce-release/paypal-for-woocommerce.php on line 576
> 
> Jun 15, 10:46:21
> 
> PHP Warning: Division by zero in /srv/users/serverpilot/apps/cleardog/public/wp-content/plugins/paypal-woocommerce-release/paypal-for-woocommerce.php on line 571
> 
> Jun 15, 10:46:21
> 
> PHP Warning: Division by zero in /srv/users/serverpilot/apps/cleardog/public/wp-content/plugins/paypal-woocommerce-release/paypal-for-woocommerce.php on line 576
> 
> Jun 15, 10:46:21
> 
> PHP Fatal error: Call to undefined function wc_get_logger() in /srv/users/serverpilot/apps/cleardog/public/wp-content/plugins/paypal-woocommerce-release/classes/wc-gateway-paypal-pro-payflow-angelleye.php on line 134

**Comment by MansoorAliKhanOfficial** [comment]
Is this issue fixed and reviewed?
Another client reported this 2 days ago.

> For the record, this thread matches my situation exactly. Removed/replaced the plugin with the latest release. Still getting the same errors. Caches have been checked/cleared, etc.
> 
> [Tue Jun 20 18:03:22.692840 2017] [:error] [pid 8527] PHP Warning: Division by zero in /wp-content/plugins/paypal-for-woocommerce/paypal-for-woocommerce.php on line 571
> 
> [Tue Jun 20 18:03:22.692912 2017] [:error] [pid 8527] PHP Warning: Division by zero in /wp-content/plugins/paypal-for-woocommerce/paypal-for-woocommerce.php on line 576
> 
> [Tue Jun 20 18:03:22.693416 2017] [:error] [pid 8527] PHP Fatal error: Call to undefined function wc_get_logger() in /wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-pro-payflow-angelleye.php on line 134
