### ISSUE TITLE
Express Checkout: Redirecting to cart page 

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#783]
Can you please take a look here, https://www.angelleye.com/support/scp/tickets.php?id=1270

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial It seems WP Engine Object/Transient/Page Cache issue, Can you please ask to disable it and recheck again?

**Comment by MansoorAliKhanOfficial** [comment]
Well, I have asked the client to do so, and they did but still, it's not working for them, As we discussed earlier and worked together the issue existed but at what part it exists is the real question. Either its us or the wpengine...

**Comment by MansoorAliKhanOfficial** [comment]
**UPDATE**: 
The issue was indeed from WPengine and here is what they did 

> Resolved the issue by excluding cookies with matching the following:
> wp_
> woocommerce_
> _stripe_ (although I don't think this one is necessary)

So everything start to work as expected. :)
