### ISSUE TITLE
Express Checkout : Credit Card Payments: Internal Server error

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#784]
Getting reports regarding internal server error 500 with CC payments.

- https://www.angelleye.com/support/scp/tickets.php?id=1280
- https://www.angelleye.com/support/scp/tickets.php?id=1279
- https://wordpress.org/support/topic/internal-server-error-when-submitting-credit-card-details-in-checkout/

**Comment by kcppdevelopers** [comment]
Issue #781
