### ISSUE TITLE
Subscriptions marked as "payment" instead of "subscription payment"..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#785]
* https://mail.google.com/mail/u/0/#inbox/15cb096d139fd975

> I have switched to your Paypal Plugin for WooCommerce, because the Pay Pal standard gateway didn't offer bank debits and for the Pay Pal reference ID we would need 3 x 10.000 € first. Your plugin worked instantly and smoothly and I really like that it has the modern paypal look, whereas the Paypal standard of WooCommerce looks like 1987 :) 
> 
> However, I wondered that the subscription orders created via the Paypal standard are declared as "subscription payment" and the new orders created via your plugin are not (just "payment"). Following you see our Paypal history, and the change that occured on 14 th of June, when I switched to your plugin: 
> 
> ![image](https://user-images.githubusercontent.com/629241/27247817-d41643f2-52c1-11e7-8a5b-4eb422c0be90.png)

**Comment by kcppdevelopers** [comment]
@angelleye Can you please explain with more details?

**Comment by angelleye** [comment]
@kcppdevelopers The screenshot provided here doesn't seem helpful, but apparently what the user is reporting is that with Woo Subscriptions + PayPal Standard the orders that get created say "Subscription Payment" in WC.  However, with our plugin they are just getting listed as "Payment".  

Can you verify this?

**Comment by kcppdevelopers** [comment]
@angelleye I have double checked and found that they are talking about PayPal history page not Woo order page.

We are using simple payment with billing agreement in express checkout and PayPal standard used PayPal subscription payment.
