### ISSUE TITLE
Braintree : BT Credit Card Button

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#787]
Do we have options to have Braintree credit card button next to EC button?
1- a client asked for this feature so just adding if possible.

**Comment by angelleye** [comment]
Not right now, no.  The braintree option (credit card) would require that you go through the WC checkout page, so for that case the user would just need to "Add to Cart" and then "Proceed to Checkout".  

We'll look into adding such an option for direct credit card payment methods.
