### ISSUE TITLE
Express Checkout - Billing Agreement Notice

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#788]
Need to provide notifications to people when setting up PayPal EC with billing agreements (either through product level option or Woo Subscriptions) that they have to get reference transactions enabled on their PayPal account in order for it to work.

**Comment by angelleye** [comment]
We can include this with #789 @kcppdevelopers

**Comment by kcppdevelopers** [comment]
@angelleye Can you please provide sample email text  for PayPal Billing Agreement Created Notification?

**Comment by angelleye** [comment]
@kcppdevelopers I don't think you understood what I'm after here.  This isn't an email notification.

Express Checkout Billing Agreements requires you to get that approved on your PayPal account before it will work.  If people simply enable billing agreements / Woo Subscription products on their site with EC, but they don't have BA's enabled, then the calls would simply fail.  

As such, I'd like to display a notice to the user when they enable EC billing agreements that...

"Express Checkout billing agreements / reference transactions require specific approval by PayPal.  Please contact PayPal to enable this feature before using it on your site."

We could trigger a basic admin notice when they check the "Enable Billing Agreement" box at the product level, and we would need to do something similar when the user sets up Express Checkout as part of Woo Subscriptions.
