### ISSUE TITLE
Express Checkout - Billing Agreement adjustment

### ISSUE THREAD

**Issue by kcppdevelopers** [angelleye/paypal-woocommerce#789]
* https://mail.google.com/mail/u/0/#inbox/15cb096d139fd975

**Comment by angelleye** [comment]
@kcppdevelopers Is this issue related to the problems we discussed where Express Checkout with Woo Subscriptions is not creating billing agreements like it should?

**Comment by kcppdevelopers** [comment]
@angelleye yes.

**Comment by angelleye** [comment]
We need some documentation that basically breaks down how this overrides other options...

- Enable Tokenized Payments in EC settings - Even if disabled, a Subscription product would still add a billing agreement to EC checkout.

- Options to "save payment method to my account" are hidden any time a subscription item is being purchased.  That option is simply enabled by default and is hidden during checkout.
