### ISSUE TITLE
Express Checkout - Woo Checkout Field Manager Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#791]
* https://wordpress.org/support/topic/shipping-insurance-option-does-not-appear-wpaypal-express/#post-9261892

Our review does not seem to be working with plugins like Woo Checkout Field Manager.

**Comment by kcppdevelopers** [comment]
@angelleye We have already applied few changes on checkout page, I have checked with WooCommerce Checkout Field Editor (Manager) Pro plugin it's working fine for me.
