### ISSUE TITLE
Express Checkout - Billing Address populated when it shouldn't be..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#793]
* https://www.angelleye.com/support/scp/tickets.php?id=1060

>while I have left the option 'Set billing address in WooCommerce using the address returned by PayPal" in the plugin config in WC -> Settings -> Paypal Express Checkout UNCHECKED, it still is added as a Billing address

**Comment by kcppdevelopers** [comment]
@angelleye I have checked issue and it's working fine for me.

**Comment by angelleye** [comment]
@kcppdevelopers I'm not sure how you tested this, but I was indeed able to reproduce the problem the user mentioned.

Just now I ran a test order on woo.angelleye.com using our current dev branch.  My settings are configured so that the option to "use the same address for billing as PayPal returns for shipping" is disabled in the gateway settings.

When I checkout, though, I do indeed see the Billing Address populated on the review page as well as on the final order details.

![image](https://user-images.githubusercontent.com/629241/30143677-c7e29402-934c-11e7-98f2-ea7f6ee88006.png)

Remember, PayPal only returns a billing name and email address, and then a shipping physical address.  So if the option to use the same address for billing is not enabled, we should not be getting the shipping address returned by PayPal filled in for Billing, but we are.

**Comment by kcppdevelopers** [comment]
@angelleye  you are right, we have also follow below WooCommerce setting.

https://www.screencast.com/t/KK4uFevK0dyJ
