### ISSUE TITLE
Express Checkout : Shipping Address adjustment 

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#794]
Please review this ticket for further understanding 
https://www.angelleye.com/support/scp/tickets.php?id=1319

> With Express Checkout the system doesn't know the address until they've signed in to PayPal and are returned...
> So it looks like we need to tie the WC triggers into our review page to deny checkout if the address isn't accepted by the site

Thanks

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial I am sure they using old version of our plugin. Our Latest version is working fine.

**Comment by angelleye** [comment]
We've asked the user to verify what version they are running, and we have yet to hear back.

**Comment by angelleye** [comment]
Never heard back from user, so closing this issue.
