### ISSUE TITLE
Order Received page adjustment..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#797]
I did a test order with Express Checkout using the WC checkout page.  When the order completes I'm left with this "order received" screen:

![image](https://user-images.githubusercontent.com/629241/27822174-6098c47a-606a-11e7-85e4-7ef945cc9b60.png)

It's odd that it's not displaying the billing and shipping address on this screen..??

Also, the "Thank you" message and the order number, date, total, etc. seem like they're smashed together and could use some spacing.  

Need to look into both of these things please.

**Comment by kcppdevelopers** [comment]
@angelleye  Order Received page/ Thank you page is not part of our Payment gateway. it is default functionality of WooCoomerce. It seems you have place order using guest checkout.

**Comment by MansoorAliKhanOfficial** [comment]
so in case of guest checkout , no address displayed? though on paypal login screen customer have to enter the address \

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial It seems that way.  @kcppdevelopers just ran another test using PayPal Standard (not part of our plugin) and it doesn't include the address info on the order complete page that way either.
