### ISSUE TITLE
Paypal guest checkout issue on mobile view

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#798]
https://www.angelleye.com/support/scp/tickets.php?id=1306

Please see this ticket and let me know if this is something related to us or paypal?

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial @angelleye I have test everything and it's working fine for me.

**Comment by angelleye** [comment]
It seems this user has billing agreements enabled and that is why it's not allowing guest checkout.  Just need to get billing agreement disabled in EC settings as well as product level settings, and then of course make sure all other settings for guest checkout are configured to solve the problem.
