### ISSUE TITLE
Tax Calculation Bug

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#80]
Sales Tax works great and gets included in the PayPal API requests correctly when the following settings in WooCommerce are set:
- Prices Entered with Tax:  No, I will enter prices exclusive of tax.
- Display prices in the shop:  Excluding tax
- Display prices during cart/checkout:  Excluding tax

Again, that way works fine.  However, I have users in the UK where it is normal to include tax in general pricing throughout the site, however, it still gets broken out on cart and checkout pages, and needs to be broken down in PayPal, but it's not.  For example, with settings like this...
- Prices Entered with Tax:  Yes, I will enter prices inclusive of tax
- Display prices in the shop:  Including tax
- Display prices during cart/checkout: Excluding tax

When that sort of setup is configured the PayPal request is simply sending a total amount to PayPal without breaking out any sales tax.  

We need to make sure that the sales tax break-down gets passed to PayPal just like it does in WooCommerce.  Those settings make it possible to have different scenarios in WooCommerce, so we just need to make sure that any time the WC cart/checkout pages are getting broken out, we also make sure the PayPal requests breaks it out that same way.

**Comment by angelleye** [comment]
I believe this was handled in the 1.1.6.3 release.

**Comment by kcppdevelopers** [comment]
We have build new calculation class, now everything is working well.
