### ISSUE TITLE
Braintree - MID Question

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#803]
* https://www.angelleye.com/paypal-express-checkout-for-woocommerce-setup-guide/#comment-33402

In #521 and #565 we made improvements to MID usage in Braintree, but it seems there is still some confusion..??

>That’s great. I’m asking because I could not find a way to enter multiple account IDs in Braintree gateway. Is there a way to do it? Thanks

**Comment by kcppdevelopers** [comment]
@angelleye our plugin are already support to Merchant Account ID.

We have not provide UI to enter multiple account ID base on store currency, We have used Braintree API to get Merchant Account ID base on checkout currency and passed it in payment request.

I don't think UI is required for enter multiple account ID, because programmatically fetch  Merchant Account ID base on checkout currency.

Let me know your suggestion on this.

**Comment by angelleye** [comment]
@kcppdevelopers  The developer of the Aelia currency switcher, Diego, seems to think it should be able to support multiple MID values.  (https://mail.google.com/mail/u/0/#search/aelia/15bfc1043b261476)

>Flash question about the Braintree gateway: can it handle multiple merchant account IDs now? I have a client who would like to use it, but I haven't been able to find a way to configure multiple merchant account IDs (one currency = one ID).

I've also had similar feedback from PayPal reps and other users, too.

**Comment by kcppdevelopers** [comment]
@angelleye yes our plugin support multiple merchant account IDs now but user not need to enter in setting panel. we have used API to get right merchant account ID base on checkout currency so it will work well without enter merchant account IDs in setting panel. and yes it will also worked well with Aelia currency switcher plugin.

**Comment by angelleye** [comment]
![image](https://user-images.githubusercontent.com/629241/29725391-8d30d96e-8991-11e7-9ddd-1b43111f2c0e.png)

@kcppdevelopers That screenshot is from the Automatic Braintree plugin, and you can see how it lets you specify a currency and enter a different MID for different currencies.  This is what our plugin is apparently missing.

**Comment by kcppdevelopers** [comment]
@angelleye We have not provide UI of MID, I don't think MID user interface is required. 


`$gateway = Braintree_Configuration::gateway();
$merchantAccountIterator = $gateway->merchantAccount()->all();

foreach($merchantAccountIterator as $merchantAccount) {
    $currencycode = $merchantAccount->currencyIsoCode;
           $mid = $merchantAccount->id
}`

https://developers.braintreepayments.com/reference/request/merchant-account/all/php

Above braintree API provide all the merchant account with currency code, we have used above code and get MID base on checkout currency code and pass to payment request.

**Comment by kcppdevelopers** [comment]
Our plugin will work same as Automatic Braintree plugin without MID UI.

**Comment by angelleye** [comment]
@daigo75 Thanks!!

**Comment by angelleye** [comment]
@kcppdevelopers Thoughts on Diego's feedback..??

**Comment by kcppdevelopers** [comment]
@angelleye i am agree with @daigo75 Thank you so much @daigo75 for your suggestion.
