### ISSUE TITLE
Payments Pro Subscriptions Issues..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#806]
* https://mail.google.com/mail/u/0/#inbox/15cd606799a075ba

Running latest version updates...

>Still no joy. Tried 3 more test purchases today, got Invalid or missing payment token fields error after clicking the Register Now button on the checkout page each time.

>Also, I'm not sure if it's related, but why does disabling "Tokenized Payments" in settings completely remove the credit card fields on the checkout page?

Remember, we're supposed to be overriding the general tokenization setting for subscription products to make sure it's always included regardless of the global setting.

>All three of the test orders show up in the dashboard (WooCommerce > Orders) as "Pending payment."

The PayPal Pro DDP log shows the $1 test orders are completing successfully, but again, she ends up with an error on checkout and the order gets stuck in pending.

**Comment by angelleye** [comment]
@kcppdevelopers Did you review this one again after I added the updates from the user saying it's still not working?  I also emailed you credentials to troubleshoot directly.

**Comment by kcppdevelopers** [comment]
@angelleye as per our discussion WP login credentials does not have admin/shop manager role to review orders details. we have already ask for admin details.

**Comment by angelleye** [comment]
@kcppdevelopers User role has been updated to admin.  Please take a look.

**Comment by angelleye** [comment]
@kcppdevelopers reviewed and noticed the plugin on their site was not updated.  We have applied our current dev branch to the site and are now confident it should work as expected.  Waiting again for customer feedback.

**Comment by angelleye** [comment]
@kcppdevelopers The user we've been working with (dswidev.com) found the reason their order IDs were not matching post IDs (Order Numbers module included with WooCommerce Booster).  They've now disabled that, but they are still running into the same problem they've had all along, which is that they get an error during checkout: "Invalid or missing payment token fields."

So apparently you didn't get this error during your tests, but they aren't able to get around this error at all.  I'm not sure why it would ever be looking for a token on an original checkout in the first place...obviously no token exists yet.

Can you think of what else could be causing this?  I've asked them for a video of their experience and I'm waiting on that.

**Comment by kcppdevelopers** [comment]
@angelleye I have checked multiple time on my localhost as well dswidevcom website but I simply unable to regenerating "Invalid or missing payment token fields." error. 

I have uploaded latest code on client website (dswidevcom) now everything is working fine for me.

Can you please ask user to re test again?

**Comment by angelleye** [comment]
@kcppdevelopers She says she's till getting the error.  :(

Could it have something to do with the product?  Maybe we need to set the exact product she's using to sandbox mode temporarily and see if we can reproduce the issue then?

**Comment by kcppdevelopers** [comment]
@angelleye She has disable product level sandbox mode, that why renewal not working well on live mode.

**Comment by angelleye** [comment]
@kcppdevelopers But she's getting that invalid token error during checkout, not when the renewal happens.

**Comment by angelleye** [comment]
I'm going to move this to next milestone for now.  We are not able to reproduce any o f this, but something is still going on with this client's site in particular, so I don't want to give up on it, but I don't want to delay this release either.
