### ISSUE TITLE
PHP Fatal error in 1.4.5.1..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#807]
* https://wordpress.org/support/topic/1-4-5-1-update-gives-php-fatal-error/

> [11-Jul-2017 12:42:31 UTC] PHP Fatal error: Uncaught Error: Call to undefined method AngellEYE_Utility::is_display_angelleye_billing_agreement_notice() in /wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye.php:665
> Stack trace:
> #0 /wp-includes/class-wp-hook.php(298): Angelleye_PayPal_Express_Checkout_Helper->angelleye_billing_agreement_notice(”)
> #1 /wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
> #2 /wp-includes/plugin.php(453): WP_Hook->do_action(Array)
> #3 /wp-admin/admin-header.php(255): do_action(‘admin_notices’)
> #4 /wp-admin/edit-form-advanced.php(472): require_once(‘/home/inkston/p…’)
> #5 /wp-admin/post.php(173): include(‘/home/inkston/p…’)
> #6 {main}
> thrown in /wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye.php on line 665

**Comment by kcppdevelopers** [comment]
@angelleye me and @MansoorAliKhanOfficial  both have test this issue but we don't see any error like this in my error log.

**Comment by MansoorAliKhanOfficial** [comment]
Well , I never see this issue becasue I dont have reference transactions enabled on my sandbox account. I m curious is there a way to do so with sandbox account??????

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial That actually wouldn't affect what's happening here.  This is simply an admin notice that should be displaying to let people know about the fact that they will need reference transactions enabled in order to use it for Express Checkout.
