### ISSUE TITLE
Express Checkout - Return / Review Page Fail..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#808]
* https://mail.google.com/mail/u/0/#inbox/15d3879337301e79

I've seen this reported a few times now...

>I'm working on another site for another client... setting up Express, and I think I have everything all setup. When I go to checkout, it takes me to Paypal where I can login and get to the point where I click "Pay Now". It spins for a second, then takes me back to the Cart page.

**Comment by kcppdevelopers** [comment]
@angelleye Can you please ask log file for more troubleshoot?

**Comment by angelleye** [comment]
Thinking maybe he's running on WPEngine and running into caching problems.  Checking with user...

**Comment by angelleye** [comment]
This was indeed a WPEngine caching issue.  Once they excluded /wc-api everything worked.
