### ISSUE TITLE
PayPal Advanced - Doesn't show up on active gateways even when enabled..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#809]
* https://mail.google.com/mail/u/0/#inbox/15cfae29fc205705

![image](https://user-images.githubusercontent.com/629241/28222405-fe5756de-688c-11e7-8361-ff162a0191fa.png)

![image](https://user-images.githubusercontent.com/629241/28222417-08ecf3e2-688d-11e7-97ba-6338a2a62ad9.png)

**Comment by angelleye** [comment]
I also notice that paypal_express is labeled as Credit/Debit Card..??  I'm not seeing that on my test sites so they've got something funky going on here..??

**Comment by angelleye** [comment]
User is also reporting that the Advanced iFrame sometimes won't display, which is the original reason he contacted us.

**Comment by kcppdevelopers** [comment]
@angelleye Payment gateway list display Title ( from gateway setting value )
