### ISSUE TITLE
REST Credit Card - Authorization / Capture Support..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#813]
* https://www.angelleye.com/support/scp/tickets.php?id=1253

> The solution was to modify the CreatePayment routine. I changed:
> 
> `$sale = $relatedResources[0]->getSale();`
> 
> to 
> 
> `$sale = $relatedResources[0]->getAuth();`

**Comment by angelleye** [comment]
@kcppdevelopers Our tool tip here for the Sale/Auth setting says that we'll have to capture funds from within the PayPal account.  We cannot capture from the WC order page..??

**Comment by kcppdevelopers** [comment]
@angelleye  I have not added capture from the WC order page, REST Credit Card payment method is deprecated so we will not get more user on this payment method. Let me know if are you still want to add this functionality?

**Comment by angelleye** [comment]
@kcppdevelopers Can you give me an estimate on hours to get it done?

**Comment by kcppdevelopers** [comment]
@angelleye It will take 3 to 4 hours to done.

**Comment by angelleye** [comment]
@kcppdevelopers Okay, don't worry about it for now.  We may address it again later because while their page does say it's deprecated, they aren't truly removing it.  We aren't getting much feedback on this, though, so I'm not worried about it for now.
