### ISSUE TITLE
Code adjustment necessary..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#817]
* https://wordpress.org/support/topic/woocommerce_review_order-shortcode-removed/

**Comment by kcppdevelopers** [comment]
@angelleye we have already code adjustment here  [link](https://github.com/angelleye/paypal-woocommerce/blob/release/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye.php#L800)
