### ISSUE TITLE
Order review : Address details not fetching

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#819]
![image](https://user-images.githubusercontent.com/11312949/28751424-83851266-7520-11e7-94b0-85dd79c190ab.png)

I have seen this issue second time using private browsing and see the above screen also the button sizes are very odd which need to be adjusted: please do what is needful :)

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial Can you please website URL for more troubleshoot?
