### ISSUE TITLE
Express Checkout - Shipping Country Restriction

### ISSUE THREAD

**Issue by ghost** [angelleye/paypal-woocommerce#82]
WooCommerce has an option to limit shipping to specific countries.  Express Checkout doesn't know the shipping address, though, until we've reached our review page, and we're not validating the shipping country against the WC rules at this point, so orders are able to come through with any country even if WC is set otherwise.

**Comment by lucf** [comment]
Hi guys,

Any update to have recurring payment on your great plugin?

*Cordialement,*

*Luc Frébourg*

<http://cherryclass.net>

**Comment by angelleye** [comment]
Not yet, sorry.  We've been busy with some other plugins we're about to release involving PayPal and WordPress. Planning on launching those very soon and then we'll be back to focusing on this one for a bit.
