### ISSUE TITLE
PayFlow : Woo subscription issue with renewal

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#823]
Can you please take a look at this ticket? its urgent.
https://www.angelleye.com/support/scp/tickets.php?id=1371

**Comment by angelleye** [comment]
@kcppdevelopers You may have addressed this already, but please double check.  I think this might be the same problem we had earlier where we weren't compatible with the latest version of Woo Subscriptions, but this 1.4.5.2 update should fix that.  Please verify.

**Comment by kcppdevelopers** [comment]
@angelleye I have review issue in client website and found that this is same problem we had earlier. yes 1.4.5.2 update will fixed issue.

**Comment by kcppdevelopers** [comment]
Issue #806

**Comment by MansoorAliKhanOfficial** [comment]
so is this merged to dev branch so that I can ask client to update and test?

**Comment by angelleye** [comment]
Yes, dev branch should resolve the issue for them.

**Comment by MansoorAliKhanOfficial** [comment]
Okay I have sent it to them waiting for their reply . Will leave any my remarks upon their reply.

**Comment by MansoorAliKhanOfficial** [comment]
**Customer Remarks After installing the Dev branch**

> Thanks again for your help. See summary below of the steps taken and tests performed:
> 
> 1) Created a DEV site, and removed all existing active/inactive client subscriptions.
> 
> 2) Duplicated the existing subscription product, and changed price to $1.00 and renewal to 1 day, all other properties stayed the same. Kept gateway in LIVE mode to rule out PayPal account setting issues.
> 
> 3) Went to the dev site, and purchased the subscription, prior to installing the new plugin update.
> a. Subscription #2603
> 
> 4) Deactivated the paypal-for-woocommerce plugin.
> 
> 5) Replaced all files in plugin folder with the dev files provided via FTP.
> 
> 6) Reactivated paypal-for-woocommerce plugin.
> 
> 7) Went back to dev site as a new visitor and purchased the subscription using a new user and credit card.
> a. Subscription #2606
> 
> 8) Both transactions were successful, screenshots from PayPal Manager attached.
> 
> 9) 24 hours later, WooCommerce attempted renewals on both subscriptions (screenshots attached):
> a. The 1st subscription (#2603) was declined with the same Error 23 as has been occurring on the live site. It continues to retry, but fails with:
> PayFlow API call failed. Error Code: 23 
> Detailed Error Message: Invalid account number 
> User IP: 162.144.102.194 
> Order ID: 2608 
> Customer Name: Don Glasgow 
> Customer Email: don@americancreative.com 
> 
> b. The 2nd subscription (#2606) was renewed successfully.

Can you check any other possibilities? as if is working for the new once it should all work for the old ones. what could be the issue with those?

**Comment by angelleye** [comment]
@kcppdevelopers Looks like we still need to review this more..??

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial So it sounds like the fresh order and renewal worked as expected, but the order from the previous plugin version would still not renew correctly.  Is that right?  If so, there may not be anything we can do about that, but new orders going forward will be fine.

**Comment by MansoorAliKhanOfficial** [comment]
Yeah, that is correct. I just gave remarks so that if there will be something which might be adjusted.
if there is nothing then its fine to move on. ;)

**Comment by angelleye** [comment]
The user now says it does work on his old order, and our testing shows the same.

**Comment by MansoorAliKhanOfficial** [comment]
Clients reply: you can check ticket for more references:

The Error Code 23's are happening on renewals. They do not appear to be happening on new orders, only on renewals. I have attached 4 of the ones that occurred today, as well as the PayPal Manager summary and the related orders from Woocommerce. These are on the live site.

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial I thought we had figured out that only his older order renewals weren't working..??  Are you saying that even on the latest update his original order works but then the renewal fails with this Error 23?

**Comment by MansoorAliKhanOfficial** [comment]
Yeah, he has left 2 more comments this week saying the exact same.

Here is the ticket for further reference.
https://www.angelleye.com/support/scp/tickets.php?id=1371

**Comment by angelleye** [comment]
I have responded to the ticket with quite a bit of info for the customer.  @kcppdevelopers will be working to resolve the conflict so that old order renewals will work on the latest versions of Woo Commerce, Woo Subscriptions, and PayPal for Woo in this release.

**Comment by angelleye** [comment]
@kcppdevelopers Still working on this one?  No rush, just noticed you had commits but it's not marked ready for review..??
