### ISSUE TITLE
EC button loading issue

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#825]
I thought I was the one facing this but yes we have someone who rated us 5 but quoted the issue too. can you take a look and make it load quickly?

![image](https://user-images.githubusercontent.com/11312949/28982832-9d68e38e-7970-11e7-9e6e-7ac9c82ae91a.png)

**Comment by angelleye** [comment]
The button is hosted by PayPal's servers, and unfortunately it can be delayed at times.  We may look to use a locally provided graphic instead of a PayPal hosted graphic to resolve this.

**Comment by kcppdevelopers** [comment]
issue #818
