### ISSUE TITLE
Express Checkout - PayPal Credit from general WC checkout gateways list.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#826]
* https://wordpress.org/support/topic/paypal-credit-not-appearing-using-paypal-express-checkout/

When PayPal Credit is enabled in EC settings we're including it with the regular EC button everywhere the EC button is output, but we don't show anything about PayPal Credit in the Express Checkout option that gets added to the WC checkout list general gateways.  Need to update that graphic there so it shows PayPal Credit if the option is enabled in EC settings.

**Comment by kcppdevelopers** [comment]
@angelleye we are already added PayPal Credit icon when it enable.

![826](https://user-images.githubusercontent.com/13145461/33118210-2b33b3c6-cf91-11e7-99a3-72d3cc1349cb.png)
