### ISSUE TITLE
Multiple PayPal Account Setup Options

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#827]
* https://mail.google.com/mail/u/0/#inbox/15dc940a76eabe30

Ability to setup multiple PayPal accounts in the system with a rule builder (similar to our IPN smart forwarder tool) that allows you to build logic that specifies where payments should go.

For example, something that comes up a lot is people who have low price items mixed with more expensive items.  It's good for them to use Micropayments for the low price stuff and regular fee pricing for the high price stuff.  Typical cutoff is $12.

So, we could setup two separate live PayPal accounts in the system, and then use a simple "rule builder" to specify that orders >= $12 should use PayPal account A, and orders < $12 should use PayPal account B.

That's just one example.  We could actually allow them to add as many different PayPal accounts as they want into the system, set a default account, and then add rules to send payments to specific accounts based on whatever logic they build with the rule builder.

**Comment by angelleye** [comment]
This could potentially be a premium extension.

**Comment by angelleye** [comment]
It would be good to make this work with Integrated Signup, too, so we should do that first.  #810

**Comment by kcppdevelopers** [comment]
@angelleye  https://www.angelleye.com/product/paypal-woocommerce-multi-account-management/
