### ISSUE TITLE
proceed to checkout button issue: 

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#828]
![image](https://user-images.githubusercontent.com/11312949/29188397-652b0f22-7e2c-11e7-8c8f-a07e3f02b1d6.png)

I dont understand why this is forecefully hidden overriding default WC css??

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial When Express Checkout is the only gateway active in the plugin then it hides the regular WooCommerce checkout button and uses only the PayPal button.  I think that's what you're seeing here.

@kcppdevelopers Can you confirm?

**Comment by MansoorAliKhanOfficial** [comment]
but there is actually some issue with logic as per my testing.
in EC settings page for Checkout Page Display -> when option is display at top of the checkout page.
this is hiding that dont know why. but after changing this option that button started to show,

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial  @angelleye 

Yes, When Express Checkout is the only gateway active in the plugin then it hides the regular WooCommerce checkout button and uses only the PayPal button.

I have double checked and it's working well as per functionality.

**Comment by angelleye** [comment]
@kcppdevelopers The experience should be the same regardless of whether you have the PayPal button set to display above or below the cart on the cart page, right?  It sounds like @MansoorAliKhanOfficial is reporting that he's getting a difference experience.  

@MansoorAliKhanOfficial Can you elaborate on what you were saying here?  Can you provide screenshots?

**Comment by MansoorAliKhanOfficial** [comment]
@angelleye , I'm sorry but its working fine now, may be due to some cache issues or something else unknown to me, I experienced that issue. you can close this now.
