### ISSUE TITLE
Express Checkout - Geolocation conflict..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#829]
* https://wordpress.org/support/topic/billing-state-is-a-required-field-error/#post-9400482

WooCommerce has an option to enable Geolocation for the default shopper address (WC -> Settings -> General Tab).  I think this is conflicting with our PayPal calls sometimes.

For example, if the geolocation sets a zip code in the WC address object, then our PayPal request includes that, however, when no street/state are included, PayPal returns an error that the address fields are missing.

We need to add some logic to our request builder that ensures the entire address is available before including it in the request.  This would be Street 1, City, State, Zip, and Country code.

**Comment by kcppdevelopers** [comment]
@angelleye We have already resolved this issue before.

**Comment by kcppdevelopers** [comment]
#735
