### ISSUE TITLE
Express Checkout - Skip Final Review no longer working..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#830]
Skip Final Review is no longer working.  I've tested this on my live angelleye.com site as well as woo.angelleye.com.

**Comment by ArMouReR** [comment]
Got internal server error on product edit page after upgrade from 1.4.5.1 to 1.4.6.1.

`#0 /wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-admin-order-payment-process.php(89): AngellEYE_Admin_Order_Payment_Process->angelleye_is_order_created_by_create_new_reference_order(Object(WC_Order))
#1 /wp-admin/includes/template.php(1037): AngellEYE_Admin_Order_Payment_Process->admin_order_payment_process(Object(WP_Post), Array)
#2 /wp-admin/edit-form-advanced.php(686): do_meta_boxes(Object(WP_Screen), 'side', Object(WP_Post))
#3 /wp-admin/post.php(173): include('/home/...')
#4 {main}`
I am on woocommerce  2.6.4
