### ISSUE TITLE
Order edit screen empty after our 1.4.6 update..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#833]
* https://mail.google.com/mail/u/0/#inbox/15dd6cf27a41b7c4

> I just updated your PayPal plugin to the latest version shown in the update plugins page. Since that time, all of our order details no longer show in the Edit Order page. The Orders listing page list looks normal however. When I deactivate your plugin the Edit Order details re-appear as normal. How do I correct this? I checked the database and all is ok. See screen shot.
> 
> ![image](https://user-images.githubusercontent.com/629241/29241490-84347614-7f40-11e7-934d-69dbe2ef24a5.png)

**Comment by angelleye** [comment]
@kcppdevelopers Any idea at all why this would be happening?

**Comment by angelleye** [comment]
@kcppdevelopers I wonder if our new sections we added for Reference Transaction Orders somehow caused this..??  I had him disable all other plugins, and he says nothing fixes it except for disabling ours.

**Comment by kcppdevelopers** [comment]
@angelleye Can you please ask user to provide WooCommerce version details?

**Comment by angelleye** [comment]
@kcppdevelopers Looks like you figured it out, but just got more info from the user that he is running WC 2.6.14.  I see you added version logic.  Is this issue resolved now or are you still working on it?
