### ISSUE TITLE
WC_Order::get_created_via is not supported by WC 2.6.4

### ISSUE THREAD

**Issue by ArMouReR** [angelleye/paypal-woocommerce#837]
Got the following error after upgrade to 1.4.6.1
`[15-Aug-2017 10:20:28 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WC_Order::get_created_via() in /wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-admin-order-payment-process.php:286
Stack trace:
#0 /wp-content/plugins/paypal-for-woocommerce/angelleye-includes/angelleye-admin-order-payment-process.php(89): AngellEYE_Admin_Order_Payment_Process->angelleye_is_order_created_by_create_new_reference_order(Object(WC_Order))
#1 /wp-admin/includes/template.php(1037): AngellEYE_Admin_Order_Payment_Process->admin_order_payment_process(Object(WP_Post), Array)
#2 /wp-admin/edit-form-advanced.php(686): do_meta_boxes(Object(WP_Screen), 'side', Object(WP_Post))
#3 /wp-admin/post.php(173): include('/home/...')
#4 {main}
`
Please advise...

**Comment by angelleye** [comment]
Thanks for the report.  We'll get this fixed on a 1.4.6.2 update ASAP.  Until then, if you need to revert back you can find previous versions of the plugin at the bottom of the page here:  https://wordpress.org/plugins/paypal-for-woocommerce/advanced/

**Comment by kcppdevelopers** [comment]
Issue #833
