### ISSUE TITLE
Express Checkout - Review with KCPPDev

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#838]
For Express Checkout I'm not sure how this suddenly shows an actual discount field broken out instead of having the discount as a line item..??

![image](https://user-images.githubusercontent.com/629241/29377148-7fbd72f0-8280-11e7-9ee6-151c373b1094.png)

**Comment by angelleye** [comment]
For Payments Pro the discount was applied but it doesn't show up anywhere..??

![image](https://user-images.githubusercontent.com/629241/29465743-f11532fa-83ff-11e7-8cf3-dfb690bb8a7d.png)

**Comment by kcppdevelopers** [comment]
@angelleye  I have double check, In express checkout and PayPal Pro we are passing discount as a line item.

PayPal Pro order screenshot line item not displaying that why discount is hidden.

**Comment by angelleye** [comment]
@kcppdevelopers Something still doesn't make sense here.  In either case if we're passing the discount as a line item then we should see it show up in the cart contents displayed on the PayPal transaction details.

Somehow, though, the Express Checkout example here actually broke out Discount as if it was passed in its own separate parameter similar to shipping, tax, handling, etc.  

With Payment Pro, again, if we're passing discount as a line item it should be getting included in the shopping cart contents displayed.  It always did before, but now it's not..??

But you're saying you have verified we never changed anything here?  We are still sending the discount as a line item in both cases?

**Comment by kcppdevelopers** [comment]
@angelleye 

- PayPal express checkout request:

![sale_ec_paypal_request](https://user-images.githubusercontent.com/13145461/34035412-f67e0680-e1a7-11e7-9a00-cdba20395e1b.png)

- PayPal express checkout details page:

![sale_ec_paypal](https://user-images.githubusercontent.com/13145461/34035500-3c578b4a-e1a8-11e7-9a44-9fe32394ccf8.png)

- PayPal Pro Request:

![auto_paypal_pro_paypal](https://user-images.githubusercontent.com/13145461/34035542-576d577a-e1a8-11e7-8930-fc5727003f66.png)

Getting same result in PayPal pro like you get.

It seem we are passing correct request parameter but PayPal handle it own ways.

**Comment by angelleye** [comment]
@kcppdevelopers Thanks for verifying.
