### ISSUE TITLE
Express Checkout - Skip Final Review not working for Subscription products.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#839]
* Majda Djukic via email and Skype reports...

In #830 we made a fix for Skip Final Review, which became broken in 1.4.6.  This seems to have fixed it for regular checkouts, but when checking out for a Woo Subscription product it's still displaying the review page even when skip enabled.

Is this intended for Subscription items for some reason, or is this something else we've missed?

**Comment by kcppdevelopers** [comment]
@angelleye  In express checkout, when skip final review enable, we are creating order manually with required order data. but when product is subscription it is hard to manage to create order manually.  that why we are display order review page for subscription product.

**Comment by angelleye** [comment]
I'll move this to the next milestone, but I want to improve upon this.
