### ISSUE TITLE
Express Checkout - In Context from WC checkout page

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#840]
* https://www.angelleye.com/support/scp/tickets.php?id=634
* https://mail.google.com/mail/u/0/#inbox/15f5453c30b4fcbb
* https://www.angelleye.com/support/scp/tickets.php?id=1437

**Update:**
Another request for this ( 02-22-2018)
https://wordpress.org/support/topic/checkout-and-visitor-stay-on-my-website/

We decided against adding In Context when checkout happens through the WC checkout page and the regular list of payment gateways.  I don't exactly remember why, though.  Need to re-visit this because we're getting quite a few requests to make it work from the checkout page.

**Comment by MansoorAliKhanOfficial** [comment]
Got someone else asking the same:
1- https://www.angelleye.com/support/scp/tickets.php?id=1437

**Comment by kcppdevelopers** [comment]
@angelleye I have spend much time on this issue, but on form submit with In Context checkout JS not working.

**Comment by angelleye** [comment]
I'll move this to 1.5.0, but I don't want to give up on it.  We get lots of requests for this.  Seems there must be some way to make it work...
