### ISSUE TITLE
Payments Advanced - Line Item Details

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#841]
* https://www.angelleye.com/support/scp/tickets.php?id=1412

It seems we are not passing any line item details to Payments Advanced..??

**Comment by angelleye** [comment]
The PayFlow Gateway does support PayPal API style line item parameters, so we need to run some tests to see if those carry into the PayPal transaction details when sent in a PayFlow request for Payments Advanced.

**Comment by kcppdevelopers** [comment]
@angelleye  We already passed line item parameters same as other Payment methods.
