### ISSUE TITLE
Flatsome theme conflict..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#842]
* https://www.angelleye.com/support/scp/tickets.php?id=1387

**Comment by kcppdevelopers** [comment]
@angelleye it seem support ticket URL is not related to Flatsome theme conflict. may be I missing something.

**Comment by angelleye** [comment]
@kcppdevelopers Looks like I must have pasted in the wrong ticket URL.  Are we able to get an updated copy of Flatsome we can test it in general?

**Comment by iMansoorAliKhan** [comment]
I have the most recent copy of flatsome, I think, If you need let me know I can provide.

**Comment by angelleye** [comment]
@iMansoorAliKhan Yes, if you can try to reproduce the problem the user is reporting that would be great.

**Comment by iMansoorAliKhan** [comment]
Sure, I will update my findings here.

**Comment by iMansoorAliKhan** [comment]
I have just tested this with latest flatsome and our plugin , this seems to be working for me. Tested Both login and without login > http://demo.mansooralikhan.com/shop/
I'm gonna attach theme here too

**Comment by iMansoorAliKhan** [comment]
[flatsome.zip](https://github.com/angelleye/paypal-woocommerce/files/1512598/flatsome.zip)
