### ISSUE TITLE
Braintree - Kount - Revisit Advanced/Custom Integration

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#844]
We added Kount in #751, but PayPal reps are a little bit confused about our Kount integration.  Seems they think there should be more involved than just choosing "advanced" from a drop down.  Somehow we need to tie in some custom options..??

**Comment by angelleye** [comment]
Another PayPal rep with questions about this:  https://mail.google.com/mail/u/0/#inbox/15ba10ff1ba546dd

```
Hey Andrew, if you have time can you help with this question we are trying to help out a merchant with. If they have Kount Custom or “Kount Direct”, they are generated a Kount ID from Kount when they enable this “Kount Direct” feature.
 
In your plugin, does it automatically detect that Kount Direct is enabled and it uses those Kount Direct Fraud Filters? Or do you paste in the Kount ID into your plugin somehow?
```
 

> In your Information pop-up, I get this:
> 
> ![image](https://user-images.githubusercontent.com/629241/29646726-c1081f6a-884a-11e7-879b-7b172daa9b24.png)
>  
> If they already have Kount Direct enabled, how do they proceed in the plugin? Thank you for helping!!

**Comment by angelleye** [comment]
Here is a specific question from PayPal reps after notifying them we had added Kount for Braintree.

>"So merchants won’t be able to use the full MID, customizable experience with WooCommerce?  Only the “out of the box” version?"

So I'm a little confused by that.  Seems that the MID is somehow related or used with Kount settings..??  And we have #803 open as well where I think we missed something regarding MID integration.

I'm not really familiar with all of this myself, so we'll have to dig around in the docs to get this all straightened out.  If we come up with any specific questions I can reach out to my Braintree tech support contact.

**Comment by kcppdevelopers** [comment]
@angelleye  MID is request parameter and we are passing as 'merchantAccountId'. No, MID is not related with Kount settings.

**Comment by angelleye** [comment]
@kcppdevelopers Okay, so do you have any idea why they're saying they're confused about our integration?  They seem to think there should be more than simply setting "Advanced" in a drop-down..??

**Comment by kcppdevelopers** [comment]
@angelleye  There are two type of Fraud Tools in Braintree.

1) Basic Fraud Tools : Basic Fraud Tools by default enable, No developer work required.

2) Advanced Fraud Tools : Advanced Fraud Tools are not set up on your account by default. If you would like use this feature, you must enable Advanced Fraud Tools in the Control Panel. https://www.screencast.com/t/KEAMcHG59G

There are two type of Advanced Fraud Tools like below:
1) Kount Standard
2) Kount Custom

We have used Kount Standard in our plugin functionality.

If user want to  Fraud Tool  'Advanced ' option in our plugin just need to enable this option : https://www.screencast.com/t/KEAMcHG59G

**Comment by angelleye** [comment]
@kcppdevelopers So what about Kount Custom?  How does that one work?

**Comment by kcppdevelopers** [comment]
@angelleye Braintree's Basic Fraud Tools and Kount Standard have been designed to help the majority of our merchants deter credit card fraud while still allowing legitimate transactions to process.

In Kount Custom, You can either establish and use your own fraud rules with Kount Custom or Braintree's rules through Kount Standard, but not both. Compared to using Braintree's fraud rules, managing your own fraud detection requires a greater investment of both resources and finances. Some specific requirements to be aware of:

- You must be processing at least 2500 transactions per month
- There are additional fees associated with Kount Custom

Kount Custom is requirement specific solution, we can't integrate in to our plugin.

**Comment by angelleye** [comment]
@kcppdevelopers Are there details in the docs about what these specific solution requirements are?  This seems to be what PayPal is after because it's for high volume sellers processing 2500+ transactions per month.  Do we know the steps involved but you're saying we can't do it in our plugin for some reason?  Or are we unsure of the steps involved?

**Comment by angelleye** [comment]
@kcppdevelopers Also, referring to the Basic vs. Advanced option that we do have integrated...I'm a little bit confused there.  It looks Basic is used by default whether you set any config setting or not, right?  And then Advanced would be enabled in the Braintree account.  Why do we even need a Basic/Advanced option in our plugin?

**Comment by kcppdevelopers** [comment]
@angelleye Basic Fraud Tools by default enable in Braintree account as well our payment gateway setting panel, In Advanced option (Kount Standard) we have to passed device data parameter in payment request.


https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v3
https://developers.braintreepayments.com/guides/advanced-fraud-tools/server-side/php

**Comment by kcppdevelopers** [comment]
@angelleye  

Below are document/guides for fraud tools:

- Basic Fraud Tools: https://articles.braintreepayments.com/guides/fraud-tools/basic/overview
- Kount Standard: https://articles.braintreepayments.com/guides/fraud-tools/advanced/kount-standard
- Kount Custom: https://articles.braintreepayments.com/guides/fraud-tools/advanced/kount-custom

**Comment by angelleye** [comment]
@kcppdevelopers The Custom link refers to a doc specific to it:  https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/ios/v4#kount-custom-integration

Did you review that?  Is there some reason we aren't able to get that integrated?  The docs explain that the merchant would need to get approval and configure everything in their back end, but then also points to these docs and says the developer could get integration done so it's ready when the merchant has everything else done.  It seems like that's what we're missing right now..??

**Comment by kcppdevelopers** [comment]
@angelleye you are right, now I have added 'Kount Direct' functionality and push to dev branch. 

![844](https://user-images.githubusercontent.com/13145461/29970019-88383970-8f40-11e7-9c89-8aab5b25b2a0.png)

**Comment by angelleye** [comment]
@kcppdevelopers Where does the term "Kount Direct" show up in the docs?  I'm a little confused by that name.

I do see the term used in the Recurley docs for Kount:  https://docs.recurly.com/v1.0/docs/kount

It has info about how to test in the sandbox, too.  Were you able to run sandbox tests with Kount to ensure we're handling various responses from it correctly?

**Comment by angelleye** [comment]
@kcppdevelopers I do see where it says "We offer a direct integration with Kount..." so I guess that's where you came up with "Kount Direct"..??

**Comment by kcppdevelopers** [comment]
@angelleye I have changed Fraud Tools as per Braintree official document.

**Comment by angelleye** [comment]
@kcppdevelopers Were you able to run tests in the sandbox for the Kount stuff to ensure it's all working based on custom rules now as expected?

**Comment by angelleye** [comment]
@kcppdevelopers Also, are these steps correct for me to document?

1.  Talk to Braintree and get a Kount account configured with merchant ID.
2.  Configure custom Kount rules within the Braintree/Kount account(s).
3.  Configure the plugin to use Kount Custom and enter your Kount Merchant ID.

Is that basically it?
