### ISSUE TITLE
Express Checkout - PayPal and Checkout buttons disappear if you close in-context window..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#850]
* https://mail.google.com/mail/u/0/#inbox/15e1b5a5b1910853

> I have a merchant that is experiencing something odd with EC on version 1.4.6.2; I’ve never seen this before either. In short, here’s what’s happening in chronological order:
>  
> 1.    Customer adds an item and redirects to the shopping cart page.
> 2.    They click on EC (shortcut button), incontext loads up, they sign in, and then continue to the merchant’s review page on WooCommerce.
> 3.    If they close the browser tab from the review page and then go back to the shopping cart page on a new tab, the “Proceed to Checkout” and PayPal buttons are no longer available.
>  
> Attached are a few screenshots for your reference. I think it might be a theme related issue because I tried to duplicate the same problem on a clean install; however, was not able to replicate what the merchant was experiencing. I thought I’d check with you to see if the recent tweaks to the plugin would cause this to happen somehow.

> ![image](https://user-images.githubusercontent.com/629241/29733938-455eebe8-89b5-11e7-8236-f08d46527b78.png)
> 
> ![image](https://user-images.githubusercontent.com/629241/29733947-506fc96c-89b5-11e7-8018-a8794ceff120.png)
> 
> ![image](https://user-images.githubusercontent.com/629241/29733964-5e1ec6e4-89b5-11e7-9140-0f9ee18ebe1e.png)

**Comment by kcppdevelopers** [comment]
@angelleye I have try same step but for me it's working fine. @MansoorAliKhanOfficial Can you please help me to regenerate issue?

**Comment by MansoorAliKhanOfficial** [comment]
@kcppdevelopers  I have seen this issue, as those address fields should be prepopulated from my details on paypal?

![image](https://user-images.githubusercontent.com/11312949/29886400-54e9c6f6-8dd3-11e7-8e3c-191776c3becb.png)

**Comment by MansoorAliKhanOfficial** [comment]
and the customer may be right as , I did the same 
1- after incontenxt payment from paypal, it returned to site to order review page as you can see in previous message.
then I closed the tab and mannually entered the cart URL and here is wat I saw

![image](https://user-images.githubusercontent.com/11312949/29886545-e132516e-8dd3-11e7-8a9b-7bdb4149553e.png)

Although before that it was showing 2 buttons the EC and proceed to checkout too.

**Comment by MansoorAliKhanOfficial** [comment]
The button is hidden forecefully somehow.


![image](https://user-images.githubusercontent.com/11312949/29886651-3e9a9442-8dd4-11e7-88ec-b4f3fdcff763.png)

**Comment by MansoorAliKhanOfficial** [comment]
and what I m paying here? the order amount?
