### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#851]
* https://www.angelleye.com/support/scp/tickets.php?id=1060

In #793 we fixed #3 in this person's feedback, but they have now provided a lengthy/detailed response about how they're using the plugin and what they would like to see changed.

@kcppdevelopers I'd like to review their feedback together and discuss it with you before you get started on this.

**Comment by kcppdevelopers** [comment]
@angelleye Issue has been closed in our support ticket system.

**Comment by angelleye** [comment]
Okay, I'll go ahead and close this issue then.
