### ISSUE TITLE
WooCommerce 3.2 Compatibility..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#853]
* https://woocommerce.wordpress.com/2017/08/28/new-version-check-in-woocommerce-3-2/

The URL above is specific to the new version check feature they're adding, but we also need to make sure we cover anything else we may need in the 3.2 update.

**Comment by kcppdevelopers** [comment]
@angelleye ohh, I have checked with 3.2.0 Beta 1 version of woo and it seems not working well with our plugin. let me work on this issue.

**Comment by kcppdevelopers** [comment]
https://github.com/woocommerce/woocommerce/issues/16724

**Comment by angelleye** [comment]
@kcppdevelopers Is this one ready to close now?

**Comment by kcppdevelopers** [comment]
@angelleye No, Need to check few thing..
