### ISSUE TITLE
Woo Subscriptions - Still an issue here..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#854]
* https://wordpress.org/support/topic/woo-subscriptions-not-renewing/#post-9459682

User reporting they've updated everything but they are still getting an error on subscription renewals:  81253 - Reference ID Missing.  

Look at latest comments from @aussieles in that thread.

**Comment by kcppdevelopers** [comment]
@angelleye Can you please ask user to provide website login details and FTP details for more troubleshot?

**Comment by angelleye** [comment]
@kcppdevelopers We've asked them to submit a ticket.  @MansoorAliKhanOfficial Please keep an eye out for that and update here when you see that ticket.

**Comment by kcppdevelopers** [comment]
@angelleye @iMansoorAliKhan 

https://wordpress.org/support/topic/woo-subscriptions-not-renewing/#post-9459682
https://wordpress.org/support/topic/woocommerce-subscription-with-paypal-for-woocommerce/

I have checked above both support ticket and found that user said: 

> Case closed, Its fixed now, the last steps i was missing is the paypal step to enable “Allow reference transactions” on PayPal PayFlow manager, after i set this its working like a charm.
