### ISSUE TITLE
Paypal Express Checkout: Unable to programmatically process payment

### ISSUE THREAD

**Issue by justlevine** [angelleye/paypal-woocommerce#856]
When manually calling `$gateways[paypal_express]->process_payment()`, I get hit with a failure generated from angelleye_redirect() (`class-wc-gateway-paypal-express-request-angelleye.php` line 75).

I can only assume that this is because your plugin hooks into woocommerce differently than most other payment gateways.

This is critical for people trying to process wc_orders programmatically (i.e. skipping both the cart and checkout pages).

Any suggestions for a workaround?

Here's an example code from a current project I was hoping to migrate to your plugin.

    $data = $_GET;
    $dataString = $data['post'];
    parse_str($dataString, $args);
    if($args['recurring'] == "true"){
      $donation_type = 21589;
    }
    else{
      $donation_type = 21586;
    }
    $donation_amt = $args['donation-amt'];

    $address = array(
      'first_name' => $args['first_name'],
      'last_name' => $args['last_name'],
      'company' => '',
      'email' => $args['billing_email'],
      'phone' => '',
      'address_1' => $args['shipping_address_1'],
      'address_2' => '',
      'city' => $args['shipping_city'],
      'state' => $args['shipping_state'],
      'postcode' => '',
      'country' => $args['shipping_country']
    );

    $order = wc_create_order();
    $order->add_product( get_product($donation_type), 1 , array('subtotal' => $donation_amt, 'quantity' => 1));
    $order->set_address($address, 'billing');
    $order->set_total($donation_amt);
    $order->save();
        
    update_post_meta( $order->id, '_payment_method', 'ppec_paypal' );
    update_post_meta( $order->id, '_payment_method_title', 'Paypal' );
    WC()->session->order_awaiting_payment = $order->id;
   
    //Process Payment
    $available_gateways = WC()->payment_gateways()->get_available_payment_gateways();
    $result = $available_gateways[ 'paypal_express' ]->process_payment( $order->get_id() );

    if($result['result'] == 'success'){
    $result = apply_filters( 'woocommerce_payment_successful_result', $result, $order->id );
      wp_send_json( $result );
    }

**Comment by angelleye** [comment]
Express Checkout requires three separate API calls:  SetExpressCheckout, GetExpressCheckoutDetails, and DoExpressCheckoutPayment.  You aren't going to be able to run a single process_payment() request like this.  Or am I missing something..??

You could do something like this if you have a billing agreement on file (WC tokenized payment).  Is that what you're trying to do?
