### ISSUE TITLE
Error Email Improvement

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#862]
Here's a copy of an error email I just received on our own live site:

![image](https://user-images.githubusercontent.com/629241/30096423-fb3818e0-929d-11e7-8caf-d9aac081e8a3.png)

This does not look very good.  I'd like to make some simple improvements here.  I would like the order of info to be like this:

**PayPal {api_name} API Call Failed**

**Error Code**: {error_code}
**Error Severity Code**: {error_severity_code}
**Short Error Message**: {short_error_message}
**Long Error Message**: {long_error_message}

Need to make sure the spacing is nice and clean and looks professional.

**Comment by angelleye** [comment]
I believe we have some customer info included in these emails when available, too.  We need to do the same sort of thing with that info, too, if it isn't already like that.

**Comment by tejasm-itpath** [comment]
@angelleye I have reorder  error info email code  but Do you need this  in logs or order note  too ?

**Comment by angelleye** [comment]
No, this issue is specific to the email that people get.  Can you provide a screenshot of what the email looks like now?

**Comment by tejasm-itpath** [comment]
Yes @angelleye 
Check this link https://www.screencast.com/t/m1rNX0D8sa
