### ISSUE TITLE
Compatibility issue with  AffiliateWP Version: 2.1.3.1

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#864]
https://www.angelleye.com/support/scp/tickets.php?id=1444

**Comment by angelleye** [comment]
Support ticket was closed, so closing this as well.

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  @angelleye 
As per link https://affiliatewp.com/changelog/ Latest version is 2.1.10 ,So can we get AffiliateWP Version: 2.1.3.1 ?

**Comment by angelleye** [comment]
@tejasm-itpath I have responded to our support ticket asking the user to verify which one they are using.
