### ISSUE TITLE
Add extra meta-data / custom fields to WC orders.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#865]
* https://wordpress.org/support/topic/meta-data-passed-to-order/

**Comment by angelleye** [comment]
Need to add the transaction fee as order meta data for all gateways that include it in the payment response.

**Comment by tejasm-itpath** [comment]
I discuss this issue with @kcppdevelopers 
There are two way to get that details 1) need to used PayPal IPN 2) or use GetTransactionDetails API Operation.

PayPal standard comes with WooCommerce and it has already PayPal IPN integrated that's why it shows in custom field/ meta field in order details. To do so in our plugin , we also need to integrate IPN.
Or other idea is to call GetTransactionDetails API as we have TxnID

**Comment by angelleye** [comment]
@tejasm-itpath The fee information is typically returned in the final API call.  GetExpressCheckoutDetails would not have the fee information, and actually, in the case of Express Checkout I think the fee may not be available at all.  We'll need to check an example of the DoExpressCheckoutPayment response to see if it's included there.  

For DoDirectPayment the fee would be available in the response.  We'll need to check PayFlow, Braintree, REST, etc. for the same.

**Comment by tejasm-itpath** [comment]
@angelleye  I have mentioned **GetTransactionDetails API**  not **GetExpressCheckoutDetails** 
so  **GetTransactionDetails API**  will be usefull for all gateways in our plugin.

**Comment by angelleye** [comment]
@tejasm-itpath Ah, yes, sorry.  I read that too fast.  Yes, GetTransactionDetails should have fee information included with it, and that would be available for Express Checkout as well as Payments Pro.  It would not be available for PayFlow or Braintree, and I don't think it will be available for REST either, but we could test that to know for sure.

**Comment by tejasm-itpath** [comment]
@angelleye  
For **Paypal - PayFlow Pro** I have found one thing about fetching Transaction details from PNREF value or w can say ORIGID.
By setting TRXTYPE=I in request (I stands for **inquiry**) , we can get following output
`RESULT=0&PNREF=A10AA8FF583E&TRANSSTATE=1&ORIGRESULT=126&ORIGPNREF=A70AA766EDF6&RESPMSG=UnderreviewbyFraudService&AVSADDR=Y&AVSZIP=N&CVV2MATCH=Y&HOSTCODE=A&PROCAVS=A&PROCCVV2=M&VISACARDLEVEL=12&TRANSTIME=2018-01-03 04:09:27&FIRSTNAME=Test&LASTNAME=Buyer&AMT=0.41&ACCT=1111&EXPDATE=1221&CARDTYPE=0&IAVS=N`
But it is not showing any field that is related to fee/amount.
What's your opinion on this ? Do  you feel any parameter need to show in Order meta in Payflow Pro ?

**Comment by angelleye** [comment]
@tejasm-itpath Actually, in the case of PayFlow we are using PayPal as the processor.  So the PayFlow response from an order actually includes a PNREF and a PPREF.  The PPREF is the PayPal Transaction ID, and this should work with GetTransactionDetails.

**Comment by tejasm-itpath** [comment]
@angelleye I look into code and check about PPREF. we are not gettting PPREF in Payflow because 
PPREF only retrieves in Reference Transaction using BAID.

**Comment by tejasm-itpath** [comment]
@angelleye 
GetTransactionDetails unction is not available in PayFlow library so How can I use that with PPREF ?
