### ISSUE TITLE
Translation file problem..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#873]
* https://mail.google.com/mail/u/0/#inbox/15e7747934c313a6

This user is trying to translate but opening our default language files in POEdit is causing problems..??

![image](https://user-images.githubusercontent.com/629241/30415965-faed2c2e-98ef-11e7-92b6-1f062913155b.png)

**Comment by kcppdevelopers** [comment]
@angelleye I think user should contribute [here](https://translate.wordpress.org/projects/wp-plugins/paypal-for-woocommerce) instead of create own language file.

**Comment by angelleye** [comment]
@kcppdevelopers I see you did make a commit here.  Is this just a fresh build of the language files so it's current with our plugin or is there something more to this commit?

Also, why are we only 95% stable for English in that WP table?

**Comment by kcppdevelopers** [comment]
@angelleye 

![lang](https://user-images.githubusercontent.com/13145461/30427670-44f3c822-996e-11e7-9510-eb4e2380a44c.png)

25 string Untranslated that's why it's display 95%

**Comment by angelleye** [comment]
@kcppdevelopers So does that mean we don't have the __() wrapped around them, or what?  English is the primary language, so how can we not have a "translation" for 25 strings?
