### ISSUE TITLE
Express Checkout - Conflict with Polylang plugin..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#874]
* https://wordpress.org/support/topic/proceed-to-paypal-button-paypal-express-creates-a-404-error-on-site

> After a huge search i found a possible conflict with the plugin Polylang.
> 
> But it´s strange.
> 
> I disabled all the plugins except the one i need for the theme and woocommerce and the error goes away: Fusion Builder | Fusion Core | oik weight zone shipping | PayPal for WooCommerce | WooCommerce
> 
> Then i activated polylang and the error is there but (and thats the strange thing):
> 
> With PolyLang active and Save Abandoned Checkouts” on PayPal Express Checkout settings checked: NO ERROR
> 
> With PolyLang active and Save Abandoned Checkouts” on PayPal Express Checkout settings unchecked: ERROR

**Comment by kcppdevelopers** [comment]
#666

**Comment by angelleye** [comment]
@kcppdevelopers I see it's a duplicate, but in the previous one you basically just say that we re-write everything so it should be working now.  I don't see any actual commits to resolve the issue specifically.

This current report is from somebody using our current release.  I'll double check that, but I'm pretty sure they are indeed updated to current release.

**Comment by kcppdevelopers** [comment]
@angelleye https://github.com/angelleye/paypal-woocommerce/issues/666#issuecomment-299129186
