### ISSUE TITLE
EC : Thank you page WPML issue

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#875]
https://www.angelleye.com/support/scp/tickets.php?id=1429
Please take a look at this ticket her have tested it in mutliple ways but the thank you page dont return to correct translation, like the checkout page was in chines , it goes to paypal again PP is in chines but when it is returned to site its in english
Do you think of any thing that would be causing this issue?

**Comment by angelleye** [comment]
@kcppdevelopers There's a lot of info in that ticket linked above, but basically it comes down to the fact that on a basic Twenty Fifteen theme our review page with Express Checkout is not translating properly with WPML.  Is that something we can fix pretty quickly?  Maybe something we need to do with that page template to make sure it's compatible with WPML..??

**Comment by MansoorAliKhanOfficial** [comment]
Is there any update to this? can we get this a bit earlier?

**Comment by angelleye** [comment]
@kcppdevelopers Is this something that can be fixed quickly?  If so let's go ahead and take care of it here on 1.4.6.4.  If not, we'll need to move it back to 1.4.7.
