### ISSUE TITLE
Language file problems..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#877]
* https://mail.google.com/mail/u/0/#inbox/15e7747934c313a6

In #873 we regenerated the language files, but the user that reported issues says it's still not working for him.

> OMG
> No change,Why don't you simply open you pot with Poedit, create a translation file and see what happens ?

@kcppdevelopers Please provide a quick video demo showing that we are able to use the language files successfully with POEdit.

**Comment by kcppdevelopers** [comment]
@angelleye https://www.screencast.com/t/yygRMCQS9

**Comment by angelleye** [comment]
@kcppdevelopers Thanks.  Sent to user to review and hopefully get more info about when it's failing for them.

**Comment by kcppdevelopers** [comment]
@angelleye Could you please ask user to clear C:\Users\bureau\AppData\Local\Temp folder and re try again?

https://user-images.githubusercontent.com/629241/30415965-faed2c2e-98ef-11e7-92b6-1f062913155b.png

**Comment by angelleye** [comment]
@kcppdevelopers Okay, will do.
