### ISSUE TITLE
Braintree - PHP failure when viewing WC order screen for failed order..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#879]
* https://mail.google.com/mail/u/0/#inbox/15eabb253a76ab1c

The user reports that when an order is placed with Braintree and the payment fails (simple decline, for example), it comes in to WC as Failed which is expected, however, when you try to view the order details there's a fatal error:

![image](https://user-images.githubusercontent.com/629241/30766719-9b3a49d2-9fbc-11e7-9b77-765e2a3088ee.png)

**Comment by angelleye** [comment]
This seems to have happened with one of our most recent updates.  Not sure what we did in Braintree that would suddenly cause this..??  Apparently we're making calls to the Braintree SDK methods that require a transaction ID, but of course with a failed payment we don't have a transaction ID to pass in.  So we need to work some logic in to only make those calls for successful auths/sales when we do have a transaction ID, but still let the WC order screen load properly when we don't have a transaction ID.

**Comment by kcppdevelopers** [comment]
#780
