### ISSUE TITLE
Fraud Filter Handling Bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#880]
* https://www.angelleye.com/support/scp/tickets.php?id=1480

>#2 - Before your very last update it worked that the fraud filter when not detecting fraud, but putting it 'under review' that in fact the order was put 'on-hold', that's not the case anymore. It just puts it as processing and it's up to us to make sure everything lines up.

>#3 - When our fraud filter detects a fraud order, it still cancels it properly, but most likely because it never lets it go to PayPal, whereas one order that gets flagged as review does get processed. Woocommerce still knows that it's on review though, see screenshot of Order Notes generated.

![image](https://user-images.githubusercontent.com/629241/30770985-8857cc8a-a003-11e7-96b1-94aba993f629.png)

>#4 - Our assumption is that it has to do with this fix of yours (just an educated guess of ours):
Fix – Resolves an issue in PayFlow where Fraud Filter flags sometimes cause duplicate order failures on re-attempts. (#861)

**Comment by kcppdevelopers** [comment]
@angelleye Can you please explain with more details?

**Comment by angelleye** [comment]
For # 2 above, he's referring to the option we have in settings for Fraud Management Filters.  He has it set to "Place order on hold for further review", however, he says the WC order is getting set to Processing instead of On Hold even when a fraud filter was triggered.

**Comment by angelleye** [comment]
I think # 3 is basically a continuation of the issue, and he provides the graphic to show that the WC order notes do show the fraud filter was triggered in the PayPal response, but the WC order status is Processing instead of On Hold.

**Comment by kcppdevelopers** [comment]
@angelleye I have checked our logic it's working well, Can you please ask user to provide gateway setting screenshot and log file for more troubleshot ?

**Comment by kcppdevelopers** [comment]
@angelleye  In our support system, issue has been resolved.
