### ISSUE TITLE
Auto generated password is not sent in email

### ISSUE THREAD

**Issue by ripieces** [angelleye/paypal-woocommerce#881]
The angelleye_process_customer function in  paypal-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-request-angelleye.php

passes a generated password to the wc_create_new_customer function

This will cause the $password_generated to be false in the function, which in return causes the password not to be displayed in the standard email template.

As a workaround I changed the email template, nevertheless this seems to be a bug to me.

**Comment by angelleye** [comment]
Thanks for the feedback.  We'll take a look and make any necessary adjustments.

**Comment by angelleye** [comment]
@kcppdevelopers Your thoughts on this?

**Comment by ripieces** [comment]
@kcppdevelopers I think the [commit](https://github.com/angelleye/paypal-woocommerce/commit/77b8829525456855a426e4af0934d2e5363c8695#diff-4e8488a26eac7ab1d37129f75f371ce5R1302) is exactly the opposite of what you wanted:

See
https://github.com/woocommerce/woocommerce/blob/3522857d23051844bea742a37a1b0b242f7850af/includes/wc-user-functions.php#L81

I think instead of 
`'yes' === get_option( 'woocommerce_registration_generate_password' )`
You probably want
'yes' !== get_option( 'woocommerce_registration_generate_password' )

**Comment by ripieces** [comment]
Thank you :-)
