### ISSUE TITLE
Express Checkout - Wrong address populating PayPal guest checkout form.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#885]
* https://mail.google.com/mail/u/0/#inbox/15cfae29fc205705
Another report for this : https://www.angelleye.com/support/scp/tickets.php?id=1653
**Ticket created on 9th december:2017**

Video: https://www.dropbox.com/s/zs25n3ixut6esq0/PayPalExpressBug.mov?dl=0

When the WC checkout page is used and you fill out the billing and shipping address, then you're sent to PayPal, the guest checkout form for credit card payment is getting pre-populated with the shipping address that was entered on the WC checkout page instead of the billing address.  

The fields that we're passing in SEC to pre-populate the PayPal Guest Checkout form should be from the WC billing...not shipping.

**Comment by angelleye** [comment]
The fields in the SEC request are indeed specific to SHIPTO address, but it doesn't make sense that we'd be pre-populating the credit card billing with shipping address and not billing.  Seems to be a quirky thing with the way PayPal is working here.

**Comment by angelleye** [comment]
I think we're going to need an option here so people can set this how they want.  I think we should set this up pretty specifically, though, based on other settings.  

If our "PayPal Account Optional" setting is enabled in EC gateway settings, and our "Checkout Page Display" is set to Display in general list of enabled gateways on the checkout page, then we would display an additional option for "Pre-populate PayPal Guest Checkout form with WooCommerce billing address."  This new option can show up right below our Checkout Page Display option.

**Comment by angelleye** [comment]
Hmmm...the thing is, if we pass the WC billing in the SEC shipping fields, then it would pre-populate the guest checkout form with billing as expected, but the shipping address on the order would then be incorrect in the PayPal review pages.  Need to think about this more...

**Comment by kcppdevelopers** [comment]
@angelleye Can you please confirm above issue details?

**Comment by angelleye** [comment]
@kcppdevelopers I'm just going to move this to 1.5.0 for now

**Comment by iMansoorAliKhan** [comment]
I found a ticket similar to this issue, I have added in the description as well and I think that fits the same scenario.

**Comment by iMansoorAliKhan** [comment]
In any case of shipping option I'm seeing like this http://prntscr.com/hmu9n4, client is seeing the same as well.
