### ISSUE TITLE
Braintree Payments Javascript error on checkout payment button click.

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#886]
There seems like some issue left in 1.4.6.3 and even in the current release its not wokring.
https://www.angelleye.com/support/scp/tickets.php?id=1477
When checking out it shows error : error processing checkout
In log it shows following.

For more please see the ticket.

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial The user says he's in Italy.  REST CC is only available for US merchants.

**Comment by MansoorAliKhanOfficial** [comment]
![image](https://user-images.githubusercontent.com/11312949/30952370-0ad9258c-a441-11e7-8458-e16528cc70fc.png)
Thanks for bringing this to my knowledge, But there is another I'm using a theme name **Deli** a child theme of storefront and seeing the above console error

**Comment by angelleye** [comment]
@kcppdevelopers Go ahead and take a look into this please.

**Comment by kcppdevelopers** [comment]
@angelleye @MansoorAliKhanOfficial  it seems Autoptimize plugin cache issue. Can you please uncheck minifies CS and JS from plugin option? and re check again.

**Comment by MansoorAliKhanOfficial** [comment]
I wasn't cache's JS already and now I have opted CSS as well still the same error if you want to check the backend I will send you details over slack

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial yes, please send backend details over slack?

**Comment by MansoorAliKhanOfficial** [comment]
Sent you already there. Soon after I sent you message here. Please check :)

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial I have review your test website and place test order it seems working well.

**Comment by MansoorAliKhanOfficial** [comment]
@kcppdevelopers Sorry, I think I didn't explain well in my last screenshot. The error resolved as there is some dependency of location and currency for REST, which is limited to USA as Andrew told. 1- we need to add a message on the dashboard for that so that we dont get any tickets for this issue.
2- the error here is with stripe js as you can see in the console. when you hit rest credit button or any credit button a JS error from stripe is fired. 
please take a look at that.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan  it seems you are using old/invalid API key.

![2017-10-04_1901](https://user-images.githubusercontent.com/13145461/31178413-992c9ec8-a936-11e7-8d49-083508b7f908.png)

**Comment by angelleye** [comment]
@kcppdevelopers I'm a little confused here.  You told @iMansoorAliKhan he was using an old key, but then you did make a commit and mark ready for review.  So I guess there was indeed an issue you had to resolve..??

**Comment by kcppdevelopers** [comment]
@angelleye  I just remove console.log for display debug data on browser console and change data-log-level='error" for hide javascript notice.

**Comment by kcppdevelopers** [comment]
I have tested with @iMansoorAliKhan and now it's working fine
