### ISSUE TITLE
AVS failure sending New order emails to clients

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#889]
https://www.angelleye.com/support/scp/tickets.php?id=1490

**Comment by angelleye** [comment]
@kcppdevelopers Please check this one out.  Looks like we messed something up with our adjustments to AVS failures and order status..??

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan @angelleye 

It seems client has selected Fraud Management Filters value as Ignore warnings and proceed as usual in gateway setting.

![payflow_error](https://user-images.githubusercontent.com/13145461/31178119-ba8e6476-a935-11e7-9d34-38cb2c55fde6.png)

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers  So you are saying that if this is option is enabled , regardless of any error the order will be process and and new order email will be sent?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan yes, if above option is enabled then it will ignore fraud filter and order process and new order will be sent.

**Comment by angelleye** [comment]
@iMansoorAliKhan Did you verify this with the user?  Can we close this issue?

**Comment by iMansoorAliKhan** [comment]
I had sent a reply to the client and here is what they said.

> Hi,
> I have always had the paypal option set to place order on hold for further review. Shouldn't a failed order or a order that doesn't pass AVS not send out a new order conformation email? This just started with the last update. Thank you

**Comment by angelleye** [comment]
@iMansoorAliKhan I'm confused.  The screenshot @kcppdevelopers placed above shows "Ignore warnings and proceed as usual", but the client is saying they didn't have it set that way..??  

If I understand correctly, what's happening is the order is getting set to Processing which triggers the new order email, but then if you have it set to place on hold it's getting switched after that.  Is that correct @kcppdevelopers?

What's interesting is the user says this didn't start happening until are last update..??  What did we do that would affect the order status and email confirmations?

**Comment by iMansoorAliKhan** [comment]
Do you need his site login to take a look?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan yes, it would be great.

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers I have responded to his ticket, I will update here upon their reply.
