### ISSUE TITLE
Express Checkout - Shipping required popping up again..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#890]
* https://mail.google.com/mail/u/0/#inbox/15ecf141d56ec759

>It's for new orders when using Express. On the review page, it isn't receiving the shipping info that should've been passed to it, even after filling out all the separate shipping info. 

> ![image](https://user-images.githubusercontent.com/629241/31114824-71eb4f00-a7e5-11e7-9414-7fa92d00861a.png)

**Comment by angelleye** [comment]
> To explain a bit more about this shipping issue - we had turned ON the option to have the shipping address visible by default. 
> 
> After we made this change, for Express orders, when they get to the Review page, its giving an error stating its not receiving the shipping first/last names (as seen in my last screenshot). Though the info on the review page actually shows that its not seeing the billing first/last name. Even if entered on the Checkout page, and seen on the Paypal payment page, on the Review it doesn't see the first/last name correctly and prevents checkout.

**Comment by angelleye** [comment]
>Here's the log for that error the customer saw. Looks like there was actually several of these, but no one else reported it.

[log-files.zip](https://github.com/angelleye/paypal-woocommerce/files/1351508/log-files.zip)

**Comment by angelleye** [comment]
@kcppdevelopers 

So he mentioned this was happening with Express, but the log files he provided look like they're for PayFlow.  Also, the error in the log file is about the cart items not adding up, and he did confirm they are using coupons.  

So it seems we're still running into our cart total error in this configuration, and somehow that is also causing a problem on our review page..??

**Comment by angelleye** [comment]
I have asked for credentials to their test site (although you may still already have them from before...this is the cannapet client.)

**Comment by kcppdevelopers** [comment]
@angelleye I have review log file and it seems client using our old version of our plugin. Can you please ask to client and confirm our plugin version?

**Comment by angelleye** [comment]
@kcppdevelopers I will give you credentials in Slack.

**Comment by kcppdevelopers** [comment]
@angelleye I have review and found they are using 1.4.6.2 version

**Comment by angelleye** [comment]
I have informed the user they need to update to our latest version and it should resolve their issue.
