### ISSUE TITLE
Payments Advanced - Payment completes successfully but WC order is pending and then cancels..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#891]
* https://mail.google.com/mail/u/0/#inbox/15cfae29fc205705

Payment completes successfully but WC order is pending and then cancels..??

> I have another issues which just popped up. A customer placed an order and the payment in our PayPal system shows as accepted. However the notes on the order in WC show as:
> 
>Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled.
> 
> And the order was cancelled for some reason.
> 
> Do you know of why this would happen as the payment was successfully accepted by PayPal Advanced. 

![image](https://user-images.githubusercontent.com/629241/31220931-a026b2b2-a987-11e7-8f59-54cb70ae66e2.png)

[paypal_advanced-0919a652d9d77eb4487e470fd94bbf54 (1).log](https://github.com/angelleye/paypal-woocommerce/files/1351588/paypal_advanced-0919a652d9d77eb4487e470fd94bbf54.1.log)

**Comment by angelleye** [comment]
One interesting thing I notice in the graphic above is it says "Payment via ." and it doesn't include the actual payment method.

**Comment by kcppdevelopers** [comment]
@angelleye yes right, It seems Just created basic order as pending status, Payment process part is not involved due to server down or PHP error.

**Comment by angelleye** [comment]
They moved to PayPal Pro and they aren't having issues there.  Sinc we don't have any other reports of this I'll close the issue.
