### ISSUE TITLE
Duplicate orders since last update..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#893]
* https://www.angelleye.com/wp-admin/post.php?post=7424&action=edit

> All of our orders are automatically(?) or manually being duplicated by the user? We keep having to Refund anywhere from 2-6 duplicate orders because we are charging credit cards 2-6 times over!
> 
> The website is https://www.pararescue.com
> 
> I have no idea how to troubleshoot this to determine if it is an automatic action or a customer-generated action. This did start happening after the previous version update of your plugin.
> 
> I would appreciate it if you could review our plugin settings fully and make sure there are no settings or variables misconfigured that could be causing this problem. Once you thoroughly review the site settings, I will then place several live transactions to see if they go through smoothly and correctly with no duplicate orders.

**Comment by kcppdevelopers** [comment]
@angelleye  Can you please ask for website login details for more troubleshoot?

**Comment by angelleye** [comment]
@kcppdevelopers Yes, I've been trying to get that from them.  Will update you as soon as I'm able to get it.

**Comment by angelleye** [comment]
I've never been able to get this guy to respond to me, and he never contacted me after placing this premium support order.
