### ISSUE TITLE
No Pending order if express checkout button used

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#894]
https://wordpress.org/support/topic/no-pending-order-if-express-checkout-button-used/

I have just tested it on my test site as well and also discussed it with Andrew, seem like some issue is there as I did not get it working even when I'm login to my site and placed an order using EC button.

**Comment by LiamBailey** [comment]
Hi - I would like to take a look at this as one of my pull requests for Hacktoberfest - would this be possible?

**Comment by LiamBailey** [comment]
@iMansoorAliKhan ^^

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have test above issue and it's working fine for me. we are only create pending order and save customer data when user placed order from checkout page using gateway list and Save Abandoned Checkouts is enable on gateway setting.

**Comment by angelleye** [comment]
@kcppdevelopers I wasn't aware that we aren't saving orders when the WC checkout page is skipped.  When do we create the WC order in that case?  Is it after they're returned to our review page?

We should probably adjust the setting description to make sure people understand that.
