### ISSUE TITLE
Express Checkout - Double check shipping address when WC checkout page is used.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#895]
* https://mail.google.com/mail/u/0/#inbox/15eee3f7da7bc69c

I don't remember exactly how we have this setup, so just need to run a test and verify.

In a situation where the WC checkout page is used, I'm pretty sure we're sending the shipping address entered to PayPal, but I don't remember if we're using SHIPPINGOVERRIDE or not..??

Need to see whether or not we are, and then consider options for how to implement this.  Some people want it and others don't.

**Comment by angelleye** [comment]
User question...

>I'd like my orders to use the shipping address in the buyer's PayPal account, not what is entered on the check out page.  I believe this protects me better from fraud and address errors.
I've been using a home built IPN listener for years in this way before WooCommerce.
Is it correct to assume that I get the shipping address from PayPal in the IPN if I remove the checkout page address form and check the address override setting?

Here is my response.  Need to make sure this response is indeed accurate.

> The simple answer to your question is that the IPN data will include whatever shipping address was set in the PayPal review pages.  I can expand on that, though.
> 
> If you have your Express Checkout buttons enabled on the product pages and/or cart page then people can skip the WC checkout page altogether, which is truly where the "Express" comes into play.  They don't have to fill out checkout forms at all, and then they would just choose whatever shipping address they want based on what's in their PayPal account, or they could also edit/enter a different address there.
> 
> If the WC checkout page is used then we will send that address over to PayPal to be used for shipping on the order.  If the user were to edit the shipping address at this point (by choosing a different one associated with their account or entering a new one) then that address would be used for the final order and would be seen in the WC order details as well as in the IPN data and PayPal transaction details.
> 
> Whether or not the address used is covered by PayPal Seller Protection is completely based on PayPal's risk formula.  In most cases, if the address used is a confirmed address on the PayPal account then it will probably be covered by Seller Protection, but not always.  Also, there are plenty of instances where a different address is used, but PayPal still covers it with Seller Protection.  
> 
> So really what you want to make sure to look for is the Protection Eligibility data that comes back in the IPN.  Make sure it's eligible, and make sure to ship to the address on that IPN, and you'll be good to go.

**Comment by kcppdevelopers** [comment]
@angelleye yes, when Express checkout used from checkout page gateway list and user has fill up address on that condition we are passing $SECFields['addroverride'] = 1
