### ISSUE TITLE
PayFlow - Refund Transaction ID

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#897]
I just submitted a refund through WC order that was paid with PayFlow.  Upon doing so, I see the refund line and it shows -15.00, but I do not see the refund transation ID anywhere in the order details now..??

![image](https://user-images.githubusercontent.com/629241/31425281-31f8b8e8-ae24-11e7-835a-9b4040b4e21c.png)

We were supposed to have added refund transaction ID into notes and meta field just like the regular transaction ID in previous issues, but it seems we missed it in PayFlow..??

**Comment by kcppdevelopers** [comment]
@angelleye 

It seems it's partially refunded order, In the partially refund order page is not reloaded that why you are not seen refund ID on post meta field and order note. if you re load order details page, Refund ID must be there on post mete field as well on the order note.

**Comment by angelleye** [comment]
Verified the refund data did show up when I reloaded the page.
