### ISSUE TITLE
Filter Hooks to adjust checkout field labels..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#898]
* https://wordpress.org/support/topic/labels-on-fields/

>If I wanted to change the titles/labels of the fields (Expiry to Expiration Date, etc) in the Braintree CC processing part of the plugin, what would be the best way to do that without modifying the plugin itself?

Need to look into adding filter hooks for all of our gateways so that people can adjust the field labels if they want to.

**Comment by kcppdevelopers** [comment]
@angelleye  In Braintree CC UI, we have used Woo default CC UI. there is no any hook/filter available to change fields name.

**Comment by kcppdevelopers** [comment]
![cc_form](https://user-images.githubusercontent.com/13145461/33828987-48bfc882-de94-11e7-8105-767ff21c6cfa.png)

**Comment by angelleye** [comment]
@kcppdevelopers As discussed in Slack it seems we're actually not using the built in Woo forms, so we can go ahead and add our own filter hooks for adjusting field labels.

**Comment by kcppdevelopers** [comment]
> add_filter('cc_form_label_card_number', 'own_cc_form_label_card_code', 10, 2);
add_filter('cc_form_label_card_code', 'own_cc_form_label_card_code', 10, 2);    
add_filter('cc_form_label_expiry', 'own_cc_form_label_expiry', 10, 2);   


> function own_cc_form_label_card_code($lable, $gateway_id) {
    // $gateway_id value like braintree, paypal_pro, paypal_advanced, paypal_credit_card_rest, paypal_pro_payflow
    $lable = 'Test Card number';
    return $lable;
}

> function cc_form_label_card_code($lable, $gateway_id) {
    // $gateway_id value like braintree, paypal_pro, paypal_advanced, paypal_credit_card_rest, paypal_pro_payflow
    $lable = 'Test Card Security Code';
    return $lable;
}

> function own_cc_form_label_expiry($lable, $gateway_id) {
    // $gateway_id value like braintree, paypal_pro, paypal_advanced, paypal_credit_card_rest, paypal_pro_payflow
    $lable = 'Test Expiration Date';
    return $lable;
}
