### ISSUE TITLE
Express Checkout - AccessPress theme conflict..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#900]
* Adendorff Johan Birgit via Facebook Messenger
* https://wordpress.org/themes/accesspress-store/

This theme seems to have a problem with our EC button on the cart page.  When the EC button is displayed above the cart it functions correctly, but when the EC button is displayed below the cart it does not function.  It displays, but you can't click on it.

![image](https://user-images.githubusercontent.com/629241/31487800-4b763dc6-af01-11e7-9a2e-46b8d60b4ff2.png)

Need to install this theme locally and see if we can reproduce the issue.

**Comment by angelleye** [comment]
@iMansoorAliKhan Can you please download the theme and test to see if you are able to reproduce this problem?

**Comment by angelleye** [comment]
User points out that bottom button is missing the additional div when compared to top button.

**Top Button**

```
<div class="wc-proceed-to-checkout angelleye_cart_button"><a class="paypal_checkout_button paypal_checkout_button_top" href="https://teleseal.de/?wc-api=WC_Gateway_PayPal_Express_AngellEYE&#038;pp_action=set_express_checkout"><img src=https://teleseal.de/wp-content/plugins/paypal-for-woocommerce/assets/images/dynamic-image/de_DE.gif class="ec_checkout_page_button_type_paypalimage"  align="top" alt="Pay with PayPal" /></a></div>
```

**Bottom Button**

```
<a class="paypal_checkout_button paypal_checkout_button_bottom" href="https://teleseal.de/?wc-api=WC_Gateway_PayPal_Express_AngellEYE&#038;pp_action=set_express_checkout"><img src=https://teleseal.de/wp-content/plugins/paypal-for-woocommerce/assets/images/dynamic-image/de_DE.gif class="ec_checkout_page_button_type_paypalimage"  align="top" alt="Pay with PayPal" /></a>
```

Not sure if that has anything to do with this issue or not..??

**Comment by kcppdevelopers** [comment]
@angelleye Can you please confirm they have Enable In-Context or not and which version they have used?

**Comment by angelleye** [comment]
@kcppdevelopers They're using our 1.4.6.5 version, but I'm not sure about In-Context or the version of the theme.  I've asked and waiting for response.

**Comment by iMansoorAliKhan** [comment]
@angelleye Here is what saw 
http://prntscr.com/gx26v7
I done see any button like that may be language change make it different?

**Comment by iMansoorAliKhan** [comment]
I I think I found the issue. Please take a look at the screenshot.
http://prntscr.com/gx28yl

**Comment by iMansoorAliKhan** [comment]
![image](https://user-images.githubusercontent.com/11312949/31560550-30d665c2-b06e-11e7-90b6-7d0fd91de99d.png)

**Comment by kcppdevelopers** [comment]
@angelleye @iMansoorAliKhan  I have checked with AccessPress theme and it seem it working fine for me.

**Comment by angelleye** [comment]
@iMansoorAliKhan Did you circle back with the customer on this after we were unable to reproduce?

**Comment by iMansoorAliKhan** [comment]
@angelleye , this client was from **Adendorff Johan Birgit via Facebook Messenger**, So I dont know where to reply back, You asked me to test and I was able to reproduce that same issue on my demo site.

**Comment by angelleye** [comment]
@kcppdevelopers So now we have an end user saying this problem happens to them, and @iMansoorAliKhan is able to reproduce, but you say everything is fine for you..??

Seems we need to dig a little deeper here.  @iMansoorAliKhan were you running latest versions of everything?  Need to figure out what's different between your test and @kcppdevelopers' test

**Comment by iMansoorAliKhan** [comment]
I had tested it with the most recent version of Plugin ( that time ) and theme too.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan Could you please provide your input here?

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers , sure I;m gonna test it today and will leave feedback.

**Comment by iMansoorAliKhan** [comment]
![image](https://user-images.githubusercontent.com/11312949/34245946-3b71deba-e64e-11e7-8eb9-5fda97d2445b.png)
if set to 100% then this happens

![image](https://user-images.githubusercontent.com/11312949/34245980-6868e6e8-e64e-11e7-8e21-03ab03b1b3d9.png)

So here is what I see: The Pay with credit card button is over this grey overlay from theme css , so I think we need to play with z-index to get our buttons to the level of **Pay with credit card button** so that this issue can be sorted

**Comment by iMansoorAliKhan** [comment]
If I add position to our buttons then they are up the overlay from theme 
http://prntscr.com/hqepkq

**Comment by angelleye** [comment]
@kcppdevelopers Looks like you should have some more info to work with here now..??
