### ISSUE TITLE
Settings Logos

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#901]
In our Settings -> PayPal for Woo I want to add logos for each of the PayPal products instead of text headers.

**Comment by angelleye** [comment]
I would also like to make each separate product a tile on the page, instead of stacked text.

**Comment by kcppdevelopers** [comment]
@angelleye I think we need to new tab for Premium Extensions / Support same like PayPal IPN for WooCoomerce.

**Comment by angelleye** [comment]
@kcppdevelopers Yes, I agree.  I think I have a separate issue for that, actually, but we can do that here.  

We'll need to pull products using a specific tag the same way we do in the IPN plugin.  In this case the tag will be `paypal_woocommerce_premium_extension`

**Comment by angelleye** [comment]
@kcppdevelopers Something isn't right here.  The new premium extensions stuff is showing up where the payment gateways should be showing up, and the same image is being output for every product.

![image](https://user-images.githubusercontent.com/629241/32204013-d70fa73e-bdb4-11e7-9261-5646bc2004d7.png)

**Comment by angelleye** [comment]
@kcppdevelopers Ah, nevermind, I guess this is just setup as tiles now, but you didn't use the separate logos..??  

We should see a PayPal Express Checkout logo in that tile, and a PayPal PayFlow logo in that tile, etc.  We should be able to find good quality graphics for that using Google image searches.

**Comment by angelleye** [comment]
The premium extensions tab isn't displaying any products.  I thought I had something setup with the tag we're using here, but I'll double check.

**Comment by angelleye** [comment]
@kcppdevelopers Please use the attached logos for the gateway tab.
[paypal-for-woo-gateway-logos.zip](https://github.com/angelleye/paypal-woocommerce/files/1460769/paypal-for-woo-gateway-logos.zip)

**Comment by angelleye** [comment]
@kcppdevelopers We need to add a little bit of spacing here:

![image](https://user-images.githubusercontent.com/629241/32651183-f7225dfa-c5c5-11e7-9d34-bbb7019ba50c.png)

The line about "Premium extension available at www.angelleye.com" needs to be spaced a little better so it's not smashed up against the tabs.
