### ISSUE TITLE
Express Checkout - WP User Account Creation Adjustments..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#903]
* https://wordpress.org/support/topic/express-checkout-doesnt-create-wp-user-with-right-details/

**Comment by kcppdevelopers** [comment]
@angelleye We are using PayPal shipping details for customer, Can you please explain with more details what we have to do on this issue?

**Comment by kcppdevelopers** [comment]
@angelleye Woo EC plugin by default create the user and order,  before the customer is leaving the website and then it updates the order with the PayPal transaction status. our plugin by default not saving order and user related data but we already provided an option name like 'Save Abandoned Checkouts' if enable 'Save Abandoned Checkouts' it will create order and save user data.

**Comment by angelleye** [comment]
@kcppdevelopers It seems logical that it should create the order before leaving for PayPal and then update that order upon return.  Is there any specific reason we didn't set ours like that to begin with?  Then we wouldn't even need that option about saving abandoned checkouts because it would just happen by default wouldn't it?

**Comment by angelleye** [comment]
@kcppdevelopers I see you did make a commit after I asked about your opinion on what the user is reporting, but then you responded as if you didn't do anything..??  What did you do in that commit?  Also, please see my last comment.

**Comment by kcppdevelopers** [comment]
@angelleye before we have used shipping details return from PayPal and Now I have add condition if checkout page used and user has already enter details than used that details.

**Comment by angelleye** [comment]
@kcppdevelopers so in that case are you including SHIPPINGOVERRIDE so that they can't change it during PayPal checkout pages?  Or if they do change it during PayPal's checkout pages are you making sure to use that address for shipping, but leaving what they enter on the WC checkout page for billing?
