### ISSUE TITLE
Express Checkout - Adjustments to button display logic on cart page.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#906]
* https://mail.google.com/mail/u/0/#inbox/15eaf03f3b996629

>Also, with Express Checkout, the "checkout" page still works, but there is no "proceed to checkout" button anymore. Even though I am using only Express Checkout, there still should be a "Proceed to Checkout" button since the "checkout with PayPal" and "PayPal credit" buttons do not make it clear that you can also pay with a credit card. 

>![image](https://user-images.githubusercontent.com/629241/31590601-bcb2406e-b1d8-11e7-93ae-50d62af9fc43.png)

**Comment by angelleye** [comment]
We should review our display logic and potentially make some adjustments to give people more control over how this is displayed.  We have logic around what gateways are enabled as well as what setting is configured for Express Checkout on the WC checkout page.

**Comment by angelleye** [comment]
Also we should consider the point they're making that when our EC button is all that shows up on the cart page you can't tell that you can also pay with a credit card.  They're wanting to force the WC checkout page so that people can tell, but it would be better to adjust our display shown in the screenshot so it's clear that people without PayPal can still pay.

**Comment by kcppdevelopers** [comment]
@angelleye Can you please explain with more details?

**Comment by angelleye** [comment]
@kcppdevelopers As I look at this again I think a simple solution would be for the user to update the EC button with their own graphic that includes whatever icons they want.  I'll let them know that.  We can skip this for now.
