### ISSUE TITLE
No item description on paypal screen

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#910]
http://prntscr.com/gyma8v

Dont know why I'm seeing this, It was working before but dont know why now its empty.
Is this option dependent on the Sending LineItem parameter in PAypal For WOO settings?

**Comment by iMansoorAliKhan** [comment]
Also , its guest checkout and the email I used to signup at checkout was demo@gmail.com
But when returned from paypal it showed me this http://prntscr.com/gymb3d, ( my paypal sandbox email ) Why?
And this field ?? http://prntscr.com/gymbrp
And then this > http://prntscr.com/gymcnj
I have accepted it previously but now again before placing order its asking me to accept but I dont see any checkbox there.
Theme Storefront and CHild theme vendor ( both same behaviour )

**Comment by iMansoorAliKhan** [comment]
Also this is the same case even when I'm login too

**Comment by angelleye** [comment]
@iMansoorAliKhan Line items will only show up in that section of the PayPal screen if you do have "Send Line Items to PayPal" enabled.

**Comment by iMansoorAliKhan** [comment]
So as per my understanding, the item details will only be showing on the paypal login / payment screen if that option is enabled, Right?

**Comment by angelleye** [comment]
@iMansoorAliKhan Correct.

**Comment by angelleye** [comment]
@iMansoorAliKhan If there's nothing else we need to review here please close the issue.  I'm not sure if that's all this was for or not..??

**Comment by iMansoorAliKhan** [comment]
Yeah, I was actually confused as previously it was working differently, or maybe I notice that now.
Anyways. Please consider this sorted.
Thanks!
