### ISSUE TITLE
Express Checkout - Adjust cancel URL when paying from pending order.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#911]
* https://wordpress.org/support/topic/cancel-page-when-paying-for-pending-order/

**Comment by kcppdevelopers** [comment]
@angelleye 

> Scenario:
> 
> 1. Put in an order as pending
> 2. go to complete payment
> 3. hit paypal button
> 4. decide to cancel out of paypal
> 5. you are now returned to the Checkout page (or whatever page configured as the Cancel Page)
> 
> This causes confusion as you are shown a page saying your basket is empty, whereas you expect to return to the order you were trying to pay for (eg to choose a different payment method).

above is by default woo functionality, Cart is empty because order created from admin panel.
