### ISSUE TITLE
Checkout page Styling issues with Payflow and Payments pro 

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#912]
https://wordpress.org/support/topic/cc-form-layout/
I have tested this on my local with 3 theme
1- enfold
2- be theme
3- salient
All have same results. The year and expiry date are actually not showing correct
**Salient**
1- http://prntscr.com/gz42qq
2- http://prntscr.com/gz4301
**BeTheme**
1- http://prntscr.com/gz440k
2- http://prntscr.com/gz448e

**Comment by kcppdevelopers** [comment]
@angelleye by default woo provide textbox for CC expired date, we have modified that functionality and provide select box. I think we need to add new option in gateway setting panel for used textbox or select box for CC expired date.

**Comment by angelleye** [comment]
@kcppdevelopers Please remind me why we added our own..??  Is it because of our option to display numbers or names?  If so, then yeah, let's add the additional option like you said, but then we should hide the options for numbers vs. names unless you've chosen to display that way.

**Comment by kcppdevelopers** [comment]
@angelleye 

Yes, because of display selectbox for Expiration Date instead of single textbox 

by default woo provide below UI

![default](https://user-images.githubusercontent.com/13145461/32044947-9fc3cf90-ba5c-11e7-9bc7-22f4b9a048dd.png)

our PayPal for Woo provide below UI

![our](https://user-images.githubusercontent.com/13145461/32044992-bf9c6886-ba5c-11e7-93e1-e1d786c6bce7.png)

**Comment by angelleye** [comment]
@kcppdevelopers Isn't there some way we could just add an option for people to apply their theme styles easily so it matches?  Or doesn't WooCommerce have a default style for drop downs we could set so it matches better?

**Comment by iMansoorAliKhan** [comment]
I had sent this to the client , they reported that it worked well on desktop/ tablet/.
but on mobile it shows something like this http://www.reedededge.com/Screenshot_20171107-101828.png. 
Can we make it look more good and the fields takes full place like adding bootstrape col-xs-6 or something like that?

**Comment by angelleye** [comment]
@kcppdevelopers Please see above screenshot.  Definitely need to figure out how to make this look better.
