### ISSUE TITLE
PayPal Pro CSS Adjustment Necessary..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#915]
* https://mail.google.com/mail/u/0/#inbox/15eaf03f3b996629

>There is also an issue with the PayPal Pro photo being shown really small on the checkout page. This is because there is an attribute for .payment_methods label img setting its max-width to 66px. I have temporarily fixed with myself with custom CSS, but it should be fixed in the plugin itself for other users.

> 
> ![image](https://user-images.githubusercontent.com/629241/32086312-fcd5e1b8-ba99-11e7-9a17-80224b3fbda8.png)
> 
> ![image](https://user-images.githubusercontent.com/629241/32086321-02f407aa-ba9a-11e7-9799-4b008572f8eb.png)

**Comment by kcppdevelopers** [comment]
@angelleye I have checked and found that above CSS is not from our plugin.
