### ISSUE TITLE
Accept terms and Condition error on Order review page

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#916]
Hi, 
I have received a ticket stating that they see error on order review page when they hit Place order button

> Please accept terms and conditions

They have this ON in their checkout settings, Al Though I was not able to reproduce this error on my test site.
Even switching to Storefront, and Basic theme didn't help either, so when I did some debugging,  following CSS was hiding that on the order review page, so Not sure why this was hidden or which condition was not fulfilling to fire this error. Please check and let me know if you I'm missing something. Or there is something in the setting which I need to be sure?

```
.form-row terms.wc-terms-and-conditions, 
.express-checkout.express-hide-terms .wc-terms-and-conditions{
display:none !important;
}
```

**Another ticket with this same issue reported 4th dec**
https://www.angelleye.com/support/scp/tickets.php?id=1642

**Comment by angelleye** [comment]
@kcppdevelopers If this can be fixed within a few minutes please take care of it on 1.4.6.6.  If not, please move it to 1.4.7.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan Can you please provide support ticket details?

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers , sure, Please see this one. https://www.angelleye.com/support/scp/tickets.php?id=1549
I have assigned this to you for review.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan Admin login details not working, Can you please ask it again?

**Comment by iMansoorAliKhan** [comment]
Well they might have changed it as it was a staging site, I have asked them for the details, Will update here soon.

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers , I need to update here, I was able to reproduce this using Flatsome theme and X theme as well. Here is how to reproduce this issue.
Add a product to cart, go to checkout page and do a normal checkout using default gaateways ( make sure order review page is enabled )
When you will return from PayPal it will not show you the button to accept terms.
but If you do checkout using EC button you will see terms and condition check .

Please try that scenario and see if you are able to reproduce this using the current Active version .
Thanks!

**Comment by iMansoorAliKhan** [comment]
**Update: ** When you are testing the scenario, check it when WC germanized is enabled too.
I guess there is a conflict coming from this plugin as well.

**Comment by iMansoorAliKhan** [comment]
Now on client side I can still see that something from our plugin is hiding that button
http://prntscr.com/hjq57l

This happens only if you have terms and condition page set too.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I found issue, it conflict with Germanized  plugin.

**Comment by iMansoorAliKhan** [comment]
```
Now on client side I can still see that something from our plugin is hiding that button
http://prntscr.com/hjq57l

This happens only if you have terms and condition page set too.
```

did you tested this scenario as well? because client dont have germanized installed at all.

**Comment by iMansoorAliKhan** [comment]
On my local test this worked for me.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan yes, I have tested above scenario as well and it's working well.

**Comment by DamirPecnik** [comment]
In my case this is not working, the js code that ticks the checkbox is not firing on Review Order page!

**Comment by iMansoorAliKhan** [comment]
Can you open your browser's debugger console and see if there are some JS errors on the order review page? Or can you share your site URL?

**Comment by angelleye** [comment]
@DamirPecnik Did you pull the entire current dev branch for testing?  Did you make sure to clear any caching / CDN tools that you may be running after updating to our latest dev branch?

**Comment by DamirPecnik** [comment]
Installed 1.4.7 and its working fine now! Sorry for the false alarm.

**Comment by kcppdevelopers** [comment]
@DamirPecnik glad to hear it! If you have a moment to [leave a review for the plugin](https://wordpress.org/support/plugin/paypal-for-woocommerce/reviews/) that would be greatly appreciated. Thanks!
