### ISSUE TITLE
Woo Subscriptions - Tokenized Payment dependency..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#917]
* https://wordpress.org/support/topic/woocommerce-subscription-with-paypal-for-woocommerce/

User says that renewal payments are not working, and are getting stuck as pending.  He noticed that "Tokenized Payments" are not enabled in his PayFlow settings.

I'm unsure if this matters..??  That option is intended to enable the ability for buyers to save their payment method with the site for faster checkout in the future.  Woo Subscriptions should not depend on that particular setting.  

Please verify whether or not this dependency does exist, and if so, we should adjust accordingly.  If not, we need to figure out why it's not working for this user.

**Comment by kcppdevelopers** [comment]
@angelleye I have double check our logic and it's working..

User said on above support ticket:

> Case closed, Its fixed now, the last steps i was missing is the paypal step to enable “Allow reference transactions” on PayPal PayFlow manager, after i set this its working like a charm.
