### ISSUE TITLE
Express Checkout - Variations / Attributes

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#918]
* https://wordpress.org/support/topic/variation-1-variation-2-missing-from-paypal-email

Product attributes are not getting included in our PayPal EC calls..??  We should check if EC provides the "option" parameters associated with line item details in the request.  If not, we need to try and get these attributes included in the Item Name line somehow (which I thought we had already done previously..??)

**Comment by kcppdevelopers** [comment]
@angelleye I have checked and found that we already passed product details.

![issue-918](https://user-images.githubusercontent.com/13145461/32551063-471ea316-c4b5-11e7-9e8a-4d23e80e2434.png)

**Comment by angelleye** [comment]
Okay, I see we're passing some extra info in the DESC field, but did you check the PayPal transaction details page to make sure that's actually showing up there somewhere?  Can you provide a screenshot of this transaction in your PayPal sandbox account you ran the test with?

**Comment by kcppdevelopers** [comment]
![transaction](https://user-images.githubusercontent.com/13145461/32593522-44a1aec8-c54e-11e7-9c82-8beb6acbc25a.png)
