### ISSUE TITLE
Express Checkout - Negative shipping amount because of our custom calcs still happening..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#922]
* https://wordpress.org/support/topic/transactions-hold-in-processing-status

**Comment by angelleye** [comment]
He's not able to provide much detail about his setup, unfortunately, but he says when he switched to the other Express plugin the problem went away.  We have got to figure out why we keep running into this.

**Comment by angelleye** [comment]
One of the users in the thread mentions that it works fine with PayFlow but not Express.  This is confusing to me because I thought we had the same calculation class being used everywhere..??

**Comment by kcppdevelopers** [comment]
@angelleye  yes, we have the same calculation class being used everywhere. it would be great to have log file to more troubleshoot.

**Comment by kcppdevelopers** [comment]
@angelleye  I have checked all the cases and it seems working fine for me.
