### ISSUE TITLE
Payments Pro PayFlow - Bad Gateway..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#927]
* https://wordpress.org/support/topic/gateway-error-3

> 2017/11/13 17:36:49 [error] 7451#0: *899299 FastCGI sent in stderr: “PHP message: billing_first_name was called incorrectly. Order properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-includes/template-loader.php’), do_action(‘template_redirect’), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::do_wc_ajax, do_action(‘wc_ajax_checkout’), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_PayPal_Pro_PayFlow_AngellEYE->process_payment, WC_Gateway_PayPal_Pro_PayFlow_AngellEYE->do_payment, WC_Order->payment_complete, do_action(‘woocommerce_payment_complete’), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, IDT_Woo_Sendy_Subscription_Integration->add_to_sendy_mailer, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
> PHP message: billing_last_name was called incorrectly. Order properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-includes/template-loader.php’), do_action(‘template_redirect’), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::do_wc_ajax, do_action(‘wc_ajax_checkout’), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_PayPal_Pro_PayFlow_AngellEYE->process_payment, WC_Gateway_PayPal_Pro_PayFlow_AngellEYE->do_payment, WC_Order->payment_complete, do_action(‘woocommerce_payment_complete’), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, IDT_Woo_Sendy_Subscription_Integration->add_to_sendy_mailer, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
> PHP message: billing_email was called incorrectly. Order properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-includes/template-loa
> 2017/11/13 17:36:49 [error] 7451#0: *899299 upstream sent too big header while reading response header from upstream, client: 67.143.192.89, server: sidewalkshield.com, request: “POST /?wc-ajax=checkout HTTP/1.1”, upstream: “fastcgi://unix:/var/run/php/php5.6-fpm.sock:”, host: “sidewalkshield.com”, referrer: “https://sidewalkshield.com/checkout/”

**Comment by kcppdevelopers** [comment]
@angelleye I have double check above error is not from our plugin, it from IDT_Woo_Sendy_Subscription_Integration->add_to_sendy_mailer function.

**Comment by angelleye** [comment]
I have responded to the WP ticket to inform the user of this info, and I'm closing this issue.
