### ISSUE TITLE
Express Checkout - Google Analytics / Facebook Pixel Tracking Bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#929]
* https://www.angelleye.com/support/scp/tickets.php?id=1570

It seems that our Express Checkout integration is interfering with Google Analytics / Facebook Pixel order tracking systems.

**Comment by tejasm-itpath** [comment]
@angelleye 
As per this link http://blog.analytics-toolkit.com/2015/payment-gateway-referrer-exclusions-google-analytics/

> utm_nooverride=1 is a parameter that you attach to your payment gateway return pages. Say your return page is /checkout/payment/success. You need to provide this URL to your payment gateway: **/checkout/payment/success?utm_nooverride=1 . This way Google will ignore the referrer information for this session if there is already another session in progress.**

**Comment by angelleye** [comment]
@tejasm-itpath The user says they excluded paypal.com from within their Google Analytics settings and now things are tracking properly.  As such, I'm curious if we still need the change we made here..??

**Comment by kcppdevelopers** [comment]
@angelleye yes, we just added "utm_nooverride" query parameters it will help to Google Analytics things tracking properly.
