### ISSUE TITLE
Premium Extensions Tab Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#932]
CSS / Div layout isn't good for the premium extensions tab.  It's showing up like this:

![image](https://user-images.githubusercontent.com/629241/32838807-cf07ffda-c9d7-11e7-9094-e9c13bf750a6.png)

Need to adjust the CSS for this tab so it correctly displays the product images.

**Comment by kcppdevelopers** [comment]
![932](https://user-images.githubusercontent.com/13145461/32852904-7c7f3250-ca5f-11e7-804d-dea3119e7522.png)
