### ISSUE TITLE
Transaction Rejected error

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#934]
https://www.angelleye.com/support/scp/tickets.php?id=1597
One of client receievd this error 

```
"10606 transaction rejected" notification message, when he tried to buy an item.
The message says there is "not enough "---item name---" to fulfil your order right now.
```
Although, in logs the 10606 means buyer can not pay , if so then why the error is reporting for stock ?

**Comment by angelleye** [comment]
@iMansoorAliKhan, where exactly did that message show up for them?  Was that part of the PayPal error from their API, or is that something that came from WooCommerce?

**Comment by iMansoorAliKhan** [comment]
![failed_order 1](https://user-images.githubusercontent.com/11312949/32881836-496d9f08-cad4-11e7-9aa1-e40c74de1f04.png)

This is what they have shared.

**Comment by kcppdevelopers** [comment]
@angelleye @iMansoorAliKhan it seem there is two error are mix-up. 1) first error from PayPal 2) It's from woo, user has Enable stock management at product level.

So it's not our plugin issue..
