### ISSUE TITLE
Updating Translation Files..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#936]
When I update other plugins with translations, they typically automate the process of updating the translation files and I see notices about it:

![image](https://user-images.githubusercontent.com/629241/32890555-dfd732dc-ca94-11e7-9b1c-7e8265ffa9ed.png)

Our plugin isn't doing this.  We need to look into how to make sure our translations are always up-to-date and updated along with our plugin updates.

**Comment by kcppdevelopers** [comment]
@angelleye I have checked found that 

> Automatic translation file updates are already enabled by default, the same as minor core updates. 

It will only automatic update translation file if translation file 100% translated.
