### ISSUE TITLE
Copy Yoast

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#937]
I'd like to Copy what Yoast SEO plugin has done with all of their support, marketing, notifications, etc. built into their plugin.

**Comment by angelleye** [comment]
With Yoast SEO installed, when you click into the SEO -> Dashboard you'll find a Notifications panel.  This allows Yoast to push notifications to this panel at any time, and the user can read / dismiss these notifications.

We don't have our plugin displayed in the primary admin panel menu sidebar, so if we have notifications available that the user has not yet read / dismissed we should display a general admin notice letting them know there are notifications to view for PayPal for WooCommerce with a link to send them to our notifications panel.

Our panel can go under Settings -> PayPal for WooCommerce -> Notifications Tab.

**Comment by angelleye** [comment]
We'll need a simple tool from angelleye.com that allows us to submit these push notifications as well.

**Comment by tejasm-itpath** [comment]
@angelleye 
For this we need to discuss on call, How can we manage notifications and How can we add that notice in particular domain.

**Comment by angelleye** [comment]
@tejasm-itpath What we'll need to do is build a plugin that we'll run from angelleye.com where I can submit new notifications to be displayed in various plugins.  So in our plugin I would select which plugin I want to send a notification to along with the message I want to send.  This would update an RSS feed, for example, that is hosted by angelleye.com.

Then our individual plugins where we've implemented this notification system (this one will be the first) we'll hit this RSS feed to see if anything new is available.  If so, we'll display in that notification panel.  End users should be able to dismiss/hide notifications after they've viewed them.

**Comment by tejasm-itpath** [comment]
@angelleye  
I have completed plugin for adding notifications. Also created the tool that will fetch the notifications from the plugin and sends to particular plugin. 
Now need to discuss on call about how we can store/dismiss the notifications on all sites.
