### ISSUE TITLE
More Issues using Incontext option

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#939]
Order for shirt created from cart page.
Options: 

- **Gateway : EC**
- **Guest checkout enabled**
- **Billing Agreement disabled on all products**
- **Click on EC button : Popup opens : shows me following page [http://prntscr.com/hc5flx]**
-** If I click on Create A paypal Account ( although I have set landing page to billing page in EC settings ) http://prntscr.com/hc5g8z ( Agree and Create account , which te;lls me that its still getting billing agreement parameter)**
-**If I login with my account , Pay, then it send me email for order but on the cart page I'm seeing this
http://prntscr.com/hc5cxm**

So dont know whats going on. Also some time its not returning to my site, Instead in the In-Context popup shows order review page and places order

Im still not seeing , guest checkout option.

**Comment by iMansoorAliKhan** [comment]
**Update:** was missing Paypal Optional in settings : I have enabled now its showing the default credit card payment options. Still the other things behave odd, still processing order on popup , if you click cancel it takes u bakc original site then keep loading for a sec the on that same windows redirect you back to the paypal screen to pay again.

NOt sure if that is the expected behavior.

**Comment by angelleye** [comment]
Moving this to 1.5.0

**Comment by iMansoorAliKhan** [comment]
Another issue: With 1.4.7 In-Context is been fired from the mini cart, but not cart page.
Theme Flatsome Latest version.

**Comment by iMansoorAliKhan** [comment]
are we going to update this one
