### ISSUE TITLE
PayFlow - Rearrange credential fields in settings.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#940]
* https://mail.google.com/mail/u/0/#inbox/15fdfe2123953944

>When configuring gateway options, the order of the credentials isn’t very intuitive for customers not familiar with our platforms.  Vendor > Password > User > Partner, I’ve had quite a few customers that think the password is only for the vendor since it comes immediately after.  Wondering if you could switch it up to Vendor > User > Partner > Password

**Comment by kcppdevelopers** [comment]
@angelleye 

Should we used same arrange as PayPal or as per your suggestion like (Vendor > User > Partner > Password) ?

![default_format](https://user-images.githubusercontent.com/13145461/33110409-b0edf626-cf6d-11e7-8007-177d4bf22d7e.png)

**Comment by angelleye** [comment]
@kcppdevelopers Sure, let's do that.
