### ISSUE TITLE
MultiCurrency Suit Plugin compatibility check

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#944]
https://www.angelleye.com/support/scp/tickets.php?id=1622
I got this ticket for the plugins and their deveoper said something like this

> 
"I am really sorry to say this, but PayPal Express is not possible to be integrated with my multi currency plugin :-( It works completely differently than any other gateway. PayPal Express does not allow WooCommerce to save the order. If you use PayPal Standard, when you go to checkout and then cancel the payment on PayPal payment page, you can see that the order has been placed in WP-Admin (the status is canceled), just like any other payment gateway - so the data is available to grab before payment. It does not happen with PayPal Express. The order is not stored in database and PayPal Express does not use ANY of the order data. Therefore any overrides (on currency or price) are simply omitted and PayPal Express does not use it."

I'm not sure if that is completely true or not, your expert opinion is required on this.
Thanks!

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan Can you please provide 'WooCommerce Ultimate Multi Currency Suite' plugin for more troubleshoot?

**Comment by angelleye** [comment]
I've moved this to the 1.5.0 milestone, but yes, we will need a copy of that plugin to troubleshoot this further.

**Comment by iMansoorAliKhan** [comment]
Please find with the attached copy provided by the user.
[codecanyon-11997014-woocommerce-ultimate-multi-currency-suite-wordpress-plugin.zip](https://github.com/angelleye/paypal-woocommerce/files/1544874/codecanyon-11997014-woocommerce-ultimate-multi-currency-suite-wordpress-plugin.zip)
