### ISSUE TITLE
Fatal error while placing order

### ISSUE THREAD

**Issue by mechanicalgux** [angelleye/paypal-woocommerce#945]
https://github.com/angelleye/paypal-woocommerce/blob/9d01903d527faa4b3a8534aac3f6d99150081da5/classes/wc-gateway-calculations-angelleye.php#L195

If `$order->get_product_from_item($values);` returns false, "Place order" will fail with an error 500.
The check is done above `if (is_object($product))` but not at line 195.

The produced error is: `Fatal error:  Uncaught Error: Call to a member function is_type() on boolean`

**Comment by iMansoorAliKhan** [comment]
@mechanicalgux Are you using the latest version of Our plugin? Can you confirm WC version, WP version and Payment gateway you are using?

**Comment by mechanicalgux** [comment]
Yes latest version 1.4.6.7, WC 3.2.5, WP 4.9 with Paypal Checkout gateway.
Bug introduced with this commit: https://github.com/angelleye/paypal-woocommerce/commit/2a207b5d6c625c9d6793b61e1d7f77888c2dbbea#diff-b529e81a0f84e28b21a8433d59d9638b

Sometimes the order doesn't contain an actual WC product (custom datastore), therefore $product is "false". Just make a check is_object($product) above and it should fix the problem.

**Comment by angelleye** [comment]
@mechanicalgux Thanks for the info!  We'll make necessary adjustments on the 1.4.7 update we're working on now.
