### ISSUE TITLE
PayFlow - Token Payment / Reference Transaction Notice

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#950]
PayFlow has a setting you have to enable in the PayPal Manager account to enable reference transactions:

![image](https://user-images.githubusercontent.com/629241/33463174-93e06c22-d601-11e7-98cc-b98091938395.png)

We need to add a notice that shows up if somebody enables Token payments in PayFlow, or if they're using PayFlow with Woo Subscriptions that informs the user that they need to enable reference transactions.

We need to make this notice include a link to documentation on our site about how to enable this feature (and I still need to build this doc on our site.)

**Comment by kcppdevelopers** [comment]
@angelleye Can you please provide document link?

**Comment by angelleye** [comment]
@kcppdevelopers It's not loading yet, but it will be https://www.angelleye.com/paypal-woocommerce-subscriptions/

**Comment by kcppdevelopers** [comment]
@angelleye We also need to add notice for "PayPal Payments Advanced" payment method right?

**Comment by kcppdevelopers** [comment]
@angelleye Please [update](https://github.com/angelleye/paypal-woocommerce/blob/dev/classes/wc-gateway-paypal-pro-payflow-angelleye.php#L1693) Updates verbiage, text etc..
