### ISSUE TITLE
Braintree - Duplicate refund triggers when refresh order page..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#955]
* https://wordpress.org/support/topic/order-refresh-after-refund-creates-duplicate-refund/

**Comment by angelleye** [comment]
Should check into this with all of the other gateways, too.

**Comment by iMansoorAliKhan** [comment]
I have another person in ticket who have issue with refunds, while testing that I did refresh the page ( in backend ) and I dont see any duplicate refunds for EC.

**Comment by angelleye** [comment]
@iMansoorAliKhan Is it the same issue being reported or something different?  Please provide ticket URL.

**Comment by iMansoorAliKhan** [comment]
@angelleye not similar like they were seeing that the option of fully refund was not available, method EC. Here is ticket URL https://www.angelleye.com/support/scp/tickets.php?id=1649

**Comment by inventusdylan** [comment]
@angelleye This still seems to be an issue. Even when using other payment methods. When the plugin is activated it will duplicate the refund total x2. When disabling the plugin and refunding an order it goes all well.

**Comment by angelleye** [comment]
@inventusdylan I'm not sure I fully understand.  You mean other payment methods in our plugin or in entirely separate plugins?
