### ISSUE TITLE
Opt-In to Logging

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#958]
When we first launched this plugin we had some basic logging in place so we could store in our database a list of all the domains that activated / deactivated the plugin.  We had to remove this because of the Woo privacy policy.  

We can add it back as long as we include an "opt-in", so we can have an admin notice that says:

"Please help us improve the plugin by tracking limited details about the use of this plugin on your site."

Then we would have an Agree or Disagree option.  If they agree we can do our logging, but if not then we can't, of course.

**Comment by angelleye** [comment]
If you look at `activate_paypal_for_woocommerce()` and `deactivate_paypal_for_woocommerce()` you'll see our call to a web service for logging is still included, but commented out.  So we just need to add our opt-in message as explained above, and then if the user has opted in we can include the logging code.

**Comment by tejasm-itpath** [comment]
@angelleye 
Right now we are displaying the buttons and message as shown in this link https://www.screencast.com/t/WOLbj0bphCos
But I am thinking about adding our plugin name too as header or anywhere else.

**Comment by angelleye** [comment]
@tejasm-itpath I agree, we need the notice to specify which plugin it's referring to.
