### ISSUE TITLE
WPML compatibility adjustments necessary..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#959]
* https://mail.google.com/mail/u/0/#inbox/160121053e732b58

WPML reached out to us saying that it looks like we need to make adjustments..??

> We would like to retest PayPal for WooCommerce as we see some changes affect WPML. I have reset the test site and activated the updated files of your extension.
> Can you please log in and demo content?
> 
> http://plugin-paypalforwoocommerce.compatibility.wpml.org/wp-admin/

**Comment by kcppdevelopers** [comment]
@angelleye Can you please provide login details on slack ?

**Comment by angelleye** [comment]
@kcppdevelopers details provided in slack...

**Comment by kcppdevelopers** [comment]
@angelleye I have logged in above website, there is nothing but simple empty website.

https://content.screencast.com/users/kcppdevelopers/folders/Jing/media/267ad39d-1aac-4e07-a1aa-06e0c39c1d7c/2017-12-19_1451.png

Can you please explain with more details about issue?

**Comment by angelleye** [comment]
@kcppdevelopers Yeah it was just a test site they setup for us to test the WPML functionality.  I've always been a bit confused with what we need to do to ensure our plugin is fully compatible with theirs.  Was hoping you could find some info about that...

**Comment by kcppdevelopers** [comment]
![959](https://user-images.githubusercontent.com/13145461/34242692-dca0b0f6-e642-11e7-9653-87e8ff2c2a9a.png)
