### ISSUE TITLE
Express Checkout - Captured Authorizations don't allow refunds from WC order screen..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#960]
* https://mail.google.com/mail/u/0/#inbox/1604cdd2da9831ac

> The issue we are seeing is when we switch the Payment Action to “Authorization”, the Refund option is always grayed out and never gets activated. We have tried multiple tests. We tried doing an authorization and then capturing that authorization but after we did that, the refund button was still grayed out.
>  
> Can you enlighten us if we are missing a step or how to have the ability to do both partial and full refunds for orders that begin in “Authorization” and then are later captured.

**Comment by iMansoorAliKhan** [comment]
I think this user is on our support as well ( id=1649 ), this seems to be the same as they showed greyed refund button. and yes , this case is true when authorization is pending, becasue on my local I see like this.
http://prntscr.com/hmu5bq

> `This order has a pending authorization. You may capture partial or full payment for this authorization, or you may void the authorization.`

**Comment by angelleye** [comment]
That would make sense that you cannot refund when the auth is pending because there is no transaction to refund yet.  If there is a capture, though, we need the ability to refund.

**Comment by iMansoorAliKhan** [comment]
So you are saying that, if its not captured / authorized then the button will be grayed, but if we have partial or full authorization/capture then this button should work?

**Comment by angelleye** [comment]
Yes, exactly.  If there are captured funds then those funds need to be available for capture.  The feedback we're getting is that even when the full amount the auth has been captured they still cannot refund.
