### ISSUE TITLE
Express Checkout - Hook or option in settings to update WC checkout page logos.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#967]
* https://wordpress.org/support/topic/change-paypal-mark-on-checkout/

**Comment by kcppdevelopers** [comment]
@angelleye I already have filter to change icon on checkout page.

`add_filter('woocommerce_paypal_express_icon', 'angelleye_change_express_checkout_icon', 10, 1);
function angelleye_change_express_checkout_icon($icon_url) {
	$icon_url = '<img src="https://www.paypalobjects.com/webstatic/en_US/i/buttons/cc-badges-ppmcvdam.png" alt="Credit Card Badges">';
	return $icon_url;
}`

**Comment by kcppdevelopers** [comment]
https://pastebin.com/REuJrWnp
