### ISSUE TITLE
Token Payment Save to Account Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#969]
The option to "save to account" for token payments is showing up like this:

![image](https://user-images.githubusercontent.com/629241/34247136-0f999b22-e5f7-11e7-9dde-df352556c9f8.png)

So the text is below the check box.  It should be next to it.  

Also, "save to account" isn't very descriptive.  I'd like to change this to say "Save payment method to my account."

**Comment by kcppdevelopers** [comment]
https://www.screencast.com/t/bOe8jGuk
