### ISSUE TITLE
Payment Gateway Fees and Discounts for Woo Conflict.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#971]
* https://wordpress.org/support/topic/1-4-7-crashes-site/
* https://wordpress.org/plugins/checkout-fees-for-woocommerce/

Our 1.4.7 update seems to be conflicting with this plugin for some reason.

**Comment by kcppdevelopers** [comment]
@angelleye  I have checked and found that it's not our plugin issue.

`Fatal error: Call to a member function get_available_payment_gateways() on a non-object in /home/[account]/public_html/wp-content/plugins/checkout-fees-for-woocommerce/includes/class-wc-checkout-fees.php on line 163`

Above Error from "Payment Gateway Based Fees and Discounts for WooCommerce" plugin.
