### ISSUE TITLE
Yith Gift card : Error : 10426 : Invalid Item Total

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#973]
Client is getting error while checking out and logs shows that shipping is negative.
I have shared logs with you on slack for review.

**Comment by iMansoorAliKhan** [comment]
#949

**Comment by iMansoorAliKhan** [comment]
@angelleye , Are we gonna check this one? As client is waiting feedback on this.

**Comment by angelleye** [comment]
@tejasm-itpath Please see if you are able to reproduce this error and get it resolved.

**Comment by angelleye** [comment]
@iMansoorAliKhan Please provide the logs referenced here so that @tejasm-itpath has them for his review.  If there is sensitive data in the log you can provide directly to TJ via slack instead.

**Comment by iMansoorAliKhan** [comment]
@angelleye , Thanks , I have shared the log with TJ on slack.

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan  Yes I will look this.

**Comment by iMansoorAliKhan** [comment]
This use is still saying they see the error.
![image](https://user-images.githubusercontent.com/11312949/35454411-c490a5e2-02ef-11e8-991a-dcc19cc2c507.png)

**Comment by iMansoorAliKhan** [comment]
The user reported that it still didnot fixed the problem, I also see that if I install 971 branch on his site then it shows plugin version 1.4.7.1 do you think that could still be casuing the probelm?

**Comment by angelleye** [comment]
May need to wait at this point to get this cleaned up.  Jignesh is working on 1.4.7.3 and he already has some other things merged into the dev branch.  Once that's done we can then merge dev back into Issue-971 to get it caught up.

That said, if the user is running this branch and it didn't solve the problem that was supposed to be fixed here, then that probably still needs to be addressed.

**Comment by kcppdevelopers** [comment]
#987
