### ISSUE TITLE
Express Checkout User Not Created When Name, SurName and Email are not empty

### ISSUE THREAD

**Issue by ripieces** [angelleye/paypal-woocommerce#974]
This bug was introduced in
https://github.com/angelleye/paypal-woocommerce/commit/ee9d8a6d1ff574df2ca1b4766902277363c2cc58

The bug is in in line 1337 in express-checkout/class-wc-gateway-paypal-express-request-angelleye.php:
https://github.com/angelleye/paypal-woocommerce/blob/release/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-request-angelleye.php#L1337

```
if( empty($first_name) || empty($last_name) || empty($email)) {
```

If all conditions are met, no user is created.

This should probably be

```
if(!empty($email)) {
```

**Comment by angelleye** [comment]
@ripieces Thanks, we'll take a look and make necessary adjustments in a patch update.

@kcppdevelopers Please review and adjust accordingly.

**Comment by angelleye** [comment]
@ripieces We'll be releasing a 1.4.7.1 update shortly that resolves this issue.  Thanks again for the feedback!
