### ISSUE TITLE
PayPal Express: Shipping address not updated when paying for an order

### ISSUE THREAD

**Issue by bjornburn** [angelleye/paypal-woocommerce#977]
Hello there!

First of all, thanks for a great plugin! PayPal Express is working fine and updating the address just as expected when doing a normal checkout, but I've run into an issue when I'm trying to pay for an order.

Here are the steps to recreate the scenario:
1. In the WP Admin, go to **Woocommerce** –> **Orders** and hit **Add order**. Add a couple of items and hit **Create**.
2. In the Order details, find and go to the **Customer payment page** (linked next to **Order status**)
3. Choose to pay with **PayPal Express**, and hit **Proceed to PayPal**.
4. Follow the PayPal steps, pay for your order and finally you'll end up on the order received view. So far so good!

Now if you revisit your order in WP Admin, you'll see that the Shipping Address has not been updated (it's still empty). Same goes for Billing Address (even if you've checked the "set billing address" option).

It would be great to be able to get the shipping address from PayPal Express when creating manual orders as well as when using the API to create orders.

Any ideas for a temporary fix/workaround would be greatly appreciated!

Thanks / bjornburn

**Comment by iMansoorAliKhan** [comment]
@bjornburn Thanks for your nice words, they mean a lot.
Please allow us some time, we will definitely gonna take a look and see whats going on there.
Please hold on for some time , we will get back to you asap.
Thanks!
