### ISSUE TITLE
Braintree - Kount Custom

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#989]
* https://wordpress.org/support/topic/braintree-avs-and-kount-issues/

>I have the ID set up and talked to Braintree and they are saying that everything is working on their end, however Device Data Captured is coming is as a false. Their reason was saying that the plug-in is not sending that data to them to verify which can result in false positives.

**Comment by kcppdevelopers** [comment]
![untitled](https://user-images.githubusercontent.com/13145461/35718222-89ce28ac-0809-11e8-9ba5-f5df6422d232.png)

**Comment by kcppdevelopers** [comment]
@angelleye  Actually braintree not providing Kount merchant ID by default for testing so for me it is difficult to testing on sandbox environment.

It would be great to please ask user provide web details for more troubleshoot?

**Comment by kcppdevelopers** [comment]
@angelleye Braintree - Kount Custom only work for Drop-in Payment UI, so we need to exclude Kount Custom option from Fraud Tool drop-down when Drop-in Payment UI option is disable.

**Comment by angelleye** [comment]
@kcppdevelopers Did you find details about that in the docs somewhere I can refer to the user to?

**Comment by angelleye** [comment]
@kcppdevelopers Also, is this ready for review now, or still waiting on feedback?

**Comment by kcppdevelopers** [comment]
@angelleye yes, this is ready for review, Actually Kount Custom is part of Drop-in Payment UI so it only work with Drop-in Payment UI.
