### ISSUE TITLE
Braintree - Error reporting adjustments..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#990]
* https://wordpress.org/support/topic/braintree-avs-and-kount-issues/

> So if a customer inputs the wrong billing address I would assume it would output the following code:
> ‘The provided address does not match the billing address for cardholder. Please verify the address and try again.’, ‘paypal-for-woocommerce’
> 
> However it seems to be outputting:
> Error: PayPal Powered by Braintree was unable to complete the transaction. Please try again later or use another means of payment. Reason: Gateway Rejected: avs
> 
> It seems to do the 2nd option for all errors such as a incorrect expiration outputs:
> Error: PayPal Powered by Braintree was unable to complete the transaction. Please try again later or use another means of payment. Reason: Gateway Rejected: cvv (why is it outputting CVV instead of expiration).

**Comment by kcppdevelopers** [comment]
[
374cc0f ](https://github.com/angelleye/paypal-woocommerce/commit/374cc0fda0a2571d158f526c22a3506d4688d6e5)
