### ISSUE TITLE
Script execition time problem with PP PFLOW 2.0 , DDP and EC too

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#991]
we are having some reports that on checkout page it take around 12 to 20 sec to move to order received page in case of Payflow and Do direct. 
And in case of EC in regular gateways still taking 10 sec to move to the paypal page.
after installing query monitiro plugin, its showing many duplicate queries, see below screnshot.
![image](https://user-images.githubusercontent.com/11312949/35667710-87a24810-0750-11e8-8b4e-1144f14f8fcc.png)

![image](https://user-images.githubusercontent.com/11312949/35667739-97d22714-0750-11e8-9f61-95072160f31d.png)

, If I check logs the time between gateway request and response are just 1 second even some have 0 seco. so I'm getting confused why its taking 12 to 20 seconds to just create the order and redirecting to order page?

REF: https://wordpress.org/support/topic/paypal-payments-pro-2-0-payflow-payments-are-slow/
https://wordpress.org/support/topic/added-over-a-second-to-my-site-loading-time/
Please look into it and let me know if you have any questions.
sandbox url is sandbox.mansooralikhan.com

**Comment by angelleye** [comment]
We got a bad review about this in the plugin page recently, and I do have 4 or 5 other random reports of it lately, too.  Definitely need to get this figured out and fixed ASAP!

**Comment by iMansoorAliKhan** [comment]
@angelleye , now the time is lowered to 9sec. as per my calculation on stopwatch

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I am still working on this issue.

**Comment by angelleye** [comment]
@iMansoorAliKhan Looks like @kcppdevelopers got this fixed up now.  can you pull the dev branch now and run some tests to confirm the problem is resolved for you?

**Comment by iMansoorAliKhan** [comment]
@angelleye  Yeah, we both ran some test yesterday, The time is now improved, still takes nearly 4-5 sec which is fine I guess, as that may vary depending on the intenet speed, server etc

**Comment by iMansoorAliKhan** [comment]
Do direct still took 11 seconds, in issue 993 I have shared a video you can check the time count there as well

**Comment by angelleye** [comment]
@kcppdevelopers 11 seconds is too long, even if internet is slow.  The PayPal logs show 1 second response to API request.  Why would everything else be adding 10 seconds?

@iMansoorAliKhan Are you still able to find what's causing it in the browser console?

**Comment by iMansoorAliKhan** [comment]
Not sure yet, payflow is taking 5sec , cant check paypal advanced

**Comment by kcppdevelopers** [comment]
@angelleye @iMansoorAliKhan 

I have checked all the payment methods on kcppdevelopers.angelleye.com below are results:

1) PayPal Pro : 1.3 second request time + 6.7 seconds page load time = 8 seconds total time
2) PayPal Payflow : 1.1 second request time + 5.8 seconds page load time = 6.9 seconds total time
3) PayPal Advanced: 0.7 second request time + 6.1 seconds page load time = 6.8 seconds total time

**Comment by angelleye** [comment]
@kcppdevelopers What about Express Checkout?  We've had complaints about it being slow as well.
