### ISSUE TITLE
Website Payments PRO: Invalid missing token fields 

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#993]
![image](https://user-images.githubusercontent.com/11312949/35845521-a0fcce24-0b34-11e8-81b8-04bc22afb558.png)

When tockenized payments is enabled , and I fill in valid details and click on save details then I m getting error.
Please look into this.
I have a ticket reporting the same too.
https://www.angelleye.com/support/scp/tickets.php?id=1774

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan  I have tested on sandbox.mansooralikhan.com and for me it's working. could you please provide details video for more troubleshoot ?

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers   I have just tested again and saw the same problem, may be you are testing with some other gateway?

I have tested with creditcard do direct.

![image](https://user-images.githubusercontent.com/11312949/35899528-c7c24d58-0bee-11e8-9fec-7cceb9fc0c2d.png)

**Comment by iMansoorAliKhan** [comment]
Are you checking with login or without login?

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have checked with login, but for me it's working.. It would be great to provide vedio demo for more troubleshot ?

**Comment by iMansoorAliKhan** [comment]
Please take a look here, it will work without login as you are not going to save payment method into account ( tokenizing ).
Please check this https://www.useloom.com/share/0b8ef5a65ff34d81b5b88080497b5f83

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have resolved issue, Could you please re test again for me?

**Comment by iMansoorAliKhan** [comment]
seems to be working now, ,
