### ISSUE TITLE
PayFlow - Payment button gone after latest update..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#996]
* https://wordpress.org/support/topic/payflow-pro-not-working-with-new-version

**Comment by angelleye** [comment]
@kcppdevelopers I have just noticed that this has happened on my own angelleye.com site as well.  Definitely need to get this resolved ASAP!

**Comment by kcppdevelopers** [comment]
@angelleye I just started work on this issue and resolved it very soon.

**Comment by angelleye** [comment]
@kcppdevelopers It only seems to be happening when PayFlow and EC are the only gateways enabled.  

On woo.angelleye.com I also had PayPal Here enabled, so the "Proceed to Checkout" button displayed.  Without that, though, the button is supposed is to say "Pay with Credit Card".  Instead we're losing that button entirely.

Please make sure to check this same thing for DoDirectPayment and anything else where we had similar logic.

**Comment by kcppdevelopers** [comment]
@angelleye I am done with this issue and push to dev branch.
