### ISSUE TITLE
Express Checkout - JSv4

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#997]
https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/upgrade-integration/

**Comment by angelleye** [comment]
We need to follow the guide above to upgrade our Express Checkout integration to their JSv4 integration using their checkout.js script.

Our API calls and everything should still work the same way, so this should just be a matter of updating how our buttons are displayed and how they trigger the API calls.  This should not require an entire re-write of the integration.

**Comment by angelleye** [comment]
This may replace the need for the "In Context" functionality.  This JSv4 integration happens on your site similar to In Context by default, so I believe we'll be able to get rid of the In Context stuff and replace it with JSv4.

**Comment by angelleye** [comment]
I believe we'll also be able to remove our option to add the PayPal Credit button because that gets tied into this JSv4 experience as well.  so where we currently have both EC and PayPal Credit buttons displayed (depending on settings) we'll just have this one "smart button" now.

Still need to verify 100% but I believe this is the case...

**Comment by angelleye** [comment]
Yeah, the Upgrade doc has links within it for "customize the button" and this shows how to present all the different options.  So we'll still need our settings, I think, and then based on the user settings we'll build the JSv4 button accordingly.

Hopefully this will help with our general button alignment issues we've had in some themes.  Now we'll just have a single button instead of trying to line up EC and Credit buttons side by side.  

We will need to consider that if they enable lots of options there will be lots of buttons stacked on top of each other.

**Comment by angelleye** [comment]
Quick example from a PayPal rep:

>One line of code -> 3 integrations! (see highlight part below) Available on REST, Classic and BT SDK (all platform)
 

```
paypal.Button.render({

       

        // Set your environment

        funding: {

        allowed: [ paypal.FUNDING.VENMO, paypal.FUNDING.CREDIT ]

},

 

        env: 'sandbox', // sandbox | production

 

        // Specify the style of the button

 

        style: {

            layout: 'vertical',// checkout | credit | pay | buynow | generic

            size:  'medium', // small | medium | large | responsive

            shape: 'rect',   // pill | rect

            color: 'blue'   // gold | blue | silver | black

        },

 

        // PayPal Client IDs - replace with your own

        // Create a PayPal app: https://developer.paypal.com/developer/applications/create

 

        client: {

            sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',

            production: '<insert production client id>'

        },

 

        // Wait for the PayPal button to be clicked

 

        payment: function(data, actions) {

            return actions.payment.create({

                payment: {

                    transactions: [

                        {

                            amount: { total: '0.01', currency: 'USD' }

                        }

                    ]

                }

            });

        },

 

        // Wait for the payment to be authorized by the customer

 

        onAuthorize: function(data, actions) {

            return actions.payment.execute().then(function() {

                window.alert('Payment Complete!');

            });

        }

   

    }, '#paypal-button-container');
```

 

Demo: https://developer.paypal.com/demo/checkout/#/pattern/responsive

**Comment by angelleye** [comment]
Need to update documentation to show that "In Context" is now called "Smart Buttons" and provide info on building your button display using the options in the Smart Buttons section of EC settings.

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan  Could you please test this issue for me?

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers  Sure, I'm just going to test it now. will give my feedback here.

**Comment by iMansoorAliKhan** [comment]
Please see my findings

![image](https://user-images.githubusercontent.com/11312949/36548792-01f87648-1813-11e8-8999-2c08b7f69149.png)


![image](https://user-images.githubusercontent.com/11312949/36548813-0c7e9142-1813-11e8-8424-1b5173de1f6b.png)

**Comment by angelleye** [comment]
@kcppdevelopers We don't have our options for Venmo in here..??

**Comment by angelleye** [comment]
@kcppdevelopers Any way to check and see if the plugin is a fresh install or an update?  For brand new installs we could enable Smart Buttons by default, but simply don't want to disrupt current users.

**Comment by kcppdevelopers** [comment]
@angelleye by default we enable all the additional funding sources but it depend on buyer PayPal account. it will only show if buyer's PayPal account support Venmo. and our gateway setting allow user to Hide the specified funding method.

**Comment by kcppdevelopers** [comment]
@angelleye Also buyer's PayPal account support Venmo it will display like other buttons but we can't hide like other funding sources.

**Comment by kcppdevelopers** [comment]
@angelleye yes, We can check and see if the plugin is a fresh install or an update, We make Smart Buttons by default enable for brand new installs, but existing user if in content checkout already enable then Smart Buttons will remain enable for them as well.

**Comment by iMansoorAliKhan** [comment]
There are still issues , I'm still working with **kcpp**

**Comment by angelleye** [comment]
@kcppdevelopers Okay, yeah, that's fine.  So the basic logic would be something like...

>If {fresh_install} or {in_context_enabled} then {enable smart buttons by default with standard options set}

Is that what you did in these recent commits?

**Comment by angelleye** [comment]
@kcppdevelopers Testing on latest updates, I added ELV and Credit to the "hide" option under smart buttons.  It's correctly adding those to the disallowed section, and the result on the front end is as expected.  However, it's still leaving those options under "allowed" too..??

```
"allowed_funding_methods":"[\"credit\",\"card\",\"elv\",\"venmo\"]","disallowed_funding_methods":"[\"credit\",\"elv\"]"
```

**Comment by angelleye** [comment]
Per discussion with @kcppdevelopers, Venmo returns an error that it cannot be disallowed when specifically added to the disallow parameter.  As such, if Venmo is added to the "hide" option under smart button settings then we'll simply leave it out entirely...so it won't be added to allowed or disallowed.

The other options can be specifically added to allowed or disallowed based on whether or not they are hidden in settings.

**Comment by kcppdevelopers** [comment]
@angelleye I have applied changes as per discussion and push to dev branch.

**Comment by angelleye** [comment]
@kcppdevelopers This looks better, thanks.  I will talk to PayPal about why Venmo doesn't show up even on their own demo.

**Comment by angelleye** [comment]
@kcppdevelopers In the Smart Button settings, if I have it set to Horizontal layout I get additional options like Button Label.  Right now, though, if I hide PayPal Credit in the hide option, I can still set Button Label to Credit so it just shows a PayPal Credit button.  This is confusing.  We need to make sure the PayPal Credit option doesn't show up in the Label option if it has been added to the hide option already.

Also, I notice that you have "Paypal" in some of these settings/options.  We need to make sure to always use "PayPal".

**Comment by angelleye** [comment]
@kcppdevelopers Also, PayPal Credit is showing up now regardless of the country set on the site..??  PayPal Credit is only available in the US and UK, so if the country is not set to one of those we need to remove PayPal Credit from the options entirely.

**Comment by iMansoorAliKhan** [comment]
@kcppdevelopers in Firefox smart button ( vertical ) is taking 2 clicks to open popup.
Screenshot: 
![image](https://user-images.githubusercontent.com/11312949/37453303-19b0d9e6-2859-11e8-8566-898f8f1a2b51.png)

**Comment by kcppdevelopers** [comment]
@iMansoorAliKhan I have checked smart button ( vertical ) it is working well in the single click. I have also checked in your website and for me it's working..

**Comment by angelleye** [comment]
@kcppdevelopers When viewing source on a cart page I see this:

```
var angelleye_in_content_param = {"payer_id":"paypal-facilitator_api1.angelleye.com","environment":"sandbox","locale":"","start_flow":"http:\/\/woo.angelleye.com\/cart\/?startcheckout=true","show_modal":"1","update_shipping_costs_nonce":"9536c47db8","ajaxurl":"http:\/\/woo.angelleye.com\/?wc-ajax=wc_angelleye_ppec_update_shipping_costs","generate_cart_nonce":"36f64e7c78","add_to_cart_ajaxurl":"http:\/\/woo.angelleye.com\/?wc-ajax=angelleye_ajax_generate_cart","is_product":"no","is_cart":"yes","is_checkout":"no","cart_button_possition":"bottom","button_size":"responsive","button_color":"gold","button_shape":"pill","button_label":"","button_tagline":"","button_layout":"vertical","button_fundingicons":"","cancel_page":"http:\/\/woo.angelleye.com\/cart\/","is_us_or_uk":"yes","allowed_funding_methods":"[\"credit\",\"card\",\"elv\",\"venmo\"]","disallowed_funding_methods":"[]","set_express_checkout":"http:\/\/woo.angelleye.com\/?wc-api=WC_Gateway_PayPal_Express_AngellEYE&pp_action=set_express_checkout"};
```

Notice that you're passing the API username into the `payer_id` parameter of the JSON string.  the Payer ID is actually something else.  Remember with Express Checkout we pass a token into GetExpressCheckoutDetails and that response gives us a PAYERID value like this:  MV88D7MFLZSVE

I'm pretty sure that's what should go in the `payer_id` parameter for the Smart Button JS.

**Comment by kcppdevelopers** [comment]
@angelleye Actually client/payer_id optional parameter and it's not required in our custom integration so I have remove completely. I have double checked and it's working fine.
